### ISSUE TITLE
Random Qt warnings

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#100]
Mostly when browsing imgur/reddit:

```
WARNING: content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem

WARNING: QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"

WARNING: QIODevice::read: device not open
```

Random error message when closing/re-opening tab:

```
WARNING: Type conversion already registered from type QSharedPointer<QNetworkSession> to type QObject
```

**Comment by The-Compiler** [comment]
@Carpetsmoker says he can reproduce the `QIODevice` one when pressing `<C-d>` on https://decorrespondent.nl/ sometimes.

**Comment by Carpetsmoker** [comment]
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.

After starting qutebrowser with one saved tab, and closing it again with `<C-q>` in 1-2 seconds. Timing seems very specific, since I can't reproduce it anymore.

**Comment by Carpetsmoker** [comment]
WARNING: QIODevice::write (QTcpSocket): device not open
	  File "/usr/lib/python3.4/site-packages/qutebrowser-0.3.0-py3.4.egg/qutebrowser/utils/log.py", line 312, in qt_message_handler
		stack = ''.join(traceback.format_stack())

**Comment by The-Compiler** [comment]
Reported by @Kingdread in #962:

> On a side note, something I noticed while using qute without network access (to make sure the data is actually from the mhtml file and not loaded), I get a lot of those in my terminal:

```
WARNING: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
  [...]
  File "/home/daniel/Code/qutebrowser/qutebrowser/app.py", line 121, in qt_mainloop
    return qApp.exec_()
  File "/home/daniel/Code/qutebrowser/qutebrowser/app.py", line 448, in _init_late_modules
    QApplication.processEvents()
  File "/home/daniel/Code/qutebrowser/qutebrowser/utils/utils.py", line 511, in wrapper
    return func(*args, **kwargs)
  File "/home/daniel/Code/qutebrowser/qutebrowser/browser/network/networkmanager.py", line 387, in createRequest
    reply = super().createRequest(op, req, outgoing_data)
  [...]
```

**Comment by The-Compiler** [comment]
Most (all?) of those are either fixed in Qt or hidden now.
