### ISSUE TITLE
hints selecting the wrong link on etsy.com

### ISSUE THREAD

**Issue by diatomine** [The-Compiler/qutebrowser#1005]
hi, there is a bug on www.etsy.com when browsing items, when you open an item with hints and you use the hint for its text link, the page for the next item will be opened instead. If you use the hint for its thumbnail link, the correct page will be opened. the bug isn't always there, but when it is it appears to be there for the entire page of items (ie you search for something and you get the result pages 1, 2, 3, 4 and so on, and the whole page 2 has the bug but not page 1 etc). With the bug, the text link of the last item on that page will not react to using the hint.

I'm not sure but I think the bug appearing or not might depend on the length of the text of the link of the first item on a page. So if the link text exceeds a certain length then the bug appears.

Ok so I played around with that idea a bit more and found that it is not restricted to the first item/the entire page, but rather the bug can start anywhere on the page if the link text of an item has a certain length. So the items before that item can be selected correctly by the text link, but the text links after it and its own text link point to the wrong item.

I generally (ie not only on etsy) noticed some problems with hint selecting links that have a multi-line text or a certain length text or something; usually the link would simply not react to the hint. I guess those problems and this issue are related.

I hope I the description is understandable I have no idea if it is. Also I guess the issue might depend on the system or the screen resolution or something so please ask if you need additional details

**Comment by The-Compiler** [comment]
I can confirm - for example, when searching for "test" I get:

![etsy](https://cloud.githubusercontent.com/assets/625793/10334513/f57730b0-6cea-11e5-814e-a1ec35827d1f.png)

And pressing `jf` will select the camera.

Looking at the label with the inspector, it seems to be as long as the text:

![etsy2](https://cloud.githubusercontent.com/assets/625793/10335584/14f31d1c-6cf2-11e5-83f3-9961306f89c8.png)

As qutebrowser is clicking the element on the right currently, the next item gets selected.

> I generally (ie not only on etsy) noticed some problems with hint selecting links that have a multi-line text or a certain length text or something; usually the link would simply not react to the hint. I guess those problems and this issue are related.

Yeah, multi-line links don't work currently - I don't think that's related though.
