### ISSUE TITLE
Crash when deleting a bookmark

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#1008]
There is a crash when trying to delete a bookmark using the following way:

* `:open`
* choose a bookmark with the mouse (everything is fine with the keyboard)
* hit `ctrl-d` to delete the bookmark

After these steps, qutebrowser crashes.

I'll try to look at this issue next week.

@The-Compiler Is it normal that the behavior is different with the keyboard and the mouse?

**Comment by The-Compiler** [comment]
I can't reproduce this - I click on a bookmark and press `ctrl-d`, and it gets deleted like I expect. Could you send a report so I have logs/stracktrace at least?

It is possible that those behaviours differ in some way - the keyboard selection code is from me, while the mouse selection is the Qt default. There's the concept of "selected" items and a "current" item, so maybe I got that mixed up somewhere.
