### ISSUE TITLE
Add a :download-clear

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1013]
It seems `:download-remove --all` is hard to figure out, so we should add a `:download-clear` command.

**Comment by Earnestly** [comment]
This would be useless if qutebrowser provided a page similar to `qute:log` for downloads such as `qute:downloads`.  An alias `:downloads` could simply be`:open -t qute:downloads`.

**Comment by The-Compiler** [comment]
Doing `:downloads` and clicking/hinting a button is a lot more work than doing `:downloads-clear` though :wink:

**Comment by Earnestly** [comment]
This is in reference to https://github.com/The-Compiler/qutebrowser/issues/1059
