### ISSUE TITLE
custom-headers config

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1020]
`[network]` should have a `custom-headers` option which takes headers to set:

```
custom-headers = X-Eggs: bacon; X-Ham: spam
```

Not sure what the best char is to separate headers - `;` might also be used, but is probably the most intuitive one (or `,`).

@meles5 is working on this.

**Comment by meles5** [comment]
You're able to see the first results [here](https://github.com/meles5/qutebrowser/tree/headers). At the moment it's just a beta version, but I think that I'll improve the code and optimize it in the future.

If you know how to solve the problem with the seperators, please let me / us know.

@The-Compiler had the idea to use something like dictionaries in the config file, maybe this will be done before the code is in the final version.

---

In my code I created a new subconfiguration in the `~/.config/qutebrowser/qutebrowser.conf` file called `custom-headers` (section `[network]`), where you are able to define your own (custom) headers. Seperator is at the moment the `; ` one, please remember the space, it's important.
