### ISSUE TITLE
SessionError without datadir with general -> save-session = true

### ISSUE THREAD

**Issue by Ambrevar** [The-Compiler/qutebrowser#1029]
When starting a new instance with `--datadir ""`, qutebrowser will segfault on exit, poping the bug report window, then restart, recrash, repop, etc.

According do the stack, this should be an easy fix:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 464, in on_last_window_closed
    self.shutdown(last_window=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 598, in shutdown
    load_next_time=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/sessions.py", line 223, in save
    raise SessionError("No data storage configured.")
qutebrowser.misc.sessions.SessionError: No data storage configured.
```

**Comment by The-Compiler** [comment]
I can reproduce this when setting `general -> save-session` to `true` - though I don't see a segfault, just the qutebrowser exception.

Do you actually see a segfault, @Ambrevar? If so, could you [show a coredump](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc#crashes-which-can-not-be-reproduced)? (No need to install the debug packages for now, maybe I can see what's going on without them).

I'm not sure what should happen in this case to be honest... what do you think? Either diplay an error to the user or silently ignore `save-session` are the things I can think of.

**Comment by Ambrevar** [comment]
My bad, there is no segfault here indeed, I must have been confused something else when I collected these issues yesterday.

I am not sure what makes you hesitate: your man page is very clear on the subject! :)
```
Set data directory (empty for no data storage).
```
When the location is empty, don't do anything. It's a great way to create temp sessions!
When it is not writable, display a warning before exiting.

Should be the same for configdir, basedir and cachedir. I haven't tried if these ones fail though.

**Comment by The-Compiler** [comment]
`--datadir ""` is not supported anymore, so I'm closing this.
