### ISSUE TITLE
Bookmark display

### ISSUE THREAD

**Issue by Ambrevar** [The-Compiler/qutebrowser#1033]
Add a page that displays all bookmarks, possibly with a javascript filter thing, and the option to show them by file order, URI order, or title order.

I like dark backgrounds better, but that migh go to another "Theme" issue.

The page could be accessed from `qute:bookmarks`.

**Comment by The-Compiler** [comment]
And in it is, thanks to @winged! Nothing special regarding style so far - waiting for someone to step up with more webdesign experience than me for that one :wink:
