### ISSUE TITLE
Can't start qutebrowser after update

### ISSUE THREAD

**Issue by Linuus** [The-Compiler/qutebrowser#1038]
I just updated QT, PyQT and qutebrowser. Now, when I run qutebrowser in the terminal I get this screen.

![img](https://cloud.githubusercontent.com/assets/379823/10631490/ac00e9c2-77de-11e5-8d08-34ec016647a9.png)

**Comment by The-Compiler** [comment]
This was resolved by doing `brew reinstall sip --with-python3`.

I think that should've happened automatically when installing `pyqt5`, so I'm not sure what was wrong - but I'll close this for now unless there are other people seeing the same.
