### ISSUE TITLE
Crash opening a xml url

### ISSUE THREAD

**Issue by helfio** [The-Compiler/qutebrowser#1047]
qutebrowser crashes when I try to open the url of a xml file like this one:
http://www.ugr.es/~pablos/publications_list_es.xml

**Comment by The-Compiler** [comment]
I already reported this upstream in March as [QTBUG-45300](https://bugreports.qt.io/browse/QTBUG-45300), without any solution so far. I guess you're on Linux as well?

Unfortunately there isn't much more I can do - probably this will be better in the QtWebEngine backend (#666)

**Comment by helfio** [comment]
Yes, I'm on Linux. Sorry, I didn't see this reported. I didn't think of closed issues.
