### ISSUE TITLE
:search-next doesn't always show a message when wrapping

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1050]
Sometimes when using `n` and the result wraps to the top of the page, there's no message about the wraparound. Probably something related to searching in multiple tabs, as it worked after a `:restart`.

**Comment by Earnestly** [comment]
This is reproducable even here.  If I attempt to search for `wrap` on this page it will cycle through all three results and not report that it has looped around.

**Comment by The-Compiler** [comment]
This seems to be fixed in the cases I could test with the QtWebEngine search restructuring - not entirely sure what the culprit was.

Note this still only works when the page actually was scrolled due to the wrap around, because that's the only way I can determine if one occurred. So if the page is too small to scroll when the search wraps, there's no message - which might have been the case for you, @Earnestly?

**Comment by Earnestly** [comment]
Ideally mimicing vim and reporting a message always, however it's a lot less important if the page didn't scroll as you don't lose your position which is why the message is useful in the first place.

**Comment by lahwaacz** [comment]
Of course this still does not work where scrolling does not work, such as iframes (see e.g. http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html).
