### ISSUE TITLE
Add a method to allow domains to be scrubed from the history.

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#1051]
This could conceptually be the same as doing `% sed ',*.\..domain\.tld,d' history cookies`.  Firefox implements this as "forget this website" which removes all history items from that domain, although it probably also clears appropriate cache data as well.

I'm not concerned as history and cookies are simple text files and easy to do this on unix systems but you might want to consider adding this as a more intelligent (as opposed to bruteforce sed) command.

**Comment by The-Compiler** [comment]
Merging this into #58 as it'll probably be a feature of `:sanitize` as well.
