### ISSUE TITLE
No space inserted after wb (window quickmark-load)

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1058]
If you press `wo`, the command line reads `open -w  |` (there is a space between `-w` and the cursor.
The same goes for `o`, `O`, ect.

If you press `wb`, it inserts `quickmark-load -w|`. There is no space after the `-w` so you can't immediately begin typing the name of your quickmark. 

```
qutebrowser v0.4.1
Git commit:
CPython: 3.5.0
Qt: 5.5.0, runtime: 5.5.1
PyQt: 5.5
```

**Comment by The-Compiler** [comment]
I can't reproduce this, and the default binding does add a space (`-s`): https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/config/configdata.py#L1348

Can you show what `wb` is bound to in your `keys.conf`?

**Comment by rcorre** [comment]
Huh, my binding was missing `-s`. I might have unintentionally tweaked it. Sorry for the noise.
