### ISSUE TITLE
tab-detach steals focus from primary window.

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#1060]
Using `:tab-detach` to separate out a webpage into its own unique window results in any newly opened url via qutebrowser to fixate on the detached window instead of the primary instance which the tab was detached from.

This makes tab detaching essentially useless as a feature. 
Even if one has the foresight to split off the "new session" window via `:tab-detach` and leaving the remaining tab as the tab one actually intended to "detach".

This proceedure must be repeated, usually by closing all tabs of the second window, leaving the tab they wish detached, and detaching into a "new session", ad infinitum in a recursive pattern.

It's an extremely awkward process to say the least.

**Comment by The-Compiler** [comment]
As mentioned in IRC, currently it's always the [last opened window](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/mainwindow.py#L70-L78) which gets used for IPC currently - it should be easy to add some flag to windows opened via `:tab-detach` so they get ignored here.

**Comment by Earnestly** [comment]
I'm aware of how `:tab-detach` works, as you explained on IRC, but I'm pointing out that its currently behaviour renders its purpose pretty close to useless as a function.

**Comment by The-Compiler** [comment]
I know you are - I'm repeating things here for possible contributors who want to pick this up :smile:

**Comment by haasn** [comment]
@Earnestly In master, the functionality of opening new tabs was extended via an option `general -> new-instance-open-target.window` which apart from the old default of `last-opened` now has two more options:

* `last-focused` to spawn new tabs in the last window you had focused (mimics e.g. firefox behavior)
* `last-visible` to spawn new tabs in the last window you had visible (where focusing also counts as updating the visibility), which is useful in a one-window-per-workspace model

Do either of these two options solve this issue for you? If not, what kind of functionality *would* you like to see? FWIW somebody already requested something like #881, maybe you could voice your opinion there to revive that feature request.

**Comment by Earnestly** [comment]
It helps certainly but still requires unnecessary effort.  Counting `last-focused` and `last-visible` as essentially the same, the user now as to remember which window he focused last which is tedious when opening URLs from IRC and then having to either hunt down which window they opened in or actively switching to the window you want to become the 'master' session.

Ideally the first session opened would simply remain the master until a command is used to start a new one or the master session is closed causing the next in order to adopt it.  I don't know how feasible this would be to implement though since it involves some kind of state tracking, or you can enumerate sockets and use a numerical first-match approach.

I'm not really sure if this suggestion is wise either, I haven't used this feature since reporting this issue so I've become accustomed to it not existing.

**Comment by haasn** [comment]
> Counting last-focused and last-visible as essentially the same

I don't think these are the same at all. `last-visible` will always open it on whatever window is on the same workspace, so you immediately know where it goes and never have to “hunt down” anything, and also doesn't require you to remember anything to reason about it (as long as you don't have multiple visible windows at the same time). Also, qutebrowser will set an urgency hint when you open a new tab (unless it's market as “silent”) so it's not like hunting down the right window is hard. :p

> Ideally the first session opened would simply remain the master until a command is used to start a new one or the master session is closed causing the next in order to adopt it. I don't know how feasible this would be to implement though since it involves some kind of state tracking, or you can enumerate sockets and use a numerical first-match approach.

It would be trivial to add a `first-opened` analog to `last-opened` which would do exactly that: open tabs in the first window you opened, by ID. (So your initial master window would remain the tab target until you completely close it, at which point the second window you opened would be, and so on)

**Comment by Earnestly** [comment]
> I don't think these are the same at all. `last-visible` will always open it on whatever window is on the same workspace, so you immediately know where it goes and never have to “hunt down” anything, and also doesn't require you to remember anything to reason about it (as long as you don't have multiple visible windows at the same time). 

I understand the difference but an example problem is that my browser workspace is not shared with my irc workspace.

> Also, qutebrowser will set an urgency hint

This is a good point, urgency hints aren't typically very common for me personally so perhaps it would not be too much effort to hunt it down.  This creates an additional issue where I accidently open a new tab on the wrong detached browser window.  It's just awkward.

> It would be trivial to add a `first-opened` analog to `last-opened` which would do exactly that: open tabs in the first window you opened, by ID. (So your initial master window would remain the tab target until you completely close it, at which point the second window you opened would be, and so on)

This would probably be the best compromise.

> So for example, if I set it to “last-visible, first-opened” then whenever I have two windows visible at the same time, it would pick the one that was opened before the other. But adding support for that would be hard for another reason: It would require figuring out whether there are multiple visible windows, rather than just using the current approach of having a single global variable that gets overwritten whenever a new window is made visible.

I think this is getting too complex personally.

**Comment by The-Compiler** [comment]
I agree a `first-opened` value should be trivial and probably useful for some people. @haasn do you want to work on this?
