### ISSUE TITLE
Youtube Fullscreen disabled

### ISSUE THREAD

**Issue by noheinen** [The-Compiler/qutebrowser#1061]
qutebrowser v0.4.1
Git commit: v0.4.0-385-geb1a1bb (2015-10-24 23:04:20 +0200)

CPython: 3.5.0
Qt: 5.5.0, runtime: 5.5.1
PyQt: 5.5

Fullscreen by youtube is disabled for me. Other websites function as expected. Have I done something incorrect or is this a bug?

**Comment by The-Compiler** [comment]
This is a missing feature in QtWebKit: [QTBUG-43625](https://bugreports.qt.io/browse/QTBUG-43625)

It's unlikely this ever gets implemented, but it should work in the future with the QtWebEngine/Chromium backend: #666 

In the meantime, you can use mpv to play videos fullscreen - see 9. in the [FAQ](https://github.com/The-Compiler/qutebrowser/blob/master/FAQ.asciidoc).
