### ISSUE TITLE
Prevent downloading until user confirmation.

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#1062]
Currently when downloading a file qutebrowser will initiate the download immediately before the user has been given the chance to accept the download.

I would prefer content is not downloaded until I have explicitly given it permission to do so.

**Comment by The-Compiler** [comment]
The reason this happens is because the connection is already open, and if you don't keep reading from it, some webservers will close the connection after a quite short time, i.e. not enough for you to enter a filename.

That's why qutebrowser starts downloading the file into RAM - after 16 MB it will download a lot slower though.

If you run wireshark, you'll notice other browsers (e.g. Firefox/Chromium) do the same, they just don't make it very obvious to the user.

**Comment by wasamasa** [comment]
Wait, what?

**Comment by Earnestly** [comment]
But I don't want them to...  just because firefox or chromium does the same thing is no excuse...

**Comment by The-Compiler** [comment]
No, but "things will break if it's not done this way" is.

**Comment by Earnestly** [comment]
Disappointing.

**Comment by The-Compiler** [comment]
FWIW, you can request downloading explicitly via `;d` or the context menu - that'll wait until you entered the filename, as it's possible then to do the request *after* the filename is entered.

**Comment by lamarpavel** [comment]
Why not download to RAM, then store as file in /tmp somewhere and then move the file once the user has entered a destination? Or am I misunderstanding the problem?

**Comment by The-Compiler** [comment]
@lamarpavel I'm not sure how this would help - sounds like more trouble (What if `/tmp` is smaller than the place you want to download the file to? What if the file is big and copying it over from `/tmp` takes some time?) for no gain at all.

**Comment by lamarpavel** [comment]
Probably not a good solution, but I have to admit I don't really understand the problem either.

**Comment by Earnestly** [comment]
The problem is that when a download starts it opens a connection and if the browser blocks this connection it will close the connection via the servers own TTL settings. So browsers initiate the download to keep the connection open.

**Comment by lamarpavel** [comment]
That part I understood, but I misread your first post and wasn't sure what the issue was with a premature download. Is it because of bandwidth usage or security concerns?

**Comment by Earnestly** [comment]
Mostly bandwidth usage.

**Comment by lamarpavel** [comment]
Well this could be solved by having an option to severly limit download speed until user interaction has taken place. Not sure how much effort it would be to add transfer rate limiting to qutebrowser, but other than that this shouldn't be too hard(tm).

**Comment by The-Compiler** [comment]
This already happens after Qt's buffer of 16 MB is full - then it downloads with 2kB/s if I'm not mistaken.

It would be trivial to make the buffer size configurable ([here](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/downloads.py#L352)) - would that solve this issue for you, @Earnestly?

**Comment by Earnestly** [comment]
16MB is fine, mostly this behaviour was surprising but in retrospect it does make a certain degree of sense (insofar as sense can be applied to the web).  Perhaps document this?  Unless I'm the only one not expecting it...
