### ISSUE TITLE
Userscript timeouts?

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#1063]
I'm not sure what the problem is but take for example this site: https://archive.org/download/DWK123

There it lists *ProleteR_-_02_-_Downtown_Irony.ogg* as a link which points to *https://archive.org/download/DWK123/ProleteR_-_02_-_Downtown_Irony.ogg*.

Currently for hints I am using a userscript due to this bug: https://github.com/The-Compiler/qutebrowser/issues/797

The userscript is:

```sh
#!/bin/dash

exec mpv --loop-file --cache-file=TMP "$QUTE_URL"
```

But when attempting to use this, after awhile qutebrowser tells me `Userscript exited with status 2`.

However if I manually run the userscript with the QUTE_URL explicitly set it works (after some time):

```
% QUTE_URL="https://archive.org/download/DWK123/ProleteR_-_02_-_Downtown_Irony.ogg" ~/.local/share/qutebrowser/userscripts/qute-mpv 
Playing: https://archive.org/download/DWK123/ProleteR_-_02_-_Downtown_Irony.ogg
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache is not responding - slow/stuck network connection?
 (+) Audio --aid=1 'Downtown Irony' (vorbis)
File tags:
 Artist: ProleteR
 Album: Curses From Past Times (EP)
 Album_Artist: ProleteR
 Comment: http://www.archive.org/details/DWK123

... [ snip ] ...

AO: [pulse] 44100Hz stereo 2ch float
A: 00:00:02 / 00:04:21 (0%) Cache: 10s+862KB
```

What could be going on?

**Comment by The-Compiler** [comment]
I've added a `> /tmp/qute-mpv-log 2>&1` to the userscript, and it seems `mpv` gets the wrong URL:

```
Playing: https://archive.org/download/ProleteR_-_02_-_Downtown_Irony.ogg
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 404: Not Found
```

This is because of the `<base href="/download/DWK123/">` tag which qutebrowser currently ignores when resolving relative links. See #739 - unfortunately not as easy to implement as I'd like to :unamused:
