### ISSUE TITLE
Sometimes the url is not updated to reflect current webpage.

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#1064]
This is hard to reproduce but there are times when navgiating to a page does not seem to update the url in the statusbar.  When I yank the url my clipboard contains the previous pages url instead.

**Comment by The-Compiler** [comment]
Duplicate of #870 - if you know a good way how to reproduce this, or other pages than GitHub/Youtube where this happens, I'd be glad!
