### ISSUE TITLE
Investigate which DLLs to package for Windows

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1068]
QupZilla has some DLLs packaged which qutebrowser hasn't:

- `audio/qtaudio_windows.dll`
- `iconengines/qsvgicon.dll`
- `mediaservice/wmfengine.dll`
- `printsupport/windowsprintersupport.dll`

I guess some of those could be useful for qutebrowser as well, and e.g. improve HTML5 video/audio compatibility?

**Comment by chenshuiluke** [comment]
I can't watch HTML5 youtube videos on Windows currently. If this will help, it'd be a great feature

**Comment by The-Compiler** [comment]
@UltraSabreman confirmed in #1655 that adding the DLLs from [dlls.zip](https://www.qutebrowser.org/tmp/dlls.zip) fixes things. Now I only need to find time to adjust my build script to include them... :wink:

**Comment by The-Compiler** [comment]
This should now be fixed with the v0.8.2 release.

cc @gregist @LaVolte @JohnMurga @UltraSabreman

**Comment by JohnMurga** [comment]
Both the 64 and 32 bit builds worked for me ...
Thanks !!

**Comment by The-Compiler** [comment]
Awesome, thanks for the follow-up! While I have some windows users gathered here, would anyone of you be interested in helping out with switching packaging systems (from cx_Freeze to [PyInstaller](http://www.pyinstaller.org/)) and writing a setup for qutebrowser (e.g. using NSIS)? cx_Freeze (what I'm using currently) can autogenerate `.msi` setups, but it's almost unmaintained and is what's keeping me from doing Windows builds with an updated Python and PyQt...
