### ISSUE TITLE
confirm-quit

### ISSUE THREAD

**Issue by thebaum** [The-Compiler/qutebrowser#1086]
Confirm-quit doesn't apply if the browser is closed by typing ":q"

**Comment by The-Compiler** [comment]
I can't reproduce this. I set `confirm-quit` to `multiple-tabs`, and I get a confirmation when I do `:q`. How did you test this precisely? Maybe you're running into #846?

**Comment by thebaum** [comment]
I just figured out that the whole browser crashs once i enter `:q` , thus `confirm-quit` should be fine

**Comment by The-Compiler** [comment]
You mean "quits", not "crashes" :wink: Closing this as that's how `:quit` is intended to work.
