### ISSUE TITLE
Owncloud RSS app rendering incorrect

### ISSUE THREAD

**Issue by z1lt0id** [The-Compiler/qutebrowser#1090]
So I thought I would post this as this rendering error stops me from using Owncloud on Qutebrowser.  When you use the rss reader Qutebrowser renders it like this.

![Qutebrowser Rendering](http://i.imgbox.com/UsCaG2Ll.png)

And below is how Firefox renders it.

![Firefox Rendering](http://i.imgbox.com/2WKRQfwZ.png)

What information can I get to help you guys look into this issue. :)

**Comment by The-Compiler** [comment]
Meh... Can you try with the [minimal webkit testbrowser](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/minimal_webkit_testbrowser.py) or another QtWebKit project such as Otter Browser?

If it happens there as well, it's a QtWebKit issue (which I suspect) and there isn't much I can do about it - chances are things will be better with the QtWebEngine backend (#666) in the future.

**Comment by z1lt0id** [comment]
Not a problem, I'll try it out.  Sorry if it seems trivial :(

**Comment by z1lt0id** [comment]
You were right, it all boils down to the QtWebEngine.  Sorry for 
inconveniencing you.

**Comment by The-Compiler** [comment]
No worries! Sorry I can't do much about this.

**Comment by The-Compiler** [comment]
Something you could try (but I don't think it'll help) is to do `:set network user-agent` and then chose Chromium on Linux from the list.

If it's something on Owncloud's side, that could maybe help.
