### ISSUE TITLE
Is there a way to use '?' in a binding?

### ISSUE THREAD

**Issue by mvucBmM0** [The-Compiler/qutebrowser#1106]
Is there a way to use '?' in a binding?
Can't seem to make it work either with keys.conf or :bind...

And thanks for you work on qutebrowser. My choice now that dwb is defunct.

**Comment by The-Compiler** [comment]
You can use it as part of a binding (e.g. `:bind x? message-info test` works fine here) - however you currently can't have a binding which starts with it due to #672.

I hope I'll get around to fix that one soon, sorry for that!

**Comment by mvucBmM0** [comment]
Oh, that's a bummer.
Actually I'm used to using ? for loading quickmarks in new tabs (cause i use ' for quickmarks in current tab, and they're both on the same key).
I'll wait for that fix then, thanks.
