### ISSUE TITLE
memory leak (?) on some websites making the system unresponsive

### ISSUE THREAD

**Issue by diatomine** [The-Compiler/qutebrowser#1113]
hi,
I've been having problems sometimes with websites that won't load while the system becomes super slow. The window manager does not react to keyboard shortcuts, the pointer movement is laggy.

io9.com is an example. It happens every time I try to load that site. But I think I had the problem with various different websites, I can't remember other addresses tho.

I can start a terminal after a minute or so and kill the browser (using xkill). After that, it won't start anymore (I think). Rebooting fixes that.

I managed to open htop, now, and I saw that the python process used up nearly all the RAM (more than 3G), and also the swap is filled to 1.5G or so (it's barely ever used by anything).

I have ~3.5G of RAM and the CPU is a dual-core i3 1.3Mhz or something like that. WM is i3wm.

**Comment by The-Compiler** [comment]
> the CPU is a dual-core i3 1.3Mhz

I'm not surprised then! :stuck_out_tongue: 

Can you please show the qutebrowser/Qt/PyQt versions when you do `:open qute:version`?

**Comment by diatomine** [comment]
Haha :P the site loads ok in google-chrome though, RAM usage climbs to around 1G, which still sounds like a lot me for a website (maybe I'm getting old lol), but it doesn't crash or get unresponsive or something

qutebrowser v0.4.1
Git commit: v0.4.0-650-g04c2e45 (2015-11-13 07:56:59 +0100)
CPython: 3.4.3
Qt: 5.4.1, runtime: 5.4.1
PyQt: 5.4.1

**Comment by The-Compiler** [comment]
I'm pretty sure you're running into [this Qt issue](https://codereview.qt-project.org/#/c/108782/) - can you please try upgrading to Qt 5.4.2 or 5.5.1? Also, what distribution is this?

**Comment by diatomine** [comment]
I upgraded to qt 5.5.1 and now qutebrowser fails to open saying it can't find the PyQt5 module. I also updated python-qt5 stuff for python3 and 2, and rebooted the system, so dunno..

I'm doing a full system upgrade now and see what happens

The dist is arch

**Comment by The-Compiler** [comment]
Partial upgrades are unsupported on Arch - so yeah, please do a full upgrade.

**Comment by diatomine** [comment]
ok I did it and io9.com does not crash anymore. Sometimes system updates do solve problems instead of creating new ones lol

Sorry for taking your time with something trivial and thanks for your help!
