### ISSUE TITLE
bind to :

### ISSUE THREAD

**Issue by vyp** [The-Compiler/qutebrowser#1115]
I was sure I saw this somewhere else before, but I cannot seem to find it now... so sorry in advance is this a duplicate..

How do I bind something to `:`, i.e. just open the command line?

So far I have tried:

```
set-cmd-text
    '

set-cmd-text ''
    '

enter-mode command
    '
```

But none of them worked. The first two of course complained that the `text` argument is required. The last one did *work*, but looks like 'command' mode is not the same as the command line (what you get when you press `:`).

**Comment by nisseblink** [comment]
```
set-cmd-text :
    '
```
Should work.

**Comment by vyp** [comment]
Yup, it works! Thanks @nisseblink, I initially thought that wouldn't work and would just set it to `::` instead.
