### ISSUE TITLE
Strange scroll behavior using mouse wheel

### ISSUE THREAD

**Issue by jlnbdt** [The-Compiler/qutebrowser#1123]
Hi,

I get a strange behavior when I try to scroll any web page with the mouse wheel.
When I start scrolling, display and scroll percent "jump" erratically. When I stop scrolling, sometimes I finally get the previous position, sometimes I get a random postion (eg: scroll percent is 64% ; pushing the wheel up, I get 69%, then 60%, then, 50%… When I finish using the wheel : 64%)

I have no problem when I use keyboard.

I run qutebrowser with Debian in Virtualbox (Windows 10 is the host). I don't have this problem with other app'.

```
$ qutebrowser --version
qutebrowser v0.4.1
Git commit: v0.4.0-662-g7de206e (2015-11-15 16:38:56 +0100)

CPython: 3.4.2
Qt: 5.3.2, runtime: 5.3.2
PyQt: 5.3.2
```

Thank you

**Comment by The-Compiler** [comment]
Weird, I've never seen that. This is a physical mouse wheel (not a touchpad), right? Can you check if you can change how Virtualbox emulates the mouse in the VM settings and see if that makes any difference?

**Comment by jlnbdt** [comment]
Absolutely, it's a physical mouse wheel.

- I've tried with the touchpad : no problem, scrolling is fine
- I've tried 3 different settings in VM (PS/2 mouse, tablet, multitouch tablet), the problem persists.

**Comment by The-Compiler** [comment]
Can you try launching `python scripts/minimal_webkit_testbrowser.py http://...` and see if it happens there as well? I'm suspecting it's an upstream Qt issue.

Note you can run qutebrowser natively on Windows as well, there are even Windows installers and standalone executables [in the releases](https://github.com/The-Compiler/qutebrowser/releases). It'd be interesting to know if it happens there as well, without a VM involved.

**Comment by jlnbdt** [comment]
You're right, I get the same problem with this test script.

It's not happening with qutebrowser natively on Windows.

**Comment by The-Compiler** [comment]
Closing this then - seems to be some upstream issue involving Virtualbox and QtWebKit I guess. Sadly I don't have time to dig into this further, and if it's QtWebKit specific, chances are upstream won't care.
