### ISSUE TITLE
Hints Affected by Zoom

### ISSUE THREAD

**Issue by NoSuck** [The-Compiler/qutebrowser#1126]
An option for preserving size of hints independently of zoom level would be nice.

Usage example:  A page displays a collection of links in a ridiculously large font.  Zooming out shows more links, but moving to a link is now difficult, as the hintchars are indiscernibly small.

The same principle would apply to a photo album, as well.

**Comment by The-Compiler** [comment]
I'm not sure if this is possible with the current way the hints are implemented - is there a CSS attribute to say "this element is not affected by zoom"?

But I guess it would make sense.

**Comment by NoSuck** [comment]
I don't know about ignoring zoom, but perhaps `min-`/`max-` `height`/`width` could keep hint dimensions in check.
