### ISSUE TITLE
Issues with caret mode on OS X and Windows

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1142]
I [wrote some end to end tests](https://github.com/The-Compiler/qutebrowser/blob/master/tests/integration/features/caret.feature) for caret mode, however they seem to have multiple issues on OS X and Windows.

@artur-shaik Any chance you can take a look at this? If you don't have a Windows/OS X available, I'd recommend creating a WIP PR where you revert a43c2068935803e559457f225031d97d68b00b4b and b344f92a9004f5725d0bf134d71b3e876a3d3d12, then you can let AppVeyor/Travis test things.

# Test setup

The test opens [a HTML file](https://github.com/The-Compiler/qutebrowser/blob/master/tests/integration/data/caret.html) which displays the following content:

```
one two three
eins zwei drei

four five six
vier fünf sechs
```

It then enters caret mode and runs the test. The test then runs some commands and compares the clipboard contents.

# Issues on OS X

It seems some commands move one line too much?

### Commands

* `:move-to-end-of-next-block` (count 2)
* `:toggle-selection`
* `:move-to-end-of-prev-block`
* `:move-to-prev-word`
* `:yank-selected`

### Expected

```
drei

four five six
```

### Actual

```
three
eins zwei drei

four five six
```

### Commands

* `:toggle-selection`
* `:move-to-start-of-next-block`
* `:yank-selected`

### Expected

```
one two three

```

(trailing newline)

### Actual

```
one two three
eins zwei drei
```

# Issues on Windows

It seems some commands move one char too much?

### Commands

* `:move-to-end-of-document`
* `:move-to-start-of-document`
* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

`one`

### Actual

`one ` (trailing space)

### Commands

* `:move-to-end-of-next-block` (count 2)
* `:move-to-end-of-prev-block`
* `:toggle-selection`
* `:move-to-prev-word`
* `:yank-selected`

### Expected

`eins ` (trailing space)

### Actual

`eins z`

### Commands

* `:move-to-start-of-next-block`
* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

`eins`

### Actual

`eins ` (trailing space)

### Commands

* `:move-to-end-of-line`
* `:move-to-start-of-line`
* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

`one`

### Actual

`one ` (trailing space)

### Commands

* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

`one`

### Actual

`one ` (trailing space)

### Commands

* `:move-to-end-of-word`
* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

` two` (leading space)

### Actual

`two ` (trailing space)

### Commands

* `:move-to-next-word`
* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

`two`

### Actual

`wo ` (trailing space)

### Commands

* `:move-to-next-word`
* `:toggle-selection`
* `:move-to-next-word`
* `:yank-selected`

### Expected

`two ` (trailing space)

### Actual

`wo t`

### Commands

* `:move-to-end-of-word`
* `:toggle-selection`
* `:move-to-prev-word`
* `:yank-selected`

### Expected

`one`

### Actual

`one ` (trailing space)

### Commands

* `:move-to-end-of-word`
* `:move-to-prev-word`
* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

`one`

### Actual

`one ` (trailing space)

### Commands

* `:move-to-end-of-word`
* `:toggle-selection`
* `:move-to-prev-char`
* `:yank-selected`

### Expected

`e`

### Actual

` ` (single space)

### Commands

* `:move-to-end-of-word`
* `:move-to-prev-char`
* `:toggle-selection`
* `:move-to-end-of-word`
* `:yank-selected`

### Expected

`e`

### Actual

` two ` (leading/trailing space)

## Scenario: :yank-selected message / :yank-selected with --keep

Failing because the count in the messages is one higher than expected.

**Comment by artur-shaik** [comment]
Hi, I'll look deeper in this issue, but unfortunatly cannot test it on Windows/OSX.

**Comment by The-Compiler** [comment]
Thanks! I edited the comment above to include the commits where I introduced the `xfail` markers (expected to fail). Let me know if I can help in any way!

**Comment by The-Compiler** [comment]
I fixed "Moving and selecting a line" and "Selecting next line" (the cases where "actual" was empty) in d6acb3c3f4a376c04279d341e90764ebe4f2dd78 by waiting until the clipboard is actually updated.

**Comment by artur-shaik** [comment]
Tests are fine in #1145 , but I did nothing special for OS X.

**Comment by The-Compiler** [comment]
Nice, thank you! I think d00f999 and 3a5ce22 fixed OS X :+1: 

I'll review and merge the PR later today.
