### ISSUE TITLE
Add timestamps to logging output

### ISSUE THREAD

**Issue by flv0** [The-Compiler/qutebrowser#1149]
I'd like to have optional timestamp prefixes in the logging mechanism to stdout. 

One could do it like either of this i guess:
- introduce a logging-timestamps boolean option, which would use completion -> timestamp-format which would then become [general|ui] -> timestamp-format
- introduce [general/ui] -> logging-timestamp-format which is by default an empty string. this would allow the format do be differently from the completion format.

What do you think? I'd prefer the latter I guess. And would you make it general or ui?

**Comment by The-Compiler** [comment]
There are already timestamps when launched with `--debug` - do you think this suffices already?

I'm not sure if the format needs to be configurable - do you really need date output there? If not, I'm not sure if the time format needs to be configurable.

**Comment by flv0** [comment]
Ah wasn't aware of that, should suffice for me. However one *could* add an option similar to what we just did with log-javascript-console, like logging-timestamps -> [none, debug, info].

**Comment by The-Compiler** [comment]
We're running into a chicken-egg problem then - I'd like to initialize the log as early as possible, definitely before the config is initialized.

We could probably change the log format after the config is inited, but I don't think it's worth the hassle. If you agree, let's close this?

**Comment by flv0** [comment]
agreed
