### ISSUE TITLE
Tab completion for undo

### ISSUE THREAD

**Issue by brianbuccola** [The-Compiler/qutebrowser#1153]
`:undo` allows you to reopen  a closed tab, optionally skipping `[count]` closed tabs. The problem is that I normally don't know the exact number of closed tabs I have to skip in order to reopen tab X. So I end up hitting `u` several times until tab X reopens, and then I have to reclose all the intermediate tabs.

It would be nice if `:undo` provided a tab-completable history of all closed tabs (or the last `n` closed tabs, where `n` is the value of `tab-history-max-items`), just like `:open` provides a tab-completable history of the last `web-history-max-items` previously viewed pages.

I would then `bind U set-cmd-text -s :undo`, so that I can hit `u` to undo the last closed tab, and `U` to go farther back in my closed tab history.

**Comment by The-Compiler** [comment]
Thanks for the suggestion! I added this to #32, but it's probably going to take a while until I get to work on this.
