### ISSUE TITLE
uCollective comments not working

### ISSUE THREAD

**Issue by NeoGeetz** [The-Compiler/qutebrowser#1157]
I'm trying to browser ucollecitve.org with qutebrowser but I can't comment on any uploads. (insert mode is not working with their interactive comment box thingy)

**Comment by The-Compiler** [comment]
Seems like we share a great music taste :wink:

Unfortunately comments there are broken in other QtWebKit browsers as well. There's not much I can do about this, but it'll work in the future with the QtWebEngine backend (#666) if you're on a distribution which packages it.

**Comment by flv0** [comment]
What? Didn't know that page! Awesomeness, thanks man!

**Comment by NeoGeetz** [comment]
lol at least I know I'm not the only one invested in it working w/ ucollective :P
