### ISSUE TITLE
Feature Request: The ability to center the tab title

### ISSUE THREAD

**Issue by dylanaraps** [The-Compiler/qutebrowser#1165]
Hello, 

I'm not sure about whether or not this is possible already but I'd love to be able to center the tab's title.  Here's what it looks like in firefox:

![firefox](https://camo.githubusercontent.com/d96bfad0531d317cd420e61cd99faf52d1aa8527/687474703a2f2f692e696d6775722e636f6d2f6f6e45427065432e706e67)

And in qutebrowser:
![qutebrowser](https://cloud.githubusercontent.com/assets/6799467/11613420/bee5befa-9c73-11e5-8634-d22b08b4c739.png)

Thanks!

**Comment by lamarpavel** [comment]
There currently is no option for text alignment, as far as I can tell.
You can somewhat fake it with `:set tabs padding {top, bottom, left, right}`, setting left and right to a higher value like 25-30, but that would only be an approximation of what you want.

Your theme is nice though, I can see why you want the option. I'll look into it if I can find the time.

**Comment by The-Compiler** [comment]
That is a beautiful desktop indeed!

It'd be quite easy to add an option:

- In `qutebrowser/mainwindow/tabwidget.py` in `drawControl`, change `alignment = Qt.AlignLeft | Qt.AlignVCenter | Qt.TextHideMnemonic` to use an option for `AlignLeft` instead
- Add a new `TextAlignment` (or so) config type (based on `MappingType`, and a new option based on that.

**Comment by dylanaraps** [comment]
I got the centered text working in my build and I'm working on adding the config type now.

Thanks guys!

**Comment by The-Compiler** [comment]
@dylanaraps Where are you stuck? I'm more than happy to help.

**Comment by dylanaraps** [comment]
I managed to add a config option to configdata.py and I'm now stuck trying to change AlignLeft to the new config option.

I've got no experience with python and I'm going in almost blind here.

Thanks for the help!

**Comment by The-Compiler** [comment]
You'll need to add a new config type if you haven't already, which should look pretty similar to `Position` in `configtypes.py`, only with `left`/`center`/`right` as possible values, and `Qt.AlignLeft`, `Qt.AlignHCenter` and `Qt.AlignRight` as mapped values in `MAPPING`. You'll also need to change `from PyQt5.QtCore import QUrl` in that file to append `, Qt` so you can access those values.

What that means is that you then can do `config.get('tabs', 'text-alignment')` (or whatever you added the option as), and will get back `Qt.AlignLeft`, etc. based on what the user set the value to.

Then you can do something like this in `tabwidget.py`:

```python
            alignment = (config.get('tabs', 'text-alignment') |
                         Qt.AlignVCenter | Qt.TextHideMnemonic)
```

The `|` is a [bitwise OR](https://en.wikipedia.org/wiki/Bitwise_operation#OR) of [Qt.Alignment flags](http://doc.qt.io/qt-5/qt.html#AlignmentFlag-enum).

I hope this made it clearer. If you're still struggling I can implement this for you, but I like to teach people things :wink:

**Comment by dylanaraps** [comment]
I've hit another hurdle, I think I've done everything above and I'm getting this error on open. Any ideas?

````
ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabwidget.py", line 570, in drawControl
    self.drawControl(QStyle.CE_TabBarTabLabel, opt, p, widget)
  File "/usr/lib/python3.5/site-packages/qutebrowser/mainwindow/tabwidget.py", line 581, in drawControl
    Qt.AlignVCenter | Qt.TextHideMnemonic)
TypeError: unsupported operand type(s) for |: 'str' and 'AlignmentFlag
````

Thanks for all the help!

**Comment by The-Compiler** [comment]
Looks like your config type is actually `String` or so instead of the mapping type which would return an `Alignment` flag. If you don't spot it, I suggest you open a work-in-progress pull request so I can look at the code :smile:

**Comment by dylanaraps** [comment]
I see! 

I think I've figured it out now. :+1:

**Comment by dylanaraps** [comment]
I opened the pull request!

**Comment by The-Compiler** [comment]
#1167 was merged, so I'm closing this. :smile:
