### ISSUE TITLE
Index for last (as in final) tab

### ISSUE THREAD

**Issue by brianbuccola** [The-Compiler/qutebrowser#1166]
The command `tab-focus` takes an index, which can be the special index `last`,
which denotes the index of the most recently used tab. This is useful because
you can, for example, bind `<Backspace>` to `tab-focus last` to bounce back to
the most recently used tab. (qutebrowser has `<Ctrl-Tab>` bound to this by
default; it's also the same as `<C-^>` in vim/vimperator.)

**Question:** Is there an index for the actual last (as in final) tab of the
tab list? In some programming languages, the index of the final element of a
list/array is -1, but `tab-focus -1` doesn't work here.

What I want to do is bind `g0` (or `g^`) to `tab-focus 1` (which is easy), and
bind `g$` to `tab-focus <final>` (just like in vimperator).

Right now, I have the following workaround:

    tab-focus 1 ;; tab-prev
        g$

...but the problem with this is that `<Backspace>` (see above) doesn't work
properly: If I start on tab 3, then hit `g$` to go to tab 7, then `<Backspace>`
brings me to tab 1, not tab 3.

So am I missing something? Is there such an index? If not, would it be easy to
implement?

Thanks.

**Comment by The-Compiler** [comment]
I have a déjà-vu now... Did you (or someone else?) ask the same thing somewhere else some days ago? I remember seeing the same question but not answering yet :laughing: 

Anyways - there's no such functionality yet, but adding it should be trivial. Any chance you want to try and submit a PR? I'm happy to help if you get stuck somewhere.

It'd basically mean handling this case (of `idx` being <0) in `qutebrowser/browser/commands.py` in `tab_focus`, and writing some tests for that in `tests/integration/features/tabs.feature`.

**Comment by brianbuccola** [comment]
Yeah, I asked the same thing [on the Arch Linux forum thread](https://bbs.archlinux.org/viewtopic.php?pid=1580543#p1580543). ;)

Alright, I'll take a stab at it. Thanks!

**Comment by The-Compiler** [comment]
Closing this as #1411 was merged.
