### ISSUE TITLE
Can't spawn any user scripts: Error 277, process failed to start

### ISSUE THREAD

**Issue by pghpete** [The-Compiler/qutebrowser#1172]
I am unable to get any user scripts to launch, all produce the following errors.  (Am I missing something simple?)

This script: copied from github How to write userscripts page...

```bash
#!/bin/bash
echo "open -t http://www.dict.cc/?s=$QUTE_SELECTED_TEXT" >> "$QUTE_FIFO"
```

located here...
```
[user@vostro userscripts]$ pwd
/home/user/.local/share/qutebrowser/userscripts
[user@vostro userscripts]$ ll dictionary.sh 
-rwxr-xr-x 1 user users 86 Dec  7 08:52 dictionary.sh
```

and launched using "spawn --userscript dictionary.sh" produces the following error
```
10:20:00 ERROR    message    message:error:277 Error while spawning userscript: The process failed to start.
```

I couldn't find a similar issue already created but if there is one and this is a duplicate, apologies.

**Comment by The-Compiler** [comment]
What qutebrowser version are you on? (See `:open qute:version` or launch it with `--version`)

**Comment by pghpete** [comment]
qutebrowser v0.4.1
Git commit: 

CPython: 3.5.0
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1

**Comment by pghpete** [comment]
odd though cause pacman -Q is showing...
$ pacman -Q qutebrowser
qutebrowser 0.4.1-2

**Comment by The-Compiler** [comment]
How is that odd?

The ability to launch userscripts from `~/.local/share/qutebrowser/userscripts` is not in 0.4.1, only in git (and will be in 0.5.0), so you'll need to use the absolute path for now.

Please let me know if that works?

**Comment by pghpete** [comment]
just thought it was odd that the --version didn't also report the -2 but I guess that's very minor lol

fantastic. that worked. and thank you very much for the amazing response time!

**Comment by The-Compiler** [comment]
Well, the `-x` suffix is the Archlinux packaging version (i.e. if the `PKGBUILD` changed without any upstream changes), so naturally qutebrowser won't know about that :wink:

You're welcome!
