### ISSUE TITLE
Timeout after auto-followed hint

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1184]
I think there should be an `auto-follow-timeout` option to inhibit key bindings after a successful auto-follow hint activation. For example if you write "newer" to match a hint in the numeric mode, but it gets auto-followed after "newe", then "r" reloads the current page before the new one is loaded. There are many other examples of similar side-effects.

**Comment by The-Compiler** [comment]
yup, see #72 :wink:

**Comment by lahwaacz** [comment]
Oops, sorry for the duplicate...

**Comment by The-Compiler** [comment]
No worries, that happens with something close to 1000 issues :wink:
