### ISSUE TITLE
Google Drive Visual Errors

### ISSUE THREAD

**Issue by logankaser** [The-Compiler/qutebrowser#1187]
![screenshot](https://cloud.githubusercontent.com/assets/7916909/11889997/5a85b08e-a504-11e5-8013-66cca01fd960.png)

Google drive has some display errors possibly related to width.
I strongly suspect that this is a QT/Webkit issue but I was unable to find
a ticket.

Test System:
arch Linux x86_64
qutebrowser 0.4.1-2
and qutebrowser-git from the AUR (lastest)

javascript on, tested from fresh
install with same results. Also tested with 
firefox and chrome user agents.

**Comment by The-Compiler** [comment]
I can't reproduce this, it looks good here - can you try with `--temp-basedir`? I'm guessing your Qt version in `:open qute:version` is 5.5.1?

**Comment by logankaser** [comment]
I have 5.5.1, with --temp-basedir it displays properly. I'll investigate tonight to see if I have something on my end that is causing this, sorry for the trouble.

**Comment by logankaser** [comment]
My issue was with Pacman and cache and was completely unrelated to this code, so I'm closeing this.

**Comment by logankaser** [comment]
I recently discovered the specific config value that was causeing the error, I has set my user agent to firefox so that I could use netflix, apperantly google uses useragents to display browser specific super ultra optimised code. Hence the bizzar visual bugs.
