### ISSUE TITLE
Adblocking not starting automatically

### ISSUE THREAD

**Issue by mvucBmM0** [The-Compiler/qutebrowser#1188]
I have 'host-blocking-enabled = true' but every time i start qutebrowser it is showing ads.
I have to do an :adblock-update and refresh for it to start blocking.
And next time i start the browser the ads are there again.
Is this the intended behaviour?

**Comment by lamarpavel** [comment]
>Is this the intended behaviour?

No. Is your config directory write protected? Or are you starting qb with --temp-dir?

**Comment by mvucBmM0** [comment]
Neither.

**Comment by mvucBmM0** [comment]
My bad.
I had a 'sanitize' script to clean up some files it leaves behind in .local/share and din't notice it was deleting a blocked-hosts file.
You can close this now and sorry again.

**Comment by The-Compiler** [comment]
No worries!
