### ISSUE TITLE
Search engines with a dash don't work

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1189]
E.g. `:set searchengines wikipedia-en https://en.wikipedia.org/w/index.php?search={}`, then `:open wikipedia-en foo` opens up the default search engine.

**Comment by The-Compiler** [comment]
I don't see any reason to constraint this to word-chars (`\w`) like it was before - so now any non-space character should work.

**Comment by lahwaacz** [comment]
Thanks :)
