### ISSUE TITLE
Focus input element and enter insert mode

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1191]
Some pages automatically focus a prominent input field when loaded, but many don't. In such cases, writing into an input field in qutebrowser involves entering the insert mode and tab-navigating through dozens of other elements (links, buttons...) until the input field is finally focused. Or, ehm, using the mouse...
In pentadactyl, there is a useful shortcut (I think `gi` by default), which focuses the first input field and enters the insert mode with just one operation. Could something similar be added to qutebrowser? Or have I just missed the feature?

**Comment by The-Compiler** [comment]
You could simply use hints (`f`) to click on that element :wink:

But I agree such a feature would be useful, see #219.

**Comment by lahwaacz** [comment]
Thanks for the advice ;) Simpler than using Tab or the mouse, but harder than `gi`. Definitely not the obvious way to do it...
