### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1192]
Is it possible to enable spellcheck for input fields in QtWebKit? Is it suitable as core feature or a plugin?

**Comment by The-Compiler** [comment]
Sorry for the late answer - I was sick the past few days, but finally feeling better!

Unfortunately, QtWebKit officially doesn't expose that functionality officially - however, there's [qtwebkit-plugins](https://github.com/QupZilla/qtwebkit-plugins) by the QupZilla project which adds that functionality. It also works with qutebrowser, but only underlines misspelled words.

It'd be nice to have some nicer integration for that, and the topic definitely needs to be checked again for QtWebEngine (the future backend) - see #700 for that.

**Comment by The-Compiler** [comment]
FWIW I now packaged `qtwebkit-plugins` in the Archlinux AUR: https://aur.archlinux.org/packages/qtwebkit-plugins-git/
