### ISSUE TITLE
High RAM use

### ISSUE THREAD

**Issue by fosskers** [The-Compiler/qutebrowser#1204]
I love qutebrowser. Unfortunately:

- I use an older laptop (2010) which only has 4g of RAM.
- I work with the JVM a lot, which is a hog.
- `qutebrowser` uses about 35% of my RAM during typical usage, and I often have to close it to stop my computer from locking up when I'm compiling.

I've been running firefox for the past few hours, having the same tabs I'd have open with QB, and it's sitting at a happy 15% RAM use.

Any thoughts?

**Comment by The-Compiler** [comment]
Chances are this is due to QtWebKit, and there isn't much I can do about it. Can you try if things are better after the same usage for some while with [Otter Browser](http://otter-browser.org/)?

**Comment by fosskers** [comment]
I have the following tabs open on all three browers:

- Github
- Hacker News
- Bitbucket
- Reddit
- Youtube
- Gmail x 3

Gmail is by far the worst RAM hog.

In this state, we have the following RAM use:

- QB: 23%
- Otter: 14.7%
- Firefox: 27%

As a sidenote on performance, Otter performs worst, followed by Firefox and then QB. Sometimes QB dies (flies up to 100% CPU) on various pages, though.

Closing all the tabs but github, we see:

- QB: 15.9%
- Otter: 16.6%
- Firefox: 15%

**Comment by The-Compiler** [comment]
Huh? That seems to contradict what you've said above (where you said Firefox' RAM usage was much lower), no?

Either way - qutebrowser's and Otter's RAM usage seem quite similar, so this looks like a QtWebKit thing. It might get better in the future with QtWebEngine (#666), but I can't promise anything.

**Comment by fosskers** [comment]
Yeah, I realize the contradiction. I seem unable to reproduce it right now, but QB often sits around 35% with one tab open.
