### ISSUE TITLE
gitlab contribution calendar not shown

### ISSUE THREAD

**Issue by martingabelmann** [The-Compiler/qutebrowser#1205]
hey guys,

visiting my profile on gitlab.com does not show the contribution calendar. instead there is a blank space between my icon and the activities.

heres my debug output:
```
13:00:09 DEBUG    commands   command:run:490 command called: reload
13:00:09 DEBUG    commands   command:run:504 Calling qutebrowser.browser.commands.CommandDispatcher.reloadpage(<qutebrowser.browser.commands.CommandDispatcher>, False, None)
13:00:09 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=4 url='https://gitlab.com/u/martingabelmann'>: LoadStatus.loading
13:00:09 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('loading') (tab 4)
13:00:09 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 4)
13:00:09 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.insert! (leave reason: load started)
13:00:09 DEBUG    modes      modeman:maybe_leave:113 Not in mode KeyMode.hint! (leave reason: load started)
13:00:09 DEBUG    modes      modeman:_eventFilter_keypress:195 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=4 url='https://gitlab.com/u/martingabelmann'>)
13:00:09 DEBUG    destroy    lineparser:_prepare_save:81 Saving to /home/martin/.local/share/qutebrowser/cookies
13:00:09 DEBUG    modes      modeman:_eventFilter_keyrelease:215 filter: True
13:00:10 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:10 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_text_changed('https://gitlab.com/u/martingabelmann') (tab 4)
13:00:10 DEBUG    webview    tabbedbrowser:on_title_changed:473 Changing title for idx 4 to 'https://gitlab.com/u/martingabelmann'
13:00:10 DEBUG    webview    tabbedbrowser:on_title_changed:465 Ignoring title change to ''.
13:00:10 DEBUG    webview    tabbedbrowser:on_title_changed:473 Changing title for idx 4 to 'Martin Gabelmann · GitLab'
13:00:10 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:10 DEBUG    save       savemanager:mark_dirty:73 Marking history as dirty.
13:00:11 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:11 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:11 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:11 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:11 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:11 DEBUG    save       savemanager:mark_dirty:73 Marking cookies as dirty.
13:00:12 DEBUG    webview    webview:_set_load_status:182 load status for <qutebrowser.browser.webview.WebView tab_id=4 url='https://gitlab.com/u/martingabelmann'>: LoadStatus.success_https
13:00:12 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed('success_https') (tab 4)
13:00:12 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(True) (tab 4)
```

**Comment by The-Compiler** [comment]
Works fine for me on https://gitlab.com/u/martingabelmann:

![cal](https://cloud.githubusercontent.com/assets/625793/12064586/d593acb4-afc6-11e5-95c3-504b05c9d9d9.png)

What version of qutebrowser and Qt (see `:open qute:version`)? Do you have some nonstandard user-agent set?

**Comment by martingabelmann** [comment]
happy new year and thanks for the fast reply
everything is up2date, qutebrowser build from master via tox.  
qute:version says:  
```
qutebrowser v0.4.1
Git commit: v0.4.0-1176-g8b76eb5 (2015-12-30 14:57:21 +0100)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1
Style: QFusionStyle
Desktop: None
sip: 4.16.9
colorlog: yes
colorama: 0.3.3
pypeg2: 2.15
jinja2: 2.8
pygments: 2.0.2
yaml: 3.11
cssutils: 1.0.1 $Id$
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2e 3 Dec 2015

Frozen: False
Platform: Linux-4.2.3-1-ARCH-i686-with-arch, 32bit
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"



--- /etc/arch-release ---```

**Comment by The-Compiler** [comment]
Can you try when starting with `--temp-basedir`? If that works, I'm guessing something in your config is triggering it.

**Comment by martingabelmann** [comment]
sorry did not help. user agent is set to ``'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36'``

**Comment by The-Compiler** [comment]
Weird... our setups are pretty much identical at this point. And you see something different from my screenshot on the exact page I linked above?

**Comment by martingabelmann** [comment]
thats how i see it:
![screen](https://cloud.githubusercontent.com/assets/12297655/12071117/a7716086-b09a-11e5-8fd9-591440e03f74.png)

**Comment by martingabelmann** [comment]
aha! if im logging out then its there!

**Comment by The-Compiler** [comment]
Heh - I was about to suggest that, but you definitely shouldn't be logged in with `--temp-basedir`.

I noticed something weird about GitLab's contribution calenders at work some days ago - I think when you logged in they only show things in projects you're involved with. How does it look when logged in with another browser?

**Comment by martingabelmann** [comment]
that was my fault i logged in to get to my contributions calendar (didnt thought that this is another scenario)... it is working with both uzbl and firefox (lwith and without been logged in)...

**Comment by The-Compiler** [comment]
Okay - can you try with another QtWebKit browser like [Otter](http://otter-browser.org/) please? If it happens there as well, it should be solved upstream either by QtWebKit (which is very unlikely), or GitLab.

Either way it'll probably be fixed in the future by the new QtWebEngine backend, see #666.

**Comment by martingabelmann** [comment]
happened in otter-browser too. I tried ``qutebrowser-0.4.1-windows-standalone-amd64.zip`` on my girlfriends windows machine and there everything works fine. Im not sure if there are many diffrences between Qt for windows and unix, but maybe it can help finding the right place searching for the problem.

**Comment by The-Compiler** [comment]
Okay, I'm afraid I'll close this then - I don't have the time to track this down and fix it inside Qt, they are unlikely to do so as QtWebKit is deprecated, and I'm quite confident it'll be fixed with QtWebEngine.

**Comment by martingabelmann** [comment]
ok, thanks a lot!
