### ISSUE TITLE
Yank image location URL

### ISSUE THREAD

**Issue by derlaft** [The-Compiler/qutebrowser#1206]
This functionality seems to be missing.

**Comment by The-Compiler** [comment]
I think this is covered by the "yank hint location" line in #521.

**Comment by derlaft** [comment]
Are you sure? I want to copy <a src="X", not <a href="X"

**Comment by The-Compiler** [comment]
Fair enough - I added a comment there :smile:

**Comment by derlaft** [comment]
Ah. I haven't noticed #521 is open :)

**Comment by cdosborn** [comment]
From the above thread #521 
*Yank image*
```
hint images yank
```
*Open image in current tab* (actual image not link)
```
hint images run open {hint-url}
```
