### ISSUE TITLE
How to determine a program to open a download with

### ISSUE THREAD

**Issue by NoctuaNivalis** [The-Compiler/qutebrowser#1211]
As suggested in #39, it'd be very useful to offer opening downloads in stead of saving them. However, the program to open the download with should be determined somehow. There's some options here:
- We ask the user which program to open the download with. This may be preset in the settings, or asked at the moment of opening if not.
- We provide a list of default programs with qutebrowser.
- We ask a standard like `xdg-open` to open the program for us.
- We allow the user to set an opener (like `xdg-open` or `rifle`) in the settings.

Some of these may be combined. For instance, the filebrowser [ranger](https://github.com/hut/ranger) combines using rifle and the asking.

Some pro's and con's:
- Asking the user:
  * Con: can be quite cumbersome for the user, even if qutebrowser remembers the programs.
- Providing a list ourselves:
  * Pro: works everywhere.
  * Con: this isn't really qutebrowser's task nor focus.
- `xdg-open`:
  * Pro: it's an existing standard.
  * Con: not everyone uses this standard.
- Configure opener:
  * Con: more cumbersome for the user then just using `xdg-open`, but we could set a good default.
  * Pro: it's really generic
  * Con: people have to install some opener. We'd be helping them by letting them install an opener, but they might not want to for some obscure reason.

**Comment by The-Compiler** [comment]
FWIW, `:download-open` currently uses [QDesktopServices::openUrl](http://doc.qt.io/qt-5/qdesktopservices.html#openUrl) which I think uses `xdg-open` on Linux, and the respective OS APIs on Windows/OS X.

This works pretty well, so I think all needed is some kind of override, like `:download-open evince`, and something similar for when #39 is implemented.

**Comment by NoctuaNivalis** [comment]
I'd suggest a more extensive override. We could allow the user to write something like `:download-open evince "$@"`, where the `$@` would be replaced by the name of the program. This allows for things like `:download-open ffmpeg -i "$@" output.mp4` to convert a movie on download (no idea why you'd want that, though, but imagine a better usecase).

To keep things simple, the name of the downloaded file could just be appended in case no `$@` is found in the opener.

**Comment by amerlyq** [comment]
It somehow recall me about DIY scope.sh preview script, used by https://github.com/hut/ranger.

**Comment by lamarpavel** [comment]
Sure, rangers rifle.sh is meant to be used in other projects as well, I wonder why I never thought of that...

**Comment by The-Compiler** [comment]
Thanks to @Kingdread we now have an argument to `:download-open` so you can do what @NoctuaNivalis showed (with `{}` as placeholder, like in other places in qutebrowser). Otherwise, `xdg-open` or other means of asking the system to open it are used. I think that's all we need, so I'm going to close this.
