### ISSUE TITLE
Display yanked link in statusbar

### ISSUE THREAD

**Issue by sudo-nice** [The-Compiler/qutebrowser#1213]
When we yank current page's url with 'yy' hotkey, we can see kind of message in the statusbar: "Yanked URL to clipboard: http://example.org". Actually, we can see the current page`s url in the statusbar by default, so we don't need that message.
Otherwise, when we yank any link with ';y' (e.g.) hotkey, we can see only short-spoken message: "URL yanked to clipboard", and we only left to guess what the yanked url looked like.
Don't you think it worth to exchange the things?

**Comment by The-Compiler** [comment]
Makes sense!

**Comment by The-Compiler** [comment]
This was fixed in #1229. I'll leave the normal `:yank` as it is, as it can also yank title/domain, so it makes sense to display it IMHO.
