### ISSUE TITLE
Autocomplete download paths with tab

### ISSUE THREAD

**Issue by glspisso** [The-Compiler/qutebrowser#1215]
Would be very useful and on Unix system probably kind of expected. Could be put in as an optional true-false setting. I am right now resorting to copy-paste from terminal or to ln -s the longest download path and place them under the default download path.

**Comment by Kingdread** [comment]
Probably already covered by #32 ("File paths for download, etc.")

**Comment by glspisso** [comment]
Ah yes, I looked up for paths among issue, but I couldn't find that one.
