### ISSUE TITLE
Extending hints to use short words: getting ValueError("Got invalid match type {}!".format(match))

### ISSUE THREAD

**Issue by ConSeannery** [The-Compiler/qutebrowser#1216]
Low priority issue, bit of a noob just looking for some clues! I'm trying to extend the hints generation to use 3 or 4 letter words instead of single characters, as I find it much easier to type simple words than random characters (even on home row).

Currently I am doing something awful just to see if I can get something working. As such, I have hijacked _hint_linear in hints.py by commenting out its return and using simple bit of code:

```python
def _hint_linear(self, min_chars, chars, elems):
    ....
    ....
    #return strings
    smallwords = []
    with open("/path/to/smallwords.txt","r") as f:
        for w in f:
            w = w.strip("\n")
            smallwords.append(w)
    return smallwords[:len(elems)]
```

This and using ":set hints scatter false" seems to work great, words from smallwords.txt show up as hints and typing some hints work, but unfortunately others do not. Partway through typing certain hints, an exception gets generated. I haven't noticed a correlation as to which letters cause an exception or which character position in a word causes an exception.

Here's the error:
Traceback (most recent call last):
  File "/home/me/git/qutebrowser/qutebrowser/app.py", line 851, in eventFilter
    return handler(event)
  File "/home/me/git/qutebrowser/qutebrowser/app.py", line 811, in _handle_key_event
    return man.eventFilter(event)
  File "/home/me/git/qutebrowser/qutebrowser/keyinput/modeman.py", line 317, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/me/git/qutebrowser/qutebrowser/keyinput/modeman.py", line 169, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/home/me/git/qutebrowser/qutebrowser/keyinput/modeparsers.py", line 192, in handle
    raise ValueError("Got invalid match type {}!".format(match))
ValueError: Got invalid match type Match.ambiguous!

Any ideas on why this would be happening?

I have attached [smallwords.txt](https://github.com/The-Compiler/qutebrowser/files/83446/smallwords.txt). I generated it using a linux wordlist and some filtering. Eg:
```
 egrep -v "[A-Z]|ü|Å|ö|é|'" /usr/share/dict/american-english > wordlist.filtered
```
followed by a quick pass through python to get 3 and 4 letter words.

Thanks!

**Comment by ConSeannery** [comment]
Ahh, I answered my own question. 

Example:
hint: awe
other hint: awesome

Crashes after typing awe, and it's not possible to get to hint "awesome". I will have to re-think my scheme...

**Comment by The-Compiler** [comment]
I suggest just waiting until #1178 is merged instead :wink:

Though if you feel like, it'd be nice if you could try that branch and let @NoctuaNivalis and me know if you're missing anything :wink:
