### ISSUE TITLE
Cookies are not shared between tabs with private-browsing=True

### ISSUE THREAD

**Issue by ikhthiandor** [The-Compiler/qutebrowser#1219]
Currently qutebrowser doesn't remember my logins in new tabs/windwos/sessions. It works only on the tab I logged in. Is there any fix for this?

**Comment by The-Compiler** [comment]
Do you have `general -> private-browsing` set to on by any chance?

**Comment by ikhthiandor** [comment]
Oops, that was it. Man, I can't thank you enough for such a great project. Cheers :smile: 

BTW, you might consider adding Gitter chat support. It can be really helpful for great projects like this. The irc channel seems dead. [Spacemacs] (https://github.com/syl20bnr/spacemacs) is hugely leveraging its development from Gitter integration. YMMV though. Have a good day.

**Comment by The-Compiler** [comment]
Hm, I'd still consider this a bug - even with private mode, the tabs should have a shared cookie jar.

I'll definitely not add gitter support, see [please don't use Slack for FOSS projects](https://drewdevault.com/2015/11/01/Please-stop-using-slack.html). Most of those arguments also apply to Gitter. (And I'm aware they have an IRC bridge - it's rather buggy though)

The IRC channel is definitely not dead, there are >80 people in it, and often there are some discussions or questions. When you joined it just happened to be 9 AM where I live on a Sunday :wink:

**Comment by ikhthiandor** [comment]
I see your point on Slack/Gitter etc. and I respect it.

Ah, timezones :stuck_out_tongue:
