### ISSUE TITLE
Switch back to flake8

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1226]
36803cba06f18d6dfe79eca7846f656af208f03a switched away from `flake8` because it depended on an outdated `pep8` version.

This got resolved in pep8 1.7.0, so we should consider switching back.

Some advantages:

- Simplified CI
- Allows us to use plugins like:
  - [x] [flake8-debugger](https://github.com/JBKahn/flake8-debugger)
  - [x] [pep8-naming](https://github.com/PyCQA/pep8-naming)
  - [x] ~~[flake8-import-order](https://github.com/public/flake8-import-order)~~
  - [x] ~~[flake8-quotes](https://github.com/zheller/flake8-quotes) (maybe?)~~
  - [x] [ebb-lint](https://pypi.python.org/pypi/ebb-lint/) (maybe?)
  - [x] [flake8-copyright](https://pypi.python.org/pypi/flake8-copyright/)
  - [x] ~~[flake8-isort](https://pypi.python.org/pypi/flake8-isort/) (maybe?)~~
  - [x] [flake8-pep257](https://pypi.python.org/pypi/flake8-pep257/) (https://github.com/jayvdb/flake8-putty/issues/2)
  - [x] [flake8-putty](https://pypi.python.org/pypi/flake8-putty/)
  - [x] [flake8-string-format](https://pypi.python.org/pypi/flake8-string-format/)
  - [x] ~~[flake8-strict](https://pypi.python.org/pypi/flake8_strict/) (maybe?)~~
  - [x] ~~[flake8-commas](https://pypi.python.org/pypi/flake8-commas/)~~
  - [x] [flake8-deprecated](https://pypi.python.org/pypi/flake8-deprecated/)
  - [x] [flake8-mock](https://pypi.python.org/pypi/flake8-mock/)
  - [x] [flake8-pep3101](https://pypi.python.org/pypi/flake8-pep3101/)
  - [x] ~~[pepper8](https://pypi.python.org/pypi/pepper8/) for the buildbot?~~
  - [x] ~~[hacking](https://github.com/openstack-dev/hacking)~~ (https://bugs.launchpad.net/hacking/+bug/1544224)

Also, maybe take a look at [radon](https://github.com/rubik/radon)/[xenon](https://github.com/rubik/xenon)

**Comment by The-Compiler** [comment]
With this `setup.cfg`:

```
[flake8]
exclude = .venv,.hypothesis,.git,__pycache__,resources.py
# E265: Block comment should start with '#'
# E501: Line too long
# E402: module level import not at top of file
# E266: too many leading '#' for block comment
# W503: line break before binary operator
# F401: Unused import
ignore = E265,E501,E402,E266,W503,F401
```

we get some legitimate warnings about indentations.

**Comment by The-Compiler** [comment]
Basic flake8 functionality is merged. radon/xenon and some of the plugins are still pending.

**Comment by jayvdb** [comment]
You may want to look at using plugins `flake8-future-import` and `flake8-print`.

**Comment by The-Compiler** [comment]
@jayvdb Thanks for the suggestion! This is python3-only code though, so this should probably raise a `SyntaxError` anyways during tests :wink:

**Comment by jayvdb** [comment]
You can configure `flake8-future-import` to prevent any use of `__future__` (there is one in `scripts/dev/ci_install.py`) and `flake8-print` can be used to prevent unexpected use of `print()` which is usually debugging left in the commit (you would need to whitelist `print` function being used in `scripts/` and a few specific files in `qutebrowser/`).

**Comment by The-Compiler** [comment]
Hehe, `ci_install.py` is the only file which is Python2 only for bootstrapping on CI systems :laughing: But it might still make sense after excluding that file via flake8-putty (which is hands-down the most useful flake8 plugin on that list, by the way!).

I guess preventing `print()` might be useful, or at least reviewing where it's still used and if it's better replaced by logging instead.

**Comment by jayvdb** [comment]
For what its worth, I've added all of the plugins on this list to `flake8-putty`'s `flakes` Travis job, which runs on 2.6+ (except 3.0 and 3.1), and runs against most versions `flake8` v220+.

It looks like you have most of these enabled in your repo now, except `hacking`.

**Comment by The-Compiler** [comment]
Good timing, I'm working on adding `flake8-{tuple,tidy-imports,future-import}` right now :laughing:

**Comment by The-Compiler** [comment]
I [added some more plugins](https://github.com/The-Compiler/qutebrowser/compare/41d52386e8cdf38da09afd2c5e61e152a863550f...579b3e81e4f490e84c6c36cf5b504b431a579dc9) now
