### ISSUE TITLE
HiDPI support?

### ISSUE THREAD

**Issue by JonathanReeve** [The-Compiler/qutebrowser#1228]
I have a 3200x1800px display. This is what qutebrowser looks like on my display, using GNOME: 

![screenshot from 2016-01-14 11-52-29](https://cloud.githubusercontent.com/assets/1843676/12330921/6a462280-bab5-11e5-8632-631d0da30855.png)

The fonts and qutebrowser UI are tiny and illegible. Is there a way to fix this?

**Comment by The-Compiler** [comment]
What Qt version? (See `qutebrowser --version` or `:open qute:version`).

You can try setting `QT_DEVICE_PIXEL_RATIO` to some integer (say, `export QT_DEVICE_PIXEL_RATIO=2`) and see if that helps.

I've also heard about others just increasing the font size in the config for all fonts, and set `ui -> default-zoom` to some sensible value.

Does this help?

**Comment by JonathanReeve** [comment]
That *almost* works. Setting the qt ratio makes most of the web stuff the right ratio, but the UI elements are super small. Setting the font size helps with the legibility a little, but then the fonts are still spaced weirdly (see screenshot). 

![screenshot from 2016-01-16 17-20-27](https://cloud.githubusercontent.com/assets/1843676/12374817/14188728-bc76-11e5-9aa0-194fea8bb24e.png)

Instead of setting the default font size to a certain point value no matter what (8pt), would it make more sense to set it based on the user's display resolution? I don't really know how QT works, so that's just my guess.

**Comment by JonathanReeve** [comment]
Here's the output of `qutebrowser --version`, by the way: 
```
qutebrowser v0.5.0
Git commit: 

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1


Copyright 2014-2016 Florian Bruhin (The Compiler)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/> or use
:open qute:gpl.
```

**Comment by The-Compiler** [comment]
Hm, odd - is this still the default font?

**Comment by JonathanReeve** [comment]
Yep, I just changed the size from 8 to 12.

**Comment by The-Compiler** [comment]
I'm guessing qutebrowser is falling back to some weird generic bitmap monospace font - can you try to install some monospace font earlier on the list of used monospace fonts?

- Terminus
- Monospace
- DejaVu Sans Mono
- Monaco
- Bitstream Vera Sans Mono
- Andale Mono
- Liberation Mono
- Courier New
- Courier
- monospace
- Fixed
- Consolas
- Terminal

I'm guessing none of those are installed and it's falling back to some generic monospace/Fixed thing.

If that isn't it, can you try removing the first `Monospace` from the `fonts -> _monospace` setting and see if that helps?

**Comment by JonathanReeve** [comment]
Ah, turns out that was a problem with the Terminus font. I have it installed, but it's a bitmap version. I changed that line to start with "DejaVu Sans Mono," and it *mostly* fixed the problem. Now the fonts display correctly, but they're cut off in unusual ways: 

![screenshot from 2016-01-18 10-16-36](https://cloud.githubusercontent.com/assets/1843676/12394890/93dfa9da-bdcc-11e5-846c-77e57b5b2f9d.png)

The URLs and the dates in the screenshot above are cut off after a certain width. Is this a setting I can change?

**Comment by The-Compiler** [comment]
This is to keep space for the page title, which is currently not recorded for the history (#768). You'll however see it for book- and quickmarks.

See #693 too.

I'm closing this then, as this all seems expected (though somewhat strange) Qt behaviour. I think there are more HighDPI improvements coming with Qt 5.6 though.

**Comment by JonathanReeve** [comment]
I spoke too soon--some websites are still displaying with tiny fonts, even with these modifications. See screenshot:

![screenshot from 2016-01-18 10-34-08](https://cloud.githubusercontent.com/assets/1843676/12395393/55c37886-bdcf-11e5-9e35-63e89cd27f5c.png)

I tried setting default minimum font sizes with `web-size-minimum` and others, but it doesn't seem to affect this.

**Comment by The-Compiler** [comment]
This is probably #252 you're seeing - unfortunately the only workaround I know of is installing Microsoft fonts.

This should be fixed in the future with the new QtWebEngine/Chromium backend (#666) too.

**Comment by lahwaacz** [comment]
This font seems familiar - I've had similar issue (though not on HiDPI) with Github using bitmap fonts and it turned out to be fontconfig issue (or rather missing fonts used by Github and misconfigured fallback). You can run `fc-match <font-family>` to see which font is used for given font family (e.g. `serif`, `sans-serif`, `monospace`, `Helvetica` etc.) and [configure the alias](https://wiki.archlinux.org/index.php/Font_configuration#Replace_or_set_default_fonts) if it falls back to a bitmap font. Use the "Inspect" tool in the browser to see which fonts are used on which websites. You can also try to [disable bitmap fonts](https://wiki.archlinux.org/index.php/Font_configuration#Disable_bitmap_fonts) completely.

**Comment by neeasade** [comment]
Can confirm get the small font problem on all browsers until I install those fonts on a fresh install.

**Comment by JonathanReeve** [comment]
You're right, installing Microsoft fonts fixed that. Thanks!
