### ISSUE TITLE
Range-based matching for numeric hinting

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1232]
When checking the operation of my bot on the Arch wiki, I need to open dozens of pages from the [contributions list](https://wiki.archlinux.org/index.php/Special:Contributions/Lahwaacz.bot). I can enter the hint mode and (in numeric mode) type "diff" to narrow down the search. Now I need to open hints e.g. `00`-`42`. The fastest way is currently to use rapid hinting and type all the 43 numbers, or, ehm, to use the mouse.

It would be nice if multiple hints could be selected at once. I was thinking to mimic Python's [slice](https://docs.python.org/3/library/functions.html?highlight=slice#slice) syntax, so the above problem could be solved by entering the hint mode with `F`, selecting with `diff[:43]` and pressing Enter to confirm. The hints matching the slice should be highlighted differently than regular hints as a visual representation before pressing Enter. To make the input easily correctable, it should be shown in the status line.

Using the brackets as special tokens would make it impossible to use them in the match string, but numerals are already "forbidden" so I guess it would not be a problem. Otherwise we could complicate things with C-style escaping.

**Comment by The-Compiler** [comment]
Nice suggestion, thanks! I merged this into #571.
