### ISSUE TITLE
Option to place status bar on top

### ISSUE THREAD

**Issue by TrilbyWhite** [The-Compiler/qutebrowser#1257]
There are configuration options for both the tab bar and the download bar to be placed on either the top or the bottom (or sides at least for tabs), but unless I've been missing it, there is not similar option to control the placement of the status/command bar.

I would love the option to have the status bar (which I have hidden by default) appear at the top.

This would raise the question of whether it would then be above or below any other top-bars (tabs, downloads).  I know dwb handled this by having a simple string in the configuration specifying the top-to-bottom order of the elements with each one represented by a character.  For example "tswd" might represent tabs on top, then status, then the web content, and downloads on the bottom.

Regardless of the implementation, I hope some method of placing the status above the web content will be considered for a new feature.

**Comment by The-Compiler** [comment]
I agree having something like dwb's `widget-packing` makes sense. This will also complicate the completion code a bit, as that's a separate toplevel widget, positioned "by hand" to line up with the statusbar.

**Comment by TrilbyWhite** [comment]
Ah, that would be tricky.  It didn't occur to me as I have the completion window configured to take up no space (essentially be iinvisible) so works more like dwb than pentadactyl.

**Comment by TrilbyWhite** [comment]
Ah, that would be tricky.  It didn't occur to me as I have the completion window configured to take up no space (essentially be iinvisible) so works more like dwb than pentadactyl.

**Comment by TrilbyWhite** [comment]
Ah, that would be tricky.  It didn't occur to me as I have the completion window configured to take up no space (essentially be iinvisible) so works more like dwb than pentadactyl.

**Comment by The-Compiler** [comment]
Implemented in #1622.

**Comment by TrilbyWhite** [comment]
Thanks!  Looking forward to trying it out.

**Comment by TrilbyWhite** [comment]
Thanks!  Looking forward to trying it out.
