### ISSUE TITLE
Open the current url in an editor

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1261]
If I want to modify the current url, it might be nice to have a command that opens the current url in an editor and navigates to that url when the editor is closed. 

Think of something like visual mode when using vi mode for bash -- you press `v` and the current command line is opened in vi. When you close the editor, the command is run.

Right now, it seems like I have to press `O` (to fill the command line with the current url), backspace a lot, then retype most of the url.

**Comment by The-Compiler** [comment]
FWIW, you can also use most [readline shortcuts](http://www.bigsmoke.us/readline/shortcuts) to navigate in the commandline.

**Comment by lahwaacz** [comment]
Except for its [vi mode](http://tiswww.case.edu/php/chet/readline/readline.html#SEC22) of course...
