### ISSUE TITLE
Per-Domain Enable Javascript

### ISSUE THREAD

**Issue by shaggytwodope** [The-Compiler/qutebrowser#1267]
Unless I've overlooked something, I'm wondering if this could be a feature someone could consider adding. Disabling Javascript is nice, but some sites simply need it to function.

**Comment by The-Compiler** [comment]
This is covered by #27. I agree it'd be really nice! This definitely will be the next thing I'll look at after there's some usable QtWebEngine backend and tests.

**Comment by NoctuaNivalis** [comment]
Just noting that this is the perfect adblocker. Before I switched to qutebrowser, I used to block all javascript except some explicitly allowed domains. Most (and all annoyingly flashing) ads are loaded with javascript hosted by an external advertiser. Those are all blocked, which leaves only some static images (and those don't really bother me).

**Comment by The-Compiler** [comment]
Ads loaded from an external advertiser are probably blocked via the current host-blocking already, javscript or not :wink:

**Comment by lamarpavel** [comment]
@NoctuaNivalis Even more effective is to block all ref-linking and whitelisting the sites you frequent. It breaks many pages more visibly though because even basic CSS is often hosted on some foreign CDN.
