### ISSUE TITLE
Problems with new tab positioning

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1272]
1. The documentation does not explain what "explicitly opened tabs" are, but shouldn't tabs opened with `qutebrowser --target tab*` be considered as explicit? Or maybe there should be another target for explicit positioning?
(This does not matter as long as `new-tab-position` and `new-tab-position-explicit` have the same value.)

2. If both `select-on-remove` and `new-tab-position` have the same value, closing and re-opening (with `u`) a tab will swap the position of two tabs (unless the leftmost or rightmost tab is closed). Setting `select-on-remove` to `previous` means even bigger chaos if a tab is restored after a "big jump". Shouldn't the closed tabs be restored at the position they were closed from?

**Comment by The-Compiler** [comment]
Sorry for the lack of feedback here, kinda forgot about this one!

I don't know about a better term, basically using something like `:open` should be considered explicit, and clicking links (with ctrl or middle-click) is not explicit. I agree opening via a new instance should be handled as explicit though.

And yeah, I agree for `:undo`, it could be more clever than it is currently.

**Comment by The-Compiler** [comment]
As for 1., those are now considered as explicit thanks to @Xitian9 (#1429).

**Comment by The-Compiler** [comment]
With #1826 tabs are now restored with the index they had when they were closed.
