### ISSUE TITLE
Manual install fails on Windows 7 on tox command

### ISSUE THREAD

**Issue by svermeulen** [The-Compiler/qutebrowser#1274]
I'm trying to follow the instructions for manual install on Windows 7 and am hitting some issues when running the tox command.

I'm installed Qt and PyQt5 as instructed, then installed tox using pip.

Then I tried running the tox command in the qutebrowser directory and am getting this result:

    C:\Projects\qutebrowser> tox -e mkvenv
    mkvenv create: C:\Projects\qutebrowser\.venv
    mkvenv installdeps: -rC:\Projects\qutebrowser/requirements.txt
    mkvenv develop-inst: C:\Projects\qutebrowser
    mkvenv installed: colorama==0.3.6,colorlog==2.6.0,cssutils==1.0.1,Jinja2==2.8,MarkupSafe==0.23,Pygments==2.1,pyPEG2==2.15.2,PyYAML==3.11,-e git+https://github.com/The-Compiler/qutebrowser@6af1cce45f2caf64c57dc2f585f2f8eb86dccd16#egg=qutebrowser,wheel==0.26.0
    mkvenv runtests: PYTHONHASHSEED='172'
    mkvenv runtests: commands[0] | C:\Projects\qutebrowser\.venv\Scripts\python scripts/link_pyqt.py --tox C:\Projects\qutebrowser\.venv
    Could not import sip with C:\Projects\CmdUtil\python3.BAT: No module named 'sip'!
    ERROR: InvocationError: 'C:\\Projects\\qutebrowser\\.venv\\Scripts\\python scripts/link_pyqt.py --tox C:\\Projects\\qutebrowser\\.venv'
    ______________________________________________________________________________________________ summary _______________________________________________________________________________________________
    ERROR:   mkvenv: commands failed

I tried googling around but cannot find much information on this.  Any thoughts?  I can install a prebuilt copy but I'd like to be able to play with the source.

**Comment by lamarpavel** [comment]
You don't need tox to build and run qutebrowser from source, tox is a suite to automate testing.

If you still want to run tox then you will want to look into python virtual environments as that seems to be where your problems originate. I have no idea how to set up virtualenv (or anything else) under Windows, but guessing from the error your virtualenv is missing at least pip (probably much more though).

**Comment by The-Compiler** [comment]
@lamarpavel qutebrowser also (ab)uses tox to set up a virtualenv with all dependencies for qutebrowser installations from source. Also note the error message says `sip` (PyQt's code generator), not `pip` :wink:

@svermeulen note how tox seems to use `C:\Projects\CmdUtil\python3.BAT` as Python. My guess would be you have two different python installs on your system, and the python used there isn't the one you installed PyQt for - the PyQt installer also should've installed sip.

**Comment by svermeulen** [comment]
@The-Compiler I actually added that python3.bat to get around this error that I was getting otherwise:

    C:\Projects\qutebrowser> tox -e mkvenv
    mkvenv create: C:\Projects\qutebrowser\.venv
    ERROR: InterpreterNotFound: python3
    ______________________________________________________________________________________________ summary _______________________________________________________________________________________________
    ERROR:   mkvenv: InterpreterNotFound: python3

The python3.bat file just consists of this and is on the PATH.

    @echo off
    python %*

And I have confirmed that the python that is on the PATH here refers to the same python that I installed PyQt into.

However - I was able to get qutebrowser running from source by not using a virtualenv at all.  Not great practice, I know, but enough for me for now.  Thanks for the help!

**Comment by The-Compiler** [comment]
Glad to hear you got it working! If you end up doing changes useful to the general public please contribute them back, and let me know if you need help with anything!
