### ISSUE TITLE
Add a way to browse cache

### ISSUE THREAD

**Issue by andya9** [The-Compiler/qutebrowser#1275]
As title says, it would be cool to have human readable cache to save elements without redownloading them (i.e. images, videos), like firefox with [cacheviewer extension](https://addons.mozilla.org/en-US/firefox/addon/cacheviewer)

**Comment by The-Compiler** [comment]
Sorry, but I'm going to say no to that one - neither the current backend (QtWebKit) nor the future one (QtWebEngine) expose the APIs needed to do this, and I really don't want to analyze the cache files on the file level. Maybe [ChromeCacheView](http://www.nirsoft.net/utils/chrome_cache_view.html) will work with the new engine in the future, but no guarantees.

**Comment by andya9** [comment]
Ah, I understand. I thought it would be fairly easy because maybe there was an index with the full path of cache elements pointing to the non-human readable filenames in the cache folder... so it would have been easy to do something like: for all urls in index ending in jpg find the file in cache they point to and rename it accordingly
