### ISSUE TITLE
Wrong path rewriting with pdfjs

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1280]
Report on v0.5.1, on  Manjaro Linux

```
20:37:10 DEBUG    webview    webpage:acceptNavigationRequest:583 acceptNavigationRequest, url http://www.skoda.ee/SiteCollectionDocuments/Tootekataloogid/Octavia_mainENG_0513.pdf, type NavigationTypeLinkClicked, hint target None, open_target ClickTarget.normal
[...]
20:37:11 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 6 to 'PDF.js viewer'
20:37:11 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/viewer.css, path: /web/viewer.css, host pdfjs
20:37:11 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/compatibility.js, path: /web/compatibility.js, host pdfjs
20:37:11 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/debugger.js, path: /web/debugger.js, host pdfjs
20:37:11 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/viewer.js, path: /web/viewer.js, host pdfjs
20:37:11 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/pdf_qute://pdfjs/web/viewer.css, path: /web/pdf_qute://pdfjs/web/viewer.css, host pdfjs
20:37:11 ERROR    misc       utils:wrapper:616 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/pdfjs.py", line 121, in get_pdfjs_res
    content = utils.read_file(res_path, binary=True)
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/utils.py", line 86, in read_file
    data = pkg_resources.resource_string(qutebrowser.__name__, filename)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1165, in resource_string
    self, resource_name
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1605, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1728, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.5/site-packages/qutebrowser/3rdparty/pdfjs/web/pdf_qute:/pdfjs/web/viewer.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/utils.py", line 614, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/network/networkmanager.py", line 369, in createRequest
    op, req, outgoing_data)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/network/qutescheme.py", line 93, in createRequest
    data = handler(self._win_id, request)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/network/qutescheme.py", line 215, in qute_pdfjs
    return pdfjs.get_pdfjs_res(urlpath)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/pdfjs.py", line 123, in get_pdfjs_res
    raise PDFJSNotFound
qutebrowser.browser.pdfjs.PDFJSNotFound
20:37:11 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
TypeError: invalid result from NetworkManager.createRequest(), bool cannot be converted to PyQt5.QtNetwork.QNetworkReply in this context
```

Note the weird URL, probably to messed up rewriting somehow?

`url: qute://pdfjs/web/pdf_qute://pdfjs/web/viewer.css, path: /web/pdf_qute://pdfjs/web/viewer.css`

cc @Kingdread

**Comment by The-Compiler** [comment]
Some observations:

- We'd have needed an already rewritten path `qute://pdfjs/web/pdf_viewer.css` so this would happen
- pdfjs is loaded from `/usr/lib/python3.5/site-packages/qutebrowser/3rdparty/pdfjs` based on the stacktrace
- `new_urls` in `pdfjs.fix_urls` is a dict, so the order the replacements are done in is unpredictable.
- `pdf.js: no` is listed in the version info (!)

**Comment by The-Compiler** [comment]
Some observations:

- We'd have needed an already rewritten path `qute://pdfjs/web/pdf_viewer.css` so this would happen
- pdfjs is loaded from `/usr/lib/python3.5/site-packages/qutebrowser/3rdparty/pdfjs` based on the stacktrace
- `new_urls` in `pdfjs.fix_urls` is a dict, so the order the replacements are done in is unpredictable.
- `pdf.js: no` is listed in the version info (!)

**Comment by Kingdread** [comment]
Some more notes:

* I'm pretty sure that this path does not appear in the unmodified pdf.js files, and no rewrite rule either adds an underscore or just the 'qute://pdfjs/web/' prefix, so while I come to the same conclusion (that `qute://pdfjs/web/pdf_viewer.css` must have been there before), I'm clueless on how it got there.
* The stacktrace might lie. The `pkg_resource` call and thus the bundled version just happens to be checked last - after all system paths have been searched - and the error is caught there. Since the filename doesn't make sense and doesn't exist in any pdfjs package, it makes sense that the final error is thrown there, when checking the bundled version. Note that for each file, the search is `system paths -> bundled version`, there is no "flag" that indicates where qute should search.
* Even though it is a dict and the order is unpredictable, the replacement parts don't containt other to-be-replaced parts, so as long as you're not applying the replacement more than once, the order should not matter (except for e.g. `qute://pdfjs/web/qute://pdfjs/web/viewer.css`, where `viewer.css` got replaced twice), but that doesn't seem to be the case here (or am I missing something?)
* The page generation relies on `web/viewer.html` (and only throws `PDFJSNotFound` when this file is not found), while the version report uses `build/pdf.js`, so it is possible to "use" pdf.js and not get an error even though the version report shows "pdf.js: no". Since the other pdf.js assets are loaded via `qute://`-urls, they lack the error catching and the error page. I consider that a bug (see the next point).
* The `qute://pdfjs` scheme should definitely be made more robust since any missing pdf.js file will crash the browser (try it yourself, `:open qute://pdfjs/web/foobar.js`). It would be bad to silently swallow all errors, but having qute crash because a pdf.js file is missing is also bad. This is something I didn't consider when I wrote it, since I (wrongly) assumed that the presence of the `viewer.html` indicates a working package - but that might not always be the case. Or the files might even come from different packages, due to the way qute searches pdf.js files (see the earlier point).

**Comment by The-Compiler** [comment]
Yeah, I can't explain it either. No reports other than that one so far either.

I'd suggest the following:

- I think using `raise PDFJSNotFound from None` will suppress the first stacktrace, which will make things a little less confusing.
- Convert `new_urls` to a list of tuples so the behavior is predictable, to be on the safe side
- Change the scheme handler to handle missing files, probably by returning a `networkreply.ErrorNetworkReply` with a 404.
- Ideally add a unittest for the change, as we'll have to reimplement/abstract the scheme part for QtWebEngine and don't want to do the same mistake again.

**Comment by The-Compiler** [comment]
Assuming this is fixed by #1290, as the reporter's install probably was messed up somehow and the crash is now gone.

**Comment by The-Compiler** [comment]
For the sake of completeness, I got another one on v0.5.1 (i.e. without that fix) on Ubuntu 15.10:

```
22:04:25 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_text_changed('http://www.tedusar.eu/files/summerschool2013/ROScheatsheet.pdf') (tab 0)
22:04:25 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 0 to 'http://www.tedusar.eu/files/summerschool2013/ROScheatsheet.pdf'
22:04:25 DEBUG    webview    tabbedbrowser:on_title_changed:483 Ignoring title change to ''.
22:04:25 DEBUG    webview    tabbedbrowser:on_title_changed:491 Changing title for idx 0 to 'PDF.js viewer'
22:04:25 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/viewer.css, path: /web/viewer.css, host pdfjs
22:04:25 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/compatibility.js, path: /web/compatibility.js, host pdfjs
22:04:25 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/debugger.js, path: /web/debugger.js, host pdfjs
22:04:25 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/viewer.js, path: /web/viewer.js, host pdfjs
22:04:25 DEBUG    misc       qutescheme:createRequest:80 url: qute://pdfjs/web/pdf_qute://pdfjs/web/viewer.css, path: /web/pdf_qute://pdfjs/web/viewer.css, host pdfjs
22:04:25 ERROR    misc       utils:wrapper:616 Error in qutebrowser.browser.network.networkmanager.NetworkManager.createRequest
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser/browser/pdfjs.py", line 121, in get_pdfjs_res
    content = utils.read_file(res_path, binary=True)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser/utils/utils.py", line 86, in read_file
    data = pkg_resources.resource_string(qutebrowser.__name__, filename)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1173, in resource_string
    self, resource_name
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1605, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1728, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/qutebrowser/3rdparty/pdfjs/web/pdf_qute:/pdfjs/web/viewer.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser/utils/utils.py", line 614, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser/browser/network/networkmanager.py", line 369, in createRequest
    op, req, outgoing_data)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser/browser/network/qutescheme.py", line 93, in createRequest
    data = handler(self._win_id, request)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser/browser/network/qutescheme.py", line 215, in qute_pdfjs
    return pdfjs.get_pdfjs_res(urlpath)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser/browser/pdfjs.py", line 123, in get_pdfjs_res
    raise PDFJSNotFound
qutebrowser.browser.pdfjs.PDFJSNotFound
```

**Comment by Kingdread** [comment]
Interesting, do you happen to know which pdf.js package was used?

I've seen some debian-specific patches in packages which made them incompatible with qute, so I could take a look at the package files (and maybe we'd know where the strange URL came from).

**Comment by The-Compiler** [comment]
I don't, I only know the version info says `pdf.js: no` too.

Though yesterday there was someone in IRC as well, who said this:

```
20:38 <sennawr> Thanks for creating qutebrowser! I've difficulty getting pdf.js working on Ubuntu 15.10, qutebrowser v0.5.1
20:42 <sennawr> I installed xul-ext-pdf.js and pdf.js-common, since pdf.js is installed at /usr/share/xul-ext/pdf.js/content I made a symbolic link: ln -s /usr/share/xul-ext/pdf.js/content to pdfjs in ~/.local/share/qutebrowser
20:43 <sennawr> result after opening a pdf-file in qutebrowser is that pdf.js is started, but problem is, that I don't see the pdf-content.
```

I'm not sure if it's the same person or not, but maybe it's something like that too?
