### ISSUE TITLE
Avoid clipboard in tests

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1285]
We were having some crazy trouble using QClipboard in tests - probably [this is why](http://doc.qt.io/qt-5/qclipboard.html):

> Lastly, the X11 clipboard is event driven, i.e. the clipboard will not function properly if the event loop is not running. Similarly, it is recommended that the contents of the clipboard are stored or retrieved in direct response to user-input events, e.g. mouse button or key presses and releases. You should not store or retrieve the clipboard contents in response to timer or non-user-input events.

The plan currently is to:

- xfail tests which magically don't work
- In the long run, avoid the clipboard entirely

For data coming from the test to qutebrowser (e.g. for the `:paste` test):

- Have some kind of "fake clipboard" which can be filled with a special command and gets used once set.

For data coming from qutebrowser to the test:

- Simply check logging instead

**Comment by lahwaacz** [comment]
I'm not sure when/where these tests fail or what the problem is, but it comes to mind that something like xvfb should be required for the clipboard tests to ensure a "private" clipboard, otherwise the tests would mess up with other programs running on the X server.

**Comment by The-Compiler** [comment]
That's indeed another issue I didn't think of yet. Thogh tests already run in Xvfb by default if it's installed, and those issues I was having were with Xvfb.

Various issues I've seen so far:

- Clipboard not updating at all
- Clipboard updating but not emitting `QClipboard.changed`
- Clipboard updating and emitting `changed`, but not updated when I read it from another process
- Various X errors

**Comment by lahwaacz** [comment]
Maybe irrelevant, but I'm also seeing a lot of these warnings when I select a text with a mouse:
```
WARNING: QXcbClipboard: SelectionRequest too old
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.5.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 153, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 111, in run
    ret = qt_mainloop()
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 121, in qt_mainloop
    return qApp.exec_()
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/log.py", line 353, in qt_message_handler
    stack = ''.join(traceback.format_stack())
```
Other than that, I haven't noticed any clipboard issues during normal usage or in the tests - but that's only one system, the most reliable one :innocent:.

**Comment by The-Compiler** [comment]
I've not seen that yet - care to open a separate issue? Might be one of the messages to investigate and then add to the list of suppressed warnings :wink:

**Comment by lahwaacz** [comment]
Sure: #1287
