### ISSUE TITLE
Unable to load page: The specified configuration cannot be used.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#129]
The above error shows up from time to time (from QtWebKit) when continuing to use a page/`QNetworkAccessManager` while the network has changed (e.g. WiFi -> LAN)

**Comment by The-Compiler** [comment]
On 5.4.1 this still seems to be an issue when roaming between different APs with the same SSID according to `rieper` in IRC.

Here opening a new tab (with a new `QNAM`) doesn't help in this case for some reason.

**Comment by The-Compiler** [comment]
Reported upstream as [QTBUG-46542](https://bugreports.qt.io/browse/QTBUG-46542).

I don't think there's anything more I can do, so I'm closing this.

Please vote/comment/... there :smile:

**Comment by The-Compiler** [comment]
I'm still seeing this with 5.5.1 in an eduroam network, FWIW... :worried:

**Comment by The-Compiler** [comment]
Anyone else ever seen this with QtWebKit and Qt versions newer than 5.5? I don't use QtWebKit anymore, so it's hard to tell.

**Comment by Nicholas42** [comment]
I get this error sometimes when running `:adblock-update`. I think it is under the same circumstances (switching between networks). It always works after restarting. I haven't looked into it very carefully and will update this when I have. Note that I use webengine, not webkit!

```
qutebrowser v2.3.0
Git commit: 
Backend: QtWebEngine 5.15.5, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.6
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.10.377 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.36.0
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.1.5
Platform: Linux-5.13.4-arch2-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Uptime: 6:19:01
```

**Comment by ValdikSS** [comment]
Probably the same Qt issue in crow-translate
https://github.com/crow-translate/crow-translate/issues/383

**Comment by ValdikSS** [comment]
Workaround:
Disable "networkbearer" plugin of Qt5
`$ sudo mv /usr/lib64/qt5/plugins/bearer /usr/lib64/qt5/plugins/bearer.mv`

Thanks to https://github.com/crow-translate/crow-translate/issues/383#issuecomment-1319991892
