### ISSUE TITLE
Text is blurry

### ISSUE THREAD

**Issue by JonathanReeve** [The-Compiler/qutebrowser#1291]
On my HIDPI monitor, at least, text is rendered very blurry. Compare this screenshot of qutebrowser on Google Play Books: 

![gp-qute](https://cloud.githubusercontent.com/assets/1843676/12862900/98e0c6c4-cc3d-11e5-9c30-07a0931c2326.png)

With this one on Chromium:
 
![gp-chromium](https://cloud.githubusercontent.com/assets/1843676/12862904/9b882ffc-cc3d-11e5-98b7-8b68f714a9ef.png)

This phenomenon doesn't happen everywhere, but it happens a lot.

**Comment by The-Compiler** [comment]
Are you scaling the text somehow, i.e. by setting `QT_DEVICE_PIXEL_RATIO`, another font size, or a default zoom?

**Comment by JonathanReeve** [comment]
Yep, I have `QT_DEVICE_PIXEL_RATIO` set per instructions in https://wiki.archlinux.org/index.php/HiDPI#Qt_5. I can unset this value, and set qutebrowser's default zoom level to 200%, and that fixes it, but then other QT applications are tiny. I guess I need to edit .desktop files to set this environment variable on a per-application basis.

**Comment by JonathanReeve** [comment]
Yep, I have `QT_DEVICE_PIXEL_RATIO` set per instructions in https://wiki.archlinux.org/index.php/HiDPI#Qt_5. I can unset this value, and set qutebrowser's default zoom level to 200%, and that fixes it, but then other QT applications are tiny. I guess I need to edit .desktop files to set this environment variable on a per-application basis.

**Comment by JonathanReeve** [comment]
Yep, I have `QT_DEVICE_PIXEL_RATIO` set per instructions in https://wiki.archlinux.org/index.php/HiDPI#Qt_5. I can unset this value, and set qutebrowser's default zoom level to 200%, and that fixes it, but then other QT applications are tiny. I guess I need to edit .desktop files to set this environment variable on a per-application basis.

**Comment by JonathanReeve** [comment]
Yep, I have `QT_DEVICE_PIXEL_RATIO` set per instructions in https://wiki.archlinux.org/index.php/HiDPI#Qt_5. I can unset this value, and set qutebrowser's default zoom level to 200%, and that fixes it, but then other QT applications are tiny. I guess I need to edit .desktop files to set this environment variable on a per-application basis.

**Comment by JonathanReeve** [comment]
Yep, I have `QT_DEVICE_PIXEL_RATIO` set per instructions in https://wiki.archlinux.org/index.php/HiDPI#Qt_5. I can unset this value, and set qutebrowser's default zoom level to 200%, and that fixes the font problem, but then all the icons that appear in qutebrowser are tiny. (Context menu items that appear on right-click, magnifying glass icon for zooming into scaled images, hand icon, etc.)

**Comment by JonathanReeve** [comment]
Yep, I have `QT_DEVICE_PIXEL_RATIO` set per instructions in https://wiki.archlinux.org/index.php/HiDPI#Qt_5. I can unset this value, and set qutebrowser's default zoom level to 200%, and that fixes the font problem, but then all the icons that appear in qutebrowser are tiny. (Context menu items that appear on right-click, magnifying glass icon for zooming into scaled images, hand icon, etc.)

**Comment by JonathanReeve** [comment]
Sorry for the barrage of comments here! Qutebrowser wasn't registering any change to the page once I clicked "comment," so I clicked it a bunch!

**Comment by The-Compiler** [comment]
@JonathanReeve the comment page not updating is a GitHub issue - it works with the default user-agent though.

I don't think I can do anything for the blurry text issue though. Are you on a distribution which packages QtWebEngine? If so, could you please run `scripts/minimal_webkit_testbrowser.py --webengine url` and see if it happens like that as well?

**Comment by The-Compiler** [comment]
I'm closing this for now, as I don't think there's anything I can do about this.

Also note there were a lot of [highdpi changes for Qt 5.6](https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/) (including deprecation of `QT_DEVICE_PIXEL_RATIO`), so maybe that got fixed there as well.

**Comment by JonathanReeve** [comment]
Cool, looking forward to seeing the changes in 5.6.

**Comment by Enzime** [comment]
Something to note is with the work in progress QtWebEngine (based off Blink/Chromium) backend, the HiDPI rendering is basically perfect now :) So when the backend gets stable enough to use as a daily driver, that will be a great day for HiDPI users.
