### ISSUE TITLE
Drag-and-drop doesn't work

### ISSUE THREAD

**Issue by JonathanReeve** [The-Compiler/qutebrowser#1292]
To reproduce: 

 * open GitHub
 * open a new issue or comment
 * try to drag and drop an image into the comment window
 * notice that it just pastes the image path instead of uploading the image

**Comment by The-Compiler** [comment]
I'm guessing either QtWebKit (the underlying engine) doesn't implement this, or GitHub does things in a way it doesn't support.

Unfortunately either way there isn't much I can do about it - other than hope it'll work in the future with the new backend (#666).
