### ISSUE TITLE
test module missing when creating deb

### ISSUE THREAD

**Issue by pacholik** [The-Compiler/qutebrowser#1293]
When I tries to make Debian package using stdeb, an error message occurred:

```
running build_ext
test (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ImportError: No module named 'qutebrowser.test'
```

So I created `qutebrowser/test/__init__.py` and it have built fine.

**Comment by The-Compiler** [comment]
This doesn't look like a qutebrowser issue. You'll need to tell stdeb to either skip trying to run tests, or to run them from the right location.

Also, we're working on a proper Debian package which hopefully will be in Debian Stretch.
