### ISSUE TITLE
Bold text is rendered way too bold

### ISSUE THREAD

**Issue by doragasu** [The-Compiler/qutebrowser#1295]
I'm running qutebrowser on ArchLinux, and loving it so far. But I have a problem with bold text rendering, it's rendered way too bold, and is uncomfortable to read. You can see the problem in this example of GitHub qutebrowser project page rendered with Firefox (up) and qutebrowser (down).

![firefox](http://i.imgur.com/CpSdDpZ.png)

![qutebrowser](http://i.imgur.com/hDv3Tmi.png)

This problem happens on my machine with default qutebrowser configuration. I have also been playing with web-family-XXX settings but didn't get the problem to disappear.

I suppose this problem might be related to my Arch install, but fonts render flawlessly on Firefox and Chromium.

**Comment by The-Compiler** [comment]
Huh, I've never seen that. Can you try with `--temp-basedir`? If it still happens with that, can you show the outputs of `pacman -Qs ttf-` and `fc-list`?

**Comment by lahwaacz** [comment]
Does it happen on many pages or only Github? Github uses the following font specs:

    font: 13px / 1.4 Helvetica, arial, nimbussansl, liberationsans, freesans, clean, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";

You can try to run e.g. `fc-match Helvetica` to see which font is actually used and compare to the Firefox/Chromium settings. Also, qutebrowser does not seem to have `web-family-clean` option.

**Comment by doragasu** [comment]
`--temp-basedir` didn't do the trick:
![temp](http://i.imgur.com/ZnA6v0M.png)

Installed fonts (yeah, I have win7 and office 2007 fonts):

```
$ pacman -Qs ttf-
local/ttf-bitstream-vera 1.10-10
    Bitstream vera fonts
local/ttf-dejavu 2.34-2
    Font family based on the Bitstream Vera Fonts with a wider range of characters
local/ttf-droid 20121017-4
    General-purpose fonts released by Google as part of Android
local/ttf-freefont 20120503-4
    Set of free outline fonts covering the Unicode character set
local/ttf-hack 2.019-1
    A hand groomed and optically balanced typeface based on Bitstream Vera Mono
local/ttf-inconsolata-gwf 1.016-1
    Hinted TrueType Inconsolata including a Bold variant provided by Googlewebfonts.
local/ttf-linux-libertine 5.3.0-3
    Serif (Libertine) and Sans Serif (Biolinum) OpenType fonts with large Unicode coverage
local/ttf-office-2007-fonts 1.0-3
    Microsoft Office 2007 TrueType Fonts.
local/ttf-symbola 8.00-1
    Font for unicode symbols (part of Unicode Fonts for Ancient Scripts).
local/ttf-win7-fonts 7.1-9
    Microsoft Windows 7 Latin TrueType fonts
```
[fc-list outputs a lot of stuff](http://pastebin.com/g81GzavK).

This problem happens everywhere, not only on GitHub. E.g. reading gmail inbox is painful.

fc-match:
```
$ fc-match Helvetica
arial.ttf: "Arial" "Normal"
```

How can I compare this with Firefox/Chromium settings?

**Comment by The-Compiler** [comment]
I've no idea to be honest - any chance you could temporarily remove those packages one-by-one and see which one triggers it?

**Comment by The-Compiler** [comment]
Also, do you see the same when you do `python3 scripts/minimal_webkit_testbrowser.py url`? What about if you install `qt5-webeninge` and launch the same script with `--webengine`?

If it only happens with QtWebKit, I'm not sure there's much I can do - reporting a bug upstream will probably mean it'll just be ignored.

**Comment by doragasu** [comment]
Using `minimal_webkit_testbrowser.py` causes the same result: extra bold text.

When adding `--webengine` switch, the page renders properly for a second (bold text renders OK, as in Firefox), and then a segfault happens!

I'll start removing font packages and report the results.

**Comment by The-Compiler** [comment]
Ah, the segfault is probably [this bug](https://bugs.archlinux.org/task/47573) - it should work better on a non-HTTPS page.

**Comment by doragasu** [comment]
Tested `--webengine` with a non-https page, and it works.

The first font package I removed was `ttf-office-2007-fonts` and the problem dissapeared!

It's nice having proper rendering in qutebrowser. Unfortunately, I would like to preserve the removed font package, as I need it for some documents to render properly.

**Comment by The-Compiler** [comment]
I'm not sure there is much I can do I'm afraid - it clearly seems to be some kind of Qt/QtWebKit issue, and upstream is likely to not care since QtWebKit is deprecated.

This will probably be fixed with the new QtWebEngine backend in the future then (#666), but that'll probably still take a few months.

Not sure what you can do, maybe someone else has an idea - maybe you could blacklist it somehow via [fontconfig](https://wiki.archlinux.org/index.php/Font_configuration), but I have no idea how to do that per-application.

Closing this for now, as it's not an issue in qutebrowser's code, and I'm not going to be able to fix it upstream.

**Comment by doragasu** [comment]
OK, thanks anyway for your help, and for making such a great browser!

**Comment by lahwaacz** [comment]
On 08.02.16 at  3:18, doragasu wrote:
> How can I compare this with Firefox/Chromium settings?
> 

You can use the "Inspect" tool and see what the "computed style" really is. I've
just noticed a difference between Firefox:

    font-family: sans-serif,Helvetica,arial,nimbussansl,liberationsans,freesans,clean,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";

and qutebrowser:

    font-family: Helvetica, arial, nimbussansl, liberationsans, freesans, clean, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';

So for some reason Firefox prefers sans-serif over the other fonts. Other
properties might also differ in your case.
