### ISSUE TITLE
Multi-Threaded Downloads

### ISSUE THREAD

**Issue by zQueal** [The-Compiler/qutebrowser#1302]
Not entirely sure how everyone feels about multi-threaded downloads, but I pretty much feel they're essential. I tried downloading a posted `webm` from the IRC channel and it took quite a while to download even though it was only 36MB. Could something such as [DSDownload](https://github.com/DiSiqueira/DSDownload) be implemented as a core feature to offer extensibility in this area?

**Comment by lahwaacz** [comment]
Multi-threaded downloads would definitely not help with downloading a single file. In the majority of cases, the bottleneck is the network bandwidth (either on the client or the server). How long does it take to download this file using a different downloader (`curl`, `wget`)?

You can also [write a user script](https://github.com/The-Compiler/qutebrowser/blob/master/doc/userscripts.asciidoc) to pass the work to a downloader of your choice, e.g. DSDownload.

**Comment by The-Compiler** [comment]
The downloads are done async, and are not CPU-bound, so multithreading won't solve anything.

What I *think* you mean is downloading with multiple connections for the same file, which however is not what DSDownload does apparently.

However, I'm afraid I'm not going to implement this, mainly because it'll be impossible to support with the future QtWebEngine API.

**Comment by zQueal** [comment]
> How long does it take to download this file using a different downloader (curl, wget)?

After some more digging it's possible it could just be the distance between the server and me. I'm in NY and the server hosting the file is in france.

|Prog|Time|
|:--|:--|
|chrome|1 minute 12 seconds|
|wget|55 seconds|
|curl|55 seconds|
|aria2c (5 connections)|13 seconds|

So regardless of what you call them, threads, connections, etc, they really help. 5 connections were able to help me download the file 5 times faster. Just seems like a feature that would be super cool to have in a browser. 

> What I think you mean is downloading with multiple connections for the same file

Yup.

> which however is not what DSDownload does apparently.

Oops.

> However, I'm afraid I'm not going to implement this

That's actually really disappointing, unfortunately.

**Comment by lamarpavel** [comment]
You can always write a user script that calls another program to download files.

**Comment by zQueal** [comment]
I'm gonna end up looking into that and see if I could pipe the download to `aria2c`. Just hope it's not above my head. Haha.

Thanks everyone.

**Comment by lamarpavel** [comment]
@zQueal I don't know aria2c, but based on the usage description something like this should work:

```:hint links spawn aria2c {hint-url}```

You can bind that to a key (eg `;d`) in your `keys.conf` like this:

```
hint links spawn aria2c {hint-url}
	;d
```

**Comment by zQueal** [comment]
Hey! That's awesome! Took me a while, but I was able to find `keys.conf` in `%appdata$\Local\qutebrowser` and I added exactly;

    hint links spawn aria2c -d "C:\Users\zqueal\Downloads" -x6 {hint-url}
        ;ad

But I get an error.

![thafq4k](https://cloud.githubusercontent.com/assets/239193/13018622/96cf8f04-d198-11e5-8e48-0cffa8ce0144.png)

Even still, I was able to get it working with just `aria2c` which by default uses 1 connection (which defeats the purpose of this whole thing) and I'm not sure where the default download location is. In addition to that, the window is hidden and I can't see the progress.

Any way that you know of to make the window visible and to get these arguments to work properly?

**Comment by lamarpavel** [comment]
I'm not sure if the quoting rules are different on Windows, but I would try this:

```
hint links spawn "aria2c -d C:\Users\zqueal\Downloads -x6" {hint-url}
    ;ad
```

**Comment by zQueal** [comment]
![s4gygkx](https://cloud.githubusercontent.com/assets/239193/13027075/1bb4ad28-d20f-11e5-9eb5-73c4dc1eb920.png)

Same error, unfortunately. :( It looks like quotes work for embedding other qutebrowser commands, but maybe not external commands?

    hint links fill ":open {hint-url}"
        ;o
    hint links fill ":open -t {hint-url}"
        ;O
    hint links fill ":open -b {hint-url}"
        .o

I also tried encasing the entire command in quotes including `{hint-url}`. Still nothing.

**Comment by lamarpavel** [comment]
Some time ago there was an issue with external command arguments that solved this problem for me, maybe your version of qutebrowser does not support this yet? Here is an example with arguments that works for me:

`spawn youtube-dl -o '~/tmp/%(uploader)s - %(title)s.%(ext)s' {url}`

The first argument here is unquoted and the string is in single quotes. I'm using the git master branch of qutebrowser.

**Comment by The-Compiler** [comment]
I think you're running into #797 there.

**Comment by zQueal** [comment]
I'm running `v0.5.1`. So the newest version available.

I tried doing this in bash, but I ended up running into the same issues;

`aria2.sh`
    #!/bin/bash
    exec aria2c -x5 -d "C:\Users\zqueal\Downloads" --file-allocation=none "$@"

`keys.conf`
    hint links spawn bash aria2.sh {hint-url}"
        ;ad

To test it, I restarted `QuteBrowser` and navigated to: https://dist.keybase.io/windows/. I then hit `;h` and `s` to hint select the file I want to download. Then I do `;ad` to attempt to spawn my batch file and download the selected file.

Is this not correct?

**Comment by toofar** [comment]
Wrapping the spawn command in quotes like

    hint links spawn '/tmp/aria -x6 -d "~/My Downloads" {hint-url}'
        ;ad

And changing the line `cmd, *args = args` to `cmd, *args = shlex.split(args[0])` in `hints.py:_spawn` works for this case. Not sure if that would break anything else that happens to call `_spawn` properly though.

**Comment by zQueal** [comment]
Thanks for the advice! Unfortunately I can't seem to locate `hints.py` anywhere. It's not in the install location, nor is it located in `%appdata%/Local/qutebrowser`. Is this strictly a linux thing? Using `The Silver Searcher` I tried to look specifically for `_spawn` in both directories as well which came up empty.

**Comment by toofar** [comment]
Oh that is one of the source files `browser/hints.py`. I'm just running it from a git checout, I don't know where it would be in a proper install. In some python library path presumably.
