### ISSUE TITLE
hints wrong on google.com

### ISSUE THREAD

**Issue by julianuu** [The-Compiler/qutebrowser#1304]
Something seems not right here. When I type `69` nothing happens, `79` leads to page 2, `89` to page 3 etc. Also, when i type `next`, then hint `81` is being selected which brings me to page 10 instead of the next page.
![hints_google](https://cloud.githubusercontent.com/assets/16508448/13034284/bfb4aaa4-d331-11e5-8c27-76c734a7023a.png)

**Comment by The-Compiler** [comment]
@error800 any idea what's going wrong there? :wink:

**Comment by lahwaacz** [comment]
Looks the same as #1298, each `<a>` contains two `<span>`s and the dimensions of `<a>` is `0px x 0px`, so qutebrowser clicks at wrong position (in this case most likely on the neighbour).

**Comment by error800** [comment]
@The-Compiler: lahwaacz is right. I think if we can get the block element issue solved, a lot of hint problems will already be gone.

**Comment by The-Compiler** [comment]
I can't reproduce this anymore even without the fix in #1311.

**Comment by NoctuaNivalis** [comment]
Who uses the second page of google, anyway?
