### ISSUE TITLE
IPFS integration

### ISSUE THREAD

**Issue by lamarpavel** [The-Compiler/qutebrowser#1314]
So this is a bit complex, but there is no use in thinking about it and then forgetting it again, so I'll write it down.

IPFS [1] is a spec in alpha stage and one reference- and two alternate-implementations, one of which is in Python. When the IPFS daemon is running, files can be queried through IPFS, bypassing anything from regular DNS to CAs, ISP routing (or censorship) tables and so on.
Basic integration could mean checking for a running daemon when a URL of the scheme /ipfs/<hash> or ipns:/ipns/<hash> is entered [2] and then querying the files through localhost:4001 instead of the www. If no daemon is running, transform the URL to ipfs.io/ipfs/<hash>.

Beyond that there are lots of more interesting and advanced integrations, such as maintaining and installing qutebrowser userscripts through ipfs or fetching TLS certs through IPFS to verify the data gotten from websites, if available. There is lots of stuff that could be done and none of it is a high priority for qutebrowser now.
The first thing that should be looked at, if at all, is recognizing and properly handling IPFS URIs though.

Some things to note:
- There is a firefox addon: https://github.com/lidel/ipfs-firefox-addon#ipfs-firefox-addon
- The weekly developments: https://github.com/ipfs/ipfs/issues/151

[1] http://ipfs.io
[2] https://github.com/ipfs/specs/pull/37

It's an interesting project for sure and discussions are nice; this issue is to continuously gather some ideas (including the questions whether it makes sense to integrate IPFS into qutebrowser or rather just handle it with userscripts). Nothing urgent, just fun.

**Comment by The-Compiler** [comment]
So... I'm not very interested in this personally, and unfortunately there's always a lot of things to do. I unfortunately don't see this happening, and don't think it should be in qutebrowser's core.

However, I added a line about custom URL schemes to the plugin API ideas (#30), so maybe at some future point it'd be possible for someone to write a plugin for this.

**Comment by The-Compiler** [comment]
Potentially interesting project: https://github.com/eversum/galacteek

**Comment by mhhf** [comment]
With major browsers integrating this ([brave]) it would be great to see this in qutebrowser as well <3

[brave]: https://brave.com/ipfs-support/

**Comment by The-Compiler** [comment]
I'm afraid this still isn't something I plan to work on. I'll probably work on exposing a suitable API via #30 in the not too distant future, but I won't be the one writing the actual integration as a lot of more important stuff is on my plate already.

**Comment by blueForestIcarus** [comment]
This makes qutebrowser more or less unusable as a primary browser for what will be an increasing number of people.

Most major linux distros using ipfs for their package index, or are planning to do so in the future.

**Comment by The-Compiler** [comment]
> This makes qutebrowser more or less unusable as a primary browser for what will be an increasing number of people.

[citation needed]

> Most major linux distros using ipfs for their package index, or are planning to do so in the future.

Do you have a source on that?

**Comment by blueForestIcarus** [comment]
I might have jumped the gun a bit, completely forgeting ubuntu/debian exists

nix-os is definately working towards it.
https://blog.ipfs.io/2020-09-08-nix-ipfs-milestone-1/
https://nixos.wiki/wiki/NixIPFS
https://news.ycombinator.com/item?id=24621276

The links suggest its early stage, but the nix contributor who was telling me about it seemed to imply it was further along, I'll have to ask. I was told arch is working on it too. But I havent found anything.

> what will be an increasing number of people.
Its pretty clear ipfs isn't going away, alot of things are built on it, NFT's / filecoin comes to mind.
Brave supports it out of the box. There are extensions for firefox and chromium. 
I've been coming across ipns links alot for frequently recently.

**Comment by blueForestIcarus** [comment]
Having it as a plugin seems pretty reasonable though.
