### ISSUE TITLE
bind keys for click on downloaded file

### ISSUE THREAD

**Issue by funeralismatic** [The-Compiler/qutebrowser#1316]
Can you add this feature? Or simple open on left click, clear on right click or something like that.

Can Qt detect file type without format suffix (i.e. `*.jpg`)?

**Comment by The-Compiler** [comment]
> Can you add this feature?

Err, what feature exactly?

>  Or simple open on left click, clear on right click or something like that.

That's about the current behaviour for downloads (other than the fact you get a context menu on right-click).

> Can Qt detect file type without format suffix (i.e. `*.jpg`)?

Not sure - why are you asking?

**Comment by funeralismatic** [comment]
>Err, what feature exactly?

In title.

>context menu on right-click

Hmm, but «Open» not work.

>why are you asking?

Because open on right-click not work (tested on jpeg picture and binary file without file-format suffix) for me.

**Comment by The-Compiler** [comment]
I don't understand it, this is why I'm asking.

> Because open on right-click not work (tested on jpeg picture and binary file without file-format suffix) for me.

What OS?

**Comment by funeralismatic** [comment]
>What OS?

Gentoo Linux, Python 3.4.3, Qt 5.5.1.

**Comment by ikhthiandor** [comment]
@funeralismatic  May be you are looking for the :download commands?

https://github.com/The-Compiler/qutebrowser/blob/master/doc/help/commands.asciidoc#download

**Comment by The-Compiler** [comment]
Qt uses `xdg-open` to open those files, so please check with that and see why it can't open those files.

**Comment by lahwaacz** [comment]
Actually, it seems that `xdg-open` does not understand URLs with the `file://` scheme:
```
$ xdg-open file:///home/lahwaacz/test.pdf
WARNING: failed to determine command precursor for file:///home/lahwaacz/test.pdf
WARNING: failed to determine command(s) for file:///home/lahwaacz/test.pdf
```

**Comment by The-Compiler** [comment]
I don't think Qt calls it with a `file://`-scheme though?

**Comment by Link-Satonaka** [comment]
Can confirm xdg-open opens things correctly from qutebrowser's download bar.

**Comment by lahwaacz** [comment]
I've seen the last two lines (warnings) in qutebrowser's log, so I think Qt calls xdg-open with `file://` scheme.

But I forgot to mention that I'm not using upstream `xdg-utils` package, I have [xdg-utils-mimeo](https://aur.archlinux.org/packages/xdg-utils-mimeo/) so I can blame `mimeo`.

**Comment by funeralismatic** [comment]
>`xdg-open`

Ok, solved. My MIME files are broken.
