### ISSUE TITLE
:navigate should strip #fragments from the URLs

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1318]
When I open e.g. `http://example.com/foo/bar#baz` and run `:navigate up`, the new URL is `http://example.com/foo#baz`. The fragment should be thrown away, there is no reason to assume that the new page will contain the same anchor.
The same probably applies also to other navigate actions: prev, next, increment, decrement.

**Comment by The-Compiler** [comment]
Agreed!
