### ISSUE TITLE
[feature request] Official userscript for chromecast

### ISSUE THREAD

**Issue by sim590** [The-Compiler/qutebrowser#1319]
Wouldn't it be cool?

**Comment by The-Compiler** [comment]
What exactly would that do? I barely know what a Chromecast is (some Google thing to show e.g. Android contents on a TV), so please enlighten me :wink:

**Comment by sim590** [comment]
>I barely know what a Chromecast is

The [chromecast][] is a device connected in your local network and plugged in monitor through HDMI cable. Once connected, it can receive requests of playing video contents from several sources (YouTube, Netflix, etc.). *It can also let you stream content from your computer to the TV* and that's what's the most interresting. Concerning this, I have recently found a GPLv3 python [project][] letting you stream all your audio from your linux computer to the chromecast.

>What exactly would that do?

Pretty much things that the [chromium's chromecast plugin][] does, i.e request the chromecast to:

- play youtube videos;
- stream my tab;
- stream audio from my tab;
- ...

[chromecast]: https://www.google.com/chromecast/
[project]: https://github.com/masmu/pulseaudio-dlna
[chromium's chromecast plugin]: https://chrome.google.com/webstore/detail/google-cast/boadgeojelhgndaghljhdicfkmllpafd%3Fhl%3Den

**Comment by The-Compiler** [comment]
Thanks for the explanation! I added this as an idea to #30, but it's unlikely I'll be the one working on this, and I'm not sure how much of it would even be possible.

**Comment by NoctuaNivalis** [comment]
Part of this could easily be achieved by "opening" youtube videos with [castnow](https://github.com/xat/castnow).

**Comment by sim590** [comment]
As @NoctuaNivalis suggested, a userscript using castnow has been integrated a while ago. See #2024.

Unfortunately, valuable functionnalities are missing compared to the official chromecast builtin extension in chromium. For instance desktop and tab casting is not possible. At this point, this type of feature would require code integrated in qtwebengine. Any idea if it is possible? The code for chromecast seems to lie [here](https://chromium.googlesource.com/chromium/src.git/+/master/chromecast/). Any idea if there's plan for qtwebengine to integrate webengine's chromecast code?

**Comment by The-Compiler** [comment]
Your best bet would be to open a [Qt feature request](https://bugreports.qt.io/). Right now, it looks like the Chromecast code [is completely excluded](https://github.com/qt/qtwebengine/blob/v5.9.0/tools/scripts/take_snapshot.py#L114). I can't see any talk about it in the issue tracker either.

**Comment by sim590** [comment]
I made a feature request [here](https://bugreports.qt.io/browse/QTWB-17). I hope I did it well and at the right place. If anyone can add something, that would be great. I hope this generates interest. :wink:

**Comment by The-Compiler** [comment]
Looks like you created it against the Qt WebBrowser project, which [seems to be](http://doc.qt.io/QtWebBrowser/) some webbrowser for embedded devices - I didn't know it existed!

I moved it to the `QTBUG` namespace instead with the `WebEngine` component, which is the right place for QtWebEngine issues :wink:

**Comment by sim590** [comment]
Oops. I thought also that Qt Web browser didn't fit, but I couldn't find the webengine project. Anyhow. Thanks! :smile:
