### ISSUE TITLE
No font hinting on Github

### ISSUE THREAD

**Issue by z1lt0id** [The-Compiler/qutebrowser#1322]
I noticed this bug only on QuteBrowser but I don't get any font hinting in Github.  Attached is a screenshot, and I've attached my .conf file

![hinting](https://cloud.githubusercontent.com/assets/2316366/13228987/c7ee5342-d9f2-11e5-8425-200f3bdd7a2d.png)

 [.conf file](https://bpaste.net/show/3b77f3612ba3)

**Comment by The-Compiler** [comment]
Can you try with another Qt5/QtWebKit based browser, such as Otter Browser?

**Comment by z1lt0id** [comment]
No problems. I'll do it this evening when I get home work and give you the outcome :)

On 23 February 2016 8:38:00 am AEDT, Florian Bruhin <notifications@github.com> wrote:
>Can you try with another Qt5/QtWebKit based browser, such as Otter
>Browser?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/The-Compiler/qutebrowser/issues/1322#issuecomment-187397507

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vext01** [comment]
I have no font hinting in OtterBrowser-0.9.09 on OpenBSD-current.

**Comment by z1lt0id** [comment]
I was able to try the latest git of Qute on both Gentoo and Arch using default configurations and both showed no hinting.  Also tried using Otter and got the same thing.  Image attached
![otter](https://cloud.githubusercontent.com/assets/2316366/13235463/22f6bdc8-da12-11e5-9b6e-6cbf2214197c.png)

**Comment by The-Compiler** [comment]
Weird, it looks fine here. Can you install `qt5-webengine` on Arch and try with `python3 scripts/minimal_webkit_testbrowser.py --webengine https://github.com` please? You'll get a segfault pretty quickly due to [it using an outdated nss API](https://bugs.archlinux.org/task/47573), but I hope you'll still see how the font looks.

If it looks fine there, it's going to be resolved in the future by #666, and there probably isn't much I can do with QtWebKit (the current backend) as it's deprecated, and an upstream issue.

**Comment by z1lt0id** [comment]
Hi Florian,

I changed the url to https://github.com/z1lt0id (my personal git) and for the split second it showed before it seg faulted all the fonts were correctly hinted.  So yeah it's the deprecated upstream issue that you specified.  I shall wait patiently I guess :) I can live with it for the time being.

**Comment by The-Compiler** [comment]
Thanks for testing! I'm closing this then, as there really isn't much I can do - sorry!

**Comment by z1lt0id** [comment]
No thank you, you were able to pinpoint the problem really quickly which leaves me less frustrated :)

**Comment by lahwaacz** [comment]
There were some obscure issues with fonts in the past (e.g. #1295), so you can try to follow the tips in the closed issues to see if it's specific to some fonts or configuration.
