### ISSUE TITLE
Can't play youtube HTML5 videos at all even though I have the packages.

### ISSUE THREAD

**Issue by chenshuiluke** [The-Compiler/qutebrowser#1326]
![qutebrowser](https://cloud.githubusercontent.com/assets/7980284/13387459/b79dd31e-de84-11e5-9a9b-4e80f7db783c.png)

The videos always look like above. I have installed the recommended packages multiple times:

	[luke@luke-server aurum-web]$ sudo pacman -S gst-libav gst-plugins-bad gst-plugins-base gst-plugins-base-libs gst-plugins-good gst-plugins-ugly
	[sudo] password for luke: 
	warning: gst-libav-1.6.3-3 is up to date -- reinstalling
	warning: gst-plugins-bad-1.6.3-5 is up to date -- reinstalling
	warning: gst-plugins-base-1.6.3-1 is up to date -- reinstalling
	warning: gst-plugins-base-libs-1.6.3-1 is up to date -- reinstalling
	warning: gst-plugins-good-1.6.3-1 is up to date -- reinstalling
	warning: gst-plugins-ugly-1.6.3-1 is up to date -- reinstalling
	resolving dependencies...
	looking for conflicting packages...

	Packages (6) gst-libav-1.6.3-3  gst-plugins-bad-1.6.3-5  gst-plugins-base-1.6.3-1  gst-plugins-base-libs-1.6.3-1
		     gst-plugins-good-1.6.3-1  gst-plugins-ugly-1.6.3-1

	Total Installed Size:  35.15 MiB
	Net Upgrade Size:       0.00 MiB

	:: Proceed with installation? [Y/n] y
	(6/6) checking keys in keyring                                               [###########################################] 100%
	(6/6) checking package integrity                                             [###########################################] 100%
	(6/6) loading package files                                                  [###########################################] 100%
	(6/6) checking for file conflicts                                            [###########################################] 100%
	(6/6) checking available disk space                                          [###########################################] 100%
	:: Processing package changes...
	(1/6) reinstalling gst-plugins-base-libs                                     [###########################################] 100%
	(2/6) reinstalling gst-libav                                                 [###########################################] 100%
	(3/6) reinstalling gst-plugins-bad                                           [###########################################] 100%
	(4/6) reinstalling gst-plugins-base                                          [###########################################] 100%
	(5/6) reinstalling gst-plugins-good                                          [###########################################] 100%
	(6/6) reinstalling gst-plugins-ugly                                          [###########################################] 100% 

This is the commandline output of when I try to watch a youtube video:

        libva info: VA-API version 0.38.1
        libva info: va_getDriverName() returns 0
        libva info: Trying to open /usr/lib/dri/i915_drv_video.so
        libva info: va_openDriver() returns -1
        libva info: VA-API version 0.38.1
        libva info: va_getDriverName() returns 0
        libva info: Trying to open /usr/lib/dri/i915_drv_video.so
        libva info: va_openDriver() returns -1
        libva info: VA-API version 0.38.1
        libva info: va_getDriverName() returns 0
        libva info: Trying to open /usr/lib/dri/i965_drv_video.so
        libva info: Found init function __vaDriverInit_0_38
        libva error: /usr/lib/dri/i965_drv_video.so init failed
        libva info: va_openDriver() returns -1
        libva info: VA-API version 0.38.1
        libva info: va_getDriverName() returns 0
        libva info: Trying to open /usr/lib/dri/i965_drv_video.so
        libva info: Found init function __vaDriverInit_0_38
        libva error: /usr/lib/dri/i965_drv_video.so init failed
        libva info: va_openDriver() returns -1
        libva info: VA-API version 0.38.1
        libva info: va_getDriverName() returns 0
        libva info: Trying to open /usr/lib/dri/i915_drv_video.so
        libva info: va_openDriver() returns -1
        libva info: VA-API version 0.38.1
        libva info: va_getDriverName() returns 0
        libva info: Trying to open /usr/lib/dri/i915_drv_video.so
        libva info: va_openDriver() returns -1
        libva info: VA-API version 0.38.1
        libva info: va_getDriverName() returns 0
        libva info: Trying to open /usr/lib/dri/i965_drv_video.so
        libva info: Found init function __vaDriverInit_0_38
        libva error: /usr/lib/dri/i965_drv_video.so init failed
        libva info: va_openDriver() returns -1

**Comment by The-Compiler** [comment]
I think you're not the only one with this issue, though it works fine for me with an i915 as well.

This seems like some issue with Qt/GStreamer/VA-API/your graphics driver, so there really isn't much I can do... I'll investigate and see if I find out about some solution later.

**Comment by chenshuiluke** [comment]
I have good news!
I seem to have resolved the issue by uninstalled gstreamer-vaapi:

    sudo pacman -R gstreamer-vaapi

**Comment by The-Compiler** [comment]
Huh, that's odd - that's usually the package *required* for playing youtube videos correctly :laughing:

**Comment by ff2000** [comment]
On Sun, 28 Feb 2016 22:57:09 -0800, Florian Bruhin <notifications@github.com> wrote:
> Huh, that's odd - that's usually the package *required* for playing youtube videos correctly :laughing: 
Really? vaapi is for video-decoding through a dedicated chip on the graphics card.
Could it be you mix that up with libav - the lib once forked from ffmpeg? That
really might be neccessary...

**Comment by chenshuiluke** [comment]
It is indeed very strange. I'm not the only one that was affected by `gstreamer-vaapi` because someone posted the solution on reply 18 [here](https://bbs.archlinux.org/viewtopic.php?id=203506). Thanks again for the help :smile: and have a good day

**Comment by The-Compiler** [comment]
> Could it be you mix that up with libav - the lib once forked from ffmpeg? That really might be neccessary...

Err, yes, I do - thanks for pointing that out. I need more :coffee:! :wink:

**Comment by Joschasa** [comment]
Just for the next guy, who might have the same problem:

I have two machines (notebook/computer) running arch with similar setup and nearly identical packages installed. Youtube worked fine on the notebook, but on computer i had a black screen.

Site to test video formats (helps finding the source of the problem): http://www.quirksmode.org/html5/tests/video.html

The computer failed to play mp4/ogg. After reinstalling libx264 (which, well, was installed before) both started working. I don't know what caused this, but maybe someone else got the same issue...
