### ISSUE TITLE
More sophisticated filtering for completion

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#133]
The completion could have nicer fuzzy-matching rather than just a substring match.

**Comment by jahkeup** [comment]
This would be especially useful with the new history completion.

**Comment by The-Compiler** [comment]
Unfortunately it's also very problematic with the history completion, as performance matters there a lot, and a Python version of the filtering is noticably slower than the default C++ version.

I might consider writing the completion models in C++ as a custom Python/PyQt extension for performance, but that's definitely not something important right now.

**Comment by jahkeup** [comment]
Gotcha. I could see there being a major impact - I'll patiently wait :+1:

**Comment by ff2000** [comment]
How "fuzzy" does the matching have to be? Like YouCompleteMe implements it? (every typed letter has to occur in the typed order) Shouldn't it be enough to match any substring (lineedit.text() separated by BLANK) in any order? It shouldn't be that hard to create a regex that does the job and feed a standard QSortFilterProxyModel with it.
But probably there are issues I currently don't see...

**Comment by The-Compiler** [comment]
Hmm, good point! I haven't considered using `QSortFilterProxyModel` with a regex at all, but that's definitely worth a try!

**Comment by The-Compiler** [comment]
This might be a good starting point:

* [fuzzyfinder](https://github.com/amjith/fuzzyfinder)
* [blog post](http://blog.amjith.com/fuzzyfinder-in-10-lines-of-python)

**Comment by The-Compiler** [comment]
[fzf](https://github.com/junegunn/fzf) is written in Go but might also be a source for inspiration.

**Comment by The-Compiler** [comment]
The current "fuzzy" matching implemented by @tex in #1195 works well enough in my opinion.

**Comment by trws** [comment]
If someone (maybe me) were to implement a more complete fuzzy matching option, would it be of interest here? It seems from the comments that many are pleased with the current state, which is good, but I'd prefer at least something with word-prefix match (ab match and-but) or similar and might be interested in implementing it.

**Comment by jgkamat** [comment]
Tom Scogland writes:

> If someone (maybe me) were to implement a more complete fuzzy matching 
> option, would it be of interest here?

I personally find the current completion much too slow as is.

> I'd prefer at least something with word-prefix match (ab match and-but) or
> similar and might be interested in implementing it.

Limiting searches to word-prefix with sqlite FTS might improve performance of 
the lookup, so I would be interested in that. I'm not sure if it's practical 
though (in terms of daily searching).
