### ISSUE TITLE
Weird change in size of link hints on specific website

### ISSUE THREAD

**Issue by cym13** [The-Compiler/qutebrowser#1331]
## Summary

This is the first time I encounter this hints on [this website](http://blog.extrawurst.org/reading/unity/dlang/2016/03/03/worthreading.html) are giant. I can provide screenshots if needed.

## Steps to reproduce

:open http://blog.extrawurst.org/reading/unity/dlang/2016/03/03/worthreading.html
:hint

## Version

qutebrowser v0.5.1
Git commit: v0.5.0-429-g7e3337a (2016-03-02 08:18:37 +0100)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1

**Comment by The-Compiler** [comment]
This looks like #925, with this CSS rule: `body > * { padding: 1em calc(33% - 6.6em); }`
