### ISSUE TITLE
Support for Animated PNG (APNG) Files

### ISSUE THREAD

**Issue by NoSuck** [The-Compiler/qutebrowser#1332]
It would be nice if qb could display them.  See [the APNG Wikipedia page](https://en.wikipedia.org/wiki/APNG) for an example.  View also with Firefox, if possible.

I realize this is an upstream issue but wanted to log interest nonetheless.

**Comment by The-Compiler** [comment]
I'm not sure if it's possible to implement this if libpng/Chromium/QtWebEngine don't, and I don't think I will, so I'm afraid I'll close this one. If this ends up getting implemented upstream, it should work in qutebrowser as well.

**Comment by Hrxn** [comment]
What's the status on this?
Since Chrom[e|ium] now shipped this? [Chrome Platform Link](https://www.chromestatus.com/feature/6691520493125632)

Is this already in QtWebEngine?

**Comment by jgkamat** [comment]
According to [caniuse](http://caniuse.com/#feat=apng) chrome seems to have added support in 60.

Qtwebengine 'basically' uses chrome under the hood. The latest release of qt (qt5.9) [is based on chromium 56](https://wiki.qt.io/New_Features_in_Qt_5.9), so this will probably not work.

The next release of qt (qt5.10) [looks like it will ship with chrome 60](https://wiki.qt.io/New_Features_in_Qt_5.10). 

So qtwebengine 5.10 will *probably* support this (but I haven't tested). You could test it out by getting a development version of qt and trying it out in the demo browser.

Keep in mind users will need to have qt5.10 to have it work properly (ie: for me, on 5.7.1, It won't work!).

**Comment by Hrxn** [comment]
Yes, I'm aware. Only unfamiliar with QtWebEngine details, versions, release cycle etc.

And this issue was one of the first relevant hits while searching for `qtwebengine apng support`, and since it also applies to qutebrowser..

So, okay, qt 5.10, or maybe on version later.

**Comment by The-Compiler** [comment]
I tried [this demo](http://littlesvr.ca/apng/gif_apng_webp1.html) with the Qt 5.10 beta, and indeed it works fine there. It's [planned](https://wiki.qt.io/Qt_5.10_Release) to be released at the end of November.
