### ISSUE TITLE
Curse Network Redirection Loop

### ISSUE THREAD

**Issue by Alzarath** [The-Compiler/qutebrowser#1333]
It seems most Curse Network sites seem to have an issue with a redirect loop or something. It seems to happen primarily to sites that use Curse's header bar. This excludes the main Curse website itself.

Affected examples:
http://gamepedia.com/
http://hearthpwn.com/

Unaffected examples:
http://mmo-champion.com/
http://terrariaonline.com/

This only seems to happen when you're logged into the Curse Network.

**Comment by The-Compiler** [comment]
I'd like to avoid creating an account there if possible :wink: Can you explain what happens in more details? "an issue with a redirect loop or something" doesn't really tell me much :wink:

**Comment by Alzarath** [comment]
Sorry, assumed you'd have or be willing to make an account and try for yourself. Anyways, for example if I go to http://gamepedia.com/ right now, I get the Error While Opening page with the words "Redirection limit reached".

Refreshing the page gets me the same error but with the url: http://auth.curse.com/NetworkService.asmx/shareSession?from=http%3A%2F%2Fwww.gamepedia.com%2Fcookie%3Ftoken%3Db20523aa-1128-4428-8ca2-271fcbd560f1%26redirect%3Dhttp%253A%252F%252Fwww.gamepedia.com%252F: 

Another refresh, same thing, url: http://www.gamepedia.com/cookie?token=e3dbd056-c3c4-46c7-95f1-c720009a013a&redirect=http%3A%2F%2Fwww.gamepedia.com%2F&cookie=VHNCSFJSDK3W7IEIDLI16XLC77NL682ITTBZNRMREJOZOU3M: 

One more refresh and the url returns to http://www.gamepedia.com/. Further refreshing continues to loop through those 3 URLs. Hopefully none of those strings of text are damning toward me (I certainly don't understand them), but I'll trust you either way.

**Comment by The-Compiler** [comment]
Can you please try with `python3 scripts/minimal_webkit_testbrowser.py http://gamepedia.com/` in the repo? If it happens in there as well, there's unfortunately not much I can do, but it'll probably be fixed in the future with QtWebEngine support (#666).

**Comment by Alzarath** [comment]
Well, the screen is completely white when I try to load using that (or accessing it via curse.com or google). Then again I'm not really considered 'logged in' with that and the redirection thing only happens in qutebrowser when I actually log in.

On the other hand, I was able to go to http://www.guildwars2guru.com/ and log in without issue on the minimal browser where, if I click 'sign in' in qutebrowser, I get that redirect issue.

**Comment by The-Compiler** [comment]
Hmm, odd. Could you try with another Qt 5 browser like [Otter Browser](http://otter-browser.org/)? If it does something different to qutebrowser, I guess I'll really need to create an account and investigate more closely.

**Comment by Alzarath** [comment]
I get similar results with Otter as I do with the minimal browser. http://guildwars2guru.com/ works fine. http://hearthpwn.com/ and http://gamepedia.com/ both give an Error 400. This makes qutebrowser the odd one out that it can access gamepedia and hearthpwn when you're not logged in.

**Comment by The-Compiler** [comment]
You can start qutebrowser with `--temp-basedir` to get a clean state which is removed when you close it.

Fun fact, with an autogenerated password with some special chars in it, the "register" button does nothing at all, in Chromium and Firefox. Honestly I'm just starting to think the site is broken in multiple ways... :wink:

**Comment by The-Compiler** [comment]
I now tried navigating Gamepedia and HearthPwn when logged in (and when not logged in), without any issues at all.

**Comment by Alzarath** [comment]
I was able to access gamepedia for a time. Logged in, out, in, out, back in, and navigated the site a bit. As soon as I visited a few other Curse sites (http://hearthpwn.com/ (unaccessible) http://curse.com/ (accessible) http://mmo-champion.com/ (accessible) http://terrariaonline.com/ (accessible) and http://www.lolnexus.com/ (unaccessible)), I'm once again getting the redirection issue for http://www.gamepedia.com/

**Comment by The-Compiler** [comment]
Sorry for the lack of a response - unfortunately, it's likely I need to add this one to the "[QtWebEngine will solve all of your problems](http://igg.me/at/qutebrowser)" pile - but I plan to take a closer look first, just haven't gotten to it yet.

**Comment by The-Compiler** [comment]
Closing this as it'll probably be fixed by QtWebEngine and it's unlikely there's anything I can do to make it work with QtWebKit.
