### ISSUE TITLE
Directory browsing is broken on Windows

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1334]
When I click on "folder" on `file:///J:/proj` I get `file://j/proj/folder` instead of `file:///J:/proj/folder` (note the `J:` and the triple-slash).

cc @antoyo

**Comment by antoyo** [comment]
I'm sorry but I don't have Windows to test this.

**Comment by The-Compiler** [comment]
no problem, I'll take a look whenever I have a windows ready and feel like it :laughing:

**Comment by The-Compiler** [comment]
I did take a quick look at the code, and I don't see where `/J:/proj` gets changed to `j/proj`.

However, some debugging/logging on Windows in `qutebrowser/browser/network/filescheme.py` (in `dirbrowser_html` and `get_file_list`) will probably reveal what's going on.

**Comment by Kingdread** [comment]
Just a quick heads up, working on this one, the fix is coming soon :wink:

**Comment by The-Compiler** [comment]
This was fixed in #1360, thanks to @Kingdread :+1:
