### ISSUE TITLE
can't use zotero

### ISSUE THREAD

**Issue by JonathanReeve** [The-Compiler/qutebrowser#1341]
One thing that's keeping me from using qutebrowser on a regular basis is that I can't seem to get it to work with the Zotero bookmarklet, which I use daily for extracting bibliographic data from websites. In keys.conf, I added these lines: 

    jseval var d=document,s=d.createElement('script');s.src='https://www.zotero.org/bookmarklet/loader.js';(d.body?d.body:d.documentElement).appendChild(s);void(0);
        Z

Qutebrowser correctly loads the JS file, and triggers a modal window that makes me log into to Zotero. So far so good, but when I log in, it complains of a "translator error." The bookmarklet works fine in other browsers. Logging into Zotero elsewhere in Qutebrowser and retrying doesn't seem to work. Any help here would be much appreciated.

**Comment by The-Compiler** [comment]
Can you check if anything changes if you set `network -> user-agent` to something like Chrome/Linux like offered in the completion?

**Comment by JonathanReeve** [comment]
It doesn't look like changing the user-agent has any effect.

**Comment by The-Compiler** [comment]
Sorry for the lack of a response - unfortunately, it's likely I need to add this one to the "[QtWebEngine will solve all of your problems](http://igg.me/at/qutebrowser)" pile - but I plan to take a closer look first, just haven't gotten to it yet.

**Comment by The-Compiler** [comment]
Closing this as it'll probably be fixed by QtWebEngine and it's unlikely there's anything I can do to make it work with QtWebKit.

**Comment by Anaphory** [comment]
I have a quickmark defined to be

    javascript:var%20 d=document,s=d.createElement('script');s.src='https://www.zotero.org/bookmarklet/loader.js';(d.body?d.body:d.documentElement).appendChild(s);void(0);

and bound that to `Z`, and it works with `qutebrowser --backend webengine`, but it took me browsing this repo for some time to find all the components there.

**Comment by rdiaz02** [comment]
@Anaphory: is this still working for you? When I rund that it tries (without success in my case) to open a "Log In to Zotero", instead of using the currently running standalone Zotero.  Any success with Zotero standalone?

**Comment by Anaphory** [comment]
No. I have not tried to find an alternative yet, either.

**Comment by rdiaz02** [comment]
Thanks for the update.

**Comment by The-Compiler** [comment]
Note that there is https://github.com/parchd-1/qutebrowser-zotero - I haven't tested it myself yet.

**Comment by JonathanReeve** [comment]
I can sometimes get Zotero to work if I'm already logged into zotero.com and already have Zotero (standalone) open. I used the javascript snippet listed above, and bound that to a quickmark.

**Comment by rdiaz02** [comment]
Thanks. I did as you said, and I also had some success. (With the caveat in capital letters that this is all way over my head) let me summarize my experiences so far in case they are of any help:

- Using the javascript snippet above, when I am logged into www.zotero.org, and I have Zotero standalone open, I can add references entries, e.g., from PubMed, both for individual entries and for a list of entries. But some other sites fail; for instance, it fails if called from the table of contents page for PLoS Computational Biology, and it fails when trying it from BMC Bioinformatics on a specific paper. In both cases there are translator errors (but there are no translator issues when doing this from firefox). 

- Interestingly, I can use `spawn --userscript zotero` from https://github.com/parchd-1/qutebrowser-zotero on some of those cases; not on the tables of contents page, of course, but on individual entries. When it works, the bookmarklet gives more feedback about what is happening, displaying the small box on the lower right.
