### ISSUE TITLE
Address bar on top of the window

### ISSUE THREAD

**Issue by niutech** [The-Compiler/qutebrowser#1346]
What will it take to make an address bar on top of the browser window, above the tabs? I don't mean the command prompt, but the real address bar, as we know from Chrome/Firefox/IE/Safari.

Thanks!

**Comment by The-Compiler** [comment]
I think first of all we'd need the `widget-packing` option from #1257, so it can be hidden by default.

Then it'd simply be a matter of implementing that widget, hooking up the right signals to it, and adding it to the main window when the respective option is set.

**Comment by The-Compiler** [comment]
With #1622, the status/command bar can be moved to the top. As for a real address bar, I don't think this is something which should be in the core, but I added it as a possible future plugin idea in #30.

**Comment by niutech** [comment]
Thanks. In my opinion a web browser without an address bar is like Windows without Start menu. ;) For many people it is a must.

**Comment by rodneyrod** [comment]
@The-Compiler Is there a way to script this up so users can implement something akin to an address bar themselves?

**Comment by The-Compiler** [comment]
@rodneyrod Not yet, maybe in the future. See my comment above.
