### ISSUE TITLE
OS X: Homebrew dropped QtWebKit

### ISSUE THREAD

**Issue by joelbrewster** [The-Compiler/qutebrowser#1357]
Fresh account with homebrew:
`$ brew install python3 pyqt5`
`$ pip3.5 install qutebrowser`

Is this related to:
https://github.com/Homebrew/homebrew/pull/50234/commits

**Comment by shaggytwodope** [comment]
You may wanna check out the mailinglist time to time. That being said check this out https://lists.schokokeks.org/pipermail/qutebrowser/2016-March/000176.html

**Comment by The-Compiler** [comment]
To clear things up: This is because Homebrew removed QtWebKit packages with Qt 5.6.

A possible workaround would be to install `qt551` from [homebrew-versions](https://github.com/Homebrew/homebrew-versions/), then installing `pyqt5` with `--build-from-source` (though you might need to change the dependency).

This will be fixed by #384 which seems like the much more sane approach on OS X anyways - I hope I'll get to look at this over easter!

**Comment by The-Compiler** [comment]
Over easter I tried building a binary with `cx_Freeze`, but that didn't work anymore at all... It's really time to look at #1004. I tried PyInstaller, and it seemed to at least start on OS X, but have trouble on Windows instead.

I'll be focused on getting v0.6 out this week, so it might take me a bit until I can look at this again. If someone on OS X feels like, I'd really appreciate some help. I pushed my work-in-progress to the [`pyinstaller` branch](https://github.com/The-Compiler/qutebrowser/compare/pyinstaller), you should be able to run `tox -e pyinstaller` there to build it. However, that means you need a working qutebrowser running already, so that's kind of an chicken-egg-problem.

**Comment by The-Compiler** [comment]
Also, the best way forward will of course be to not require QtWebKit at all, and run with QtWebEngine, its successor. The best way to make that happen is helping with better tests (#999) and/or [contributing to the crowdfunding I'm currently running](http://igg.me/at/qutebrowser) with the goal of working on it full-time for a few weeks.

**Comment by nullren** [comment]
For now, I was able to manually download older versions of pyqt5 and qt5 with homebrew.

    cd $(brew --prefix)/Library/Formula
    curl -OO https://raw.githubusercontent.com/Homebrew/homebrew/f802822b0fa35ad362aebd0101ccf83a638bed37/Library/Formula/{py,}qt5.rb
    brew install qt5 pyqt5

This at least lets me run qutebrowser today.

**Comment by tjelvar-olsson** [comment]
Tried to follow the updated homebrew instructions in commit dad1e48018e2bbd09c390b3522400c5170fa9b06 but I could not get it to work. It seems that the homebrew's pyqt5 requires QT5.6.

Error: dlopen(/usr/local/lib/python3.5/site-packages/PyQt5/QtCore.so, 2): Library not loaded: /usr/local/opt/qt5/lib/QtCore.framework/Versions/5/QtCore
  Referenced from: /usr/local/lib/python3.5/site-packages/PyQt5/QtCore.so
  Reason: Incompatible library version: QtCore.so requires version 5.6.0 or later, but QtCore provides version 5.5.0

Is there a way to specify the pyqt5 version to install using homebrew?

**Comment by The-Compiler** [comment]
Hmm, odd - that worked for me, but someone else reported the same.

FWIW, I recently did a test-build of a dmg which you can find at https://t.cmpl.cc/qutebrowser-dmgv2.dmg

I plan to build another dmg of v0.6.1 and release that in the coming few days, but in the meantime some testing of that dmg would be really appreciated!

**Comment by tjelvar-olsson** [comment]
Thanks I'll try it out.

Tjelvar

On 11 April 2016 at 12:12, Florian Bruhin <notifications@github.com> wrote:

> Hmm, odd - that worked for me, but someone else reported the same.
>
> FWIW, I recently did a test-build of a dmg which you can find at
> https://t.cmpl.cc/qutebrowser-dmgv2.dmg
>
> I plan to build another dmg of v0.6.1 and release that in the coming few
> days, but in the meantime some testing of that dmg would be really
> appreciated!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/The-Compiler/qutebrowser/issues/1357#issuecomment-208290827>
>



-- 
Dr. Tjelvar Olsson
tjelvarolsson.com
@tjelvar_olsson <https://twitter.com/tjelvar_olsson>

**Comment by oisincar** [comment]
I also wasn't able to get it to work through any of the above methods or the updated install instructions, but the dmg's working beautifully, thanks.

**Comment by for-coursera** [comment]
> FWIW, I recently did a test-build of a dmg which you can find at https://t.cmpl.cc/qutebrowser-dmgv2.dmg

On OS X 10.8.5, the build fails to launch. Console.app has the following:

    2016-04-22 07:40:33.378 com.apple.launchd.peruser.501[342]: ([0x0-0x36d36d].qutebrowser[43750]) Exited with code: 255

While running `/Applications/qutebrowser.app/Contents/MacOS/qutebrowser` manually provides the following output:

    /Applications/qutebrowser.app/Contents/MacOS> ./qutebrowser
    Error loading Python lib '/Applications/qutebrowser.app/Contents/MacOS/.Python': dlopen(/Applications/qutebrowser.app/Contents/MacOS/.Python, 10): Symbol not found: ___sincos_stret
      Referenced from: /Applications/qutebrowser.app/Contents/MacOS/.Python
      Expected in: /usr/lib/libSystem.B.dylib
     in /Applications/qutebrowser.app/Contents/MacOS/.Python

**Comment by The-Compiler** [comment]
Thanks, good to know! I won't support 10.8 then though, as that means I'd have to build the package on 10.8 as well, and I don't have the time to take care of that - sorry!

**Comment by for-coursera** [comment]
OK, but is this error exactly because of 10.8, or does it tell you something else? :)

**Comment by The-Compiler** [comment]
It didn't tell me anything, but searching for it tells me it's very likely to be that, yeah - also, nobody on 10.9, 10.10 and 10.11 had problems so far.

As for a rough update on this issue: I'm trying to build Qt 5.6 on OS X myself to have proper HiDPI and QtWebKit support, but having some trouble :wink:

**Comment by The-Compiler** [comment]
I just got a Qt 5.6 running and built a fresh dmg here, I'd appreciate some testing: https://qutebrowser.org/tmp/qutebrowser-v6.0.2.dmg

**Comment by tjelvar-olsson** [comment]
Hi Florian,

I did not have any joy trying to start it from the GUI. Below is the
feedback gathered trying to launch it from the command line.

$ /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Traceback (most recent call last):
  File "<string>", line 46, in <module>
  File
"/Users/flo/qutebrowser/.tox/pyinstaller/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py",
line 573, in load_module
ImportError: dlopen(/Applications/qutebrowser.app/Contents/MacOS/
PyQt5.QtCore.cpython-35m-darwin.so, 2): Library not loaded:
@loader_path/QtCore
  Referenced from: /Applications/qutebrowser.app/Contents/MacOS/
PyQt5.QtCore.cpython-35m-darwin.so
  Reason: image not found
pyi_rth_qt5plugins returned -1

Let me know if you need any further details.

Tjelvar

On 10 May 2016 at 08:00, Florian Bruhin <notifications@github.com> wrote:

> I just got a Qt 5.6 running and built a fresh dmg here, I'd appreciate
> some testing: https://qutebrowser.org/tmp/qutebrowser-v6.0.2.dmg
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/The-Compiler/qutebrowser/issues/1357#issuecomment-218074790>
>



-- 
Dr. Tjelvar Olsson

website: tjelvarolsson.com
twitter: @tjelvar_olsson <https://twitter.com/tjelvar_olsson>
skype: tjelvar.olsson

**Comment by The-Compiler** [comment]
Thanks for testing! I bet this is something about a framework vs. non-framework build of Qt... I guess I'll need to rebuild and play with it again. Or maybe I should just stick with the Qt 5.5 build until QtWebEngine is ready, seems easier that way...

**Comment by The-Compiler** [comment]
Okay, I think I finally got a running DMG with Qt 5.6 - can you please try [qutebrowser-20160528.dmg](https://www.qutebrowser.org/tmp/qutebrowser-20160528.dmg)?

**Comment by joelbrewster** [comment]
Working! Both the 20160528 and 20160528-2. Thanks for working on this.

**Comment by The-Compiler** [comment]
Awesome! I have a reliable build toolchain now, and I'll release dmg's starting with the 0.7.0 release.
