### ISSUE TITLE
Add a "." command/binding (repeat last command)

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1370]
The most naive implementation would just be to re-run the last command, basically the equivalent to `:`, `Ctrl-P`, `Enter`.

I guess a better implementation would need to do some more advanced stuff, at least I vaguely remember vim doing some more magic (see [repeat.vim](https://github.com/tpope/vim-repeat)).

**Comment by rcorre** [comment]
I've got a naive implementation that uses the command-history.
The problem is that some commands (e.g. `r` for `reload`) never go through the statusbar commandline and so never get recorded in the history.

**Comment by The-Compiler** [comment]
Hmm, true - anything using a keybinding won't land there.

The best implementation I can think of right now is just adding a global (`_last_command = None` or so) to `qutebrowser/commands/runner.py` and setting it in `CommandRunner.run`.
