### ISSUE TITLE
Add a way to substitute ({url}) and yank decoded URL

### ISSUE THREAD

**Issue by Jumblemuddle** [The-Compiler/qutebrowser#1372]
Not sure if this is intended. I'm piping the output to xclip, but I want the bash script to receive normal spaces.

**Comment by The-Compiler** [comment]
That's intended currently - qutebrowser uses [`QUrl::FullyEncoded`](http://doc.qt.io/qt-5/qurl.html#ComponentFormattingOption-enum) to make sure no information gets lost. Maybe there should be a `{url:pretty}` or something too?

**Comment by Jumblemuddle** [comment]
Something along those lines would be a nice addition. Though not very
important.
It'd be nice to not have to parse % codes elsewhere.

**Comment by lahwaacz** [comment]
Speaking of percent encoding, it would be nice to be able to `:yank` the decoded URL. Most browsers, email clients or anything you might want to paste it into will automatically encode unicode input anyway, so you wouldn't lose any information and gain human readability :wink:

**Comment by The-Compiler** [comment]
Implemented in #1435 and #1436 thanks to @forkbong!
