### ISSUE TITLE
Smooth scrolling does not work with :scroll if spatial navigation is enabled

### ISSUE THREAD

**Issue by mark-otaris** [The-Compiler/qutebrowser#1374]
If `ui.smooth-scrolling` is set to true but `input.spatial-navigation` is as well, smooth scrolling will still work with PgUp, PgDn, ^F and ^B, but it will not work with the arrow keys and with the h and j keys, all of which use the `scroll` command. Spatial navigation seems to work with the arrow keys and the h and j keys (and even with the `scroll` command called from the status bar!), but they will still be used to scroll up and down if nothing else can be done, and it would be reasonable to expect smooth scrolling in this case.

**Comment by The-Compiler** [comment]
Smooth scrolling is implemented by QtWebKit, so unfortunately there isn't anything I can do about this. Sorry!
