### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Jumblemuddle** [The-Compiler/qutebrowser#1376]
I'm sure there's a way to enable more in depth logs. Could someone let me know how to do that?
```
09:05:32 INFO: Opening in existing instance
Fatal Python error: Segmentation fault

Current thread 0x00007fc2161f8700 (most recent call first):
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 121 in qt_mainloop
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 111 in run
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 153 in main
  File "/usr/bin/qutebrowser", line 9 in <module>
```

**Comment by The-Compiler** [comment]
Seems like you're seeing the same like in #1027 - unfortunately, all stacktraces I've seen so far were unusable, and from what I've gathered from the PyQt mailinglist those kind of problems are complex interactions between Python (the garbage collector destroying objects in a random order on shutdown) and C++ (trying to run C++ destructors of objects).

Can you try [getting a stacktrace](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc)? Maybe yours is more usable for some reason.
