### ISSUE TITLE
Xslt Support

### ISSUE THREAD

**Issue by netei** [The-Compiler/qutebrowser#1380]
For example, this website uses xslt, and is printed as plain xml in qutebrowser.

https://google.github.io/styleguide/shell.xml

**Comment by The-Compiler** [comment]
Looks good here:

![xslt](https://cloud.githubusercontent.com/assets/625793/14135524/0ed5bfa2-f65e-11e5-9092-d2c1ee89aee7.png)

What Qt version are you using? (See `:open qute:version`)

**Comment by netei** [comment]
Version info

qutebrowser v0.5.1
Git commit: v0.5.1 (2016-01-18 21:45:28 +0100)

CPython: 3.4.3
**Qt: 5.5.1, runtime: 5.5.1**
**PyQt: 5.5.1**
Style: QWindowsVistaStyle
Desktop: None
sip: 4.17
colorlog: yes
colorama: 0.3.3
pypeg2: 2.15
jinja2: 2.8
pygments: 2.0.2
yaml: 3.11
cssutils: 1.0.1 $Id$
pdf.js: 1.2.109
Webkit: 538.1
Harfbuzz: system
SSL: OpenSSL 1.0.1i 6 Aug 2014

Frozen: True
Platform: Windows-8-6.2.9200, 64bit
OS Version: 8, 6.2.9200, , Multiprocessor Free

**Comment by The-Compiler** [comment]
Might be something Windows specific. I'll be able to try there later.

**Comment by The-Compiler** [comment]
It indeed looks like QtWebKit doesn't support this on Windows - not much I can do about that, sorry.
However, I tested with QtWebEngine and it works with that backend - so I guess throw that on the [QtWebEngine will solve all of your problems](http://igg.me/at/qutebrowser) pile.

**Comment by annulen** [comment]
QtWebKit has code implementing XSLT with QXmlPatterns, however right now it is never built, and XSLT is enabled only if libxslt is available (and it is not available in case of official Windows builds).
