### ISSUE TITLE
Upgrading Qt changes font rendering

### ISSUE THREAD

**Issue by brianbuccola** [The-Compiler/qutebrowser#1385]
Hi,

(Disclaimer: This issue may be better suited to the Arch forums (not sure), in which case, just let me know.)

Upgrading the following packages on Arch changes the way fonts are rendered in qutebrowser:

    qt5-base (5.5.1-10 -> 5.6.0-2)
    qt5-xmlpatterns (5.5.1-10 -> 5.6.0-1)
    qt5-declarative (5.5.1-10 -> 5.6.0-1)
    qt5-location (5.5.1-10 -> 5.6.0-1)
    qt5-sensors (5.5.1-10 -> 5.6.0-1)
    qt5-webchannel (5.5.1-10 -> 5.6.0-1)
    qt5-webkit (5.5.1-10 -> 5.6.0-2)

Here's a before and after screenshot:

![before-qt-upgrade](https://cloud.githubusercontent.com/assets/1738710/14188766/d818aae8-f792-11e5-9994-f2b458a010a7.png)

![after-qt-upgrade](https://cloud.githubusercontent.com/assets/1738710/14188799/f5fe883e-f792-11e5-8d2c-9b860c8cd6b7.png)

The main differences after upgrading are:

1. Sans font is smaller and narrower.
2. Monospace font gets rendered as sans (see `Ctrl-P` and `Enter` in the screenshots).

In case it helps, here are the fonts I have installed:

    $ pacman -Qs ttf-
    ttf-dejavu
    ttf-inconsolata-g

Running `fc-match monospace` correctly yields `"DejaVu Sans Mono" "Book"`, but that's not what qutebrowser ends up showing.

Installing `ttf-ms-fonts` doesn't help. (The sans font changes a bit, but is still rendered weird, and what should be monospace still shows up as sans.)

Any ideas? Florian, since you use Arch, are you getting this result too?

**Comment by The-Compiler** [comment]
I updated to Qt 5.6 just now, and I'm seeing the same. QtWebKit has a history of bad/odd font rendering, so I guess put that one on the [QtWebEngine will fix all of your problems](http://igg.me/at/qutebrowser) pile as well...

Feel free to open an upstream [Qt bug](https://bugreports.qt.io/secure/Dashboard.jspa) but chances are it'll just be ignored...

**Comment by brianbuccola** [comment]
Thanks. Actually, I found a workaround: simply set the appropriate font settings in qutebrowser manually. For me, this was:

    web-family-fixed = DejaVu Sans Mono
    web-family-serif = DejaVu Serif
    web-family-sans-serif = DejaVu Sans

I'm not exactly sure what `web-family-standard`, `web-family-cursive`, and `web-family-fantasy` are, so I left them blank (default). But manually changing the fixed, serif, and sans serif fonts seems to do the trick.
