### ISSUE TITLE
Pressing Enter when only one : command doesn't execute command.

### ISSUE THREAD

**Issue by Jumblemuddle** [The-Compiler/qutebrowser#1386]
It'd be nice if, when there is only one command matching the search term, that command was executed.
Instead of having to press tab then enter.

e.g. :bac should execute :back
![qutebrowser](https://cloud.githubusercontent.com/assets/3629343/14189690/3814a86e-f754-11e5-8382-7b3d193dd1d4.png)

**Comment by Jumblemuddle** [comment]
I don't believe I'm able to add labels event to my own issue.
Should probably be marked as a feature request.

**Comment by The-Compiler** [comment]
Consider yourself labelled :wink:
