### ISSUE TITLE
emoji popup in slack doesn't popup

### ISSUE THREAD

**Issue by neeasade** [The-Compiler/qutebrowser#1398]
When I go to react to a message in [slack](slack.com) with an emoji, the menu does not popup. Making an issue so it's documented. 

```txt
$ qutebrowser --version
qutebrowser v0.6.0
Git commit: v0.6.0-3-gf91935c (2016-04-04 21:31:27 +0200)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.6.0
PyQt: 5.5.1

```

**Comment by The-Compiler** [comment]
FWIW, it works fine here:

![slackemoji](https://cloud.githubusercontent.com/assets/625793/14306280/e1bae23c-fbc5-11e5-8f3d-065496fae98e.png)

Can you try with `--temp-basedir`?

**Comment by neeasade** [comment]
huh, interesting.. -- also failed with `--temp-basedir`.

**Comment by The-Compiler** [comment]
I just tried on Debian with Qt 5.3.2, no problems here either.

I'm curious, can you try testing with `scripts/testbrowser.py` with and without `--webengine` (assuming you have QtWebEngine installed)? If this goes away with QtWebEngine, I'm inclined to just close it.

**Comment by neeasade** [comment]
confirmed
