### ISSUE TITLE
Noscript-like javascript control

### ISSUE THREAD

**Issue by northern-fluff-bunny** [The-Compiler/qutebrowser#1401]
The only thing holding me back from switching from firefox to qutebrowser at the moment is the lack of noscript-like javascript control. In other words, easy way to see what javascripts and other scripts website runs and to whitelist/blacklist them per need basis.

**Comment by The-Compiler** [comment]
This will be implemented as a part of per-domain settings, see #27. I'll close this as a duplicate, but I suggest you subscribe to that issue.

My current focus is the [QtWebEngine backend](http://igg.me/at/qutebrowser) - but as soon as that's working, the next thing I'll work on is per-domain settings, so this will hopefully be implemented in the coming months.

**Comment by northern-fluff-bunny** [comment]
Thanks for the information, I'll do that.
