### ISSUE TITLE
No HiDPI support

### ISSUE THREAD

**Issue by asvc** [The-Compiler/qutebrowser#1404]
Running on OSX 10.11.3:
```
> ./qutebrowser --version
Harfbuzz fix attempted but QtWidgets is already imported!
qutebrowser v0.6.0
Git commit: v0.6.0-60-g6f5ab97 (2016-04-06 21:39:02 +0200)

CPython: 3.5.0
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5
```

![screen shot 2016-04-07 at 23 45 59](https://cloud.githubusercontent.com/assets/300146/14357344/e8bfb16a-fd1a-11e5-8f61-17fa3b30d44e.png)

**Comment by The-Compiler** [comment]
HiDPI is handled by Qt and should be fully supported with Qt 5.6. qutebrowser is currently using Qt 5.5 on OS X due to Homebrew dropping QtWebKit with Qt 5.6, but I guess that might be a reason to look into building Qt by hand...

What happens if you do `QT_DEVICE_PIXEL_RATIO=auto ./qutebrowser`?

**Comment by asvc** [comment]
with `QT_DEVICE_PIXEL_RATIO=auto ./qutebrowser` it's the same:

![screen shot 2016-04-10 at 14 31 59](https://cloud.githubusercontent.com/assets/300146/14408477/1edd2aba-ff29-11e5-92d7-b79eebcffc6d.png)

**Comment by The-Compiler** [comment]
Now I'm confused - the screenshots look perfect on my cellphone (which you can probably count as a high-dpi screen), but pixelated on my laptop. I'm guessing they look pixelated for you too?

The only thing I can see which might help is updating to Qt 5.6 - but then I'd have to get it compiling first... I'll take a look at it, but it's going to take me a while.

**Comment by asvc** [comment]
Sounds like an isolated OSX/Qt issue. Lower priority for sure.

**Comment by The-Compiler** [comment]
I just got a Qt 5.6 running and built a fresh dmg here: https://qutebrowser.org/tmp/qutebrowser-v6.0.2.dmg

Does this change anything?

**Comment by asvc** [comment]
It does, qutebrowser fails to start:
```
> ./qutebrowser 
Traceback (most recent call last):
  File "<string>", line 46, in <module>
  File "/Users/flo/qutebrowser/.tox/pyinstaller/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: dlopen(/Volumes/qutebrowser/qutebrowser.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/QtCore
  Referenced from: /Volumes/qutebrowser/qutebrowser.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so
  Reason: image not found
pyi_rth_qt5plugins returned -1
```

**Comment by The-Compiler** [comment]
Okay, I think I finally got a running DMG with Qt 5.6 - can you please try [qutebrowser-20160528.dmg](https://www.qutebrowser.org/tmp/qutebrowser-20160528.dmg)?

**Comment by The-Compiler** [comment]
I just found out about OS X' HiDPI emulation, and found out what the culprit was - [qutebrowser-20160528_2.dmg](https://www.qutebrowser.org/tmp/qutebrowser-20160528_2.dmg) should fix it.

**Comment by xtuc** [comment]
```
qutebrowser v0.6.0
Platform: Darwin-14.5.0-x86_64-i386-64bit, 64bit
OS Version: 10.10.5, x86_64
```

I solved this issue with https://stackoverflow.com/questions/20426140/how-to-enable-use-low-resolution-on-retina-display-for-an-application-when-shi

**Comment by The-Compiler** [comment]
@xtuc can you please try the latest dmg I linked above, and confirm it works fine there without changing anything?

**Comment by xtuc** [comment]
![screen shot 2016-06-04 at 17 55 46](https://cloud.githubusercontent.com/assets/1493671/15800589/9b3de8a4-2a7d-11e6-93be-3976597ab56e.png)

Yes, it looks better now.

**Comment by asvc** [comment]
@The-Compiler latest published .dmg works just fine. Thanks!

![screen shot 2016-06-04 at 23 59 43](https://cloud.githubusercontent.com/assets/300146/15800614/84bb2cbc-2ab0-11e6-95d0-1c57ef883322.png)

**Comment by xtuc** [comment]
I took some time to build the project myself. I'm not a Python developer and it felt like the dependency hell.
Could you publish that dmg as a release ? Thank you.

**Comment by The-Compiler** [comment]
The pain you had is probably due to Qt (and missing QtWebKit), the pure Python dependencies are the least painful part in my experience :wink:

I'll release the .dmg with the v0.7.0 release which will hopefully be in the next few days.

**Comment by xtuc** [comment]
Yes, exactly.

That's great. Thanks.

I think you can close this issue. HiDPI support is available and if not it's configurable in Mac.

**Comment by The-Compiler** [comment]
Ah, right - forgot to do so, thanks for the reminder!
