### ISSUE TITLE
Show summary when a BDD test fails

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1418]
Currently BDD failures dump a truckload of information, but it's really hard to find out what actually went wrong. It'd be nice if we could output a summary like:

```
:open http://localhost:1234/foo.html
:follow-hint a
<Waiting for "abcd" in the log>
Test failed: Expected bar.html to be loaded but it wasn't. Loaded URLs:
    http://localhost:1234/foo.html
    http://localhost:1234/baz.html
```

**Comment by phansch** [comment]
Hm, I'm new to Python, but coming from Ruby I was wondering the same about the verbose output. Is this something that upstream (`pytest-bdd`?) would like to have integrated?

**Comment by The-Compiler** [comment]
With my pytest-bdd co-maintainer hat on :wink::

There is https://github.com/pytest-dev/pytest-bdd/pull/147 already which gives you a more BDD-style output when running the tests. However it doesn't work together with [pytest-instafail](https://github.com/pytest-dev/pytest-instafail) which qutebrowser is also using. Contributions to change that certainly would be welcome!

The qutebrowser log output you're seeing on a failure is however produced by the qutebrowser testsuite (`pytest_runtest_makereport` and `Process._log` in `tests/integration/testprocess.py`). I'd like to keep it as it's very useful when debugging weird issues.

The "summary" logging like I presented above seems too qutebrowser-specific to add to pytest-bdd, I also think that's something which should be added to the qutebrowser testsuite.

**Comment by The-Compiler** [comment]
I decided to not add a separate summary, but to add sections to the log instead, which makes it much more readable.

I also improved the output of several common errors, and plan to improve that incrementally once I see a weird/hard to read error.
