### ISSUE TITLE
Qs: undo closed tabs between sessions

### ISSUE THREAD

**Issue by amerlyq** [The-Compiler/qutebrowser#1420]
Is there something like `undo history` or maybe it's possible to enable `u` to work in between sessions/closed windows?

When using `last-close = close` (which is my preffered way) I occasionally unintentionally may close last tab with window altogether, which I would liked to keep otherwise. But there is no way to restore it at all. So I'm forced to look through history seeking my relevant page url (which lies rather deep and only rarely at the top).

P.S. It's not strictly related to `tabs-are-windows`, because I keep multiple instances with several tabs each.

**Comment by The-Compiler** [comment]
This currently isn't possible, sorry. There's already an issue open about it however: #1031.
