### ISSUE TITLE
How to return from `view-source` to rendered page?

### ISSUE THREAD

**Issue by lucc** [The-Compiler/qutebrowser#1421]
If a view any page and hit execute `view-source` I can only get back to the orignal rendered page by reloading it. I didn't find any command to "undo" the view change done by `view-source`. But in my opinion it is sometimes undesireable to reload a page in this scenario (slow connection & big page, forms that shoud not be resent, ...). I hope to find or request a command to do the reverse of `view-source`.

Is there any command that I missed? Is this a feature that sounds reasonable?

**Comment by The-Compiler** [comment]
`:view-source` opens in a new tab here, I'm guessing it doesn't for you? Do you have some special tab setting set I don't?

**Comment by lucc** [comment]
No I don't, I just had to many tabs open to notice.
