### ISSUE TITLE
Non numbered lines in source view

### ISSUE THREAD

**Issue by cym13** [The-Compiler/qutebrowser#1431]
Description:
============

Some lines are not numbered in source code view on some pages.

How to reproduce:
=================

:open http://blog.malwaremustdie.org/2016/02/mmd-0052-2016-skidddos-elf-distribution.html
:view-source
G

Lines after the 2205th aren't being numbered.

Screenshot:
===========

![2016-04-16-112708_1366x768_scrot](https://cloud.githubusercontent.com/assets/4958985/14580227/3a889798-03c7-11e6-9ea8-ec7827bbe20d.png)

Details:
========

This was the first time I encounter this bug (but of course I don't spend most of my time checking sources).

Version:
========

qutebrowser v0.6.1
Git commit: v0.6.0-75-g4368daf (2016-04-14 18:00:06 +0200)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.6.0
PyQt: 5.5.1

**Comment by The-Compiler** [comment]
Thanks for the detailed report!

It looks fine here:

![src](https://cloud.githubusercontent.com/assets/625793/14582719/3c1b68d8-040d-11e6-9639-4004332613af.png)

When you do `:open qute:version`, what version do you get for pygments?

**Comment by cym13** [comment]
Pygment 2.1.3, the full version infos are below for reference:

Version info

qutebrowser v0.6.1
Git commit: v0.6.0-85-gd33fae4 (2016-04-15 19:31:54 +0200)

CPython: 3.5.1
Qt: 5.5.1, runtime: 5.6.0
PyQt: 5.5.1
Style: QFusionStyle
Desktop: None
sip: 4.18
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2g  1 Mar 2016

Frozen: False
Platform: Linux-4.5.0-1-ARCH-x86_64-with-arch, 64bit
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
--- /etc/arch-release ---

**Comment by cym13** [comment]
Also, I haddn't noticed before but the same phenomenon occurs at the top of the document too: lines before the 37th aren't numbered and line 38 is labeled 1.

**Comment by The-Compiler** [comment]
If you do `:debug-dump-page ~/foo.html` while in the source view and then open that file in another browser, does it look correct?

Also, can you try if it looks better when you start with `--temp-basedir`?

**Comment by cym13** [comment]
It looks correct in Firefox 45.0.2 using debug-dump-page.
There is no difference when starting with --temp-basedir.

**Comment by The-Compiler** [comment]
Okay, so pygments does the right thing, but somehow qutebrowser renders it wrong.

What confuses me is that it's not rendered monospace for you - could it be possible that you don't have any monospace font installed at all? Can you try if `pacman -S terminus-font` or so helps?

**Comment by cym13** [comment]
Actually we talked about the monospace font problem once on IRC but I forgot to raise a proper issue at that time. I have terminus and in fact it is my main font everywhere else. Someday it just wasn't used by qutbrowser anymore. That's a separate issue though.

**Comment by cym13** [comment]
Also I've tried looking at sources on other pages and almost every page has the numbering problem although not with the same offset (the numbers indicate the "real number" of the line numbered 1):

- http://blog.tenstral.net/2016/04/introducing-appstream-generator.html  18
- https://github.com/The-Compiler/qutebrowser  63
- http://ponycountdown.com/ 11

and more. The numbering problem seems quite recent, I update qutebrowser daily so I think I would have noticed it earlier otherwise.

**Comment by The-Compiler** [comment]
As mentioned in #1432 this seems like an upstream Qt/QtWebKit issue too, and it's unlikely anyone will care when I report it upstream... On the positive side, things will get better soon with QtWebEngine :wink:
