### ISSUE TITLE
Monospace font isn't used anymore

### ISSUE THREAD

**Issue by cym13** [The-Compiler/qutebrowser#1432]
Description
===========

Pages that used to be displayed using monospace fonts such as terminus aren't
anymore.

How to reproduce
================

    :open https://github.com/The-Compiler/qutebrowser
    :view-source

A monospace font should be used but isn't.

Version
=======

For qutebrowser:

    qutebrowser v0.6.1
    Git commit: v0.6.0-85-gd33fae4 (2016-04-15 19:31:54 +0200)

    CPython: 3.5.1
    Qt: 5.5.1, runtime: 5.6.0
    PyQt: 5.5.1
    Style: QFusionStyle
    Desktop: None
    sip: 4.18
    colorlog: no
    colorama: no
    pypeg2: 2.15
    jinja2: 2.8
    pygments: 2.1.3
    yaml: 3.11
    cssutils: no
    pdf.js: no
    Webkit: 538.1
    Harfbuzz: old
    SSL: OpenSSL 1.0.2g  1 Mar 2016

    Frozen: False
    Platform: Linux-4.5.0-1-ARCH-x86_64-with-arch, 64bit
    OS Version: 

    --- /etc/os-release ---
    NAME="Arch Linux"
    ID=arch
    PRETTY_NAME="Arch Linux"
    ANSI_COLOR="0;36"
    HOME_URL="https://www.archlinux.org/"
    SUPPORT_URL="https://bbs.archlinux.org/"
    BUG_REPORT_URL="https://bugs.archlinux.org/"
    --- /etc/arch-release ---

Others:

    Installed terminus-font: 4.40-2

**Comment by The-Compiler** [comment]
Qt 5.6 changed some font selection stuff compared to 5.5, so I'm guessing that's what's causing it. However, I still see Terminus there.

Can you please install `qt5-webengine`, and then try with `python scripts/testbrowser.py file:///path/to/foo.html` (where `foo.html` is the thing you produced in #1431 with `:debug-dump-page`), and then try the same with `--webengine`?

If it only shows up with QtWebKit, I'm inclined to add it to the [QtWebEngine will fix all of your issues](http://igg.me/at/qutebrowser) pile as well :wink:

**Comment by cym13** [comment]
Did that, both problems are still present with just testbrowser.py but disappear when using --webengine.

**Comment by The-Compiler** [comment]
Thanks! Unfortunately I really can't do much then, as this is an upstream Qt/QtWebEngine issue, and it's unlikely anyone will care when I report it upstream... On the positive side, things will get better soon with QtWebEngine :wink:

**Comment by AdaJass** [comment]
when will the code update to qtWebEngine?

**Comment by The-Compiler** [comment]
I'll answer in #1492 which you just opened.

**Comment by oatberry** [comment]
@cym13 try this: `:set fonts web-family-fixed <mono-font-of-your-choice>`

**Comment by cym13** [comment]
Thanks, it worked. What's strange is that I already had the font set in my .config/qutebrowser/qutebrowser.conf and it did nothing, but now that I have set it once by hand in the browser I can't reproduce the problem anymore.

Weird, but thanks really.

**Comment by rumpelsepp** [comment]
@oatberry Thx. It works.
