### ISSUE TITLE
qutebrowser-git PKGBUILD causes xmllint error?

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1442]
Can't reproduce this, but for @tschaerni this happens:

```
==> Aktualisierte Version: qutebrowser-git r7672.a559523-1
==> Beginne build()...
Calling asciidoc for FAQ.asciidoc...
Calling asciidoc for CHANGELOG.asciidoc...
Calling asciidoc for CONTRIBUTING.asciidoc...
Calling asciidoc for quickstart.asciidoc...
Calling asciidoc for userscripts.asciidoc...
Calling asciidoc for settings.asciidoc...
Calling asciidoc for index.asciidoc...
Calling asciidoc for commands.asciidoc...
Copying files...
a2x: ERROR: "xmllint" --nonet --noout --valid "/tmp/yaourt-tmp-rcerny/aur-qutebrowser-git/src/qutebrowser/doc/qutebrowser.1.xml" returned non-zero exit status 4
```

**Comment by The-Compiler** [comment]
I have `xmllint` installed, but still no error here... fun

**Comment by tschaerni** [comment]
Mee,
If I execute the xmllint command alone, I have a strange error message, and also the exit code 4:
`% xmllint --nonet --noout --valid "/tmp/yaourt-tmp-rcerny/aur-qutebrowser-git/src/qutebrowser/doc/qutebrowser.1.xml"                                                                                                                                           :(
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/tmp/yaourt-tmp-rcerny/aur-qutebrowser-git/src/qutebrowser/doc/qutebrowser.1.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
/tmp/yaourt-tmp-rcerny/aur-qutebrowser-git/src/qutebrowser/doc/qutebrowser.1.xml:5: validity error : Validation failed: no DTD found !
<refentry lang="en">
                   ^`

**Comment by The-Compiler** [comment]
It's started with `--nonet` which is described as "refuse to fetch DTDs or entities over network" - Maybe you'll need to install `docbook-sgml` so that file is present? I still can't explain why it works on other machines though :wink:

**Comment by tschaerni** [comment]
I see...
I've tested it with the package `docbook-sgml` installed, still no success. If I execute the above mentioned commend without the parameter `--nonet` it exit with 0. As you pointed out, it is not really explainable why this happens on my system...
(Of course, the whole system is an rather old install and was running on three other machines in the past, maybe there are some corrupt files?)

**Comment by The-Compiler** [comment]
No idea - but I'm going to close this as I don't think I can do anything about that - definitely doesn't look like a syntax error in any of qutebrowser's asciidoc file or anything like that.

**Comment by HolySmoke86** [comment]
One cause of this can be a broken or missing `/etc/xml/catalog`. It can be regenerated with `xmlcatalog --noout --create /etc/xml/catalog && pacman -S --asdeps docbook-xsl docbook-xml` (as root; remove or rename `/etc/xml/catalog` if it exists, but invalid)
