### ISSUE TITLE
Please make Control-d close currently highlighted tab in buffer view

### ISSUE THREAD

**Issue by gnosticscrounger** [The-Compiler/qutebrowser#1443]
While the new buffer view is a great addition to the ease of tab management, closing tabs is still more laborious than it should be. I would like a new hidden command that closes highlighted tabs in buffer view. This should ideally be bound to Control-d, making that keybinding a context sensitive means for deleting/closing selected elements in command view.

**Comment by The-Compiler** [comment]
> While the new buffer view is a great addition to the ease of tab management, closing tabs is still more laborious than it should be. I would like a new hidden command that closes highlighted tabs in buffer view. 

Sounds like a great idea - @toofar, do you want to take a look?

You'll need to implement `delete_cur_item` in `TabCompletionModel`, see `UrlCompletionModel` in `urlmodel.py` for an example.

> This should ideally be bound to Control-d, making that keybinding a context sensitive means for deleting/closing selected elements in command view.

It already is, and works for quickmarks/bookmarks

**Comment by The-Compiler** [comment]
Implemented in #1444 thanks to @toofar!
