### ISSUE TITLE
Add script for removing whitespaces

### ISSUE THREAD

**Issue by kanikaa1234** [The-Compiler/qutebrowser#1447]
A script can be added to remove trailing white spaces from ```python``` files in the repository.

**Comment by The-Compiler** [comment]
I personally don't need this (I just configure my editor to show them in red so I don't miss them), but I'm not against it either - so I'm okay with a PR to add it to `scripts/dev`, but I won't do it myself :wink:

**Comment by anikamurarka** [comment]
I would like to take up this issue @The-Compiler.

**Comment by rumpelsepp** [comment]
As an inspiration, that's basically a sed one liner: http://stackoverflow.com/a/4438318

**Comment by The-Compiler** [comment]
I added a sed/bash script in ee579b4bc3eec503ca62f4bd12a6ceff3ae053c9
