### ISSUE TITLE
YouTube embeds occasionally segfault

### ISSUE THREAD

**Issue by wu4** [The-Compiler/qutebrowser#1458]
Pressing "play" on an embedded YouTube video *sometimes* crashes with a segfault. Here are the last few lines of gdb's output, with --debug, from the result of one of these cases:

	17:52:40 INFO     webview    networkmanager:createRequest:389 Request to s.youtube.com blocked by host blocker.
	17:52:41 DEBUG    misc       webelem:is_editable:261 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html='<a href="javascript:;" data-cmd="embed" data-type="yt">Embed</a>'>
	17:52:41 DEBUG    mouse      webview:_mousepress_insertmode:282 Clicked non-editable element!
	17:52:41 DEBUG    modes      modeman:maybe_leave:114 Not in mode KeyMode.insert! (leave reason: click)
	17:52:41 DEBUG    mouse      webview:_mousepress_opentarget:325 Normal click, setting normal target
	17:52:41 INFO     webview    networkmanager:createRequest:389 Request to static.doubleclick.net blocked by host blocker.
	17:52:42 DEBUG    misc       webelem:is_editable:261 Checking if element is editable: <qutebrowser.browser.webelem.WebElementWrapper html='<div class="ytp-thumbnail-overlay ytp-cued-thumbnail-overlay" data-layer="4" style="background-image: url(https://i.ytimg.com/vi/haUWnw9oMPg/sddefault.jpg);"><button class="ytp-large-play-button ytp-button" aria-label="Watch THE KING OF FIGHTERS XIV : TRAILER #2(US)" style=""><svg height="100%" version="1.1" viewBox="0 0 68 48" width="100%"><path class="ytp-large-play-button-bg" d="m .66,37.62 c 0,0 .66,4.70 2.70,6.77 2.58,2.71 5.98,2.63 7.49,2.91 5.43,.52 23.10,.68 23.12,.68 .00,-1.3e-5 14.29,…'>
	17:52:42 DEBUG    mouse      webview:_mousepress_insertmode:282 Clicked non-editable element!
	17:52:42 DEBUG    modes      modeman:maybe_leave:114 Not in mode KeyMode.insert! (leave reason: click)
	17:52:42 DEBUG    mouse      webview:_mousepress_opentarget:325 Normal click, setting normal target
	
	Program received signal SIGSEGV, Segmentation fault.
	0x00007fffefad7c80 in QPainterPath::elementCount() const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5

**Comment by The-Compiler** [comment]
This is [a known QtWebKit bug](https://bugreports.qt.io/browse/QTBUG-44361), but QtWebKit is deprecated upstream.

This will be solved by the upcoming [QtWebEngine support](http://igg.me/at/qutebrowser) though.
