### ISSUE TITLE
[Feature request] A command to split tab into a new window

### ISSUE THREAD

**Issue by Oreolek** [The-Compiler/qutebrowser#1462]
I want an easy tab switch like Alt+Nums but also being able to split off a tab into a separate window (to put it on a different monitor, for example).

**Comment by The-Compiler** [comment]
Both of that already exists - Alt+Num works, and `:tab-detach` detaches a tab into its own window :wink:

**Comment by ipstone** [comment]
this is changed to :tab-give now. (just for people who land here when searching).

**Comment by moritzschaefer** [comment]
Is it mapped to some binding?

**Comment by jgkamat** [comment]
Moritz writes:

> Is it mapped to some binding?

should be gD by default
