### ISSUE TITLE
Drag and dropping images doesn't work

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1474]
For example, in this text box, it is not possible to attach files by drag-dropping them.

I'm using version 0.6.2

**Comment by The-Compiler** [comment]
The current backend (QtWebKit) doesn't support this, but the new [QtWebEngine backend](http://igg.me/at/qutebrowser) will support drag&drop. Not much I can do until then I'm afraid :smile:

**Comment by annulen** [comment]
Opened https://bugreports.qt.io/browse/QTBUG-53769
