### ISSUE TITLE
All magnet links open in qutebrowser

### ISSUE THREAD

**Issue by seb321** [The-Compiler/qutebrowser#1479]
Hi,
(sorry for my English, it isn't my first language.)
When I open magnet link (not only in qutebrowser) it opens first in qutebrowser. Torrent client appears when I close qb.

**Comment by The-Compiler** [comment]
Weird... what happens if you run `xdg-open magnet://...`? And I guess qutebrowser asks you "Open external application for magnet-link?" when it opens? What do you answer?

**Comment by seb321** [comment]
`xdg-open "magnet:?xt=urn:btih:33130de5c14a8bb5410746ee5a9604cdfb9538ef&dn=archlinux-2016.05.01-dual.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce"
21:18:14 WARNING: Removing NUL bytes from entry ['\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x001458504891', 'http://www.google.pl/'] - see https://github.com/The-Compiler/qutebrowser/issues/670
/usr/bin/xdg-open: linia 771: 18574 Naruszenie ochrony pamięci   (zrzut pamięci) $browser "$1"

(tixati:18727): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(tixati:18727): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(tixati:18727): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(tixati:18727): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(tixati:18727): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
~% 
`

**Comment by The-Compiler** [comment]
Okay - so it seems your system is misconfigured and thinks qutebrowser is the right thing to open a magnet-link with. You'll need to reconfigure this in your system, how to do so depends on your distribution and desktop environment.

**Comment by seb321** [comment]
hmm, but

> xdg-mime query default x-scheme-handler/magnet 
> tixati.desktop
>

**Comment by The-Compiler** [comment]
Hmm, weird! I suggest you ask on the [xdg mailinglist](https://lists.freedesktop.org/mailman/listinfo/xdg) or `#freedesktop` IRC channel (on Freenode)... I really have no idea why `xdg-open` would pick qutebrowser, but I have no idea how it works in detail, so I'm afraid I can't really help...

**Comment by seb321** [comment]
Ok, thanks.
I'll will search.
