### ISSUE TITLE
Configure behavior of middle mouse

### ISSUE THREAD

**Issue by SirCmpwn** [The-Compiler/qutebrowser#1487]
Hi there! I'd like to configure qutebrowser to open a new tab in the background when I middle click, rather than immediately focusing it. Can this behavior be configured, and if not, can an option be added?`

**Comment by neeasade** [comment]
`background-tabs = true`

**Comment by The-Compiler** [comment]
What @neeasade said should work - though that also opens tabs from some other actions in the background IIRC.

**Comment by SirCmpwn** [comment]
Thanks. I'd prefer to configure it alone but I suppose that works.
