### ISSUE TITLE
when will the code update to qtWebEngine? 

### ISSUE THREAD

**Issue by AdaJass** [The-Compiler/qutebrowser#1492]
I'm using this code, if possible i could help maybe.

**Comment by The-Compiler** [comment]
I plan to start working full-time on QtWebEngine support (after a [successful crowdfunding](http://igg.me/at/qutebrowser)) in May/June/July, can't give a more exact date yet. Probably mid-June, but don't quote me on that.

After I started it's difficult to say how long things will take, and it also depends on what features you need to work exactly. See #666 for a rough list.

Help would certainly be appreciated - the best way to help out currently is by writing tests, see #999 for some more details. Help with QtWebEngine itself will probably be problematic as initially I'll be refactoring and moving around a lot of stuff. At some later point when the initial things are done that might make more sense.
