### ISSUE TITLE
Searching text on page: regex impossible?

### ISSUE THREAD

**Issue by amerlyq** [The-Compiler/qutebrowser#1500]
Actually, each time switching windows from vim to qutebrowser feels like my hands broken, as I can't input searched token as regex. Investigating many similar articles for similar words is tiresome without that -- necessary words are very common ones and only their mutable combo is unique. So almost whole page is yellow by matches on each search of any word and I can't see desired entries -- either if I haven't used page search at all. 

I suppose adding support for native perl-compatible regexes activated by option in config (for those which can type them without restrictions) isn't too troublesome, isn't it?

**Comment by The-Compiler** [comment]
It is, because the Qt API doesn't provide any way to search via regex. I asked to add that to QtWebEngine (qutebrowser's future backend) in [QTBUG-50420](https://bugreports.qt.io/browse/QTBUG-50420), but until they add support for it, there really isn't much I can do...

**Comment by amerlyq** [comment]
It's a pity. I thought there was more low-level api to gain access to text layer on top of which we could use python. I hope that QT feature request won't be rejected.

**Comment by The-Compiler** [comment]
I took a quick look at it and I don't see any easy way how Chromium would expose an API to search for a regex, so it's somewhat unlikely QtWebEngine will...

There's always javascript, but that'd mean reimplementing the whole search feature in JS, which sounds like a lot of effort...

**Comment by emilBeBri** [comment]
Any progress on this? would love to use wildcarrds/globs/regex/search at current position on page, whatever would get me to where I need to go faster than the current search method

**Comment by The-Compiler** [comment]
@emilBeBri See #5652

**Comment by emilBeBri** [comment]
Ok, so as far as I can tell from the link, no solution, but that would be the place to look if/when there is a solution, is that correctly understood? thanks.

**Comment by The-Compiler** [comment]
correct, yes.

**Comment by slacksystem** [comment]
> It is, because the Qt API doesn't provide any way to search via regex. I asked to add that to QtWebEngine (qutebrowser's future backend) in [QTBUG-50420](https://bugreports.qt.io/browse/QTBUG-50420), but until they add support for it, there really isn't much I can do...

It looks like this issue in the link is closed and marked as fixed? Does that mean this would be manageable to implement now?

**Comment by The-Compiler** [comment]
See the comments there, nothing changed about regex matching unfortunately.
