### ISSUE TITLE
Use json logging for end-to-end tests

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1501]
Parsing the normal qutebrowser log line-by-line was useful to get started writing tests, but it comes with some problems:

- Sometimes multiline-stuff is logged, which needs some changes to how things is logged or indentation
- Things like cutting off too much information when there's an exception

Instead we should have a `--json-logging` argument which gets used for end-to-end tests, a custom `logging.Formatter` which outputs a json-line for each log message, and some code to convert that back to a normal log line for output in the test process.

**Comment by Kingdread** [comment]
Working on it, give me a few days :wink:
