### ISSUE TITLE
Notification acceptance is not persisted

### ISSUE THREAD

**Issue by thiderman** [The-Compiler/qutebrowser#1509]
We use [Slack](https://slack.com) at work. They have desktop notifications, which work well with qutebrowser (a fact that gave me insane amounts of warm fuzzy feelings).

However, whenever I close my Slack tab and bring it back up again, Slack will ask me once again and I have to confirm with qutebrowser that I want to allow Slack to do desktop notifications. This feels off. Shouldn't such a thing be persisted?

**Comment by The-Compiler** [comment]
I agree, see #832 - I'll implement that once per-domain settings are in (#27).
