### ISSUE TITLE
Startup Urls inside config

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1511]
I know it is possible to open urls from the command line when starting qutebrowser, but I think it would make sense to allow the possibility of opening urls on startup from the config file, do you agree ?

**Comment by The-Compiler** [comment]
I agree, and the [general -> startpage](https://github.com/The-Compiler/qutebrowser/blob/master/doc/help/settings.asciidoc#general-startpage) setting does just that :wink:
