### ISSUE TITLE
Make C-w behave like in readline

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1512]
Hi, I'm used to `C-w` deleting up to the next whitespace.

For example, if your command is : `:open -t http://google.com`, Hitting `C-w` should remove the whole http://google.com part, however it only removes up to the first `.`.

Usually the readline binding to remove up to the next word is bound to `C-Backspace`

**Comment by The-Compiler** [comment]
The associated command (`:rl-unix-word-rubout`) simply uses Qt's [`QLineEdit::cursorWordBackward`](http://doc.qt.io/qt-5/qlineedit.html#cursorWordBackward) currently which has that behaviour. It should probably do the word matching manually to match words like readline.

**Comment by edi9999** [comment]
It seems that there isn't any standard component for readline keybindings in Qt, maybe I will find the time to create such a library :-)

**Comment by The-Compiler** [comment]
I won't be able to use an external library which isn't commonly packaged in distributions, but a pullrequest to fix this in qutebrowser's [`readline.py`](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/misc/readline.py#L151-L163) would certainly be most welcome!
