### ISSUE TITLE
Hints click wrong position on Geizhals

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1514]
On http://geizhals.de/?o=9 when hinting a title (e.g. "Intel Sockel 1151"), the wrong link is clicked (Gigabyte, under the title)

@error800 @lahwaacz any idea what's going on there?

**Comment by lahwaacz** [comment]
No deep insights, but it seems to work fine for me with #1433 (due to 4c06e3407438fc299618f8d2afbc99512b7bc608) :wink:

**Comment by The-Compiler** [comment]
Yay! I'll try to create a small testcase for it tomorrow or so based on the geizhals page.

**Comment by The-Compiler** [comment]
Added it to `tests/manual/hints/other.html` for now.
