### ISSUE TITLE
Avoid displaying key-hints in some situations

### ISSUE THREAD

**Issue by lamarpavel** [The-Compiler/qutebrowser#1515]
The new feature of key-hints is very useful for commands I don't remember well or didn't know about, but they can get annoying for commands like `gg`, that I type a lot and know by heart.

I have two quick ideas about this, but I haven't reached a conclusion for myself yet, so this issue is meant for discussing ideas - hoping for input from others.

1. There could be a delay for showing the hints. Key chains that I know well, like `gg` will be entered rapidly and should not trigger hints, so a delay of ~500ms might work to avoid showing unnecessary hints while still helping when I'm hesitating.

2. Have a blacklist for key chains that should not trigger hints. If the only chains starting with `g` are `gg` and `gh` (for example) and both `gg` and `gh` are on a blacklist, then don't trigger hints when I press `g`. This scheme has the nice property of being adaptive: When I add another key chain `gt`, the hints will show again when pressing `g` until I have memorized `gt` and blacklist it as well.

Of course, both of these ideas can also be combined.

Discussion and further ideas welcome. And thanks to @rcorre for introducing key-hints.

**Comment by The-Compiler** [comment]
FWIW having a delay is what I see in other applications (like spacemacs) as well, and I think it makes a lot of sense - if you know a binding you're going to be faster than, say, 500ms - and if you don't, you'll naturally wait a bit trying to remember what to type, and then you get help :wink:

**Comment by rcorre** [comment]
Both good ideas! I figure the blacklist could also interpret globs like `g*` to ignore all bindings starting with `g`.

**Comment by rcorre** [comment]
If it did support globs, should `keyhint-blacklist` replace `show-keyhints` as `keyhint-blacklist=*' would be equivalent to `show_keyhints=false`?

Does `keyhint-blacklist` belong in `ui` or `input`? (`show-keyhints` is in `ui`)

**Comment by The-Compiler** [comment]
I'm all for replacing the option instead of adding a new one :wink: I think `ui` is good.

**Comment by lamarpavel** [comment]
Wow, that was fast, thanks a lot for this quick feature patch @rcorre 

The hint delay might have implications for the key timeout though, doesn't it? The hints vanish rather fast now.
Also, I would set the standard font and color of keyhints to that of regular hints or the status bar: eg. `keyhint = ${statusbar}`.
That way they fit the already configured theme of the user.

**Comment by rcorre** [comment]
> The hint delay might have implications for the key timeout though, doesn't it
Good point, I should probably add the delay to the timeout. It shouldn't be too quick by default though, as the new timeout is 5 seconds. Maybe yours is still the old default (1s), so you only get 0.5s to read it?

**Comment by rcorre** [comment]
Actually, that makes it a bit confusing, as now the hints would be shown 0.5s _after_ the partial timeout ends, meaning you could no longer actually input the keychain.

**Comment by lamarpavel** [comment]
>Maybe yours is still the old default (1s), so you only get 0.5s to read it?

It was 2 seconds, apparently I configured that at some point.

**Comment by The-Compiler** [comment]
FWIW I'd rather keep the font definitions separate - otherwise you could argue everything should use the font of the statusbar/completion by default, which is kind of pointless - people can still adjust `${_monospace}` or they'll just have to set up new options to their liking :wink:

**Comment by lamarpavel** [comment]
@The-Compiler Fair enough. My impulse was that a new feature was added and did not fit with my other configuration, using existing config as default for a new feature seemed reasonable to me.
