### ISSUE TITLE
Feature Request: Purge UTM data when yanking url

### ISSUE THREAD

**Issue by demure** [The-Compiler/qutebrowser#1516]
It would be desirable if [UTM](https://en.wikipedia.org/wiki/UTM_parameters) data at the end of URL's could be striped on yank, as they both track and make links unwieldy.

**Comment by The-Compiler** [comment]
Hmm, I wonder if that should be configurable or just be done by default?

**Comment by The-Compiler** [comment]
`ref` probably should also be stripped away

**Comment by demure** [comment]
I would vote for it being the default. But I can see the benefit in having a setting, and by extention a per site setting in the future.  Depending on how this is implemented and how many kinds of stripping (utm, ref, etc) are used, it might be desirable to let certain sites be excluded. Examples massdrop can have `?mode=guest_open` at the end to allow viewing a page without logging in; and a developer might want to work with UTM on their own site.

**Comment by The-Compiler** [comment]
I think it'd make most sense to add a list of parameters as a setting, with `ref, utm_source, utm_medium, utm_campaign, utm_term, utm_content` as default.

**Comment by The-Compiler** [comment]
This should probably implemented by creating a [QUrlQuery](http://doc.qt.io/qt-5/qurlquery.html) from the URL, using [RemoveQueryItem](http://doc.qt.io/qt-5/qurlquery.html#removeQueryItem) to remove them, and then setting the query on the URL via [setQuery](http://doc.qt.io/qt-5/qurl.html#setQuery) again.

**Comment by The-Compiler** [comment]
Implemented in #1889 / 29715ae7a72eb8a304b924a179f6037d018a2275.
