### ISSUE TITLE
textbox on wolframalpha rendered incorrectly

### ISSUE THREAD

**Issue by craftyguy** [The-Compiler/qutebrowser#1522]
The main textbox/search box on wolframalpha.com does not render correctly. It only displays characters up to about 1/3rd of the total length before it starts scrolling:

![2016-05-23_1243x1367_scrot](https://cloud.githubusercontent.com/assets/1474209/15480126/b01249cc-20d8-11e6-88dc-92438860c030.png)

**Comment by The-Compiler** [comment]
Unfortunately I'll need to give you the usual answer - QtWebKit issue (maybe due to it not supporting CSS flex layout which is used for the box? Not sure.),  but it works fine with QtWebEngine (tested with `scripts/testbrowser.py --webengine`).
