### ISSUE TITLE
Consider <ctrl>+n and <ctrl>+p for completion

### ISSUE THREAD

**Issue by rumpelsepp** [The-Compiler/qutebrowser#1529]
I am used to the vim keybindings, since I use it every single day. When my autocompletion triggers I usually select the item from the drop down with <kbd>ctrl</kbd> + <kbd>n</kbd> and <kbd>ctrl</kbd> + <kbd>p</kbd>. In qutebrowser I have to use <kbd>tab</kbd> and <kbd>shift</kbd> + <kbd>tab</kbd>. The context switch is a bit annoying; mind adding that to the default binds as well? :)

**Comment by NoctuaNivalis** [comment]
IIRC, those to are currently used by default to step through the command history.

**Comment by rumpelsepp** [comment]
hmm, I see...

**Comment by The-Compiler** [comment]
I'd rather keep the current behavior (which is the same as the commandline in vim, by the way) :wink:

**Comment by ewtoombs** [comment]
The current behaviour is fine, of course, but ^N and ^P are unmapped in this context.
I don't see the harm in adding them as aliases.
(I, too, reached for ^N and ^P first, and actually had to come here to even learn that the mappings were Tab and Shift+Tab.
It's like that in fish, for instance.)

**Comment by The-Compiler** [comment]
They aren't unmapped, as already pointed out above.

**Comment by ewtoombs** [comment]
I just tried it out, @The-Compiler  .
I see how they work.
But then as soon as you go to edit a line, they do nothing.
Also, nothing happens when I hit 'o' in normal mode, then try ^N and ^P.
It's at that point where they could work the same way as the arrow keys.

**Comment by The-Compiler** [comment]
They use the existing input as a filter for the history, so after `:open ` it will go through all previous `:open` commands.

**Comment by ewtoombs** [comment]
Oh, now I see.
I never noticed because I was like hammering on ^N the whole time, but never thought to try ^P lol.
Yeah, those keys are actually mapped.
It's useful, really.

**Comment by ewtoombs** [comment]
I'm getting other issues using it, though.

I have to type https://the^P to get the first completion.
It can't do mid-string substring matches.
Then, after just one ^P, the next search fails because the whole line is already full and it searches with the entire line.
So, I can only search backward once.
It is useful but could be more useful.
In any case, this is a different issue.

**Comment by The-Compiler** [comment]
Works fine here.

**Comment by ewtoombs** [comment]
mid-string substring matching works with ^P?

**Comment by The-Compiler** [comment]
Sure:

- `:open https://the1.example.org`, `<Enter>`
- `:open https://the2.example.org`, `<Enter>`
- `:open https://the`, `<Ctrl+P>` → `:open https://the2.example.org`
- `<Ctrl+P>` again → `:open https://the1.example.org`

But like you say, nothing of this has anything to do with this 9 year old issue.

**Comment by ewtoombs** [comment]
That isn't midstring substring matching.
:open the^P should complete to both of those results.

**Comment by ewtoombs** [comment]
I don't know why two ^Ps isn't working for me, but I tried it again, and it definitely isn't.
