### ISSUE TITLE
High CPU usage on some pages

### ISSUE THREAD

**Issue by sim590** [The-Compiler/qutebrowser#1537]
### Version

```
qutebrowser v0.6.2
Git commit: v0.6.0-653-g97ad808 (2016-05-31 23:45:12 +0200)

CPython: 3.5.1
Qt: 5.6.0, runtime: 5.6.0
PyQt: 5.6
```

### Issue description

For e.g., this [page](http://www.forbes.com/sites/bernardmarr/2016/05/27/how-blockchain-technology-could-change-the-world/#673b7f7a49e0) triggered alot of cpu usage. This occurs when the currently viewed tab is running the faulty page. Having this page open, I presently have 30% CPU usage. Here's a screenshot showing some info:

![high cpu usage monitored](https://i.imgur.com/FDCZZu2.png)

As you can see in the right bottom corner of the image, I have run `sudo perf top -p ${qute_pid}` and you can see that `libQt5Gui.so.5.6.0` seems to be the source of all that.

If I should provide any more information, tell me.

**Comment by NoctuaNivalis** [comment]
Might have something to do with this:
![2016-06-02-091454_1920x2160_escrotum](https://cloud.githubusercontent.com/assets/994166/15736792/81ff7ce0-28a2-11e6-9496-9b2c8d61f2f6.png)

The site uses quite some javascript, and it doesn't look very stable.

**Comment by The-Compiler** [comment]
Viewing this page with Firefox or Chromium also gives me 40%-120% CPU usage by the respective process.

I'm going to have to blame the page here.
