### ISSUE TITLE
support for launching multiple websites from 1 quickmark

### ISSUE THREAD

**Issue by zeltak** [The-Compiler/qutebrowser#1538]
Hi

in vimperator, cvim, dwb etc its possible to assign multiple web pages to one quickmark.

so when i press QM 'a' a bunch of associated links open in separate tabs

for example in vimperator the syntax is like this

``` silent qmark 6 http://woot.com , http://1saleaday.com/ , http://mobile.dailysteals.com/ , http://slickdeals.net/ , http://www.priceplunge.com/ , http://deals.woot.com/ ```

would love to see support in qute

best 

Z

**Comment by rcorre** [comment]
Would #1422 work for you? Rather than having one quickmark with multiple urls, you would put multiple quickmarks under one 'folder' and open everything in that folder.

**Comment by The-Compiler** [comment]
@zeltak Hey, any update on the comment by @rcorre? I think that would be the cleaner solution to this.

**Comment by The-Compiler** [comment]
We agreed in IRC #1422 would be a better solution.
