### ISSUE TITLE
Allow hint --rapid with normal

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1541]
Right now rapid hinting is disabled in `normal` hint mode.
Recently I had to delete a bunch of items from my Amazon shopping cart.
There are no checkboxes to perform a multi-select, just a `delete` link on each item.

I removed the limitation on using `--rapid` with `normal`, and to my suprise, it worked!
It was a little disorienting as the link positions shifted each time I deleted an item, but it saved me from pressing `f` each time.

Should we remove this limitation?

**Comment by The-Compiler** [comment]
Hmm, good point. When I added the limitation I didn't think about clicking links which do something other than following a new link.

I bet it's nice when having to tick a lot of checkboxes for some reason too. Let's get rid of it!
