### ISSUE TITLE
:bind is case-sensitive

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1544]
```
:bind <ctrl-T> message-info this
:bind <Ctrl-T> message-info shouldn't
:bind <ctrl-t> message-info work
```

Pressing `ctrl-t` still executes the originally mapped command `open -t`, but none of the above complain about a conflict.

I guess for now we should capitalize all keys when we load or set bindings (as `<Ctrl-T>` seems to be the canonical way to spell it)?

**Comment by rcorre** [comment]
Actually, I guess its just easier to store them all lowercase in memory

**Comment by The-Compiler** [comment]
I think this is a duplicate of #816.
