### ISSUE TITLE
Directory to share Qutebrowser userscripts?

### ISSUE THREAD

**Issue by t1mxg0d** [The-Compiler/qutebrowser#1549]
Is there anywhere for devs to post links to userscripts we've created?

I created a simple userscript for saving the current page to Instapaper via keyboard shortcut: (https://github.com/t1mxg0d/instapaper.zsh). Currently working on another for Pinboard.

A Github wiki or a page on [Qutebrowser.org](https://qutebrowser.org) would be perfect.

**Comment by The-Compiler** [comment]
As mentioned in IRC, there's [misc/userscripts](https://github.com/The-Compiler/qutebrowser/tree/master/misc/userscripts) in the repo, on some distributions those even get installed by default.
