### ISSUE TITLE
Youtube opens a blank pape after loading - cant close it

### ISSUE THREAD

**Issue by maxepowers** [The-Compiler/qutebrowser#1558]
Hello all,

some days ago youtube started displaying this blank pape after loading the website:
http://s33.postimg.org/sudotgqsv/2016_06_07_123944_1510x1038_scrot.png

Iam unable to close it. Also trying to follow links on the youtube page does not work.
It seems like its an notefication from youtube where i have to accecpt something, but there is just no content on this thing.

Best regards, maxe

**Comment by The-Compiler** [comment]
I think it's the Google privacy reminder thing - can you open youtube with another browser, and accept it? Then it should be gone in qutebrowser as well.

Unfortunately there isn't much I can do, but the future [QtWebEngine backend](http://blog.qutebrowser.org/) should help with that as well.

**Comment by maxepowers** [comment]
I tried that, but the white blank page stills opens in qutebrowser.
I dont mind waiting for the new Engine backend. I dont browse youtube that often.
Thanks for the reply, at least i know what it is now.

I wonder if there are other people having that issue and if they could fix it by accepting it with another browser.

**Comment by maxepowers** [comment]
I tried that, but the white blank page stills opens in qutebrowser.
I dont mind waiting for the new Engine backend. I dont browse youtube that often.
Thanks for the reply, at least i know what it is now.

I wonder if there are other people having that issue and if they could fix it by accepting it with another browser.

**Comment by The-Compiler** [comment]
I've seen the same thing a few weeks/months ago, and I think I was able to do that.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
I experience the same with youtube.com as well as google.com.

Excepting the policies in both firefox and chrome also don't fixed it for
me. So I just ignore it, because I use youtube usually with mpv and youtube-dl.

**Comment by fischerling** [comment]
Sorry for the spam don't now what went wrong! o.O

**Comment by The-Compiler** [comment]
@fischerling hehe - do you happen to have a custom user-agent? GitHub doesn't show submitted comments (and has other issues) except with the default UA.

**Comment by fischerling** [comment]
@The-Compiler Aah thanks ! I changed it a while ago and forgot about it.
@maxepowers Changing the UA back to default fixed weird github as well as the blank page at youtube. :)

**Comment by maxepowers** [comment]
@fischerling: Yes clearing the entry in User Agent also worked for me. What was the default? I just deleted everything in the field.
I forgot why i even filled it with something ..
