### ISSUE TITLE
Error in refactoring numeric hinting

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1559]
There was an error in the refactoring after #1194, I've added a line note to the commit: https://github.com/The-Compiler/qutebrowser/commit/5ddc57566d24bd34cd6ab01a41029de35a933fbd#commitcomment-17773363

If you'd like to add a test case, press `f` and type something to get an incomplete match, press Backspace and type something that doesn't match any hint on the page.

**Comment by The-Compiler** [comment]
Whoops - thanks!
