### ISSUE TITLE
tab-history command feature

### ISSUE THREAD

**Issue by esprout** [The-Compiler/qutebrowser#1561]
It would be useful to have a tab-history command that lists the tab history of the current tab.

tab-history
Syntax: :tab-history [--left] [--right]
Show history of current tab.
optional arguments
-l, --left: Show back history only.
-r, --right: Show forward history only.

Could be mapped to keys such as `<Alt-H>` and `<Alt-L>`

**Comment by The-Compiler** [comment]
How would it show the history? What about a HTML page, similar to `:messages` (or `:open qute:log` on older versions)?

**Comment by rcorre** [comment]
This might not fufill the OP's use case, but it would be neat if `back` listed tab-history urls as completions.

**Comment by esprout** [comment]
Yes, it should show it the same way :open shows all history right now.  Having :back list history of current tab would suffice for my use case.  Wouldn't be as flexible, but would be good enough.

**Comment by The-Compiler** [comment]
Sounds like a great idea, didn't even think of that!

However `:back`/`:forward` taking an URL sounds weird, so the completion would have to complete to indices or something.

I added it to #32 which lists several "missing" completions, so I'm closing this one.
