### ISSUE TITLE
Add ability to jump between completion sections

### ISSUE THREAD

**Issue by flv0** [The-Compiler/qutebrowser#1567]
For people having many quickmarks (or searchengines if we decide to show them in the completions) it would be great to be able to jump between the different sections (quickmarks, bookmarks, history, searchengines). 

Keybinding proposal: 
tab : next entry
shift-tab : prev entry
ctrl-tab : next section
shift-ctrl-tab : prev section

**Comment by The-Compiler** [comment]
Since @rcorre merged `:completion-item-prev` and `:completion-item-next` into `:completion-focus {prev,next}`, this could be implemented as `:completion-focus prev-category` and `:completion-focus next-category`.
