### ISSUE TITLE
are.na sign-up not working

### ISSUE THREAD

**Issue by vyaas** [The-Compiler/qutebrowser#1569]
Is it just me, or does the [are.na](https://www.are.na/) sign-up page not render? 

Here's what I see on qutebrowser when I click "Sign up":
![qute_arena](https://cloud.githubusercontent.com/assets/4044380/15973295/81047b8c-2ef7-11e6-879b-53b062207f12.png)
And here's what I should be seeing (I used icecat):

![icecat_arena](https://cloud.githubusercontent.com/assets/4044380/15973315/a45c57f8-2ef7-11e6-94ed-18c7c812c281.png)

Please pardon my noobness for posting this as a separate issue while it may very well be related to one of the js issues posted previously.

**Edit:** fixed link

**Comment by The-Compiler** [comment]
It works for me with qutebrowser but not with the minimal testbrowser (`scripts/testbrowser.py`). Do you have private browsing enabled by any chance?

**Comment by vyaas** [comment]
I don't have private browsing enabled.
I run qutebrowser on arch linux and this is my version info:

>qutebrowser v0.6.2
>Git commit: 
>
>CPython: 3.5.1
>Qt: 5.6.0, runtime: 5.6.0
>PyQt: 5.6

**Comment by The-Compiler** [comment]
Does it work for you when you start qutebrowser with `--temp-basedir`?

**Comment by vyaas** [comment]
>Does it work for you when you start qutebrowser with --temp-basedir?

Ah it does! So what have I been doing wrong?

**Comment by The-Compiler** [comment]
I don't know, it must be some setting which is influencing it - can you please reproduce it in a fresh instance and then do `:report` so I get a debug log?

**Comment by vyaas** [comment]
>I don't know, it must be some setting which is influencing it - can you please reproduce it in a fresh instance and then do :report so I get a debug log?

Indeed! 

I use a tor-polipo-privoxy proxy chain and had disabled all cache-storage on qutebrowser by setting

>maximum-pages-in-cache = 0
>object-cache-capacities = 
>offline-storage-default-quota = 
>offline-web-application-cache-quota = 
>offline-storage-database = false
>offline-web-application-storage = false
>local-storage = false
>cache-size = 0

in qutebrowser.conf. Just to make extra sure, I always run qutebrowser with _--cachedir=""_.

It turns out that when I set the _local-storage_ to _true_, the site opens properly. 

Your thoughts?

(I have also filed a report as you suggested.)

**Comment by The-Compiler** [comment]
I bet the page won't work in another browser when turning off local storage either :wink:

Can you verify that somehow? Otherwise I'll take a look later.

**Comment by vyaas** [comment]
>I bet the page won't work in another browser when turning off local storage either 
>
>Can you verify that somehow? Otherwise I'll take a look later.

I used icecat and overrode the "cache management" to use 0MB of cache and made it use my tor-polipo-privoxy proxy chain. The site still works. Don't know why.

**Comment by The-Compiler** [comment]
Cache and [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) are two different things. I tried with Firefox and `dom.storage.enabled` set to `false` in `about:config`, and I see the same.
