### ISSUE TITLE
Delay in showing hints when there are a large number of links

### ISSUE THREAD

**Issue by craftyguy** [The-Compiler/qutebrowser#1573]
I've noticed, within the last day or two, that there's a rather large delay (~5seconds) between hitting 'f' and qute showing hints. This seems to happen on sites where there are a lot of links, it can easily be reproduced on https://reddit.com/r/frontpage

**Comment by The-Compiler** [comment]
I don't think that link is correct, but whatever :laughing: 

That's a consequence of the new (more accurate) JS hint implementation. It might get better when I have a pure JS implementation for hints, which will probably happen for QtWebEngine.

You can switch back to the Python implementation via `:set hints find-implementation python`. Then the better implementation will still be used for clicking, but the drawing of hints might be off in some corner cases.

**Comment by craftyguy** [comment]
Thanks, I'll switch back since the previous implementation worked OK for me and having a delay on some  sites  I use is less desireable :)
