### ISSUE TITLE
Npmjs.org fails to show results

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1581]
It seems that the search site of npm doesn't show any results on npm (version 0.6.2)

For example : 

https://www.npmjs.com/search?q=lodash

Here are the errors that show in the console.

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://img.en25.com/i/elqCfg.min.js https://api.stripe.com https://checkout.stripe.com/checkout.js https://js.stripe.com https://platform.twitter.com/oct.js https://www.google-analytics.com https://fonts.googleapis.com https://s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js https://npmjs.us9.list-manage.com https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js https://cdn.optimizely.com/js/3318080746.js https://cnstrc.com/js/ac.js https://ac.cnstrc.com https://static.accountdock.com/app.min.js https://assets.npmjs.com https://js-agent.newrelic.com https://bam.nr-data.net 'nonce-2dd06a511a6045712292f9b4eb846d5ea0790e5f25f4a9942409cb874c0bb1190d44bc6d3fdd3e1ccc46e98e5bed28ec053e889f5bfebd80450c9c1092c050a4'".
 /search?q=lodash:5
GET https://img.en25.com/i/elqCfg.min.js %HOSTBLOCK% search:32
GET https://www.google-analytics.com/analytics.js %HOSTBLOCK% [native code]:1
```

Do you know if this is on npmjs or on qutebrowser ?

**Comment by The-Compiler** [comment]
I get search results, however for some reason there's a screen full of blue (rather than just a bar) rendered before them.

I tested with QtWebEngine, and this will be one of many issues which will be fixed by it :wink:

**Comment by edi9999** [comment]
Ok, yep, indeed, I just have to scroll to see the results.

Is master already using QtWebEngine ?
Would you recommend to follow master or is it too unstable yet ?

**Comment by The-Compiler** [comment]
> Is master already using QtWebEngine?

No - there's a `qtwebengine` branch I started today but it's not usable at all so far

> Would you recommend to follow master or is it too unstable yet?

Master should usually be pretty stable, and I can always use a few more guinea pigs :wink:

**Comment by edi9999** [comment]
Ok, thanks, will be following master than !
