### ISSUE TITLE
Don't reload page when url didn't change with `:edit-url`

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1604]
Everything is in the title, since I bound `e` to `:edit-url` and sometimes press it by mistake, I would like to be able to quickly undo this (so I just hit `ZZ` in vim), but this will then reload the page, which I don't want since the URL hasn't changed.

Do you agree ?

**Comment by The-Compiler** [comment]
Sounds good, and should be easy to implement!

**Comment by blyxxyz** [comment]
I'm implementing this as a general command that calls `:open`/`open_url` only if the URL for the tab changed. It makes sense for the `go` keybinding too (currently `:open {url:pretty}` - any other suggestions?

**Comment by The-Compiler** [comment]
Hmm, not so sure if it's really necessary to add a new command, we have enough of those already :wink:

I can see how it'd make sense with `go`, but there an user can just press `esc`. I'd prefer this just being implemented for `:edit-url` to be honest.

**Comment by blyxxyz** [comment]
That's true. I needed to implement it as a full wrapper function around `:open` because of the way `:edit-url` calls it, so I thought I might as well make it into a command. I'll leave it as just a function.

**Comment by blyxxyz** [comment]
If you give `:edit-url` a count it edits the url of the current tab, not of the specified tab, but loads it in the specified tab. Is that intended?

**Comment by The-Compiler** [comment]
Hmm, I'm not sure, both behaviours make sense in some way. Maybe we should disallow a `count` for `:edit-url` altogether? /cc @rcorre

**Comment by edi9999** [comment]
> Maybe we should disallow a count for :edit-url altogether? /cc @rcorre

I agree with that.

**Comment by rcorre** [comment]
edit-url has a count? news to me :)
I think it shouldn't.

As far as reloading, I think `:open` and friends should always reload, but `edit-url` should only reload if it changed.

**Comment by blyxxyz** [comment]
> Maybe we should disallow a `count` for `:edit-url` altogether? /cc @rcorre

Sounds good to me. I'll remove that too, then.

**Comment by The-Compiler** [comment]
okay, great! :+1:

**Comment by rcorre** [comment]
edit-url takes a count? News to me :)
I think it probably shouldn't.

As far as reloading, I think :open and friends should always reload, but it makes sense for :edit-url to only reload if it changed. 

Now I'm curious what happens if you delete all content (I'm thinking of how git aborts on an empty commit message)


On June 30, 2016 11:05:23 AM EDT, Florian Bruhin <notifications@github.com> wrote:
>Hmm, I'm not sure, both behaviours make sense in some way. Maybe we
>should disallow a `count` for `:edit-url` altogether? /cc @rcorre 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/The-Compiler/qutebrowser/issues/1604#issuecomment-229687132

- Ryan

**Comment by The-Compiler** [comment]
> Now I'm curious what happens if you delete all content (I'm thinking of how git aborts on an empty commit message)

I suspected a possible crash, but it shows an `Invalid URL` error :laughing:

**Comment by edi9999** [comment]
Closed since : https://github.com/The-Compiler/qutebrowser/pull/1608
