### ISSUE TITLE
Is they a way to copy the link instead of going to the link with something like yf ?

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1605]
Sometimes, I have to copy a link to the clipboard instead of wanting to go there (going to the link is what `f` does).

Is they a way to do that already, or should I create a PR to add this possibility ?

**Comment by The-Compiler** [comment]
You mean with hints? See the extended hints starting with `;`, so what you're searching for is `yy`.

**Comment by edi9999** [comment]
Oh, yes that's exactly what I want. Thanks a lot !!
