### ISSUE TITLE
Add :hint --group input

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1607]
Sometimes, when I use f, I want to focus on a textarea/input/other type of form.

When I want to do this, I achieve it using the `f` keyboard shortcut and press the letter that is on the given input element.

I found out that they are special "groups" , for example to show only the links, or only images. I think it would make a good feature to only have "input" elements (this would also target textarea)

What do you think ?

**Comment by The-Compiler** [comment]
You can do `:hint inputs` since v0.7.0 thanks to @Liambeguin :wink:

**Comment by edi9999** [comment]
Maybe a default keybinding would make sense. 

What do you think of `;t` (for text, since ;i is already for images) ?

**Comment by edi9999** [comment]
Also this seems to be undocumented

**Comment by edi9999** [comment]
Anyway, that is great, thanks a lot for the help, I'm mapping ;t on my machine for now

**Comment by The-Compiler** [comment]
Oh, good catch - thanks! I added `;t` as default binding and documented it in ce8315b.

**Comment by edi9999** [comment]
Awesome work ! Thanks !
