### ISSUE TITLE
Mark expected errors clearly in end2end test output

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1611]
When an end2end test expects an error and later fails, that error gets shown in the log (in red!):

```
19:07:38 ERROR    message    message:error:308 Error while splitting command: No closing quotation
```

This distracts from the actual issue - expected errors should be marked with something like `(EXPECTED)` or so (and maybe not be red?).

See e.g. https://github.com/The-Compiler/qutebrowser/pull/1608#issuecomment-229766960

cc @blyxxyz 

@Kingdread maybe one for you (as you're familiar with the end2end logging) if you feel like and have time?

**Comment by Kingdread** [comment]
Sure, I can take a look over the weekend :smile:
