### ISSUE TITLE
Cannot enter text fields with images by hinting

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1613]
Go to any product page on amazon. Scroll down to the 'Search customer reviews' fields and select it with hints. Even if you manually enter insert mode, you cannot input any text. You can input text if you click it.

**Comment by The-Compiler** [comment]
The search field looks like this:

![rev](https://cloud.githubusercontent.com/assets/625793/16520204/d71c93cc-3f8e-11e6-8607-081ff8a910a2.png)

I'd guess hints end up clicking the search icon instead of the text field itself?

@lahwaacz do you have an idea if there's a good way to fix this?

**Comment by lahwaacz** [comment]
It could be solved by avoiding clicking for `:hint inputs` completely. That would solve other issues as well, see #70.

**Comment by rcorre** [comment]
Same issue on https://www.humblebundle.com/ (search bar at top of page)

**Comment by rcorre** [comment]
And another: https://answers.tasktools.org/

**Comment by rcorre** [comment]
Though in the last two cases, you can tab over to the input field after hinting.

**Comment by The-Compiler** [comment]
Some more from #1879:

- https://help.hushmail.com/hc/en-us
- https://openclassrooms.com/
