### ISSUE TITLE
Validate type of self/instance for commands

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1620]
To avoid things like https://github.com/The-Compiler/qutebrowser/pull/1617#issuecomment-230196671 we should check if we can validate something like `type(self._instance) is self.handler.__class__` or so in `qutebrowser.commands.command`

(This is probably a situation where `type(foo) is bar` is more appropriate than `isinstance`, as we really want an exact match)

cc @rcorre

**Comment by rcorre** [comment]
This may be difficult: http://stackoverflow.com/a/2188518/1435461
:frowning:

**Comment by The-Compiler** [comment]
Hmm, interesting - this makes sense, but `foo.__qualname__` *does* have that information, but only as a string...

```python
def deco(func):
    print(func.__qualname__)


class Foo:

    @deco
    def func(self):
        pass
```

-> `Foo.func`

**Comment by rcorre** [comment]
Yeah ... I suppose I could just use the first bit of that string. Sounds ugly, but in our case it would probably be good enough?

**Comment by The-Compiler** [comment]
Yeah, something like `self._instance.__class__.__name__ == self.handler.__qualname__.split('.')[0]` would probably work, but eww... :laughing: 

Not sure yet if we should really do this or just drop it... :laughing:

**Comment by The-Compiler** [comment]
```
14:25 <The-Compiler> is there no way to get the class an unbound method is in (i.e. as decorator) even on 3.4? I can see the class name in __qualname__ so the information *is* there...
14:25 <Yhg1s> The-Compiler: the name of the defining scope is there, but not a reference to the class object. (It'd be a circular reference.)
14:25 <cyphase> there are no unbound methods in python 3
14:26 <The-Compiler> so should I feel dirty for doing something like   assert self._instance.__class__.__name__ == self.handler.__qualname__.split('.')[0]  ...? :D
14:27 <cyphase> :O
14:27 <Yhg1s> The-Compiler: yes, very dirty. Why does it matter?
```

:wink:

After some discussion, a better way to do this would probably be to just set some attribute on the method in the decorator (rather then doing the registering there), and then do the command registering of methods when we register the instance (using `objreg.register`) by iterating over all methods of it and checking for the attribute.

Then again, not sure if it's worth the trouble...

**Comment by The-Compiler** [comment]
@rcorre What's the state of this? I'm kind of inclined to close it for now, I think it's not worth doing weird dirty stuff for this - it's a mistake which happens too rarely for that.

**Comment by rcorre** [comment]
Agreed.
