### ISSUE TITLE
Implement CTRL-6 to go to last viewed tab

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1624]
In vim : 

> *CTRL-^* *CTRL-6*
> Edit the alternate file.  Mostly the alternate file is
> the previously edited file.  This is a quick way to
> toggle between two files.  It is equivalent to ":e #",
> except that it also works when there is no file name.

Whenever I have a few tabs open, I sometimes do 4J to go to a specific tab. It would be great to have a way to go the last tab that was open (we can call that the alternate tab)

**Comment by The-Compiler** [comment]
There's already `Ctrl-Tab` (`:tab-focus last`) for that, freel free to rebind it if that's what you prefer :wink:

**Comment by edi9999** [comment]
Thanks, it works well !
