### ISSUE TITLE
Copy as curl from devtools

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1625]
In the chrome devtools, it is possible to "Copy a request as curl" when you open the network tab of the developper tools.

In qutebrowser, they is only "Inspect element". 

Is this something that we have to rewrite in python or can we reuse what chrome did ?

**Comment by The-Compiler** [comment]
With the current QtWebKit backend there's nothing we can do to influence the web inspector.

With QtWebEngine (which I'm working on currently) it will be there, as that uses the same inspector as Chromium does.

**Comment by dijit** [comment]
Any chance of re-opening since you've moved to the new engine now?

**Comment by jgkamat** [comment]
I don't think we have much control over the inspector on webengine as well.

However, according to [this changelog](https://wiki.qt.io/New_Features_in_Qt_5.11), it looks like an improved devtools is landing, which might solve this issue on webengine.

**Comment by The-Compiler** [comment]
FWIW this works just fine on Qt 5.11 with the inspector.

**Comment by rcorre** [comment]
I'm pretty sure I've used this from qutebrowser 2.X / pyqt5, but in qutebrowser 3.0.0 / pyqt 6.5.2, I'm not seeing it:

![inspector](https://github.com/qutebrowser/qutebrowser/assets/2496231/eb404f6f-2377-40d2-9c35-7794bb907100)

**Comment by The-Compiler** [comment]
@rcorre See #7676
