### ISSUE TITLE
Support adding bookmarks by url

### ISSUE THREAD

**Issue by ismail-s** [The-Compiler/qutebrowser#1628]
Please remember to mention your version info (qutebrowser, Qt, PyQt,
OS/distribution) from the `qute:version` page or `qutebrowser --version`

---
(I am using Qutebrowser version 0.7.0)

# Summary
Is there any way of adding a bookmark by just entering the url?

# What I'm trying to do
I have a url (let's call it url1) that does some magic (probably with cookies) and then redirects to another webpage (let's call it url2). Doing `:bookmark-add` whilst on url2 does save url2 as a bookmark, but the magic that happens when url1 is clicked doesn't happen.

Just allowing bookmark-add to accept an optional url parameter would probs be the easiest way of doing this.

**Comment by The-Compiler** [comment]
This probably makes sense, but automatically retrieving the title will probably be a bit tricky.

cc @antoyo

**Comment by ismail-s** [comment]
Could set the title to "" (ie blank) until first load. Or allow the user to set one when creating the bookmark, which is what other browsers do.

So, in other words, `:bookmark-add` adds the current webpage as a bookmark with the page title as a title. `:bookmark-add some-url some-title` adds some-url as a bookmark with some-title as the title. And `:bookmark-add some-url` could either show an error saying a title is required, set the title to "", or create a title eg "Untitled bookmark 1".

**Comment by ismail-s** [comment]
Could set the title to "" (ie blank) until first load. Or allow the user to set one when creating the bookmark, which is what other browsers do.

So, in other words, `:bookmark-add` adds the current webpage as a bookmark with the page title as a title. `:bookmark-add some-url some-title` adds some-url as a bookmark with some-title as the title. And `:bookmark-add some-url` could either show an error saying a title is required, set the title to "", or create a title eg "Untitled bookmark 1".

**Comment by ismail-s** [comment]
In #1631, I have put a basic idea of what I think could be done for this issue. I have not updated tests/docs atm, as I don't know if this is the best solution / the right way of doing this yet.
