### ISSUE TITLE
Bad font rendering outside of page content

### ISSUE THREAD

**Issue by sagotsky** [The-Compiler/qutebrowser#1636]
I get a lot of weird visual artifacts in the text around a page.  Page content looks fine though.  I tried a 

![Fugly text](http://i.imgur.com/HRyUcVY.png)

I tried a few other apps that I expect use QT, but couldn't find any with similar problems.  

I'm using debian stable and installed from the qutebrowser_0.7.0-1_all.deb package.

qutebrowser v0.7.0
Git commit: v0.7.0-5-g7a2cb90 (2016-06-15 22:14:24 +0000)

CPython: 3.4.2
Qt: 5.3.2, runtime: 5.3.2
PyQt: 5.3.2

**Comment by The-Compiler** [comment]
Do you see them in the tab bar as well? Do you know what font it is?

**Comment by sagotsky** [comment]
Yes, the tab bar does the same thing.  No idea, it's whatever the default is.

**Comment by The-Compiler** [comment]
This seems similar to #92, which was fixed in Qt 5.4 according to someone with the same issue. Not much I can do about it I'm afraid...

**Comment by lachs0r** [comment]
That is a Qt bug which occurs when anti-aliasing is enabled for bitmap fonts. Makes no sense to me, but that’s what triggers it. Workaround is to explicitly disable it for bitmap fonts using fonts.conf.

**Comment by sagotsky** [comment]
TY for the workaround!
