### ISSUE TITLE
Youtube videos don't show (Just black screen and audio) (again)

### ISSUE THREAD

**Issue by Penaz91** [The-Compiler/qutebrowser#1645]
Hello, after a bit of tinkering (about 2 months) I decided to post an issue here.
As many others found out, I can't see any videos on Youtube, but I can hear the audio.
I tried MetaCafe and it works fine, tried Dailymotion too and I had another problem that I'll post on a different Issue.
I made sure to check if all gstreamer plugins are installed, and reinstalled them without any improvement.
After visiting http://youtube.com/html5 I noticed that MSE, MSE+H264 and MSE+WebM &VP9 are not supported.
Could this be the root of the problem?
I attached the output of qute:version
Thanks for your help in advance.
[quteversion.txt](https://github.com/The-Compiler/qutebrowser/files/364209/quteversion.txt)

**Comment by The-Compiler** [comment]
Are you sure you installed the plugins for the GStreamer version you compiled QtWebKit for?

Unfortunately there really isn't much I can do, and you'll probably see the same in other QtWebKit browsers like Otter. Maybe someone with some more Gentoo knowledge can jump in.

**Comment by Penaz91** [comment]
I tried with Otter and I'm getting the same issue.
I checked the dependency graph and I'm pretty sure I installed the right plugins.
After cross-referencing the html5 page from youtube and html5test.com I found something interesting. Seems that in the latter, the "Streaming" section finds no codecs. Is it normal?
I'll attach some pictures to explain better.
![video](https://cloud.githubusercontent.com/assets/6682630/16846692/bcbe7928-49ed-11e6-9f3a-bc2d45e53337.png)
![streaming](https://cloud.githubusercontent.com/assets/6682630/16846706/c76e96a0-49ed-11e6-9a8f-ab78474ea1bb.png)
Could this have anything to do with this matter?

**Comment by Penaz91** [comment]
Small update: this seems limited to the MP4 format using the H264 codec. I'm doing some tests by removing x264 and replacing it with openh264

**Comment by The-Compiler** [comment]
FWIW I don't see streaming codecs on http://html5test.com either (but I see H.264 and WebM VP8 at https://www.youtube.com/html5), and youtube works fine here.

I can also recommend using a video player like mpv to watch videos - see 9. in [the FAQ](https://github.com/The-Compiler/qutebrowser/blob/master/FAQ.asciidoc)

**Comment by Penaz91** [comment]
I solved this, seems that gst-plugins-vaapi was blocking the videos from being seen. Which makes very little sense because it's the Video Acceleration API.
Anyway now videos on Youtube are visible again.
Thanks a lot for your feedback and keep up the amazing work

**Comment by The-Compiler** [comment]
Oh, right - from what I've heard, VAAPI is just quite buggy, especially in intel drivers. Glad to hear you got it working!
