### ISSUE TITLE
Crash on Dailymotion.com if using freshplayer

### ISSUE THREAD

**Issue by Penaz91** [The-Compiler/qutebrowser#1646]
Hello, when using FreshPlayer (https://github.com/i-rinat/freshplayerplugin) and trying to view a video on DailyMotion, the browser crashes. This is the only browser where this issue seems to take place.
I Attached the last lines of the traceback, as well as the GDB traceback and the qute:version information.
Thanks for all your work.
Hope you have a nice day.
[gdb.txt](https://github.com/The-Compiler/qutebrowser/files/364222/gdb.txt)
[quteversion.txt](https://github.com/The-Compiler/qutebrowser/files/364223/quteversion.txt)
[trace.txt](https://github.com/The-Compiler/qutebrowser/files/364224/trace.txt)

**Comment by The-Compiler** [comment]
Looking at the stacktrace, this happens in some thread without any Qt and qutebrowser code involved:

- `#1  0x00007fffdd3dae83 in ?? () from /usr/lib64/dri/i965_dri.so`
- `#2  0x00007fff5c2b2c43 in ?? () from /usr/lib64/nsbrowser/plugins/libfreshwrapper-flashplayer.so`
- `#3  0x00007fff3f86b6f3 in ?? () from /usr/lib/chromium-browser/PepperFlash/libpepflashplayer.so`
- ...

This seems like some kind of bug in your graphic driver or FreshPlayer, and I can't do much about it I'm afraid. However, soon qutebrowser will support the QtWebEngine backend based on Chromium - if Gentoo has a QtWebEngine package, you can already play with it with the -git version using `--backend webengine`.

Sorry!

**Comment by Penaz91** [comment]
Gentoo has a webengine package and it's already installed, I think i'll give it a try. Thank you!
