### ISSUE TITLE
[Request] Support X11 geometry string

### ISSUE THREAD

**Issue by Link-Satonaka** [The-Compiler/qutebrowser#1647]
A launch argument that allows you to define the dimensions and position of an X11 window. Here's what it looks like in my terminal's manpage:

```
-g geometry
   defines the X11 geometry string.  The form is [=][<cols>{xX}<rows>][{+-}<xoffset>{+-}<yoffset>]. See XParseGeometry(3) for further details.
```

**Comment by neeasade** [comment]
IMO this should be handled at a WM level or scripted with something like `xdotool`.

**Comment by Link-Satonaka** [comment]
That is not ideal. This is part of the X11 spec (and Windows has such APIs, too). We are given this functionality for a reason. A script to adjust window size after the fact can never be efficient or as functional- and the complexity of such a script would probably rival the effort of simply implementing this functionality.

**Comment by lahwaacz** [comment]
The [GEOMETRY SPECIFICATIONS](https://www.x.org/releases/X11R7.7/doc/man/man7/X.7.xhtml#heading7) section is not a specification of a standard, the "specifications" just means the user specifying the geometry. And "most X programs accept [...] `--geometry`" is a great exaggeration nowadays...

The next section says: "Although many window managers will honor geometry specifications as given, others may choose to ignore them". So you can't expect that qutebrowser's `--geometry` argument would always override the window manager - doing so would be complex. Besides, I'd say that most people run the browser with size managed by the window manager, i.e. fullscreen, full-size (with something like statusbar visible) or half-size (two windows on screen), so the feature would not be very useful. If you want fixed size, IMHO you should get a window manager that allows to configure this easily.

**Comment by The-Compiler** [comment]
FWIW I can see how this would be useful, and it'd be something line two lines plus a bit to parse the geometry string. I won't work on it anytime soon, but I'd accept a PR for it.

**Comment by Link-Satonaka** [comment]
`And "most X programs accept [...] --geometry" is a great exaggeration nowadays...`
I am under no illusion; I am aware that very few programs have this. I did not build an argument around that premise.

`So you can't expect that qutebrowser's --geometry argument would always override the window manager - doing so would be complex.`
I expect nothing more than what the EWMH standard requires; if a WM doesn't obey it, it's a bad WM, and that would be a WM bug. I wouldn't expect qutebrowser to deal with that. 

`Besides, I'd say that most people....`
It's a trivial feature, sure, but is trivial to implement, and would not impact performance or require any amount of ugly/hacky code. I'm sure some people, myself included, would appreciate it being there. Again, the goal here is to spawn the window with certain geometries, and any after-the-fact solution is just going to be inefficient and sloppy.

The-Compiler:
`I won't work on it anytime soon, but I'd accept a PR for it.`

I just might make an attempt at that :)

**Comment by lahwaacz** [comment]
> any after-the-fact solution is just going to be inefficient and sloppy.

Why? If the window is placed/resized by the window manager, you woudn't notice a thing performance-wise.

**Comment by Link-Satonaka** [comment]
> Why? If the window is placed/resized by the window manager, you woudn't notice a thing performance-wise.

Well, perhaps you know something I don't? Which WM allows you to define the geometry and position of a window on a granular, per-class/title/etc level at the moment it is created? Where is this functionality hidden in Windows Explorer? If there is such a WM that exists, is your answer really going to be "change your WM/don't use Windows if you want this feature"?

Sure, a WM might be able to do this neatly, but I'm not using one that supports such granular control. My comments about efficiency are therefore directed at relying on scripts with xdotool/wmctrl

**Comment by lahwaacz** [comment]
Oh, so "any after-the-fact solution" includes only xdotool and wmctrl. In that case I completely agree with your assessment.

Now just for the record, the WMs I know of that support extensive per-window configuration are [KWin](https://userbase.kde.org/KWin_Rules_Window_Attributes) and [Openbox](http://openbox.org/wiki/Help:Applications), but I'm pretty sure that this is a widespread feature among the WMs for X. Though if you are stuck with Windows, I understand that you are not interested in these.

**Comment by The-Compiler** [comment]
Someone in the qutebrowser IRC channel just pointed out Qt supports this out of the box, and something like `--qt-arg geometry 650x555+200+300` works on X11 already. I added this as an example for the `--qt-arg` docs, so I'm closing this now.
