### ISSUE TITLE
Ugly font rendering

### ISSUE THREAD

**Issue by ranzpirat** [The-Compiler/qutebrowser#1648]
Qutebrowser renders fonts very ugly for me, see the linked images as comparison with firefox and another qt5 browser.

Qutebrowser: https://i.imgur.com/qzGLbhe.png 
Firefox: https://i.imgur.com/pLwXaqN.png
Otter: http://i.imgur.com/VYdM75b.png

---

qutebrowser v0.7.0
Git commit: v0.7.0-392-ga8dc940 (2016-07-14 23:17:39 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

Platform: Linux-4.4.14-1-lts-x86_64-with-arch, 64bit
Desktop: xfce (also happening with i3)
Distribution: Archlinux

**Comment by The-Compiler** [comment]
#549 seems like the same issue, which was fixed in cef49864d90db46c44a6a2dd55db539418920c4d. Maybe that regressed somehow.

Do things look better if you comment out `websettings.init()` in `qutebrowser/app.py`?

**Comment by ranzpirat** [comment]
This fixes the fonts on wikipedia (also adds visible scrollbars) http://i.imgur.com/ULSiljF.png but leaves for example github fonts in the same unhinted way http://i.imgur.com/yYNpysd.png

**Comment by The-Compiler** [comment]
Okay, so there is some bug in websettings again... How does GitHub look in Otter?

**Comment by ranzpirat** [comment]
Also unhinted: http://i.imgur.com/NyKqdSC.png

**Comment by The-Compiler** [comment]
If it looks the same in Otter, unfortunately it's some kind of QtWebKit issue and I can't really do much until QtWebEngine lands - so let's focus on the Wikipedia issue for now.

Could you maybe quit qutebrowser, do `git checkout cef4986`, move your `~/.config/qutebrowser`, `~/.local/share/qutebrowser` and `~/.cache/qutebrowser` away (as this is so old it doesn't support `--temp-basedir`...) and check if it looks better there? If yes, do you know how to use `git bisect`? :wink:

**Comment by damienr74** [comment]
Hi, I have a similar issue and would be willing to help if I can. Mine looks like so:  
![2016-07-18-202834_1366x768_scrot](https://cloud.githubusercontent.com/assets/6934867/16969009/788627de-4de8-11e6-81e8-25d414ab2c16.png)
![2016-07-18-203023_1366x768_scrot](https://cloud.githubusercontent.com/assets/6934867/16969010/7888d4f2-4de8-11e6-8869-0d77042f79d5.png)
![2016-07-19-193132_1366x768_scrot](https://cloud.githubusercontent.com/assets/6934867/16969011/788d1c24-4de8-11e6-9844-5825359411af.png)

The last picture is when I tried to move the config files and `cef4986`. I do know how to use `git bisect`. 

---
I'm on gentoo (installed version 0.7.0 from portage)
PyQt5-5.5.1
Kernel 4.7.0-rc7...
wm: bspwm

**Comment by The-Compiler** [comment]
@damienr74 Do you see the same in something like Otter Browser? If yes, there isn't much I can do (though there are chances things will work better with QtWebengine).

**Comment by ranzpirat** [comment]
Just for reference: we had a small discussion in IRC about earlier commits and it concluded that they all crashed on startup for me (cef49864d90db46c44a6a2dd55db539418920c4d and 5db4ed0ed116c09335457be3ec57a7e097ccd513). As I'm still interested in proper™ fonts, I will be able to perform more tests.

**Comment by The-Compiler** [comment]
@ranzpirat Can you find out what setting is responsible like outlined in https://github.com/The-Compiler/qutebrowser/issues/549#issuecomment-78600218 ?

Also, can you run `qutebrowser --temp-basedir --loglevel vdebug  --logfilter config` and show the relevant log?

**Comment by damienr74** [comment]
Yes, this also happens in Otter, thanks anyway

![2016-07-20-204526_1366x768_scrot](https://cloud.githubusercontent.com/assets/6934867/17006962/1ebfbcc8-4ebb-11e6-9c48-25606b4dd5dc.png)

**Comment by The-Compiler** [comment]
I wonder if https://codereview.qt-project.org/#/c/168903/ changes anything.

**Comment by arsv** [comment]
Hit the same issue with ugly fonts, and I think I see what could be causing it.
Making a new ticking now, to keep the relevant data near the top.

**Comment by The-Compiler** [comment]
In #1571 @paretje says those settings helped with font problems with QtWebKit-NG:

```
web-family-standard = serif
web-family-fixed = monospace
web-family-serif = serif
web-family-sans-serif = sans
web-family-cursive = cursive
web-family-fantasy = fantasy
```

Does that change anything for you as well?

**Comment by arsv** [comment]
On my system, with xorg-fonts-100dpi installed, this fixes Wikipedia text (sans-serif) but not h1's (serif).
Github remains all-bitmapped. Google front page all-bitmapped.

Here's what I use to get nice fonts everywhere:
```
web-family-standard = Tinos
web-family-fixed = Cousine
web-family-serif = Tinos
web-family-sans-serif = Arimo
web-family-cursive = Tinos
web-family-fantasy = Tinos
```
Works with more common fonts as well (DejaVu). But those are exact names of the fonts I have installed, not something generic that could be used as safe defaults.

**Comment by haasn** [comment]
@arsv You can go the extreme route and force `* { font-family: Tinos !important; }` in your user-stylesheet. That's basically what I do (except with Terminus)

**Comment by code-hunger** [comment]
Here is a simple test case: https://jsfiddle.net/3tLwv7zb/ for anyone to edit and test out this behaviour.

With `:set fonts web-family-fixed monospace` here's what I get in qutebrowser:
![qute](https://cloud.githubusercontent.com/assets/11772321/21293157/dc80f9f4-c524-11e6-8781-41217555fc7c.png)
And in chromium:
![chrom](https://cloud.githubusercontent.com/assets/11772321/21293156/dc80c1f0-c524-11e6-933b-3bf062826476.png)

The same result applies everywhere markdown-style tables are used.

Here's some random question on stackoverflow with a table: http://stackoverflow.com/q/2594829, the result is the same as in the jsfiddle above.

**Comment by haasn** [comment]
My result:

![fonts](https://0x0.st/9S4.png)

**Comment by The-Compiler** [comment]
Can someone affected by this (with `web-family-fixed` empty) please test with Qt 5.7.1?

**Comment by code-hunger** [comment]
@haasn Actually, in the HTML editor I do also see the text properly aligned, but in the "Result" box the text is not:
![screenshot](https://cloud.githubusercontent.com/assets/11772321/21295933/27b38b24-c568-11e6-9a1b-ecbc53a553bf.png)
If I remove all but "Inconsolata,monospace" it still works for the HTML editor, but not in the Result box.

The-Compiler - I'm with 5.0.9-0, updating it now; I'll post when it's ready.

**Comment by code-hunger** [comment]
@The-Compiler it works now, with the updated qt. (and the `web-font-family` set to an empty string)

**Comment by The-Compiler** [comment]
If anyone here is still on 5.7.0 (or willing to downgrade to test a workaround) - do things look properly if you set `web-family-fixed` to something, and then set it back to an empty string again?

**Comment by The-Compiler** [comment]
Closing this as it's fixed in Qt and I don't think we need a workaround.
