### ISSUE TITLE
Completion: highlight only the matched terms

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1650]
1. start `qutebrowser --temp-basedir`

2. `:open https://github.com/The-Compiler/qutebrowser/`

3. `:open git vim` (not followed by Enter)

4. then only the terms "Git" and "vim" in the title should be highlighted

    (currently everything between the terms is also highlighted: "GitHub - The-Compiler/qutebrowser: A keyboard-driven, vim")

**Comment by The-Compiler** [comment]
The problem with that is that it's confusing with overlapping terms since the highlight doesn't match the actual matching - see https://github.com/The-Compiler/qutebrowser/pull/1195#discussion_r48901865

**Comment by lahwaacz** [comment]
(at least it unhides the comments...)

So I take it that with proper detection of overlaps it would be preferred this way? Sounds like a challenge for me... :wink:

**Comment by The-Compiler** [comment]
Yes, though I'm also worried about the performance impact when we start with more complicated logic (the matching is run over thousands of items with the first few letters typed).

**Comment by lahwaacz** [comment]
Well, it's not about matching itself, only highlighting the results. It should be fine to run it just over the items that are actually going to be displayed...

**Comment by The-Compiler** [comment]
Oh, right! I need more coffee! :wink:

**Comment by lahwaacz** [comment]
As far as I understand, the highlighting already happens only for the to-be-displayed items, which is probably why there was no performance difference in https://github.com/The-Compiler/qutebrowser/pull/1195#issuecomment-169145881.

And I don't see how you managed to get the highlighting described in https://github.com/The-Compiler/qutebrowser/pull/1195#discussion_r48901865 (your link from above). With this change on top of current master:

```diff
--- a/qutebrowser/completion/completiondelegate.py
+++ b/qutebrowser/completion/completiondelegate.py
@@ -200,7 +200,7 @@ class CompletionItemDelegate(QStyledItemDelegate):
             columns_to_filter = index.model().srcmodel.columns_to_filter
             if index.column() in columns_to_filter and pattern:
                 repl = r'<span class="highlight">\g<0></span>'
-                text = re.sub(re.escape(pattern).replace(r'\ ', r'.*'),
+                text = re.sub(re.escape(pattern).replace(r'\ ', r'|'),
                               repl, self._opt.text, flags=re.IGNORECASE)
                 self._doc.setHtml(text)
             else:
```

and the same URL (`http://qutebrowser.org:8010/waterfall?reload=5`) and pattern (`qute t`) I get this highlighting: h**tt**p://**qute**browser.org:8010/wa**t**erfall?reload=5
I think that is much better than http://**qutebrowser.org:8010/wat**erfall?reload=5

**Comment by Kingdread** [comment]
If you want to get fancy, you could build to pattern to highlight with groups (like `pattern = '(' + re.escape(pattern).replace(r'\ ', r').*(') + ')'`) and then manually iterate over the groups and insert the HTML tags only where you really want them (i.e. the matched words), like

```python
match = re.search(pattern, text)
result = rext
for index in range(match.lastindex, 0, -1):
	start, end = match.span(index)
	result = result[:start] + "<b>" + result[start:end] + "</b>" + result[end:]
```

This should produce a highlight like "bar hi **foo** baz **bar** bye" if you've searched for "foo bar" (that is, the first occurence of "bar" is not highlighted).

**Comment by lahwaacz** [comment]
I think that the order of the terms supplied by the user is not important (see #1651), so if we don't know in which occurrence the user is interested in, we'd better highlight all of them.
