### ISSUE TITLE
Key shortcuts not working sometimes

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#1653]
Hello.

Sometimes, my custom keyboard shorcuts does not work.
For instance, I added a shortcut `pu` to insert the login credentials and submit the form.
However, sometimes, when I press on `p` then `u`,  I only see the dialog with the possible shortcuts (including `pu`) as though I did not completed the shortcut.
I need to restart the browser to get my custom shortcuts back (the default shortcuts seem to work fine).

I don't know if it is related to this dialog (or my shortcuts) but I see this dialog everytime I have this issue.

Do you have any idea so that I can investigate?

Thanks.

Git commit: d079caafa864604f0b65313c61a45c7a12d919d4

Here is the versions:

```
CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch, 64bit
Desktop: xinitrc
Frozen: False

OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
```

**Comment by The-Compiler** [comment]
Can you do `:report` and submit a debug log when it happens?

**Comment by antoyo** [comment]
Yes, I've just `:report`ed right after I saw the bug.

**Comment by The-Compiler** [comment]
Sorry for the late answer - you did `pu` in the log multiple times, and the last time before you did `:report` it didn't work? According to the log, everything seems fine to me...

```
19:44:25 DEBUG    keyboard   basekeyparser:_debug_log:111 Definitive match for 'pu'.
19:44:25 DEBUG    commands   command:run:508 command called: load-password-submit
19:44:25 DEBUG    commands   command:run:523 Calling qutebrowser.browser.passwordfiller.PasswordFiller.load_password_submit(<qutebrowser.browser.passwordfiller.PasswordFiller object at 0x7fdf44585e48>)
19:44:25 DEBUG    modes      modeman:_eventFilter_keyrelease:214 filter: True
19:44:26 DEBUG    misc       mainwindow:reposition_keyhint:414 keyhint rect: PyQt5.QtCore.QRect(0, 732, 254, 105)

# Here you press esc I think?

19:44:26 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
19:44:26 DEBUG    commands   command:run:508 command called: clear-keychain
19:44:26 DEBUG    commands   command:run:523 Calling qutebrowser.keyinput.modeman.ModeManager.clear_keychain(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.normal: 1>>)
19:44:26 DEBUG    keyboard   basekeyparser:_debug_log:111 discarding keystring ''.
19:44:26 DEBUG    commands   command:run:508 command called: search
19:44:26 DEBUG    commands   command:run:523 Calling qutebrowser.browser.commands.CommandDispatcher.search(<qutebrowser.browser.commands.CommandDispatcher>, '', False)
19:44:26 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=39 url='https://fr.glassdoor.ca/profile/login_input.htm'>)
19:44:26 DEBUG    statusbar  bar:_set_severity:281 Setting severity to Severity.normal
19:44:26 DEBUG    statusbar  text:set_text:55 Setting temp text to ''.
19:44:26 DEBUG    modes      modeman:_eventFilter_keyrelease:214 filter: True
19:44:26 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
19:44:26 DEBUG    keyboard   basekeyparser:_debug_log:111 Ignoring only-modifier keyeevent.
19:44:26 DEBUG    keyboard   basekeyparser:_debug_log:111 Got key: 0x1000020 / text: ''
19:44:26 DEBUG    keyboard   basekeyparser:_debug_log:111 Ignoring, no text char
19:44:26 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=39 url='https://fr.glassdoor.ca/profile/login_input.htm'>)
19:44:27 DEBUG    modes      modeman:_eventFilter_keypress:169 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
19:44:27 DEBUG    keyboard   basekeyparser:_debug_log:111 No binding found for shift+:.
19:44:27 DEBUG    message    message:set_cmd_text:352 :
```

**Comment by antoyo** [comment]
I don't remember every detail, but I am sure that the last time I pressed `pu` before `:report`, it did not work (the command was not called because it always has an effect: either fill the login form and submit or show an error, but I saw none of these).
I am not sure I pressed `escape`, though.
The next time it happens, I will report and provide you with more details.
Besides looking at the log, is there anything else I can do to help you debug this issue?

**Comment by The-Compiler** [comment]
If you're able to add a little screencast that might help, so I can see what's exactly going on. Other than that, I can't think of anything so far...

Also pinging @rcorre as he implemented the shortcut dialog.

**Comment by antoyo** [comment]
I think I found a bug in my password filler feature: when there are multiple windows, it does not work well sometimes (the command seems to be called on every window, it is normal?).

But I still think there is an issue with the dialog (it should not show up when a command is called).
I don't know if this issue is caused by the fact that I use multiple windows (instead of multiple tabs).
I will continue to investigate.
If I don't find it, I will do a screencast.

**Comment by rcorre** [comment]
Does this happen with other custom shortcuts? I'd be curious if this happens for a custom mapping to a simpler command (as opposed to a userscript).
It's possible the dialog doesn't behave well with multiple windows -- I need to test that.

**Comment by antoyo** [comment]
I've fixed the bug in my script by using the right `win_id`.
I'll let you know if it changes anything.

**Comment by The-Compiler** [comment]
Newer log:

> I was trying to login on a website (using my pu shortcut).
> The first time, I think I pressed escape to hide the dialog.
> The second time I did pu, I pressed space to hide the dialog.
> I've pressed pu only twice during this session, and both time, it did not work.
> Even though the logs indicates that the load-password-submit command was called, I am not sure it was (why the dialog would show up if a command was found and why did the command not work?).
> However, I will add debug log at the start of my command just to check.
> By the way, the logs indicates "No binding found for u." which seems to be why the dialog shows up.

The full log is here: http://paste.the-compiler.org/view/0b380e80

If I remember correctly, "No binding found for u." is just the first key handler (special keys -> keychains), but that message should be improved.

**Comment by antoyo** [comment]
I have not seen this bug anymore.
It was probably caused by a bug in my branch.
Sorry.

**Comment by The-Compiler** [comment]
No problem, thanks for the follow-up!
