### ISSUE TITLE
Fatal error on OS X launch

### ISSUE THREAD

**Issue by hajzso** [The-Compiler/qutebrowser#1656]
I get the this error on launch after following the instructions on the webpage: 

It says that pyqt5 is required to run but could not be imported. I installed it with homebrew, qt55 and symlinked it to qt5. pyqt5 is also installed through homebrew, and i tried installing pyqt5 with pip too.

Error: dlopen(/usr/local/lib/python3.5/site-packages/PyQt5/QtCore.framework/Versions/5/QtCore
  Referenced from:/usr/local/lib/python3.5/site-packages/PyQt5/QtCore.so
  Reason: image not found

**Comment by The-Compiler** [comment]
Hmm - that way worked for me, but I think some other people had issues as well.

Could you try the standalone `.app` on the download page? I just realized that doesn't get mentioned in the install instructions...

**Comment by hajzso** [comment]
It works with the .app ! Thanks 👍

**Comment by The-Compiler** [comment]
I updated the instructions now to point to the `.app`.
