### ISSUE TITLE
Block HTML5 canvas

### ISSUE THREAD

**Issue by sjug** [The-Compiler/qutebrowser#1659]
It would be great to improve the privacy of qutebrowser by having an optional config to disable HTML5 canvas.

https://www.browserleaks.com/canvas

---

**Comment by The-Compiler** [comment]
So I'm not sure if this is possible to implement, but the existing Chromium/Firefox addons do this in JS somehow I guess:

- [CanvasBlocker](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/)
- [CanvasFingerprintBlock](https://chrome.google.com/webstore/detail/canvasfingerprintblock/ipmjngkmngdcdpmgmiebdmfbkcecdndc/reviews?hl=en-US)
- [Canvas Defender](https://addons.mozilla.org/en-US/firefox/addon/no-canvas-fingerprinting/?src=search)

**Comment by sjug** [comment]
The CanvasBlocker for Firefox is the most feature full it allows a variety of modes: block, random, ask.

**Comment by The-Compiler** [comment]
I forgot about this issue and opened #2235 recently - since that has some more information, I'm closing this one.
