### ISSUE TITLE
:open should open quickmark when given a quickmark name

### ISSUE THREAD

**Issue by spiderbit** [The-Compiler/qutebrowser#1663]
if I write exactly the name of a quickmark and even if I deactivate autosearch I have to press Tab and then Enter.

When Enter would be enough. Makes no sense to priotise url over quickmarks, the possibility that you choose a shortcut for a quickmark that is identical with a url you type in in basicly Null, and if you do that you did somethnig very wrong.
I cant see a case where that would be a sane thing to do.

please execute exact quickmark matches as quickmark expensions.

You could argue that pressing tab is no big thing, the whole point of such browsers is micro-optimations, so accepting this would be missing the point.

**Comment by The-Compiler** [comment]
Added in #1704.
