### ISSUE TITLE
passwd_fill supergenpass backend

### ISSUE THREAD

**Issue by spiderbit** [The-Compiler/qutebrowser#1665]
I tried to write a backend for supergenpass but got error 2 at the end. I am a bit lost in how I have to debug that cause I am no bash expert and if I cant call the script from bash I dont know how to debug the issue.

I tried following code:
```bash
# backend: supergenpass
sgp_backend() {
    init() {
        return
    }
    query_entries() {
	true
    }
    open_entry() {
        local domain="${1%% *}"
        username="USERNAME"
        password=$(sh supergenpass.sh "$domain")
    }
}
```

I used the supergenpass.sh script here from github and modified it by hardcode in my master password.

master=XXX

I have also a small other issue with that script it uses !/bin/bash as handler, thats not a good practise I use nixos where bash is not installed there and there are other unixes bsds and stuff that also dont have that.

Better is to use either /bin/sh or /usr/bin/env bash as handler.

**Comment by The-Compiler** [comment]
You can set the respective environment variables and run it via bash to find out more.

cc @t-wissmann

**Comment by t-wissmann** [comment]
Sorry about the `/bin/bash` issue and thanks to @The-Compiler for fixing this!

I can only guess what is wrong with your backend. First of all, you backend does not list entries in `query_entries()` before opening them. But you need to do that, because otherwise the `password_fill` script will think there is no password for the current domain in the sgp database.

So one very simple implementation would be:

```
# backend: supergenpass
sgp_backend() {
    init() {
        return
    }
    query_entries() {
        files=( "$1" )
    }
    open_entry() {
        local domain="${1%% *}"
        username="USERNAME"
        password=$(sh supergenpass.sh "$domain")
    }
}

sgp_backend
```

Please be also sure to load your backend (see the last line above).

**Comment by spiderbit** [comment]
```javascript
# backend: supergenpass
sgp_backend() {
    init() {
        return
    }
    query_entries() {
        domain="$1"
        files+="USERNAME"
    }
    open_entry() {
        username="$1"
        password=$(supergenpass.sh "$domain")
    }
}
```
of course with the master password fix in the supergenpass.sh file set.
that did work for me, not 100% shure I have no changes to the rest of the code but I think so.

Maybe not the best solution, having maybe a optional username saved in files would be neat, but on the other hand its a very lightweight solution where you dont have to sync any files with other devices, so having maybe a seperate script to fill from 3/4 usernames/email adresses would maybe a more apropriete way, if that level of automatisation is really needed.

I tried to set the local domain like you did, but it did not work, maybe cause I did not set the files the way you did. does your solution depend on having files for each domain or creating it?

**Comment by t-wissmann** [comment]
Of course, you can include supergenpass.sh in the backend script, especially if it's just a few lines.


Regarding uesrnames: it's completely up to supergenpass to handle the usernames. So sorry, I can't give a recommondaton here. But you should set the username variable correctly, because otherwise the user has to fill the name in his/her own. (I often tend to forget the usernames)

I don't know how to correctly handle the master password the best way. Maybe
you can prompt it by

```
masterpw="$(zenity --password --title='Master password')"
```
But you should avoid saving the master password to a file. Unfortunately, I
don't see a possibility to safe the master password in the qutebrowser session
in a safe way.

And btw the backend interface does not require the passwords to be stored in
seperately files.

**Comment by spiderbit** [comment]
Thanks for the tipps, the way I use this system normaly is that in other browsers that I keep logged in on the most important sites for me, like google and some other sites, so for the most used sites it does not matter that much.

but for this 1000 sites you have a account, but you log in 1 time a year, this system is good, and most of the time its the email adress or 1 Username I use for it.

So having a small list or manually change the username is not that big of a deal.

This password system is a bit like webmail, you can use it easily on basicly every device/browser without a big setup.

Even without this plugin it would be okish to use by externaly generate the passworts. I dont need internet so I could use it on a train without internet connection and without a current version of a passwort file synced over cloud.

But thats maybe to much personal details how I use it and why. But maybe it is useful context information.

Back to the userscript, Supergenpass dont handle usernames in general, its only a algorythm to generate with your master passwort and a hostname a password, so you dont have to save it. The way as example the firefox plugin handles it, is that you can set ONE username, that get set always, basicly a default-username, that you then have to manually change if you have a site without that username.

So Storing usernames in a file seems a bit silly cause the whole point of that solution is that you dont have to save/sync/backup/manage a database(file). :)

But of course it would add some convinience in using it. :)

firefox or the supergenpasswd plugin btw asks the password each time you restart it, the advantage besides security cause you dont have to save it in a file, is that you could have maybe 2 master passwords or 3 and change it, for A sites you want different accounts, or B to slowly switch your sites to a more secure master password.

It gives you a bit flexibility. there was a article about how save that is, but in the end it seemso te be reasonable save.

Most of this addons/tools also support different algorythms that work similar.
https://addons.mozilla.org/de/firefox/addon/hash-password-generator/

One other advantage this tool seem to have is that a username and a email setup, but I think it acts not so clever that it uses the email adress as username if the username is supposed to be a email. its more for the registration formulars to fill there the email adress in.

So to summ up my long statement maybe, I still think saving somehow the password to the browsers process would be the golden way to do it. Asking it each time makes on sense then you have no added usability / advantage except a bit more security.

**Comment by The-Compiler** [comment]
I also can't think of a way to safe the password per-session. I guess that's really the point to wait for a proper plugin API :wink:

**Comment by spiderbit** [comment]
k fair enough, I am ok with saving / setting the password in a file, as long as my laptop gets not stolen, or some serious hackers use much effort to break into my systems, I should be fine.

The major security concern I had, why I started using this method, is that each website has a different password, and so if their sites get hacked nobody has a passwort to access all my accounts. (or most of them).

And I am happy to have this now, in conkeror I had nothing, and the emacs sgp module I set the passwort somewhere to staticly in cleartext, cause I was to lazy to write in the passwort each time :)

of course there you could uuse the authinfo file and use pgp on it, to store the password but then you would have the same problem.

Still a authinfo backend would be a future nice idea, too?

**Comment by t-wissmann** [comment]
If your username is always the same, then you can set `username` to a fixed value, namely your e-mail address.

By authinfo, do you mean [Gnu Authinfo](https://www.emacswiki.org/emacs/GnusAuthinfo)? If you are using it and need a backend, you're welcome to implement one ;-).

Personally, I am very much convinced of https://www.passwordstore.org/ and I can recommend it anybody.

**Comment by spiderbit** [comment]
yes I have set it to a fixed value at the moment. (username) and yes I meant gnu auth info, I dont use to heavy yet, but I use it for my email password, which is no generated one (at least yet), but I read normaly mail not over the browser so whatever.

Maybe I make up a backend, who knows at the moment not so important. was just a feature-suggest or something for a wishlist maybe.

But I dont see it having big adoption outside sysadmin tools :) so whatever.

**Comment by The-Compiler** [comment]
I kind of lost track here - would it make sense to add that `sgp_backend` to the userscript in `misc/` as-is? Does someone of you want to open a PR for it? :wink:

**Comment by t-wissmann** [comment]
I don't think it makes sense, because the backend is not complete yet and I can't see the as-is state of the script. (Maybe that's again due to my poor github abilities). I'm also not sure where this 'issue' leads to ;-).

**Comment by The-Compiler** [comment]
[This](https://github.com/The-Compiler/qutebrowser/blob/master/misc/userscripts/password_fill) is the current file in the repo, I haven't seen anything else from @spiderbit yet :wink:

@spiderbit If you got supergenpass to work, what about opening a PR with your additions?

Closing this for now, as it isn't really actionable.

**Comment by spiderbit** [comment]
The problem is the Master password, you can ask that each time, which would work, then this would be more or less @t-wissmann posted I think his solution is a bit cleaner than mine.

But the real solution would be to save the master passwort to the browser-instance or something. else people would need to set the passwort into the file anyway, cause its not practical to get asked the master passwort each time.

Also I would have to include the small sgppassword script directly there, so it would not have a unnessesary external dependency.

I maybe pull that together later. would then have I guess something like that incuded:

```
masterpw="$(zenity --password --title='Master password')"
# you can set it here fix instead for more comfort (and less security)
# masterpw="SECRET"
```

also I need some seperated fill-mail fill-username scripts or keybindings... but thats seperate issue I guess.

**Comment by lamarpavel** [comment]
>But the real solution would be to save the master passwort to the browser-instance or something. else people would need to set the passwort into the file anyway, cause its not practical to get asked the master passwort each time.

Unless you are using something like pass (linked by @t-wissmann above) which makes use of the GPG-agent. Having a script call `pass supergenpass/master` won't prompt the user unless the GPG-agent is locked.

**Comment by spiderbit** [comment]
So I reopen this old bug again. Its hard to create a PR for it cause it depends on some external things, but maybe I try afterwards.

But my problem at the moment is that my version of that userscript dont removes the subdomain but all the addons for other browsers of supergen as example firefox remove it, so it generates incompatible passwords:

local domain="${1%% *}"

can I change that so that it removes all subdomains?

**Comment by t-wissmann** [comment]
Per default, this userscript removes subdomains until there is at least one match in your pass database. So I guess your configuration prevents password_fill from doing this. What's your password_fill_rc?

By the way I have the following configuration: my full pass database is shown in rofi and it is only pre-filtered by the current domain, so I can manually strip subdomains if neccesary. My configuration can be found at https://github.com/t-wissmann/dotfiles/commit/afdd9fd0c27d845c3deae97a3e61aaf889149ee7#diff-0adf0ca3d7669d6fce98ea03d5ee023a

**Comment by spiderbit** [comment]
I dont use pass I use supergenpass see the code in the initial post of this bug
