### ISSUE TITLE
Toggle bookmark command

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1667]
Sometimes I accidentally hit `M` and want to quickly undo that. It would be nice if I could just press `M` again to unbookmark the current page. Maybe a `--toggle` flag for `bookmark-add`? I can see why some might not want this so it probably shouldn't be default behavior.

**Comment by The-Compiler** [comment]
Sounds good to me!

I guess a flag would be appropriate (so it's somewhat explicit that `:bookmark-add` can also delete something), but I think we could change the default keybinding as well - after all, all it takes if accidentally unbookmarking something is to press M again.

**Comment by mlochbaum** [comment]
I have code for this, but it's kind of entangled with my previous pull request #1671, so I'm waiting on that before submitting.
