### ISSUE TITLE
Keyboard navigation not working within pdfjs

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#1672]
Hello.
It would be nice to be able to use the default keyboard navigation (`h`, `j`, `k`, `l`, `Ctrl-B`, `Ctrl-F`, …) even when reading a PDF file with `pdfjs`.
Thanks.

**Comment by The-Compiler** [comment]
yep, see #1209 :wink:

**Comment by nabsiddiqui** [comment]
This does seem to work in Firefox with VimFx.  Is it possible to send a longer keypress if pdfjs is detected?  Some of the other keys work such as gg to go to the top, etc.
