### ISSUE TITLE
HIDPI issues on latest release

### ISSUE THREAD

**Issue by hajzso** [The-Compiler/qutebrowser#1678]
It's very weird because some images and text display perfectly, and some are blurry. Youtube is a good example for this, or DuckDuckGo. This browser is amazing... I want to use it so much but I'm already scaling to 1680 so sharpness is very important to see text properly.

I'm using the latest dmg:
qutebrowser v0.7.0
Git commit: v0.7.0-1-g5c1401b (2016-06-10 16:29:35 +0200)

CPython: 3.5.1
Qt: 5.6.1, runtime: 5.6.1
PyQt: 5.6
Style: QMacStyle
Desktop: None
sip: 4.18
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: 1.0.1 $Id$
typing: yes
pdf.js: 1.4.20 (bundled)
Webkit: 538.1
Harfbuzz: system
SSL: Secure Transport, OS X El Capitan (10.11)

Frozen: True
Platform: Darwin-15.5.0-x86_64-i386-64bit, 64bit
OS Version: 10.11.5, x86_64
---

**Comment by The-Compiler** [comment]
Can you do a screenshot? When you check the dmg properties in finder, is it marked as highdpi-compatible?

**Comment by The-Compiler** [comment]
@hajzso any update on this? :wink:

**Comment by hajzso** [comment]
Oh sorry, totally missed the e-mails... just came back to see what's up. Took some screenshots.

<img width="772" alt="screen shot 2016-08-02 at 21 03 50" src="https://cloud.githubusercontent.com/assets/1897608/17341439/e6ec9f48-58f4-11e6-9efc-f1c2063018a2.png">
<img width="584" alt="screen shot 2016-08-02 at 21 04 08" src="https://cloud.githubusercontent.com/assets/1897608/17341446/ec913058-58f4-11e6-805f-9289670a2a6e.png">

**Comment by The-Compiler** [comment]
What about my question there? :wink:

> When you check the dmg properties in finder, is it marked as highdpi-compatible?

Also, does setting `QT_AUTO_SCREEN_SCALE_FACTOR=1` in your environment change anything? 

Not sure if that simply works with `.app` files - can you do `:debug-pyeval __import__('os').environ` and check if that variable actually shows up there (e.g. using `/SCREEN`)?

**Comment by hajzso** [comment]
I didn't find any highdpi compatible property, maybe I was looking at the wrong place ( right click get info ) There is an option called 'open in low resolution' , that is unchecked. If I tick it, the ui elements become blurry too. 

**the debug command returns this, no screen scale var. probably this is the problem. Noob question: how do I add it? :)** 

environ({'LOGNAME': 'hajzso', 'XPC_SERVICE_NAME': '0', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.lhbwvDCdpY/Render', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'USER': 'hajzso', 'HOME': '/Users/hajzso', 'TK_LIBRARY': '/Applications/qutebrowser.app/Contents/MacOS/tk', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.05j2V7eZ27/Listeners', 'XPC_FLAGS': '0x0', 'SHELL': '/usr/local/bin/zsh', 'TCL_LIBRARY': '/Applications/qutebrowser.app/Contents/MacOS/tcl', 'SECURITYSESSIONID': '186a7', 'TMPDIR': '/var/folders/nh/mn_14n6x7l18m5fq_sjc4ch40000gn/T/'})

**Comment by The-Compiler** [comment]
Right, "Open in low resolution" was what I was looking for, in earlier versions of the dmg it was checked and greyed out.

For an initial test, something like `QT_AUTO_SCREEN_SCALE_FACTOR=1 ./Contents/MacOS/qutebrowser` (after using `cd` to navigate inside the `.app` folder) should probably work.

**Comment by hajzso** [comment]
Did it, didn't fix it :/  I also tried :reload -f on 'blurry' sites with no luck. Not sure if this is important, I got this message after the command: 'Harfbuzz fix attempted but QtWidgets is already imported!'

**Comment by hajzso** [comment]
I started using the browser as a daily driver actually, I couldn't resist it, and I noticed something now, check out this gif: 
![qute](https://cloud.githubusercontent.com/assets/1897608/17419292/01d4ceda-5a9d-11e6-861d-b151b726d15c.gif)

From this it seems like it is a render problem with certain css effects. The lack of pattern (until now) and that most css animations are choppy also suggest this.

**Comment by The-Compiler** [comment]
So at this point I'm pretty confident this is some kind of QtWebKit issue, and I can't do much about those.

I'd ask you to try with QtWebEngine (the new rendering backend) where this probably is solved, but that's currently broken in the `.app` (see #1692).

Thanks for tracking this down though, and sorry I can't do more right now!
