### ISSUE TITLE
Proxy Auto Config (PAC) support

### ISSUE THREAD

**Issue by nibogd** [The-Compiler/qutebrowser#1683]
It would be awesome to have PAC files support. Here it's the most convenient way to access blocked websites without proxying all traffic.

**Comment by The-Compiler** [comment]
With QtWebKit, this would require quite some custom code (with a second JS interpreter with [QJSEngine](http://doc.qt.io/qt-5/qjsengine.html)) and thus is unlikely to be implemented unless someone steps up.

With QtWebEngine, using something like `auto_proxy=http://myserver/myconf.pac qutebrowser --backend webengine --temp-basedir` should already work out of the box - I'll try to expose that via some config option as soon as settings support is in for QtWebEngine.

**Comment by nibogd** [comment]
Thank you, i'll wait for Qutebrowser to be ported to QtWebEngine 👍

**Comment by The-Compiler** [comment]
Could you maybe try the command above with a current git clone? I wonder if it actually works :wink:

**Comment by nibogd** [comment]
Yup, works perfectly

**Comment by abbradar** [comment]
For QtWebKit, I wonder if this can help: http://ivandemarino.me/2011/03/21/How-to-handle-Proxy-PAC-configuration-with-Qt/

**Comment by The-Compiler** [comment]
Qt Script was also [deprecated](https://wiki.qt.io/New_Features_in_Qt_5.5#Deprecated_Functionality) with Qt 5.5 so I'd rather not add code relying on that :wink:

Otter Browser [uses](https://github.com/OtterBrowser/otter-browser/blob/master/src/core/NetworkAutomaticProxy.cpp) [QJSEngine](http://doc.qt.io/qt-5/qjsengine.html) instead, which is certainly a possibility, but not something I see myself working on anytime soon I'm afraid - contributions welcome though!

**Comment by abbradar** [comment]
I've implemented [a PAC resolver](https://gist.github.com/abbradar/4a872799154931fbc887449bfc9bd41a) as a curious exercise using QJSEngine, but I'm unsure how to proceed -- I have no knowledge of qutebrowser internals to embed this. Still, I hope this will be helpful...

**Comment by abbradar** [comment]
Updated it -- looks much nicer and smaller now, and I've moved all logic into Python.

**Comment by The-Compiler** [comment]
@abbradar 's PR is merged now, so closing this.
