### ISSUE TITLE
OS X .app won't start on El Capitan 10.11.5 

### ISSUE THREAD

**Issue by coljac** [The-Compiler/qutebrowser#1686]
I understood from the INSTALL instructions that the standalone app should work best. It won't launch, quitting immediately. Invoking qutebrowser.app/Contents/MacOS/qutebrowser from the command line results in the following error:

```
Failed to execute script pyi_rth_qt5plugins
Traceback (most recent call last):
  File ".tox/pyinstaller/lib/python3.5/site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py", line 46, in <module>
  File "/Users/flo/qutebrowser/.tox/pyinstaller/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: dlopen(/Applications/qutebrowser.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/QtCore
  Referenced from: /Applications/qutebrowser.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so
  Reason: image not found
```

The file `./PyQt5.QtCore.cpython-35m-darwin.so` is present.

*(edited by @the-compiler to use triple-backticks for the multiline output)*

**Comment by The-Compiler** [comment]
Do you get this with the v0.8.0 .app? Does the v0.7.0 one work?

**Comment by coljac** [comment]
Apologies. 0.8.0.

0.7.0 initialises properly.

**Comment by The-Compiler** [comment]
I can reproduce this - seems like there was some issue during packaging. I'll investigate.

**Comment by The-Compiler** [comment]
I just uploaded `qutebrowser-0.8.0-2.dmg` where this should be fixed. I also added a smoke test to the packaging script so this shouldn't happen again. Sorry!
