### ISSUE TITLE
Google Images buttons (webengine)

### ISSUE THREAD

**Issue by FLHerne** [The-Compiler/qutebrowser#1699]
Using 0.8.1 on Arch, with backend=webengine.

Left- or middle-clicking on the "View {Source,Image}" buttons in Google Images has no effect.

Right-click -> Follow Link does work.

**Comment by The-Compiler** [comment]
Seems like it's trying to create a new window/tab via JS which is not implemented yet. I added a stub in 08a9786a73536ff364d0b3ff8742901c42339509 and added this to #666.
