### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#17]
We should have bookmarks or improved bookmarks. This means:

* No name, or a default generated one (from URL/title).
* Possibly a hierarchy

**Comment by The-Compiler** [comment]
Also see #32 for the completion.

**Comment by fosskers** [comment]
I endorsed this before I knew about quickmarks. Quickmarks serve the purpose I was looking for.

**Comment by antoyo** [comment]
Hi.
For your information, I started to work on this issue.

**Comment by The-Compiler** [comment]
There now are bookmarks (URL/title) thanks to @antoyo, so I'm closing this :+1:
