### ISSUE TITLE
Move current tab to the end

### ISSUE THREAD

**Issue by mlochbaum** [The-Compiler/qutebrowser#1701]
Currently it's possible with `:tab-move ;; tab-move -`, provided `wrap` is set. But one or both of the following would be much better:
* An option to change `tab-move`'s default to the last tab, or
* Some way to get a negative argument to `tab-move`, like `tab-focus`.

For the second, the most feasible way seems to be an explicit direction for "absolute", plus an `index` argument like `tab-focus` has. It's also possible to split up `tab-move`.

I'll implement the changes but would like to know if anyone has thoughts on how to do this.

**Comment by The-Compiler** [comment]
What about `:tab-move` just taking an `index` (rather than `direction`), and describe that the index can be `-` or `+` for relative moving? Then the count would just override that index if given, like with `:tab-focus`.

That seems the most consistent for me.

**Comment by mlochbaum** [comment]
That's better. It also removes the need for a `tab-move-default` option, since `:tab-move -1` bound to a key would work the same as `:tab-move` defaulting to the last tab.

Currently `:tab-focus` works opposite to the way you described, with the index overriding the count. This seems much less useful than the other way around. Is it correct?

**Comment by The-Compiler** [comment]
> Currently `:tab-focus` works opposite to the way you described, with the index overriding the count. This seems much less useful than the other way around. Is it correct?

I don't really thing it was a consicous decision - I agree that it'd probably make more sense to make the count win.
