### ISSUE TITLE
Keybinding for completion selection/navigation

### ISSUE THREAD

**Issue by madhat2r** [The-Compiler/qutebrowser#1706]
I have been unable to find the command that selects/navigates the completion areas. Right now it seems that TAB/SHIFT-TAB, up/down arrows both work. I would like to add my own keybinding for this. Could someone point me in the right direction?

**Comment by lahwaacz** [comment]
Look at the `[command]` section in `keys.conf`, that's where the default bindings are set. The commands are `completion-item-prev` and `completion-item-next`.

**Comment by madhat2r** [comment]
Brilliant! Not sure how I missed those, especially given it was clearly
documented, feeling a bit daft now :). Thanks.

On Jul 29 at 08:04 AM, Jakub Klinkovský <notifications@github.com> said
thus:

**Comment by lahwaacz** [comment]
You're welcome :smile:
