### ISSUE TITLE
:bind/help completion should show hidden commands

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1707]
Many commands have `hide=True` set so they are not shown in the command completion (mainly because they are commands you'd never run by hand, like `:prompt-accept`).

I think it would make sense to show them in the `:bind` completion, and probably in the `:help` completion too.

One for @rcorre maybe if you have time? :wink:

**Comment by rcorre** [comment]
Also, this just reminded me to file #1708
