### ISSUE TITLE
scripts/asciidoc2html.py missing in 0.8.1 release

### ISSUE THREAD

**Issue by fiete201** [The-Compiler/qutebrowser#1709]
The 0.8.1 release tarball misses that script.

**Comment by The-Compiler** [comment]
Was this ever in a release? It's explicitly [excluded](https://github.com/The-Compiler/qutebrowser/blob/v0.8.1/MANIFEST.in#L25) (as the documentation is already generated in the release tarball), and even when repackaging v0.7.0 that file isn't contained in it.

Is it possible you switched from autogenerated GitHub tarballs to release tarballs?

**Comment by V155** [comment]
I usually build from git but want to build from the tars on the releases page https://github.com/The-Compiler/qutebrowser/releases/ where can I find the docs there?

**Comment by lahwaacz** [comment]
The release tarballs have `doc/qutebrowser.1.asciidoc`, not the generated man page. Arch packages run `a2x` to generate the man page (see the [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/qutebrowser#n28)).

Inconsistently to this, the release tarballs contain the generated HTML documentation in `qutebrowser/html/doc/`.

**Comment by The-Compiler** [comment]
Yeah, the release tarball really should contain the generated manpage as well. I added it some while back in #474.

@lahwaacz already answered where the docs are, s
