### ISSUE TITLE
Add binding for unix-filename-rubout

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1710]
`ctrl-backspace` in prompt mode will delete to the previous `/`, but it is not
rebindable. 
We should add a binding for this. It is called `unix-filename-rubout` in readline.

This was previously the behavior of `ctrl-w` but was changed in #1512.

**Comment by The-Compiler** [comment]
We came to the same conclusion in #1698, so I'm closing this and renaming the other issue.
