### ISSUE TITLE
"rl-backward-kill-word" backwards compatibility issue

### ISSUE THREAD

**Issue by LadyClaire** [The-Compiler/qutebrowser#1717]
After starting a version of qutebrowser after the readline style "kill-word" shortcut was added, and then starting an older verision before that commit (such as the version in the Arch Linux repositories), the browser does not start up and instead gives the error message 

> Error while reading key config:
> In line 573: : Invalid command 'rl-backward-kill-word'!  

While those who use the newer version and then downgrade to the older version should probably expect to experience some buggy behaivior, perhaps errors in keyconfigs should be handled in a less abraisive way?

Version info:

qutebrowser v0.8.1
Git commit: v0.8.0-116-g57f256e (2016-07-30 18:49:58 +0200)
CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6
Arch Linux 2016.07.01, Kernel 4.6.3

---

**Comment by The-Compiler** [comment]
Handling this in a sane way is unfortunately not possible with the current config code. If qutebrowser would silently ignore it, it would be gone with the next config write, which is problematic if there actually was some typo or so.

However, after #499 (which is something I want to look at after the current QtWebEngine stuff) only settings an user explicitly changed will be in the config, which means this kind of thing is going to be much less painful.
