### ISSUE TITLE
Errors when `completion show` setting is false

### ISSUE THREAD

**Issue by mlochbaum** [The-Compiler/qutebrowser#1722]
Pressing up, down, or tab when there are completions available but the `completion show` setting is `false` crashes qutebrowser. The relevant error:

```
  ...
  File "/home/marshall/Github/qutebrowser/qutebrowser/completion/completionwidget.py", line 164, in _next_idx
    idx = self.selectionModel().currentIndex()
AttributeError: 'NoneType' object has no attribute 'currentIndex'
```

This appears after the recent completion fixes from @rcorre.

Generally, the completion `show` and `auto-open` options don't seem to make sense. Before the change, `show` would do what I expected `auto-open` to do (turning it off hides the completion window until the user asks for it with up, down, or tab). `auto-open` doesn't do anything (before or after the change), as far as I can tell.

**Comment by The-Compiler** [comment]
I can reproduce this with `show` being `false` and `auto-open` being `false`.

I think the intention was for `auto-open` to open the completion when pressing tab, and then hiding it again when completing is done. It seems indeed like that broke at some point, but no idea when...

**Comment by rcorre** [comment]
I remember this working at some point during completions, so I'm guessing I broke it pretty recently and  missed it in testing somehow.

**Comment by rcorre** [comment]
I haven't been able to repro this. Both `auto-open` and `show` work as expected and don't crash anything for me. Have any more detailed repro steps?

**Comment by rcorre** [comment]
Ah, never mind, got it. You have to have them `false` right from the start. If you open the completion at least once everything is fine.
