### ISSUE TITLE
Some Javascript buttons and menus do not work

### ISSUE THREAD

**Issue by tjanson** [The-Compiler/qutebrowser#1723]
Some Javascript-based buttons and menus do not work for me. As a concrete example:

1. Go to [`https://github.com/The-Compiler/qutebrowser/issues`](https://github.com/The-Compiler/qutebrowser/issues).
2. Press on the "Author" drop-down menu.
3. Expectation: Menu is displayed. Actual: Nothing happens.

Other Javascript-based pages work fine (e.g., Google’s search page uses JS extensively, including similar drop-down menus, and appears to work 100%).

I’m using the latest release, v0.8.1, on OS X 10.11.6 ([paste of full version info](https://gist.githubusercontent.com/tjanson/2b1a6e356ff9e92d9167cfb5c61c51bc/raw/26af4f97c2649c057282e8765b07aef479c7c642/Qutebrowser%2520version)).

Am I missing something obvious?

**Comment by The-Compiler** [comment]
Do you have a custom user-agent set? Unfortunately, GitHub breaks when you do that. Not much I can do about this with QtWebKit I'm afraid, but the upcoming QtWebEngine backend will not have that issue.

**Comment by tjanson** [comment]
Yes, I do, thanks. (I do because otherwise Gmail/Inbox don’t work.) Good hear that there’s hope. ;)
Great job with the project overall!

**Comment by apheleia** [comment]
I have the same problem :(
It would be nice to know why GitHub does that ...

**Comment by The-Compiler** [comment]
@apheleia So don't use a custom user-agent, or use QtWebEngine, or use QtWebKit-NG.

GitHub probably has some feature which the legacy QtWebKit doesn't support. It falls back on something working with QtWebKit based on the UA.

**Comment by apheleia** [comment]
Yes, I removed the custom user agent, thanks for the help.
Was just curious if anyone knows how GitHub breaks the functionality.
