### ISSUE TITLE
Tab completion crashes browser when no completion available

### ISSUE THREAD

**Issue by NextHendrix** [The-Compiler/qutebrowser#1731]
Typing anything after a colon that doesn't have a completion available, and then hitting tab, crashes the whole browser.

Log: [http://paste.the-compiler.org/view/50f45666](url)

Reproducible and confirmed on other systems in IRC

Version Info: qutebrowser v0.8.1
Git commit: v0.8.0-186-gef439bb (2016-08-01 18:19:34 +0200)

**Comment by Kingdread** [comment]
Can confirm that the browser crashes when no completion is available.

git-bisect shows f31e8908627edce679127712b096c2b04a16e07f as the commit that introduced this behavior.
