### ISSUE TITLE
Feature Request: Open Link in New Tab(background) on Right Click Menu?

### ISSUE THREAD

**Issue by nabsiddiqui** [The-Compiler/qutebrowser#1733]
qutebrowser v0.8.1
Git commit: v0.8.1-1-g27e9ff7 (2016-07-27 10:56:14 +0000)

CPython: 3.5.2
Qt: 5.5.1
PyQt: 5.5.1

sip: 4.17
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (/home/nabeel/.local/share/qutebrowser/pdfjs/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2g-fips  1 Mar 2016

Platform: Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
Desktop: mate
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

--- /etc/os-release ---
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

Currently, open link in new window allows you to open in a tab if tabs are windows is set to true. Is there a way that open in new tab(background) could be implemented?  I use the keyboard mainly but sometimes prefer to use the mouse if I am already doing something mouse based.

**Comment by The-Compiler** [comment]
> Currently, open link in new window allows you to open in a tab if tabs are windows is set to true.

And also without that :wink:

Currently qutebrowser doesn't customize the menu at all, see #349 for that.

However, you can middle-click or ctrl-click links to open them in a new tab (in background if you have set `tabs -> background-tabs` to true, or press shift too).

**Comment by nabsiddiqui** [comment]
Oh never noticed that I could middle-click.  Thanks a lot.

**Comment by nabsiddiqui** [comment]
Oh never noticed that I could middle-click.  Thanks a lot.
