### ISSUE TITLE
Behavior of cmdutils.arg_or_count

### ISSUE THREAD

**Issue by mlochbaum** [The-Compiler/qutebrowser#1735]
I am looking at making `tab_focus` work the same way as the new `tab_move`, with `count` overriding the `index` argument if present. Currently `tab_focus` and one other command, `zoom`, compute their indices with the `arg_or_count` method. As a consequence, each:
* Uses the argument or count if only one is given
* Fails if both are given (with appropriate error message)
* Uses a default value if neither is given.
* Also, `tab_focus` uses the last tab if the count is zero, but I don't see how it's possible to pass a zero count.

This seems overly complicated to me, and it buries functionality that's cleanly expressed with conditionals in a function in a different file. So I propose getting rid of `arg_or_count` and replacing it with something like
```python
index = count if count is not None else index
if index is None:
    index = # default value
```

The change in behavior for both commands would be to use the count rather than giving an error if both count and index are given.

**Comment by The-Compiler** [comment]
I don't really have a strong opinion on this, but I can see how it could be useful to bind a key to something with an index, and then override that index when passing a count.

Your proposal sounds good to me, want to go ahead and implement it?

> Also, `tab_focus` uses the last tab if the count is zero, but I don't see how it's possible to pass a zero count.

I have no idea either off-hand :laughing: This was introduced over 2 years ago in 5a6208862ecfd9065d6fa6d61812b5b210296031 FWIW (and the handling of 0 existed even before that). I'm fine with getting rid of it.

**Comment by mlochbaum** [comment]
On it. I assumed this issue was overkill, but it doesn't hurt to check.
