### ISSUE TITLE
ubuntu 16.04 start error

### ISSUE THREAD

**Issue by ibeex** [The-Compiler/qutebrowser#1746]
`~/Downloads ❯❯❯ qutebrowser --debug
17:59:55 DEBUG    init       earlyinit:init_log:301 Log initialized.
17:59:55 DEBUG    init       earlyinit:fix_harfbuzz:183 Using old harfbuzz engine (auto)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/earlyinit.py", line 278, in check_libraries
    importlib.import_module(name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'PyQt5.QtWebKit'
~/Downloads ❯❯❯ sudo apt install python3-pyqt5.qtwebkit                                                                                                                        ⏎
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5.qtwebkit is already the newest version (5.5.1+dfsg-3ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

installed from `qutebrowser_0.8.1-1_all.deb`

---

**Comment by The-Compiler** [comment]
That's odd. What does `python3 -c "from PyQt5 import QtWebKit; print(QtWebKit)"` say?

**Comment by ibeex** [comment]
that is strange
    ~/Downloads ❯❯❯ python3 -c "from PyQt5 import QtWebKit; print(QtWebKit)"
    Traceback (most recent call last):
       File "<string>", line 1, in <module>
    ImportError: cannot import name 'QtWebKit'`

**Comment by The-Compiler** [comment]
What about `python3 -c "import sys; print(sys.executable)"` and `ls /usr/lib/python3/dist-packages/PyQt5/QtWebKit.*`?

**Comment by ibeex** [comment]
here it is
    ~/Downloads ❯❯❯ python3 -c "import sys; print(sys.executable)"
    /usr/bin/python3
    ~/Downloads ❯❯❯ ls /usr/lib/python3/dist-packages/PyQt5/QtWebKit.*
    /usr/lib/python3/dist-packages/PyQt5/QtWebKit.cpython-35m-x86_64-linux-gnu.so

**Comment by The-Compiler** [comment]
Hmm, nothing special there... I don't see why your Python would be unable to import it.

Can you please show `python3 -c "import PyQt5; print(PyQt5)"` and `python3 -vc "from PyQt5 import QtWebKit"`?

**Comment by ibeex** [comment]
https://gist.github.com/ibeex/7f985de60f3bb117624f3668a4b5d82a

**Comment by The-Compiler** [comment]
Looking at `<module 'PyQt5' from '/usr/local/lib/python3.5/dist-packages/PyQt5/__init__.py'>` it seems like you have a custom PyQt5 install in `/usr/local/lib` (which isn't the one installed via apt-get), probably without QtWebKit. Maybe try to get rid of it?

**Comment by ibeex** [comment]
yes that was case, pip3 uninstall fixed it, THX!!

**Comment by The-Compiler** [comment]
Yay - glad you solved it! :tada:
