### ISSUE TITLE
Amazon site not displaying properly.

### ISSUE THREAD

**Issue by madhat2r** [The-Compiler/qutebrowser#1750]
Go to amazon->Departments->Amazon Video->All Videos

On that page there are supposed to be quite a few side-scroller widgets, but they do not display.

---
qutebrowser v0.8.1
Git commit: v0.8.0-222-g53b0cf8 (2016-08-02 22:45:08 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Platform: Linux-4.4.14-1-lts-x86_64-with-arch, 64bit
Desktop: None
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

**Comment by The-Compiler** [comment]
First of all, having a direct link and a screenshot really helps with removing ambiguity for bug reports like this :wink:

This is how it looks for me [on this page](https://www.amazon.com/b/ref=lp_2858778011_nav_shopall_aiv?rh=i%3Ainstant-video%2Cn%3A2858778011&ie=UTF8&node=2858778011) in qutebrowser (left) and Chromium (right):

![qute](https://cloud.githubusercontent.com/assets/625793/17356317/095b0a94-5957-11e6-8567-29ccac918f2d.png)

With "side-scroller widgets", do you mean the missing scrollbars?

**Comment by lahwaacz** [comment]
I don't see any horizontal scrollbars even in Chromium: https://postimg.org/image/9z1bqhs3b/

The same issue that @madhat2r described actually happens on WMF's Phabricator too: on the [workboard](https://phabricator.wikimedia.org/tag/mediawiki-api/) each column should have its own scrollbar, but they don't and also the scrollwheel does not work, so it's impossible to reach the hidden tasks. This issue is already solved with the webengine backend.

**Comment by madhat2r** [comment]
@The-Compiler you are right, links are better, not sure what I was thinking there. 

What I meant by side scrolling widgets is that each horizontal row is set up kind of light a light box widget with an arrow at the end that allows scrolling past the visible elements. In firefox/chromium these elements exist, but in qute browser they do not. This appears to be the same issue @lahwaacz is mentioning.

You can see this in my screenshot. qutebrowser on left, chrome on right. 
![lastimg](https://cloud.githubusercontent.com/assets/4122449/17367245/d44dcf14-5954-11e6-9e47-91dea84ff35d.png)

**Comment by The-Compiler** [comment]
Thanks for the clarification! I see those arrows in Firefox too, but not in Chromium... so I'll have to blame Amazon for that one.
