### ISSUE TITLE
Make 0 an usable count for commands

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1758]
Some commands might want to handle a count of 0 differently than others - this came up for `0T` (to focus the last tab) in #1753.

Adding this per se should be easy, but we might need a new `zero_count=True` argument to `@cmdutils.argument` as I'd guess most commands would rather not have a count of 0 by default?

**Comment by munyari** [comment]
Hey @The-Compiler. Apologies, my python is somewhat rusty. Would this change entail changing `__init__` in the `argument` class in `commands/cmdutils.py` to accept an additional argument?

**Comment by The-Compiler** [comment]
@munyari If we want to go the route of adding such an argument, `@cmdutils.argument` simply takes any keyword argument (via `**kwargs`) and then passes then to `command.ArgInfo` which does the actual validation.

However I'm wondering how many commands actually could make sense of a `0` count, and if it'd make more sense to handle it there directly?

**Comment by The-Compiler** [comment]
@munyari Are you still working on this? Otherwise @knaggita would like to take over :wink:

**Comment by munyari** [comment]
Hey @The-Compiler, I'm unfortunately tied up at the moment. @knaggita can
go ahead.

**Comment by knaggita** [comment]
Thanks @munyari

**Comment by munyari** [comment]
Thank you for your contribution :smile:

**Comment by The-Compiler** [comment]
This is implemented now, thanks @knaggita! :tada:
