### ISSUE TITLE
Hard crash on twitter videos

### ISSUE THREAD

**Issue by NextHendrix** [The-Compiler/qutebrowser#1760]
Scrolled down a twitter page with the videos doing that autoplay thing they do, entire browser locks up hard.

pkill qutebrowser doesn't kill it, quitting it with my windows manager doesn't kill it, even SIGTERM doesn't kill it
have to SIGKILL from htop to get rid of it, can reproduce every time

1. Go to someones twitter page
2. Click media
3. Scroll down some
4. Crash

I ran qutebrowser from a terminal for the output, and pasted it below

https://ptpb.pw/x3zK

**Comment by The-Compiler** [comment]
Seems like your GStreamer is misbehaving in some way. Do you have `gstreamer-vaapi` or similar installed? If so, can you try uninstalling it?

Also, what Qt version is this (`:open qute:version`), and which distribution?

**Comment by moozzz** [comment]
I have a very similar problem but with any media whether it be twitter or youtube or any other platform with videos and/or music. Qutebrowser crashes once I try to play a video. `gstreamer-vaapi` is installed. And here is the output of `:open qute:version`:

qutebrowser v0.8.1
Git commit: v0.5.0-2358-g2f50d10 (2016-08-03 17:43:49 +0200)

CPython: 3.5.2
Qt: 5.6.1
PyQt: 5.6

sip: 4.18.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.0-1-amd64-x86_64-with-debian-stretch-sid, 64bit
Desktop: awesome
Frozen: False
Imported from /home/user/Software/qutebrowser/qutebrowser
OS Version: 

--- /etc/os-release ---
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian

**Comment by The-Compiler** [comment]
@moozzz Okay, please try deinstalling `gstreamer-vaapi`. It's very unstable, especially with Intel graphics.

**Comment by moozzz** [comment]
Done. But the problem is still present...

What I also noticed is that these crashes didn't begin suddenly. It started with some videos on youtube and then spreaded to all youtube videos and then other platforms. Finally, qutebrowser now can play practically no video.

**Comment by The-Compiler** [comment]
It probably is, yeah... Could you maybe [get a C++ stacktrace](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc) of the crash?

**Comment by NextHendrix** [comment]
I don't have gstreamer-vaapi installed, but have intel integrated graphics with the kernel modesetting driver, not xf86-video-intel
I do however have gst-plugins-{base,good,bad,ugly,base-libs} and gst-libav installed

qute:version:   qutebrowser v0.8.1
Git commit: v0.8.0-257-g2f50d10 (2016-08-03 17:43:49 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch, 64bit
Desktop: i3
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

**Comment by NextHendrix** [comment]
I don't have gstreamer-vaapi installed, but have intel integrated graphics with the kernel modesetting driver, not xf86-video-intel
I do however have gst-plugins-{base,good,bad,ugly,base-libs} and gst-libav installed

qute:version:   qutebrowser v0.8.1
Git commit: v0.8.0-257-g2f50d10 (2016-08-03 17:43:49 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch, 64bit
Desktop: i3
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

**Comment by NextHendrix** [comment]
I don't have gstreamer-vaapi installed, but have intel integrated graphics with the kernel modesetting driver, not xf86-video-intel
I do however have gst-plugins-{base,good,bad,ugly,base-libs} and gst-libav installed

qute:version:   qutebrowser v0.8.1
Git commit: v0.8.0-257-g2f50d10 (2016-08-03 17:43:49 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch, 64bit
Desktop: i3
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

**Comment by NextHendrix** [comment]
I don't have gstreamer-vaapi installed, but have intel integrated graphics with the kernel modesetting driver, not xf86-video-intel
I do however have gst-plugins-{base,good,bad,ugly,base-libs} and gst-libav installed

qute:version:   qutebrowser v0.8.1
Git commit: v0.8.0-257-g2f50d10 (2016-08-03 17:43:49 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch, 64bit
Desktop: i3
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

**Comment by NextHendrix** [comment]
I don't have gstreamer-vaapi installed, but have intel integrated graphics with the kernel modesetting driver, not xf86-video-intel
I do however have gst-plugins-{base,good,bad,ugly,base-libs} and gst-libav installed

qute:version:   qutebrowser v0.8.1
Git commit: v0.8.0-257-g2f50d10 (2016-08-03 17:43:49 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch, 64bit
Desktop: i3
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

**Comment by NextHendrix** [comment]
I don't have gstreamer-vaapi installed, but have intel integrated graphics with the kernel modesetting driver, not xf86-video-intel
I do however have gst-plugins-{base,good,bad,ugly,base-libs} and gst-libav installed

qute:version:   qutebrowser v0.8.1
Git commit: v0.8.0-257-g2f50d10 (2016-08-03 17:43:49 +0200)

CPython: 3.5.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Style: QFusionStyle
Platform: Linux-4.6.4-1-ARCH-x86_64-with-arch, 64bit
Desktop: i3
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

**Comment by The-Compiler** [comment]
@NextHendrix You submitted your comment 6 times, I deleted the other ones :wink: If you have a custom user agent set, you'll need to unset that for GitHub to work correctly unfortunately...

Could you please also show a [C++ stacktrace](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc) of the crash? If you don't want to get through the hassle of installing debug symbols, even one without them might already be useful to get an idea of what's going on.

**Comment by NextHendrix** [comment]
Sorry mate i wondered why github was acting up, didnt know it was actually
submitting. Ill sort that trace out when i get a minute

**Comment by NextHendrix** [comment]
Ill assume i can safely skip the 2GB qt5-webengine-debug for now since it was while running in qtwebkit at the time?

**Comment by The-Compiler** [comment]
Indeed!

**Comment by NextHendrix** [comment]
http://paste.the-compiler.org/view/7605026e

Thats your gdb trace, with the last few lines of the program working and then running ctrl-c bt

**Comment by The-Compiler** [comment]
Looking at that it's indeed somewhere deep inside WebKit -> GStreamer... I'm afraid there's not really anything I can do about this, except continue working on the new QtWebEngine backend :wink: Sorry!

**Comment by NextHendrix** [comment]
No sweat, i look forward to webengine too
