### ISSUE TITLE
Use default system fonts for generic family names like “sans-serif”

### ISSUE THREAD

**Issue by Markus00000** [The-Compiler/qutebrowser#1764]
By default the `web-family-*` options are unset. Sites like Wikipedia that use `font-family: "sans-serif";` will currently not use the system’s default font for `sans-serif` as returned by `fc-match sans-serif`.

As a workaround one can set them explicitly:

    web-family-standard (Current: sans-serif)
    web-family-fixed (Current: monospace)
    web-family-serif (Current: serif)
    web-family-sans-serif (Current: sans-serif)
    web-family-cursive (Current: cursive)
    web-family-fantasy (Current: fantasy)

This might be relevant to #1648 as, depending on the used font, rendering might be poor.

qutebrowser v0.8.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6
Distribution: Arch Linux
Window manager: i3

**Comment by The-Compiler** [comment]
I'm simply setting those Qt options, I can't really do much more than that.

It's possible that I'm doing something wrong when they are set to the default (empty string), which is tracked in #1648 - so I'm closing this one.
