### ISSUE TITLE
external editor 'gvim' under windows launches in read-only mode

### ISSUE THREAD

**Issue by troubas** [The-Compiler/qutebrowser#1767]
Hi There

Today I found out, that a long missed feature existed all along. The external editor configured via `general/editor`.

I assume I'm one of the first people actually using it with windows because when I tried to edit the file with gvim it always got opened in read-only mode. Naturally I wanted to try other editors and `notepad` turned out to be very helpful towards finding the cause. When trying to save the following message popped up:
```
The process cannot access the file because it is being used by another process.
``` 

I assume that the file is still open in python. A possible solution would be to close the file upon opening an external editor and reading it once the external editor gets closed.

Thank you for this amazing project!
troubas

**Comment by The-Compiler** [comment]
Hmm, I definitely have used it on Windows in the past, but that might be before there were some bigger changes in this area. I'll look into it, but it might take me some while as I'm not usually using Windows.

**Comment by Kingdread** [comment]
`editor.py` should probably use `tempfile.NamedTemporaryFile` instead of `mkstemp`, then we don't need to deal with OS-level handles in Python. At least, it should close the handle like troubas said. Currently, we open the file twice when creating it (the handle returned by `mkstemp` and the `with open(self._filename)`)

**Comment by The-Compiler** [comment]
Right, that (with `delete=False`) would probably be the better approach indeed.

**Comment by The-Compiler** [comment]
Tenatively marking this as `easy` in the hope that the thing @Kingdread mentioned would fix this.
