### ISSUE TITLE
Replace :paste by {clip} and {sel} variables

### ISSUE THREAD

**Issue by blyxxyz** [The-Compiler/qutebrowser#1770]
`{clip}` and `{sel}` variables would make clipboard access more general and make `:paste` obsolete.

`:open` would have to get support for `:paste`'s opening of newline-separated lists of URLs, that feature is really useful sometimes.

Does removing a command give issues with updating?

**Comment by The-Compiler** [comment]
I like that idea!

> Does removing a command give issues with updating?

The main problem is of course keybindings, but there [is some code](https://github.com/The-Compiler/qutebrowser/blob/v0.8.2/qutebrowser/config/configdata.py#L1625-L1654) to automatically adjust them on updates.

What I'd still recommend though is first adding `deprecated="Use :open {clipboard}"` to the `@cmdutils.register` decorator - then it'll be marked as such and a warning will be shown when using it. Then I'd remove it in the next minor release after deprecating it.

And time for some bikeshedding: I think `{clipboard}` and `{selection}` (or `{primary}`?) would be better names. Still not awfully long, but they make it more clear what they're for.

**Comment by rcorre** [comment]
The only issue I see is `sel` (or `selection`) could be confused with the visual selectin, but I guess you probably won't discover these things without looking at the docs anyways. I don't have much preference on the short vs long names.

**Comment by The-Compiler** [comment]
Good point - let's go for `{primary}` then I'd say?

**Comment by blyxxyz** [comment]
I agree with `{clipboard}` and `{primary}`.

**Comment by The-Compiler** [comment]
Implemented in #1791
