### ISSUE TITLE
Font/color overrides like firefox?

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1779]
In firefox there's a way to override a web page's colors and fonts to my own settings, plus an easy way to toggle this behavior with a keybinding (in pentadactyl).

Specifically, the overrides I'm interested in:

1. Disable website's own fonts and always force my choice (like the firefox “Allow websites to load their own fonts instead of your choices?” dialog). In firefox this is subdivided into serif/sans-serif/monospace etc. but for my purposes I want to use the same font for everything either way so I don't care about the subdivision.

2. Disable website's own colors and always force my choices. In firefox, this is split up into four distinct colors: 1. background, 2. foreground, 3. anchor, 4. anchor(visited) and I think that model makes the most sense.

Maybe there's a way to do this already in qutebrowser, but more importantly than the override itself I also need it to be something I can toggle on and off easily.

**Comment by haasn** [comment]
After noticing `set colors webpage.bg`, I recommend implementing #2 in the form of also adding `webpage.fg`, `webpage.link` and `webpage.visited`, and then providing a boolean to force these colors even if the website has other colors set.

**Comment by lahwaacz** [comment]
For 2. you can probably use the custom stylesheet (`ui -> user-stylesheet` setting).

**Comment by The-Compiler** [comment]
I agree a custom stylesheet should be enough (and more flexible) here.

For the first suggestion, check the `web-family-*` settings in the `fonts` section.

**Comment by haasn** [comment]
On the topic of custom stylesheets, what would instantly propel this feature to great usefulness would be a pentadactyl-like `:style` command.

For example, in pentadactyl I can type:
```:style -name=fixwidth github.com .discussion-timeline { width: 80% !important; } .container { width: 90% !important; }```

And then, I can use `:styletoggle`, `:styleenable` or `:styledisable` to affect whether or not any given style is enabled at a point in time.

Having only a single, global style sort of limits its usefulness in my books.

**Comment by The-Compiler** [comment]
This should all be covered by #27, #47 and #135 :wink:

**Comment by haasn** [comment]
Note: `* { font-family: Terminus !important; }` in my user-style sheet perfectly solves the wrong fonts issue ;)
