### ISSUE TITLE
uMatrix-style permission matrix?

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1780]
This is one of my most heavily relied upon browser features and I would absolutely love to see a replacement for it in qutebrowser.

To summarize: uMatrix is a matrix-style website permission system, which allows me to do things like “allow images from githubusercontent.com but only from github.com”, or “allow XHRs from foo.example.com to bar.example.org” or even “allow 1st-party images and css by default”.

The interface uMatrix provides is primarily mouse-driven, but I don't mind what the interface is as long as it's functionally equivalent. Here's a screenshot of what it looks like, in case you're unfamiliar:

![umatrix](https://0x0.st/BZ6.png)

In particular, I rely on this for cookie control, script control, plugin control, frame control and also a rudimentary form of ads control. (Basically host blocking). I also think that matrix-style blocking is *much* better than flat/linear list-based blocking because I may want to allow youtube.com to access scripts/cookies on google.com without enabling other domains to do the same.

**Comment by The-Compiler** [comment]
I agree, and it's one of the first things I want to write once there is a plugin API - see #30
