### ISSUE TITLE
UX issue: If not in insert mode, don't have a cursor

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1781]
I'm very used to treating myself as being in insert mode if I see a cursor/selected element on the page.

For example, if I click on “new issue” here on github, it automatically focuses the title input field, but qutebrowser does not automatically land in insert mode. (Note that this happens regardless of what :set input auto-insert-mode is set to!) A similar issue arises when simply pressing escape to leave insert mode - my caret is left in the input box (and the blue border around it indicating it's selected as per CSS rules).

In both cases, this visual dissonance causes me to think I'm in insert mode already and therefore to start typing, even though it's not the case and my keystrokes get interpreted by qutebrowser instead.

I would greatly appreciate it if qutebrowser deselected all input elements when not in insert mode (even *if* the caret position is remembered internally, which pentadactyl/firefox does), and only re-selected them when actually entering insert mode again.

**Comment by lahwaacz** [comment]
AFAIK the cursor can be hidden only by removing focus from the element completely and it's sometimes useful to remember which element was focused previously. But the current behaviour is not ideal, there are many weird issues with this (e.g. #218).

**Comment by The-Compiler** [comment]
See #581
