### ISSUE TITLE
Some minor keybinding suggestions

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1782]
I could probably easily bind these myself (assuming I figure out how key bindings are supposed to work), but I think others would benefit from these:

* `g0` to go to the first tab
* `g$` to go to the last tab
* `gi` to enter insert mode (which element to select is left up to interpretation/magick by the browser, but usually pentadactyl picks the right one here)

**Comment by lahwaacz** [comment]
For the first two, see https://github.com/The-Compiler/qutebrowser/issues/1753#issuecomment-237624954 :laughing: 

The last is tracked in #219.

**Comment by The-Compiler** [comment]
Nothing more to add here :wink:

**Comment by haasn** [comment]
Note to future readers: `g$` can already be implemented as `:bind g$ tab-focus -1`. (similarly `g0` as `:bind g0 tab-focus 1`)

`gi` can be roughly approximated as `:bind gi hint inputs` (will work better assuming #1809 is fixed)
