### ISSUE TITLE
:undo should provide an undo list

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1785]
Very often I want to access a tab that I closed some while ago, rather than the tab that I closed last.

In pentadactyl, just typing :undo (as a command) gives me this useful list of recently closed tabs, from which I can select the one I want to re-open:

![:undo](https://0x0.st/BZG.png)

A similar functionality in qutebrowser's :undo command would not be wasted.

**Comment by The-Compiler** [comment]
See #32.
