### ISSUE TITLE
Add count to keybindings

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1787]
`:bind` has no mechanism of specifying a count to use for a keybinding.

I want to replicate the effect of what would be `:noremap j 3j` in pentadactyl etc., i.e. affect the scrolling distance.

(Maybe there's a better way to affect the number of lines scrolled, though? I know firefox has a setting for it)

**Comment by lamarpavel** [comment]
Hm, not exact number of lines, but you can scroll with different speed using `scroll-page 0 <float>`. A default binding is
```
scroll-page 0 0.5
    <ctrl-d>
```
To scroll half a page. You could bind `scroll-page 0 0.01` to `j`, which would be faster than regular line scrolling as long as the browser has a height of more than 100 lines.

So actually, yeah, rebinding j with 3j would be nice to have.

**Comment by haasn** [comment]
@lamarpavel Thanks for that suggestion - I consider scroll-page perfectly adequate for my use case.

Feel free to close this issue unless there's a nother good reason to add counts to keybindings

**Comment by The-Compiler** [comment]
Note there's also `:scroll-px` to scroll by a given amount of pixels. However, unlike `:scroll down` they use the scrolling API of QtWebKit (`:scroll down` emulates a keypress), which has some problems with multiple scrollable div's.

Keeping this open for now though, as I think it should be quite easy and could have other uses.

**Comment by haasn** [comment]
I just saw the `:repeat` command which can be used to repeat other commands. I guess that addresses the original request?

**Comment by The-Compiler** [comment]
There are some commands taking a count for other purposes (like a tab index), but I agree most things should probably be covered - let's close this and see if someone else speaks up in the future :wink:
