### ISSUE TITLE
Command for inserting text

### ISSUE THREAD

**Issue by blyxxyz** [The-Compiler/qutebrowser#1790]
A command to insert text would be useful for bindings and userscripts. It could be based on `:paste-primary`'s code, and then `:paste-primary` could be replaced by `:insert {primary}` (see #1770).

**Comment by The-Compiler** [comment]
Sounds good, but maybe `:insert-text` would be a better name - I first thought you were asking for the equivalent of `:enter-mode insert`.

**Comment by blyxxyz** [comment]
Yeah, that would be less confusing.

**Comment by blyxxyz** [comment]
Implemented in #1836.
