### ISSUE TITLE
:set colors completion.category.border.bottom works badly with gradients

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1793]
I want the category header's bottom border to be a pentadactyl-style horizontal gradient across the whole width. Unfortunately, if I set it to a `qlineargradient`, the gradient repeats itself for every “sub-section” of the completion list.

Not a huge deal since this is purely aesthetic either way, but it just sort of struck me as odd.

To perhaps explain the issue better, a screenshot:

Desired:
![pentadactyl](https://0x0.st/BbS.png)

Actual:
![qutebrowser](https://0x0.st/BbQ.png)

**Comment by The-Compiler** [comment]
I took a quick look at this, and all qutebrowser does is [constructing a Qt stylesheet](https://github.com/The-Compiler/qutebrowser/blob/v0.8.2/qutebrowser/completion/completionwidget.py#L66-L80) from the settings - unfortunately I don't think it'd be possible to customize how the gradient is applied that way...
