### ISSUE TITLE
Provide status bar feedback on whether or not JavaScript enabled?

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1795]
I have a keybinding `gj` to toggle javascript on and off, and I'd like to get some immediate visual feedback for when it's enabled - preferably in the form of something in my status bar.

Since I'm not sure how many other users would appreciate this exact functionality, the best way to approach it might be as some form of  general-purpose status bar customization (similar to how it can be done in vim).

Another way to approach this entire issue would be to have a built-in concept of “sudo” mode vs “safe” mode -> the latter would disable new cookies, localstorage, javascript, etc. (basically provide a sort of “disable all the site nastiness” mode), and for websites that break in this mode - or to log in and have my login cookie remembered - I could enter “sudo” mode temporarily (perhaps only for this tab) and turn off these restrictions.

**Comment by The-Compiler** [comment]
What you can do right now is to bind it to `:set -p` (`--print`). I agree this should be implemented in a generic way - see #1052 and the "adding widgets to the statusbar" part of #30.
