### ISSUE TITLE
(Option to) suppress hiding hints in rapid mode

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1799]
Right now if I start typing one hint in rapid mode, the next completion will end up disappearing as I'm typing the current one, which throws me off if I'm trying to read in advance to see what the next one would be.

**Comment by lahwaacz** [comment]
Note that this applies only to the `word` mode, and maybe `letter`, but in `number` it is intentional to hide the other hints as you type, because in numeric mode writing works as filter.

This is probably something I've caused sometime in winter... I'll take a look.

**Comment by lahwaacz** [comment]
Actually, in number mode writing the numbers and letters are separate, so for consistency we can suppress hiding the hints while typing the _hint string_.

**Comment by The-Compiler** [comment]
If someone would prefer this being optional, speak up - I think I don't mind either way :wink:

**Comment by The-Compiler** [comment]
Added by @lahwaacz as a new `hints -> hide-unmatched-rapid-hints` option.
