### ISSUE TITLE
Open new tabs in last focused window

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1801]
Right now qutebrowser opens new tabs (e.g. ``--target tab``) in whichever window was opened last, rather than whichever window had focus last.

Often I want to direct a new tab to a specific qutebrowser instance. Especially in light of the fact that there's currently no `:tab-attach` command (see #1788), there's currently no very elegant way to do this other than `yyd`/`pp`.

**Comment by The-Compiler** [comment]
This is partly covered by #881 already, but I guess it makes sense to have a separate issue.
