### ISSUE TITLE
Escape is not handled properly in hinting mode

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1805]
The following (new) test fails:

```gherkin
Scenario: Entering, leaving and re-entering hinting mode
    When I open data/hints/html/number.html
    And I run :hint
    And I run :fake-key -g k
    And I run :fake-key -g <Esc>
    And I run :fake-key -g d
    And I wait until data/numbers/5.txt is loaded
    Then the following tabs should be open:
        - data/numbers/5.txt (active)
```

The problem is that after pressing `Esc` and re-entering the hinting mode, `k` is still remembered and the hint for `kd` is followed instead of `d`. This is very similar to #1464. Maybe also #1657 is related to the `Esc` handling.

**Comment by The-Compiler** [comment]
I don't really follow - I guess this is with `data/hints/number.html` (outside `html/`)? Also, is this in letter hint mode? I get different letters, but everything seems to work as expected for me.

**Comment by lahwaacz** [comment]
Right, that should be `data/hints/number.html`. And do you have `hints -> scatter` set to false by any chance? For some reason it happens only when it's set to true, regardless of the letters (which will be pretty hard to test consistently with scattering :sweat:).

**Comment by The-Compiler** [comment]
Reproduced with `scatter` turned on - weird! Testing shouldn't be a problem, the scattering isn't random, i.e. for the same sets of link you should get the same hints.

**Comment by lahwaacz** [comment]
Just noticed that this is not reproducible on every page, even with `scatter` turned on.

**Comment by lahwaacz** [comment]
Next scenario which fails:

```gherkin
Scenario: Entering and leaving numeric hinting mode
    When I open data/hints/html/simple.html
    And I run :set hints mode number
    And I run :hint
    And I run :fake-key -g <Esc>
    And I wait for "Leaving mode KeyMode.hint (reason: leave current)" in the log
    Then no crash should happen
```

Note that this is not about crash, I'm just missing `Then nothing should happen`. What happens is that instead of leaving the mode, the keyinput gets "frozen" in some undefined dead-end state.

This works fine in `letter`, but not in `number` and `word` modes.

**Comment by The-Compiler** [comment]
There's a `Then ... should be logged` for those cases FWIW :wink:

**Comment by lahwaacz** [comment]
Thanks, but if this was a real test, I should probably add `And I run :set hints mode letter` between `And I wait for ... in the log` and `Then nothing should happen` to not affect other scenarios. But the weirdest thing is that if I do that, the test passes already...

**Comment by lahwaacz** [comment]
I hit this issue again when writing tests for the word mode in #1817. I haven't been able to track this down precisely, but know how to hopefully fix this :wink:

In the first scenario, the old key obviously stays in the keychain longer than it should. I've looked at how clearing the keychain currently works and that is by binding `Escape` to `clear-keychain ;; leave-mode` in the config. Not only this looks like users might omit `clear-keychain` without hindering usability, but considering this issue, it's somewhat flaky. If leaving the mode implies clearing the keychain in the mode to be left, it should be done directly, e.g.
```diff
diff --git a/qutebrowser/keyinput/modeman.py b/qutebrowser/keyinput/modeman.py
index 9aa4920..31c5406 100644
--- a/qutebrowser/keyinput/modeman.py
+++ b/qutebrowser/keyinput/modeman.py
@@ -282,6 +282,7 @@ class ModeManager(QObject):
             raise NotInModeError("Not in mode {}!".format(mode))
         log.modes.debug("Leaving mode {}{}".format(
             mode, '' if reason is None else ' (reason: {})'.format(reason)))
+        self.clear_keychain()
         self.mode = usertypes.KeyMode.normal
         self.left.emit(mode, self.mode, self._win_id)
 ```
I haven't tried eliminating `clear-keychain` from the binding yet, but I think it should work.

Since this is rather fragile, I figured that I should ask here first before making a PR, so what do you think?

**Comment by The-Compiler** [comment]
I think the reason `clear-keychain` is in the keybinding is because you could press escape in normal mode to cancel a keychain without leaving anything (because you're in normal mode already).

But I don't see a reason for the keychain not to be cleared when leaving a mode, so your diff looks good.

**Comment by lahwaacz** [comment]
Actually, `clear-keychain ;; leave-mode` is bound only when not in normal mode (see [here](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/config/configdata.py#L1454-L1456)). There is also a binding for normal mode, `clear-keychain ;; search`, which also looks redundant because `search` with empty text should clear the keychain on its own.

**Comment by The-Compiler** [comment]
Why should it? What `:search` does (clearing search highlights) seems totally independent from keychains to me.

**Comment by lahwaacz** [comment]
Of course you're right, `:search` terms are not stored in keychain, so I mixed up couple of things here.
