### ISSUE TITLE
Buffer completion: Selecting buffers from other windows doesn't work

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1808]
From #1778 by @haasn:

> Ah, another pretty big difference between qute's buffer list and pentadactyl's: pentadactyl's only shows buffers from the current window.
>
> I'm not sure what good showing me buffers from another window is supposed to do in `:buffer`, since it's not like selecting them does anything. I think that maybe this should be a flag to `:buffer`, and off by default.

I'm pretty sure it at least used to focus the window that buffer was in, or mark it as urgent?

cc @toofar

**Comment by haasn** [comment]
Ah, indeed. It switches that window to that tab, but it does not mark it as urgent (for me).

**Comment by rcorre** [comment]
For me, with AwesomeWM, it will switch focus to the window iff it is in my current workspace.

**Comment by The-Compiler** [comment]
Hmm, I think this will work if the window manager is cooperative enough then, so I'm closing this.
