### ISSUE TITLE
HintManager.filter_hints is called only for numeric hinting mode

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1809]
See https://github.com/The-Compiler/qutebrowser/issues/219#issuecomment-238270637 for why it should be called for _every_ mode. Now it's called only from [HintKeyParser._handle_special_key](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/keyinput/modeparsers.py#L168-L200) only if `hints.mode = number` and from [HintManager.fire](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/hints.py#L925) only if rapid hinting is active.

**Comment by The-Compiler** [comment]
Other hints are filtered in `handle_partial_key` FWIW - I agree it'd probably make sense to clean this up, but I wouldn't call it a bug. The docs for `auto-follow` even says "Follow a hint immediately when the hint text is completely matched.", so I think the original intention - without answering the question whether it makes sense or not - is the current behaviour.

**Comment by lahwaacz** [comment]
OK, so the existence of [HintManager._filter_non_number_hints](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/hints.py#L804) is just a coincidence of https://github.com/The-Compiler/qutebrowser/commit/82da79d05a90f28d237a845842c4b14a33407e44#diff-cb0972e31fcd54fcde537fce4053f7acR914, which apparently came too ahead of time :angel: 

Considering that the original `filter_hints` code was tested only in number mode, there might be more extensive changes needed...

**Comment by lahwaacz** [comment]
Regarding the partial key handling, I'm wondering how the `keystring_updated` signal actually works. It is declared as a class attribute on the [BaseKeyParser](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/keyinput/basekeyparser.py#L75) class, so I would expect it to be shared among all instances of all children, but that's not what happens in practice. For example [status.keystring.setText](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/mainwindow.py#L324-L325) is connected only for the normal mode and [HintManager.handle_partial_key](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/hints.py#L751) gets signals only from the HintKeyParser. Could somebody explain this to me?

**Comment by The-Compiler** [comment]
From the [PyQt docs](http://pyqt.sourceforge.net/Docs/PyQt5/signals_slots.html):

> A signal (specifically an unbound signal) is a class attribute. When a signal is referenced as an attribute of an instance of the class then PyQt5 automatically binds the instance to the signal in order to create a bound signal. This is the same mechanism that Python itself uses to create bound methods from class functions.

This is done using [descriptors](https://docs.python.org/3/howto/descriptor.html), which I don't fully understand myself though :laughing:

**Comment by lahwaacz** [comment]
Oh, thanks :+1:

**Comment by lahwaacz** [comment]
So I don't think that the problem is in keyinput anymore - removing the "component: keyinput" label. In #1817 I've done some refactoring and apply the auto-follow option even from `handle_partial_key`, which is the part that makes sense for all modes.
