### ISSUE TITLE
WolframAlpha gives 400 bad request

### ISSUE THREAD

**Issue by pmiddend** [The-Compiler/qutebrowser#1828]
When using WolframAlpha with any input, after a few seconds I get the following error page:

    Bad Request

    Your browser sent a request that this server could not understand.
    Size of a request header field exceeds server limit.
    Cookie: WR_SID=89.233.90.145.1470821474435700; wa_tr_session=91817967221140870000; JSESSIONID=239315FE0431908FFDBEA8841278BBD2; CookieWarning=nom; wa.randomInputs=%5B%22%7B%7B0%2C-1%7D%2C%7B1%2C0...

This does not happen with chrome or firefox.

`qutebrowser --version` gives `Git commit: v0.8.0-456-g83b15be (2016-08-10 09:53:41 +0200)`

**Comment by The-Compiler** [comment]
What Qt version does `qutebrowser --version` show? Can you reproduce it with `--temp-basedir`? Works fine here.

**Comment by pmiddend** [comment]
I cannot reproduce it with `--temp-basedir`. What does this option do? From the `--help` output, I don't really get it.

Full output of `qutebrowser --version`:

    qutebrowser v0.8.1
    Git commit: v0.8.0-456-g83b15be (2016-08-10 09:53:41 +0200)
    
    CPython: 3.4.5
    Qt: 5.6.1
    PyQt: 5.7
    
    sip: 4.18.1
    colorama: no
    pypeg2: 2.15
    jinja2: 2.8
    pygments: 2.1.3
    yaml: 3.11
    cssutils: no
    typing: no
    PyQt5.QtWebEngineWidgets: no
    pdf.js: no
    Webkit: 538.1
    Harfbuzz: old
    SSL: OpenSSL 1.0.2h  3 May 2016
    
    Platform: Linux-4.6.4-x86_64-Intel-R-_Core-TM-_i7-3630QM_CPU_@_2.40GHz-with-gentoo-2.2, 64bit
    Desktop: None
    Frozen: False
    Imported from /usr/lib64/python3.4/site-packages/qutebrowser
    OS Version:
    
    --- /etc/lsb-release ---
    DISTRIB_ID="Gentoo"

    --- /etc/gentoo-release ---
    Gentoo Base System release 2.2

    --- /etc/os-release ---
    NAME=Gentoo
    ID=gentoo
    PRETTY_NAME="Gentoo/Linux"

**Comment by The-Compiler** [comment]
`--temp-basedir` starts with an empty config/state/cache.

I'd guess it's something related to your settings then, or possibly cookies. Can you try quitting existing instances and then starting with `-c ""` to only have a fresh config?

**Comment by pmiddend** [comment]
With `-c ""` I cannot reproduce it.

I do have private browsing on. Shouldn't this delete all cookies on exit?

**Comment by The-Compiler** [comment]
That was the missing bit, I can reproduce it with private browsing turned on...

For some reason, with private browsing, qutebrowser tries to send a giant cookie to the server:

```
Cookie: WR_SID=[redacted]; wa_tr_session=[redacted]; JSESSIONID=[redacted]; CookieWarning=nom; wa.randomInputs=[5311 chars here]
```

Not sure what this is, and why it doesn't happen with private browsing turned off. Either way, this is an issue either with QtWebKit or with Wolfram Alpha, and I'm afraid there is nothing I can do about it. I suggest waiting for the new QtWebEngine backend, and turning private browsing off in the meantime if you want to use Wolfram Alpha.
