### ISSUE TITLE
Buffer command does not complete on id

### ISSUE THREAD

**Issue by Enzime** [The-Compiler/qutebrowser#1830]
When the `:buffer` completions are shown, typing in the numbers for the tab indices does not get completed.

**Comment by The-Compiler** [comment]
Hmm, do you think it should? Not sure if it's very useful.

**Comment by Enzime** [comment]
As a result of completions always being filtered as you type, because there are no completions on the tab indices, it makes it confusing typing a tab index, because if there are no completions on the tab indices then the tab index you were just typing might disappear as you were typing it.
