### ISSUE TITLE
Error `stack` property doesn't exist

### ISSUE THREAD

**Issue by edi9999** [The-Compiler/qutebrowser#1832]
With this simple html: 

index.html
```
<html>
<head>
</head>
<body>
  <script src="/foo.js"></script>
</body>
</html>
```

foo.js
```
a = new Error()
console.log(a);
console.log(a.stack);
```

In quteBrowser, this shows : 

```
Error {} foo.js:2
undefined foo.js:3
```

in chrome, we get : 

```
Error(…)
foo.js:3 Error
    at foo.js:1-
```

I'm using qutebroser master (commit 75bdd1f7971ae3eba724f0d9045d6a4871f3a944)

**Comment by The-Compiler** [comment]
That property is [non-standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack) so I'm guessing QtWebKit doesn't support it. It works with QtWebEngine though.
