### ISSUE TITLE
Custom file browser (for <input type="file">)

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1839]
The file browser used currently if you click on a file input dialog (`Browse...`) is very keyboard unfriendly, at least on my end.

Pentadactyl has an immensely useful file browser feature, where it uses the normal completion dialog to let you browse through files on your system. A replacement would be very cool.

On a side note, pentadactyl can also use it for the sake of directly opening files, e.g. say I have `~/dev/qutebrowser/tests/end2end/data/foo.html` and I want to look at how it looks - under pentadactyl I could literally just start typing `:open ~/dev/qutebrowser/` etc. and it would pop up completion along the way, and then open the file afterwards.

**Comment by The-Compiler** [comment]
Closing this in favor of #1365 and #32 - also see #1621 for a first completion approach.
