### ISSUE TITLE
Doesn't proprely display a html page

### ISSUE THREAD

**Issue by LaVolte** [The-Compiler/qutebrowser#1845]
Hi !

Qutebrowser doesn't properly show the attached html page. 

Other browser like Firefox/Chrome display it like it should be. 

[homepage.html.zip](https://github.com/The-Compiler/qutebrowser/files/413797/homepage.html.zip)

Qutebrowser 0.8.2.1 (community)
Archlinux  
Kernel : x86_64 Linux 4.6.4-1-ARCH

If you need more information let me know !

**Comment by The-Compiler** [comment]
This is a QtWebKit issue, but it displays correctly with the future QtWebEngine backend - you can check with `--temp-basedir --backend webengine`, but some features are still missing.

**Comment by LaVolte** [comment]
Thank you for you fast answer !
Indeed it's well displayed with the webengine backend.

The major problem is that every time I restart the browser it erase my
.conf and set the default one.

How can I fix that ?

I wish you a good day !

Nicolas.M

Le jeu. 11 août 2016 19:23, Florian Bruhin <notifications@github.com> a
écrit :

**Comment by The-Compiler** [comment]
Quit qutebrowser before editing the config, or simply use `:set` and `:bind` instead. I guess #499 will make your life easier in the not-so-distant future :wink:
