### ISSUE TITLE
Navigating with a count

### ISSUE THREAD

**Issue by pvsr** [The-Compiler/qutebrowser#1854]
It would be convenient to have `:navigate increment` and `decrement` take a count argument for the number to increment/decrement the url by. This would be useful for skimming through paged content a couple pages at a time, or even jumping to a specific page without having to edit the url directly. Obviously it would be consistent with vim's ctrl-a and ctrl-x behavior as well.

It would probably also be nice to make `:navigate up` take a count, but maybe that's a matter for a separate issue.

**Comment by The-Compiler** [comment]
This should be very easy to implement for `:navigate {increment,decrement,up}`, and a lot harder for `prev`/`next`.

**Comment by The-Compiler** [comment]
Implemented for `increment`/`decrement`/`up` in #1857 - I think it's rather complex for `prev`/`next`, so I'm closing this in the hope nobody wants it there :laughing:
