### ISSUE TITLE
Bindings with control ignore counts

### ISSUE THREAD

**Issue by blyxxyz** [The-Compiler/qutebrowser#1856]
For example, typing "3" and pressing Ctrl-PgUp only switches a single tab back, and doesn't clear the entered count. This is a problem for #1854.

**Comment by Enzime** [comment]
I was going to report this, I had made my own binding for `C-a` and noticed that it didn't work with counts.

**Comment by The-Compiler** [comment]
This should be properly solved as part of #319 some day.
