### ISSUE TITLE
Text panels don't respect system DPI

### ISSUE THREAD

**Issue by abbradar** [The-Compiler/qutebrowser#1869]
Configuration:

* OS: Linux, NixOS 16.09.git.09f67a7 (Flounder)
* DE: XFCE, with xmonad as WM
* qutebrowser: 0.8.2
* Qt: 5.6.1-1

Text panels (tabs panel and status panel) don't scale when system DPI is changed. Furthermore they don't change when `QT_AUTO_SCREEN_SCALE_FACTOR` is set, although the webpage is affected. High (correct) DPI is visible both in `xdpyinfo | grep dots` and in `xrdb -query | grep dpi`.

Screenshot with 175% zoom, compare fonts in `xfce4-appearance-settings` and `qutebrowser`:
![Screenshot](http://i.imgur.com/WwkewHk.png)

**Comment by abbradar** [comment]
Same page with `QT_AUTO_SCREEN_SCALE_FACTOR`:
[!Screenshot](http://i.imgur.com/V2NlSmj.png)

**Comment by abbradar** [comment]
One more thing just to give the full info: the size doesn't change when I change DPI (all other windows change on the fly, but these stay the same even after relogin).

**Comment by zuglufttier** [comment]
I cannot confirm this. If I change the dpi setting within KDE, qutebrowser changes the size of the fonts accordingly.

However, the scale factor set within QT will not change the size of the fonts but only the content of the web page.

**Comment by abbradar** [comment]
Interesting -- it doesn't work in XFCE for me. Maybe KDE change some value that qutebrowser doesn't use? FWIW I don't have this problem in any other application, but as we all sadly know there may be several incompatible sources for the same setting in Linux...

**Comment by abbradar** [comment]
I'm sorry, it seems that there is no bug, after all. Text panels _do_ increase their size, just a restart is needed and they are not scaled as much as I hoped them to (smaller than the rest of the system). This is another issue, though (and I haven't investigated yet but hope that I can just set font size in qutebrowser's config).
