### ISSUE TITLE
qutebrowser.app

### ISSUE THREAD

**Issue by pippocode** [The-Compiler/qutebrowser#1875]
Because installation in macos is a pain in the ass (like everything that ends with ".py"), please update https://qutebrowser.org/INSTALL.html page with the link to the app.

**Comment by The-Compiler** [comment]
I already [did that](https://github.com/The-Compiler/qutebrowser/blob/master/INSTALL.asciidoc#on-os-x) but forgot to regenerate qutebrowser.org - done now!

> Because installation in macos is a pain in the ass (like everything that ends with ".py")

I'd argue it's a pain because of Homebrew not packaging QtWebKit anymore, not because of Python :wink:
