### ISSUE TITLE
:debug-loglevel should change the log format

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1876]
#52 is implemented now, but doing `:debug-loglevel debug` should also switch to the debug output format. Seems like we can't change the format of an existing `logging.Formatter`, so we'd need to remove the existing one and add a new formatter.

**Comment by ryanjmortenson** [comment]
I have submitted at pull request for this #1881.

**Comment by The-Compiler** [comment]
@ryanjmortenson Thanks for the PR! I'm a bit busy currently, but I hope I'll get to reviewing it today or tomorrow.
