### ISSUE TITLE
Google New: Follow Link Problem with qtwebengine

### ISSUE THREAD

**Issue by rumpelsepp** [The-Compiler/qutebrowser#1882]
The recent HEAD has a problem with [google news](http://news.google.com) using the qtwebengine backend. Clicking on any link just expands the box and does not follow the links. One has to use the context menu to actually follow the provided links on google news. Can anybody confirm this issue?

I am on up to date archlinux; qutebrowser revision is: 2989875

**Comment by The-Compiler** [comment]
This is due to the JS `createWindow` method not being implemented yet, see #666. It's one of the next things I plan to do, but I won't get to much qutebrowser stuff in the next two weeks probably.
