### ISSUE TITLE
Focusing input fields in qute://settings does not enter insert mode

### ISSUE THREAD

**Issue by teto** [The-Compiler/qutebrowser#1883]
If you go to qute::settings then focus an option, qb doesn't enter insert mode.

```
qutebrowser v0.8.1
Git commit: v0.8.0-813-gbcb06f0 (2016-08-19 15:47:35 +0200)

CPython: 3.5.2
Qt: 5.5.1
PyQt: 5.5.1

sip: 4.17
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2g-fips  1 Mar 2016

Platform: Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
Desktop: i3
Frozen: False
Imported from /home/teto/qutebrowser/qutebrowser
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

--- /etc/os-release ---
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
UBUNTU_CODENAME=xenial

```

**Comment by lahwaacz** [comment]
From the config:

> auto-insert-mode (Bool):
    Whether to automatically enter insert mode if an editable element
    is focused after page load.

So this sounds like expected behaviour, since there is no focused editable element after `qute://settings` is loaded.

**Comment by teto** [comment]
If you focus the editable element of a setting like trying to set partial-timeout to 2000, I would expect to enter insert mode, shouldn't I ?

**Comment by The-Compiler** [comment]
What @teto describes is a default behaviour and doesn't depend on `auto-insert-mode` - and indeed I don't get insert mode after clicking elements on `qute:settings`.

To be fair, `auto-insert-mode` is a horrible name, as `auto-leave-insert-mode` actually *is* about clicking elements...

From the log:

```
20:34:18 DEBUG    misc       webelem:is_editable:275 Checking if element is editable: <qutebrowser.browser.webkit.webkitelem.WebKitElement html='<input type="input" onblur="cset(\'general\', \'ignore-case\', this)" value="smart">'>
20:34:18 DEBUG    mouse      mouse:_mousepress_insertmode_cb:152 Clicked non-editable element!
```

**Comment by lahwaacz** [comment]
Right - I've renamed the issue then.

**Comment by lahwaacz** [comment]
It seems that the `<input>` fields in `qute://settings` have `type="input"`, which is not in the list of supported attribute values: http://www.w3schools.com/tags/att_input_type.asp
