### ISSUE TITLE
AppVeyor rolling builds

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1894]
I think it would be useful to enable the [rolling builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds) on AppVeyor to not hold up the queue. The option should be [somewhere in the UI](https://github.com/appveyor/ci/issues/38#issuecomment-137943997).

**Comment by The-Compiler** [comment]
Hmm, I thought the settings in the web UI were always ignored when there's an `.appveyor.yml`, but I can't find a way to configure this in the YAML file.

I turned it on now, let's see if it works :wink:
