### ISSUE TITLE
Setting javascript-can-open-windows not respected

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#1896]
Hello.
The setting `javascript-can-open-windows` is not respected: JavaScript can still open windows after setting this setting to false.
I've fixed this issue and I will open a pull request.

**Comment by The-Compiler** [comment]
I can reproduce this with other QtWebKit browsers (like Otter) as well... No idea if there's anything we can do to fix this though, as we can't figure out why a window was opened with `createWindow`.

**Comment by antoyo** [comment]
Yeah, I saw the same issue with qupzilla.
I also tried to make a javascript file to set `Window.prototype.open` to `undefined` when the setting is activated, but for some reasons, it only worked on the first page load.
With this hack, the `Window.open` method was disabled on the first load, but if I reloaded the page or if I navigated to another page in the same window, the `Window.open` method was reset to its original version, even thought the script was still executed.

**Comment by The-Compiler** [comment]
So it turns out this setting is simply badly named in QtWebKit (and QtWebEngine), and is actually about opening JS windows without any user interaction. I renamed it to `javascript-can-open-window-automatically` now to reflect that.

**Comment by lahwaacz** [comment]
What does the "user interaction" really mean? Can you give a simple example where the option makes difference? Just trying to avoid incrementing the virtual counter of total hours wasted here :wink:

**Comment by The-Compiler** [comment]
Doing `window.open` as a response of clicking a button doesn't make a difference. Doing `window.open` via `jseval` (or probably in some other way via JS, without the user e.g. having clicked something) does.

**Comment by lahwaacz** [comment]
Thanks - so the engine somehow tracks user events in the code execution.
