### ISSUE TITLE
open-editor should work outside of insert mode

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1902]
`open-editor` should open the editor on whatever input field my cursor is in,
same as if I had done `enter-mode insert ;; open-editor ;; leave-mode`
instead.

It's not a big deal because you can currently just create precisely that
binding on your own, but there's still no technical reason to restrict it.

**Comment by The-Compiler** [comment]
This should probably be a matter of writing a test and removing the respective constraint.
