### ISSUE TITLE
Parts of webpages fail to use HiDPI on qutebrowser 0.8.1 (OS X 10.11.6)

### ISSUE THREAD

**Issue by sxmichaels** [The-Compiler/qutebrowser#1903]
Version info:
```
qutebrowser v0.8.1
Git commit: v0.8.1-1-gc94ed93 (2016-07-27 12:36:43 +0200)

CPython: 3.5.1
Qt: 5.6.1
PyQt: 5.6

sip: 4.18
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.4.20 (bundled)
Webkit: 538.1
Harfbuzz: system
SSL: Secure Transport, OS X El Capitan (10.11)

Platform: Darwin-15.6.0-x86_64-i386-64bit, 64bit
Desktop: None
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
OS Version: 10.11.6, x86_64
Failed to execute script __main__
```

Using qutebrowser 0.8.1 on OS X 10.11.6 (installed via Homebrew) on a Retina Mac, the browser interface itself is hi-DPI, but parts of certain webpages are not. I can't identify a consistent pattern of what works and what doesn't — but floating headers like those on NY Times and YouTube seem to be the most common. I've provided some sample images below, with a second version of each that highlight the hi-DPI (green) and normal-DPI (red) areas on the page.

<img width="842" alt="issue" src="https://cloud.githubusercontent.com/assets/13933679/18070093/3e7c793c-6e11-11e6-9906-7f9cc0f5b590.png">
<img width="842" alt="issue 2" src="https://cloud.githubusercontent.com/assets/13933679/18070095/41679032-6e11-11e6-8bfc-52ad21d62002.png">
<img width="839" alt="issue 3" src="https://cloud.githubusercontent.com/assets/13933679/18070097/444990de-6e11-11e6-8800-df87f27c305f.png">
<img width="839" alt="issue 4" src="https://cloud.githubusercontent.com/assets/13933679/18070098/47017a08-6e11-11e6-8ed8-d3365048f05c.png">

**Comment by The-Compiler** [comment]
Thanks for the great bug report! See #1678 - this is most likely a QtWebKit issue, which means there isn't really much I can do about it. It'll most likely be fixed with the future QtWebEngine backend, but that's currently unavailable on OS X due to #1692, but I hope I'll be able to take a look at that soon.
