### ISSUE TITLE
Missing anti-aliasing font on some page

### ISSUE THREAD

**Issue by wheatdog** [The-Compiler/qutebrowser#1904]
I found that fonts on google, hacker news and setting page aren't anti-aliasing.

![screenshot](https://cloud.githubusercontent.com/assets/7741908/18092365/9abf5168-6efe-11e6-8c5c-7b604147590d.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/7741908/18092366/9acafb94-6efe-11e6-90a6-5f4c6c07649d.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/7741908/18092410/c30feb78-6efe-11e6-9ca1-84d6b8ab9efb.jpg)

However, it seems ok on duckduckgo.

![screenshot2](https://cloud.githubusercontent.com/assets/7741908/18092446/e8b224cc-6efe-11e6-8eb4-cd360e872a5a.jpg)

Output of `qutebrowser --version`

```
qutebrowser v0.8.1
Git commit: v0.8.0-908-g6dace67 (2016-08-30 13:23:53 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Platform: Linux-4.7.2-1-ARCH-x86_64-with-arch, 64bit
Desktop: None
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
```

**Comment by The-Compiler** [comment]
See #1648 - this changed with some Qt upgrade (5.6 I think?) for some people, but I haven't been able to track it down so far.
