### ISSUE TITLE
Add :version command

### ISSUE THREAD

**Issue by B0073D** [The-Compiler/qutebrowser#1907]
Add :version command for quick access to version information.

Vim also has this.

**Comment by lahwaacz** [comment]
Vim has a way to display the output. AFAIK, qutebrowser doesn't.

**Comment by The-Compiler** [comment]
We discussed this in IRC for a bit - since "how do I show the version" is a common question (and you can't really know about `qute:version`), I think the easiest solution is to add such a command.

**Comment by lahwaacz** [comment]
Why yet another command when all you need is an alias (as I edited above)? Unless of course you'd like to show the info similarly to vim or pentadactyl.

**Comment by The-Compiler** [comment]
Discoverability. Even if `qute:*` URLs are documented (which they should be!), the question "what version am I running right now?" comes up from time to time and doesn't have an obvious answer (other than `qutebrowser --version`, that is)

**Comment by lahwaacz** [comment]
Well, a _default_ alias would do just that

**Comment by rcorre** [comment]
>  doesn't have an obvious answer (other than qutebrowser --version, that is)

Isn't `--version` obvious enough? That's the go-to answer for almost any application, except the weird ones (*cough* `ssh` *cough*).

**Comment by The-Compiler** [comment]
On a second thought, I guess `--version` is enough indeed. Seems like I wasn't the only one initially thinking that then, I just was convinced that I might be wrong :wink:
