### ISSUE TITLE
Add search history

### ISSUE THREAD

**Issue by julianuu** [The-Compiler/qutebrowser#1908]
I have not seen a way to repeat a recent text search. I like how it works in vim: when '/' is pressed one can get to the last searches by pressing arrow up.

**Comment by lahwaacz** [comment]
I think you can use the bindings for the `command-history-prev` and `command-history-next` commands, which are `<ctrl-p>` and `<ctrl-n>` by default.

**Comment by The-Compiler** [comment]
Nothing more to add to that :wink:

**Comment by julianuu** [comment]
I did not mean the internet search (with google or whatever), but the one that searches for a word on the currently displayed website, the one that can be done using `/`. I don't know how to use `ctrl-p` to get me to the last couple of searches of this kind.

**Comment by The-Compiler** [comment]
Search something, then press `/`, then press `ctrl-p` :wink:

**Comment by julianuu** [comment]
ah I see, thanks ;)
