### ISSUE TITLE
QtWebEngine JS not loaded with window.open()

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1911]
How to reproduce by hand, on the `webengine-createwindow` branch:

- `python3 -m http.server 1234` in `tests/end2end`
- `qutebrowser --debug --temp-basedir --backend webengine localhost:1234/data/hints/iframe_target.html`
- Click the link (for some reason it gets opened in a new tab, not in the iframe?)
- Use `f` on the opening page

When loading `hello.txt` normally the JS gets loaded though...

log:

```
08:34:55 DEBUG    mouse      mouse:_mousepress_opentarget:223 Normal click, setting normal target
08:34:55 DEBUG    webview    webenginetab:_js_cb_single:344 Got element from JS: {'outer_xml': '<a href="/data/hello.txt" target="my-iframe">link</a>', 'tag_name': 'A', 'text': 'link', 'attributes': {'target': 'my-iframe', 'href': '/data/hello.txt'}, 'rects': [{'width': 28.296875, 'top': 182, 'left': 24.03125, 'bottom': 201, 'height': 19, 'right': 52.328125}], 'id': 0}
08:34:55 DEBUG    misc       webelem:is_editable:275 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a href="/data/hello.txt" target="my-iframe">link</a>'>
08:34:55 DEBUG    mouse      mouse:_mousepress_insertmode_cb:152 Clicked non-editable element!
08:34:55 DEBUG    modes      modeman:maybe_leave:114 Not in mode KeyMode.insert! (leave reason: click)
08:34:55 DEBUG    webview    tabbedbrowser:tabopen:372 Creating new tab with URL None
08:34:55 DEBUG    webview    tabbedbrowser:_get_new_tab_idx:432 new-tab-position right -> opening new tab at 1, next left: 0 / right: 2
[...]
08:34:55 DEBUG    webview    webview:acceptNavigationRequest:143 navigation request: url http://localhost:1234/data/hello.txt, type NavigationTypeLinkClicked, target ClickTarget.normal, is_main_frame True
08:34:55 DEBUG    webview    browsertab:_on_link_clicked:600 link clicked: url http://localhost:1234/data/hello.txt, override target None, open_target ClickTarget.normal
[...]
08:34:55 DEBUG    webview    browsertab:_set_load_status:573 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='http://localhost:1234/data/hello.txt'>: LoadStatus.success
[...]
08:34:59 DEBUG    commands   command:run:514 command called: hint
08:34:59 DEBUG    commands   command:run:529 Calling qutebrowser.browser.hints.HintManager.start(<qutebrowser.browser.hints.HintManager object at 0x7f338a029f78>, False, <Group.all: 1>, <Target.normal: 1>, mode=None, win_id=0)
08:34:59 DEBUG    modes      modeman:_eventFilter_keypress:194 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: None)
08:34:59 ERROR    js         webview:javaScriptConsoleMessage:122 [:2] Uncaught TypeError: Cannot read property 'webelem' of undefined
08:34:59 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginetab.py", line 331, in _js_cb_multiple
    for js_elem in js_elems:
TypeError: 'NoneType' object is not iterable

```

**Comment by The-Compiler** [comment]
FWIW the iframe opening in a new tab is [a Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=135498) :laughing:

**Comment by The-Compiler** [comment]
This is pretty likely to be [QTBUG-54419](https://bugreports.qt.io/browse/QTBUG-54419) - currently rebuilding with a patch to verify that.

It also affects user stylesheets in QupZilla, and I'm really not sure what to do now - all options kind of suck :cry:

- Raise requirements for QtWebEngine to Qt 5.6.2/5.7.1 which both aren't even released yet
- Don't support `createWindow` in older Qt versions, but continue to run
- Don't support hinting/insertmode on click/scroll position etc. in windows opened via `createWindow` (more effort, as everything calling into JS code needs to be aware of this possibility)
- Stop using QWebEngineScript and have less organized javascript files (because we always need to send the full file when calling into JS)
- Use `runJavaScript` to set up the JS functions, but I couldn't get that to work reliably...

**Comment by DarkDefender** [comment]
I think you should keep it as it is until the new QtWebEngine version is out. The webengine backend is still experimental and not stable, right? So I would just wait until 5.7.1 in available and then just bump the required version then. No need to spend time on creating workarounds when it will be fixed in the next point release.

**Comment by The-Compiler** [comment]
So now qutebrowser simply displays an error message when opening windows via JS, unless it's on Qt 5.6.2+ or 5.7.1+.

You can also set `QUTE_QTBUG54419_PATCHED=1` and use my [`qt-debug` packages](https://github.com/qutebrowser/qt-debug-pkgbuild) where the patch is backported. Note that I'll ignore any crash reports with that set if I suspect no debug packages are installed :laughing:

**Comment by FLHerne** [comment]
I see the error message when using middle-click to open (standard, non-JS) links in a new tab.

That (still) appears to work as normal, the message seems like a false alarm.

**Comment by The-Compiler** [comment]
Hmm, right - seems like `createWindow` is called before `acceptNavigationRequest`, in two different cases:

- Chromium handles the link (`window.open`, frames, etc.)
- We handle the link (clicked to open in a new window/tab)

In the first case, this issue happens, but in the second case, it doesn't. Unfortunately, since `createWindow` happens *before* we get to decide who handles the request, there's no way I can see to tell the two apart.

I now removed the error message entirely, which means javascript windows will silently do nothing again. Seems like the least bad solution right now :wink:
