### ISSUE TITLE
"Running without the SUID sandbox!" error when using webengine

### ISSUE THREAD

**Issue by craftyguy** [The-Compiler/qutebrowser#1914]
I see this error when running the latest qutebrowser from git with the webengine backend:

```
$ qutebrowser --backend webengine                                                     
[0902/211430:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
```

It basically hangs after that and never proceeds to run.

```
$ qutebrowser --version                                                              
qutebrowser v0.8.1
Git commit: v0.8.0-940-g64b3980 (2016-09-02 19:13:37 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Platform: Linux-4.7.2-1-ARCH-x86_64-with-arch, 64bit
Desktop: None
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
```

**Comment by The-Compiler** [comment]
That error message is actually [harmless](https://bugreports.qt.io/browse/QTBUG-54225) and got suppressed in Qt 5.7.1 (Chromium also [removed it](https://bugs.chromium.org/p/chromium/issues/detail?id=598454)).

So the question is why nothing actually happens for you - do you ever see a qutebrowser window, or nothing at all?

**Comment by craftyguy** [comment]
I think it was something with my session but not sure what.. it seems to load find now though after whatever page that was in my previous session is no longer there. Sorry I can't provide any more info than "it's now magically fixed after my session was cleared away" :(
