### ISSUE TITLE
"Error while reading key config"

### ISSUE THREAD

**Issue by TheGag96** [The-Compiler/qutebrowser#1915]
I just pulled the repo to update the browser, and I get a popup with this error on startup:

```
Error while reading key config:
: Duplicate key chain <crtl-pgdown>
```

I've done no keybinding editing since I first installed the browser (on Debian x64, btw)... Was there a change to the default config that could have broke existing installs?

**Comment by The-Compiler** [comment]
Yeah, something went wrong there - see #1835.
