### ISSUE TITLE
script successful in shell, hangs in qutebrowser

### ISSUE THREAD

**Issue by noahrama** [The-Compiler/qutebrowser#1920]
```
qutebrowser v0.8.2
Git commit: 

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2h  3 May 2016

Platform: Linux-4.7.1-1-ARCH-x86_64-with-arch, 64bit
Desktop: None
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
```
**When i run the following code from a terminal, it exits successfully. When i run the code from Qutebrowser, it is successful on the first run (downloads the video) but hangs on the second (video in filesystem already)**

```
#!/bin/bash

myfile=$HOME/.youtube_buffer

if [ ! -e "$myfile" ] ; then 
    touch "$myfile"
fi

dunstperc(){

    while true; do


        if grep "\[download\] 100.0%" < "$myfile" ; then 
            break
        fi

        if grep "downloaded and merged" < "$myfile" ; then # < --- here!
            break
        fi

        sleep 1
    done
}

dunstperc &

youtube-dl --newline https://www.youtube.com/watch?v=oSYZekLljpg 1> "$myfile"

```
**any ideas as to why this might be?**

**Comment by The-Compiler** [comment]
As mentioned in IRC, I can't see why the behavior in qutebrowser would be different from what you get in the shell.

Some questions:

- Do you wait for the first run to be finished before starting the second one?
- How do you figure out it's hanging there?

**Comment by noahrama** [comment]
i was using notifications, like such.
`while true; do

        dunstify "Downloading" "$(tail -n1 "$myfile" | awk '{ print $2 }')"  -r 101 -h string:fgcolor:\#ffffff -h string:bgcolor:\#E6261C

        if grep "\[download\] 100.0%" < "$myfile" ; then 
            dunstify   "Done" ""  -r 101 -h string:fgcolor:\#ffffff -h string:bgcolor:\#E6261C 
            rm "$myfile" 
            break
        fi

        if grep "downloaded and merged" < "$myfile" ; then # < --- here!
            dunstify   "Already in Filesystem" ""  -r 101 -h string:fgcolor:\#ffffff -h string:bgcolor:\#E6261C 
            rm "$myfile" 
            break
        fi
`
Yes i wait for one to end before starting the next one. program is stuck in endless loop for some reason and its only when i use qutebrowser to launch

**Comment by The-Compiler** [comment]
So I just tried this based on your previous posts:

```bash
#!/bin/bash

myfile=$HOME/.youtube_buffer

if [ ! -e "$myfile" ] ; then 
    touch "$myfile"
fi

dunstperc(){

    while true; do
        dunstify "Downloading" "$(tail -n1 "$myfile" | awk '{ print $2 }')"  -r 101 -h string:fgcolor:\#ffffff -h string:bgcolor:\#E6261C

        if grep "\[download\] 100.0%" < "$myfile" ; then 
            dunstify   "Done" ""  -r 101 -h string:fgcolor:\#ffffff -h string:bgcolor:\#E6261C 
            rm "$myfile" 
            break
        fi

        if grep "downloaded and merged" < "$myfile" ; then # < --- here!
            dunstify   "Already in Filesystem" ""  -r 101 -h string:fgcolor:\#ffffff -h string:bgcolor:\#E6261C 
            rm "$myfile" 
            break
        fi
    done
}

dunstperc &

youtube-dl --newline https://www.youtube.com/watch?v=oSYZekLljpg 1> "$myfile"
```

and it runs fine from me both inside qutebrowser and outside of it. What's the situation with the exact same script for you?

(Also, please use three backticks on their own line before/after source code, so GitHub renders it correctly)

**Comment by noahrama** [comment]
It is working now!!!
