### ISSUE TITLE
Ability to change file chooser

### ISSUE THREAD

**Issue by Zekario** [The-Compiler/qutebrowser#1924]
Choosing a file (i.e. when uploading) brings up the Qt file chooser dialog. The option to change this to the GTK file chooser (that Firefox uses by default) would be nice, as it may be easier to use/more familiar to some people.

**Comment by haasn** [comment]
Good luck using the GTK file chooser in a Qt program

IMO it would be more important to make sure we have a good command-line based file browser (like pentadactyl's) available.

**Comment by The-Compiler** [comment]
As @haasn mentioned, using the GTK filepicker from Qt won't be possible :wink:

I agree having a filepicker with qutebrowser's completion would be best - see #32, #1365 and #1621 for some related issues.

**Comment by Migacz85** [comment]
For me it would be best just to ctrl+v path to the file in qutebrowser "shell", instead of this. I'm using ranger to locate the filepath. And with the current file picker I'm stuck.
