### ISSUE TITLE
better/alternative hinting system

### ISSUE THREAD

**Issue by spiderbit** [The-Compiler/qutebrowser#1929]
So I have some small issues with the hinting system of qutebrowser, first I partialy welcomed it, cause using only the homerow for selecting links has some advantages, so you dont have to move your hand/fingers to much IF you have them on the home row.

Of course with limiting the chars in the settings you could also use a onehand version or a number version I guess.

So if you are just browsing a bit besides doing other non-computer work you could get away, but that system is then not so flexible you have either the one usecase covered or the other.

I used before this browser the conkeror browser, and I use emacs which has also a fuzzysearch based command and file searcher.

So in conkeror you have a dynamic 2-tier mixed hint/search system, what does that mean:

1. you have numbers behind your links on the site
2. you can narrow the availible links with typing the link-TEXT

you can use only one of them:
1. press number 54 for link XY <enter> Done
2. press a substring on the website of a link you like, on this site as example "gist" <enter> and go there.

Or you can mix it, lets say you have youtube search with 50 links, 3 of them have in the name Caster_XY and you want the 2nd of them:

Type "XY" "2" <enter>

This has several advantages:
- I dont have to parse the sometimes difficult to read hint letters 
- you can choose if you have lets say a mug in the hand, to type with one hand the numbers and if you have your hands on the keyboard use words
- people are faster in typing words than they are in typing a few letters that are no word
- people on the internet, or on most desktops are used to use search engines non stop, your first thoughtprocess is this video from XY is what I want, not I want the letters aaso (I use dvorak so thats on the home row) . thats a unnessesary additional step to map the video name to a letter combination that has nothing to do with the video.

Also that system has a additional advantage, pressing 0 selects the current location, if you want to follow a link that makes no sense but for many scripts that make a sense to start a action on a current url.

Of course there are shure other ways to seperately cover this, but its a pretty good way to do that in one mechanism. 

as example I have a fuction (implemented externaly but I can call it from within conkeror and qutebrowser) to send a selected youtube url (the video link of it) to my kodi machine, in conkeror I can select a linked video or the current url, with the same hint command, in qutebrowser I have to go back to the side where the current url is linked to use this mechanic or paste the url around. Of course I could also create a seperate command for the current url but its another command to remember to code in, and I see no benefit in it.

Again I just see the fuzzy search of emacs (smex) as very powerful feature, and navigating using hints are not so much limited about the keys you have to press or if you have to press 1 or 2 keys that are not in the homerow, its more limited by your brain, how fast and naturaly can I START typing. how much reading and how FAST can you type in that letters, not how many letters are there.

Maybe my mind works differently, but I am constantly looking for uniqueness of stuff, when I want to select them, and if I am tired or somethnig I have the fallback with numbers. I think thats a very dynamic system that fits your needs in every mindset you might be.

And I dont say replace the old system, but give that system maybe as alternative?

even to yank the link of a refering page not with the hint system is at least unusual for me, and because each window of conkeror is a different instance copy& paste does not work aperently, so I cant add a link to the system.

**Comment by The-Compiler** [comment]
Apart from the thing with `0`, sounds like `:set hints mode number` is what you want?

**Comment by spiderbit** [comment]
1. you are a fast reader :)
2. mode number would not give me a mixed search system I think? So I can then use numbers, but not hint by link-texts?

**Comment by The-Compiler** [comment]
You can filter links based on text, like you described. Otherwise there would be no point in having two different modes, you could just set `hints -> letters` to `0123456789` :wink:

**Comment by spiderbit** [comment]
wow you are right, thats close.

So then there are 2 limitations:

1. letter 0 does not work like you said
2. if I press enter, it does not follow the number 1 link, which makes sense for me :) and conkeror does it that way, btw also emacs does it that way, if you can compare this command/file searcher.
3. it does not highlight the link you would get if you press enter
4. if I try to type in "comment" to send this commentary, it does not work. it only works for links but not buttons.

**Comment by lahwaacz** [comment]
If the hints are numbered starting with 0, as is the current state, then 0 can't be used for any special purpose. I don't understand what "pressing 0 selects the current location" means, but you should probably start a new issue about that.

For 2. and 3. see #219 and #1305.

About 4., obviously `:hint links` works only for links, but `:hint all` works also for buttons.

**Comment by spiderbit** [comment]
thanks for clearifying 4.

to the current location I talk about the current url the link to the site I am on at the moment. Of course you can use "yank" for that but having one shortcut to send urls to some command instead of 2 kind of makes sense to me. also yank is ok for copying the current location but lets say you have 20 scripts that do stuff with a given url.

you would have to have 40 shortcuts for it instead of 20. just to cover the current url. so conkerors solution scales better I think?

But I can make up a new bug report for this

**Comment by lahwaacz** [comment]
Oh, now I get the intention for 0! That's an interesting idea, thanks for creating the issue for it.

As all missing functionality mentioned here seems to have their own separate issue, I'll close this one.
