### ISSUE TITLE
Some things :hint does not find

### ISSUE THREAD

**Issue by julianuu** [The-Compiler/qutebrowser#1932]
When I go there https://www.uni-bonn.de/studium/im-studium/studienorganisation/termine-und-fristen and follow 'Einschreibefristen' then I can't open those bullets 'für grundständige Studiengänge...' etc using `:hint`.

Something similar on https://www.ebay-kleinanzeigen.de. When I search for something, I cant select the sorting button which says 'Neueste zuerst' via `:hint`.

**Comment by The-Compiler** [comment]
This is because those are all not actually links, but `<span>`/`<div>` elements with JS click handlers attached, which qutebrowser doesn't detect yet. I added them to #178.
