### ISSUE TITLE
completion with 'space' seems broken

### ISSUE THREAD

**Issue by apm256** [The-Compiler/qutebrowser#1934]
For instance, when I hit `o` then enter "qute mast", "https://github.com/The-Compiler/qutebrowser/commits/master" does not match anymore.

Git commit: v0.8.0-1087-g861ce47 (2016-09-07 20:26:41 +0200)

**Comment by The-Compiler** [comment]
Indeed, looks like I accidentally broke that in faa052ad6f2b04afcf5bc8bb3d1481c8f74a5d6d - thanks!

**Comment by apm256** [comment]
Thanks! Nevertheless, I've just tested the latest commit, and the problem seems to persist.
"qute  browser" matches "qutebrowser", but "qute rowser" does not match anything.

**Comment by The-Compiler** [comment]
Hmm, indeed! I'll take a closer look soon, unless someone else wants to - @rcorre @lahwaacz @mlochbaum? :wink:

At least the pattern looks correct to me now...

**Comment by lahwaacz** [comment]
It should be `re.sub(r'(\\ )+', r'.*', val)` (escaped backslash and parentheses to match repeated pair instead of backslash followed by multiple spaces).

**Comment by The-Compiler** [comment]
Let's hope this is finally squashed now :laughing: Thanks @apm256 for the report and @lahwaacz for the help!

**Comment by apm256** [comment]
Now, it works perfectly well! Thanks to all.
