### ISSUE TITLE
Include data/config/cache/runtime paths in qute:version output

### ISSUE THREAD

**Issue by dnebauer** [The-Compiler/qutebrowser#1947]
The `qute:version` command already includes a great deal of useful runtime information. It would help users wanting to use userscripts if `qute:version` output included the userscript directory path.

In that way the userscripts documentation would not have to explicitly list the userscripts directories for all platforms, but could instead direct users to the `qute:version` command.

**Comment by The-Compiler** [comment]
FWIW `qute:version` probably should show some other useful paths while we're at it :wink:

**Comment by The-Compiler** [comment]
@dnebauer Do you think it'd suffice to display the config/data/cache/runtime directories? With that, "it needs to be stored in your data directory" should be clear enough, no?

**Comment by dnebauer** [comment]
That should do it.

**Comment by dnebauer** [comment]
Do not see data/config/cache/runtime paths in qute:version output in windows 0.8.4. Here is the output of that command:
```
qutebrowser v0.8.4
Git commit: v0.8.4 (2016-11-06 00:44:24 +0100)

CPython: 3.4.3
Qt: 5.5.1
PyQt: 5.5.1

sip: 4.17
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: 1.0.1 $Id$
typing: no
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.5.188 (bundled)
Webkit: 538.1
Harfbuzz: system
SSL: OpenSSL 1.0.1i 6 Aug 2014

Platform: Windows-7-6.1.7601-SP1, 64bit
Desktop: None
Frozen: True
Imported from C:\Program Files\qutebrowser\library.zip\qutebrowser
OS Version: 7, 6.1.7601, SP1, Multiprocessor Free
```
Same output from command line: `qutebrowser --version`

**Comment by The-Compiler** [comment]
@dnebauer v0.8.4 is a patch release, containing bugfixes on top of v0.8.x only. You'll see this appearing in v0.9.0.
