### ISSUE TITLE
Default Search Engine Disallows Search String Containing URL

### ISSUE THREAD

**Issue by NoSuck** [The-Compiler/qutebrowser#1954]
Example:

`:open site:cookies.com oatmeal raisin`

This search fails, as qutebrowser asks for an "external application for site-link" with a URL of "site:cookies.com".  Perhaps qutebrowser should check for spaces in the search string, which would indicate search terms and not a URL.

As a temporary workaround, "site:cookies.com" may be placed at the end of the search string.

qutebrowser v0.8.1
Git commit: v0.8.0-1123-g4c55963 (2016-09-10 17:32:04 +0200)

**Comment by The-Compiler** [comment]
That was an easy fix :wink:
