### ISSUE TITLE
Bitmapped fonts are picked over scalable ones

### ISSUE THREAD

**Issue by arsv** [The-Compiler/qutebrowser#1959]
With empty strings for `web-family-*` in qutebrowser.conf, the browser renders some sites including www.google.com and reddit.com in ugly bitmapped font.

This only happens with xorg-fonts-100dpi installed (Arch packages) and neither Verdana nor Arial available. *Removing xorg-fonts-100dpi resolves the issue immediately*.

Taking Reddit for example, Chromium shows computed font family as "verdana, arial, helvetica, sans-serif". Output of `fc-list | grep -i $font` for relevant $font values:

* verdana: nothing
* arial: nothing
* helvetica: ... /usr/share/fonts/100dpi/helvR24-ISO8859-1.pcf.gz: Helvetica:style=Regular ...
* sans-serif: nothing (as expected)

Output of `fc-match $font`:

* arial: Arimo-Regular.ttf: "Arimo" "Regular" (from `ttf-croscore` which I have installed)
* verdana: DejaVuSans.ttf: "DejaVu Sans" "Book"
* helvetica: helvR08-ISO8859-1.pcf.gz: "Helvetica" "Regular"
* sans-serif: DejaVuSans.ttf: "DejaVu Sans" "Book"

A crude check using xfontsel and xmag confirms that qutebrowser chooses bitmapped Helvetica to render the page, despite much better fonts being available.

I did not go any further yet, but a wild guess is that Arimo and DejaVu Sans get discarded as substitutes (the name does not match what was requested) while Hevetica is deemed a good match. Or alternatively, qutebrowser falls back to something similar to fc-list to find out which fonts are available.

No ideas yet how to fix it, just an info dump for now.
I think trying to detect bitmapped fonts and skipping them altogether may be an option, or trying less-than-perfect scalable matches first.

qutebrowser v0.8.2
Git commit: 
CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7
Webkit: 538.1
Platform: Linux-4.7.2-1-ARCH-x86_64-with-arch, 64bit

**Comment by The-Compiler** [comment]
Apart from setting other defaults for those settings (which comes with their own problems I guess) there is nothing I can do to influence font selection, this is all handled by Qt.

Closing this in favour of #1648 for now, as that seems to be the more actionable issue.
