### ISSUE TITLE
Can't use space for keybindings

### ISSUE THREAD

**Issue by wachambo** [The-Compiler/qutebrowser#1961]
Can't use ```space``` for a keybindig.

I do:
```
<unbound>
     
tab-focus 1
     1

tab-focus 2
    <space>2
```
The line after ```<unbound>``` is **five** spaces: **four** spaces for the usual indentation + **one** space as a literal space to say that any existing ```<space>``` binding should be unbound.

Similarly, the line below the ```tab-focus 1``` command is **five** spaces + **one** space, to signify a <space>1 keybinding. 

The problem is that after pressing ```<space>1``` or ```<space>2```, it does work: does not select neither first tab nor second tab.

```
% qutebrowser --version
qutebrowser v0.8.2
Git commit: 

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7
```

Thank you for your outstanding work

**Comment by vyp** [comment]
#1120

**Comment by The-Compiler** [comment]
Closing this as a duplicate then :wink:
