### ISSUE TITLE
Document how to use .netrc

### ISSUE THREAD

**Issue by haasn** [The-Compiler/qutebrowser#1975]
This seems to be an undocumented feature of qutebrowser, and I also can't figure out how to make it work (without looking at the code).

**Comment by takugt** [comment]
Hello haasn, 
I have 5k imac and I start to use mpv player.
I have read this thread https://github.com/mpv-player/mpv/issues/1563 and I wanted to download the BT.709 color profile with a gamma of 2.4 (I think the original have a gamma of 2.2) at this 
adress http://www.nand.wakku.to/bt709/bt709-gamma2.4.icc but the page is no longer work.
Please , can you make it avalaible in order I download it.
I know it is not the subject of this tread so sorry.

Thanks
