### ISSUE TITLE
:zoom-* commands' output stack on one each other

### ISSUE THREAD

**Issue by sim590** [The-Compiler/qutebrowser#1980]
**Observed behavior**
When hitting the zoom key, the consecutive status messages stack on one each other.

**Expected behavior**
Messages should replace the last one on the same height.

**Version info**

```
qutebrowser v0.8.1
Git commit: v0.8.0-1311-g05dddf4 (2016-09-26 15:43:13 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.2.109 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2h  3 May 2016

Platform: Linux-4.7.4-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version:

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
```

**Comment by The-Compiler** [comment]
This is intended, all messages stack now. I'm not really convinced this should be different for zoom messages to be honest...

**Comment by sim590** [comment]
Although I understand the motivation behind stacking messages, pressing `ctrl-+` 3-4 times becomes quickly annoying for the eye.

**Comment by haasn** [comment]
Agree, this is annoying rather than beneficial. Either the zoom messages should inherently replace themselves somehow (e.g. perhaps only display one of each message “kind” at once?) or the stacking should be toggleable (i.e. have every message overwrite the previous one)

**Comment by The-Compiler** [comment]
I don't think it's a good idea to turn off stacking in general as you might "lose" earlier error messages when more than one is displayed (the old code dealed with that via a message queue with a timeout, but bringing messages resulting from direct user input to the front).

Marking some messages (like the zoom ones, and maybe more in the future?) as replaceable, and then a replaceable message not stacking if there was no other message in between sounds like a nice solution.

**Comment by abbradar** [comment]
This is very painful when using mouse wheel -- especially if you play around trying to find "right" zoom size with it. Messages quickly take up to half of screen size...

**Comment by The-Compiler** [comment]
I'll have to agree :wink: Also adding the easy label as it shouldn't be very hard to fix this. It'll probably take a bit until I get to it though, so contributions would be very welcome! And as always, I'm happy to help if there's an issue.
