### ISSUE TITLE
Private-Browsing Indicator in Statusbar

### ISSUE THREAD

**Issue by wohfab** [The-Compiler/qutebrowser#1985]
Is there any way to indicate the status of `private-browsing` inside the status bar?

**Comment by The-Compiler** [comment]
There currently isn't - I'd like to have a generic way of showing a setting in the statusbar, see #1052 (especially https://github.com/The-Compiler/qutebrowser/issues/1052#issuecomment-246557721) and #30.

For private browsing specificially, that might be revamped for QtWebEngine anyways (as part of #666) so you can open an icognito window similar to how that works in other browsers.

**Comment by The-Compiler** [comment]
The thing I talked above has now been implemented, see #2615.
