### ISSUE TITLE
Can't yank Qt codereview URL

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#1987]
When I'm on [this page](https://codereview.qt-project.org/gitweb?p=qt/qtbase.git;a=patch;h=b3b8b1a4b4623b344f3e50644d4b662a572ec139) I can't yank the URL in a format e.g. wget understands, because the `=` get converted to `%3D`, even with `:yank pretty-url`.

**Comment by lahwaacz** [comment]
`:yank pretty-url` decodes the first `=`, but not the other, which are attributed a special meaning. The problem is that the URL uses `;` instead of `&` as a separator in the query string.

FWIW, both curl and wget understand the fully-encoded URL:
```
$ curl -O "https://codereview.qt-project.org/gitweb?p=qt/qtbase.git;a%3Dpatch;h%3Db3b8b1a4b4623b344f3e50644d4b662a572ec139"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43590    0 43590    0     0  14466      0 --:--:--  0:00:03 --:--:-- 14472
```

**Comment by The-Compiler** [comment]
Sorry, I wasn't specific enough there - they understand the URL, but they load the index page and not the patch file I get when opening the URL in qutebrowser.

**Comment by HolySmoke86** [comment]
Changing the `=` to `%3D` after the `?` changes the meaning of the URL, what separator is used does not matter.

**Comment by HolySmoke86** [comment]
The modification is introduced in browser/commands.py:685-689 to support the general->yank-ignored-url-parameters option.
