### ISSUE TITLE
Spawn command on Windows

### ISSUE THREAD

**Issue by wohfab** [The-Compiler/qutebrowser#1992]
Is there a way to use the `spawn` command on Windows (10)?

I'd like to use the _Open-Video-in-App_-functionality which is stated in the FAQ.

Right now I get `Error while spawning command: The process failed to start.`.

**Comment by The-Compiler** [comment]
What exactly is the command you're using? Spawning an `.exe` or `.bat` file should work just fine.

**Comment by wohfab** [comment]
in my `keys.conf`: `hint links spawn vlc.exe {hint-url}`

but `:spawn vlc.exe` gives the same error.

**Comment by The-Compiler** [comment]
Is `vlc.exe` in your path? Can you run `vlc` inside `cmd.exe`?

**Comment by wohfab** [comment]
It is in my path and can be run via `cmd`.

**Comment by The-Compiler** [comment]
Can you also run `vlc.exe` there? Do you happen to have a separate Python install ready? I'd wonder what `python -c "import subprocess; subprocess.check_call('vlc.exe')"` says.

**Comment by wohfab** [comment]
`vlc.exe` runs there, yes.

I have an Anaconda installation, I think. 

`python -c "import subprocess; subprocess.check_call('vlc.exe')"` gives me a `FileNotFoundError`.

**Comment by The-Compiler** [comment]
Does `:spawn notepad.exe` work? What does `where vlc.exe` in `cmd.exe` say? Are those files actually executable files, or some kind of wrappers?

**Comment by wohfab** [comment]
`:spawn notepad.exe` is working. But `where vlc.exe` doesn't find anything.

**Comment by wohfab** [comment]
Okay, it worked out. I am dumb - sorry and thanks for your time!

I hadn't restarted my computer in a week or so. So the `PATH` changes were not set.

Sorry again :+1:
