### ISSUE TITLE
Github copy-to-clipboard button does nothing

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#1995]
Go to any github repo, click the 'Clone or download' dropdown, and click the 'copy to clipboard' button to the right of the remote url (using hints or the mouse). Nothing happens.

Tested on 0.8.2 and master with webengine and webkit.
It does work with Chromium.

**Comment by The-Compiler** [comment]
This should be implemented in QtWebEngine with https://codereview.qt-project.org/#/c/161263/ which I think wasn't part of 5.6.1. I don't expect it to be implemented in QtWebKit :wink:

**Comment by raj-magesh** [comment]
Recent regression, according to [this Reddit thread](https://www.reddit.com/r/qutebrowser/comments/vh25sc/do_copy_text_buttons_work_consistently_for_you/)
