### ISSUE TITLE
[webengine] QT_SCREEN_SCALE_FACTORS does not work with fractions, 1.5 e.g.

### ISSUE THREAD

**Issue by zuglufttier** [The-Compiler/qutebrowser#1996]
I start qutebrowser with the following command:

`QT_SCREEN_SCALE_FACTORS=eDP1=1.5; qutebrowser --backend webengine`

This results in the following screenshot: https://i.imgur.com/Fct3n6e.png

If the scale factor is set to 1 or 2 everything is working as expected.

**Version info**

qutebrowser v0.8.1
Git commit: v0.8.0-1336-g80b5c91 (2016-09-29 10:59:32 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: Breeze::Style
Platform: Linux-4.7.5-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

Paths:
config: /home/zlt/.config/qutebrowser
cache: /home/zlt/.cache/qutebrowser
download: /home/zlt/Downloads
system_data: /home/zlt/.local/share/qutebrowser
data: /home/zlt/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
From http://doc.qt.io/qt-5/highdpi.html#issues-with-high-dpi:

> Note: Non-integer scale factors may cause significant scaling/painting artifacts.

So this is simply not supported by Qt.
