### ISSUE TITLE
GitHub rich text buttons don't work

### ISSUE THREAD

**Issue by JonathanReeve** [The-Compiler/qutebrowser#2000]
To reproduce: 

1. Go to GitHub.com
2. Open a new issue
3. Paste some code. 
4. Select the code
5. Try to press the "code" button to mark the code as such 
6. Notice that nothing happens
7. Repeat with other buttons

**Comment by JonathanReeve** [comment]
Version info: 

qutebrowser v0.8.1
Git commit: v0.8.0-1311-g05dddf4 (2016-09-26 15:43:13 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.5.188 (/home/jon/.local/share/qutebrowser/pdfjs/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2i  22 Sep 2016

Style: QFusionStyle
Platform: Linux-4.7.4-1-ARCH-x86_64-with-arch-16.9-ISO-Rolling, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/arch-release ---
Antergos Linux release 16.9 (ISO-Rolling)

--- /etc/os-release ---
NAME="Antergos Linux"
VERSION="16.9-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:16.9"

**Comment by JonathanReeve** [comment]
Version info: 

qutebrowser v0.8.1
Git commit: v0.8.0-1311-g05dddf4 (2016-09-26 15:43:13 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.5.188 (/home/jon/.local/share/qutebrowser/pdfjs/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2i  22 Sep 2016

Style: QFusionStyle
Platform: Linux-4.7.4-1-ARCH-x86_64-with-arch-16.9-ISO-Rolling, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/arch-release ---
Antergos Linux release 16.9 (ISO-Rolling)

--- /etc/os-release ---
NAME="Antergos Linux"
VERSION="16.9-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:16.9"

**Comment by JonathanReeve** [comment]
Version info: 

qutebrowser v0.8.1
Git commit: v0.8.0-1311-g05dddf4 (2016-09-26 15:43:13 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.5.188 (/home/jon/.local/share/qutebrowser/pdfjs/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2i  22 Sep 2016

Style: QFusionStyle
Platform: Linux-4.7.4-1-ARCH-x86_64-with-arch-16.9-ISO-Rolling, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/arch-release ---
Antergos Linux release 16.9 (ISO-Rolling)

--- /etc/os-release ---
NAME="Antergos Linux"
VERSION="16.9-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:16.9"

**Comment by JonathanReeve** [comment]
Sorry for the multiple comments--it looks like the GitHub "comment" button doesn't work on Qutebrowser, either.

**Comment by The-Compiler** [comment]
GitHub breaks with the QtWebKit backend when you set the useragent to something non-default. With the default user-agent, everything should work fine. Nothing I can do about that, but it'll be fixed with the new backend as well.

(Also, congrats on issue #2000 I guess :laughing:)
