### ISSUE TITLE
Neither QtWebKit nor WebEngine renders Nullchan sites properly.

### ISSUE THREAD

**Issue by tidux** [The-Compiler/qutebrowser#2005]
[Nullchan](https://github.com/Nullchan/nullchan) is software for hosting imageboards on [ZeroNet](https://github.com/HelloZeroNet/ZeroNet).  Due to the nature of ZeroNet there's a lot of WebSockets magic going on under the hood, so I don't expect this will ever get fixed in QtWebKit.  The sites work in Chromium, so I suspect it's not an upstream issue with Blink or QtWebEngine.

qutebrowser v0.8.1
Git commit: v0.8.0-1347-gcd17433 (2016-10-01 22:51:58 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.7.4-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/arch-release ---
Arch Linux release

Paths:
config: /home/tidux/.config/qutebrowser
cache: /home/tidux/.cache/qutebrowser
data: /home/tidux/.local/share/qutebrowser
download: /home/tidux/Downloads
system_data: /home/tidux/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
What does "does not render properly" mean exactly? How can I easily reproduce this?

**Comment by tidux** [comment]
Install ZeroNet, get it running on your test machine, and then go to http://localhost:43110/0chan.bit/ and try to use the site.

**Comment by The-Compiler** [comment]
I reported this upstream as https://github.com/Nullchan/nullchan/issues/12 and [QTBUG-56383](https://bugreports.qt.io/browse/QTBUG-56383). Nothing else I can do about this, so I'm closing this.

**Comment by The-Compiler** [comment]
The Qt bug mentions that it works in the next QtWebEngine release (based on Chromium 53), and it's broken in Chrome 49 too.
