### ISSUE TITLE
Setting ui->confirm-quit broken

### ISSUE THREAD

**Issue by HolySmoke86** [The-Compiler/qutebrowser#2009]
The confirmation prompt is aborted "because we're shutting down".

Following feature test can be used:

```
    Scenario: Exiting qutebrowser via :quit command with confirmation
        Given I set ui -> confirm-quit to always
        When I run :quit
        Then the message "Really quit?" should be shown
```

This affects all `confirm-quit` values (except for `never`, of course).
This does not happen when quitting via closing the window.

**Comment by The-Compiler** [comment]
Closing this as duplicate of #632.
