### ISSUE TITLE
:spawn umpv   not working on OS X

### ISSUE THREAD

**Issue by m2habert** [The-Compiler/qutebrowser#2015]
[QB 0.8.2  under MacOS - El Capitan]   spawn umpv does not work : 

If called from terminal, everything works fine. 
...But, from QB:
    `:spawn --userscript ~/my_bin/umpv {yTube url}`
‡
  Userscript exited with status 1.

`:spawn --userscript ~/my_bin/umpv {yTube url}`
‡
Command exited with status 1.

   ` :spawn Users/usr_name/my_bin/umpv {yTube url}`
‡
  Command exited with status 1.

 The 3 logs are the same:

```
_Process stderr:
Traceback (most recent call last):
  File "/Users/usr_name/my_bin/umpv", line 91, in <module>
    subprocess.check_call(opts)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle_
```

---
On the other hand, mpv works when using an absolute path:
`    :spawn /opt/local/bin/mpv {yTube url}`
works fine (although it seems a bit slow: I have no prior experience with mpv, but it can take anything between 15 to 50 seconds to open the stream)

When 'trusting' on my bash profile path:
`:spawn mpv {yTube url{yTube url}`
‡
  Error while spawning command: The process failed to start.
...which I guess it means QB didn't find the Command

(when testing umpv with files instead of urls, if the file is inputed as " ~/path/file.mp3", then I get "command exited w/status 2"; If inputed "/Users/user_name/etc" : status 1 and same log as above)

**Comment by The-Compiler** [comment]
In your [mail](https://lists.schokokeks.org/pipermail/qutebrowser/2016-October/000275.html) you mentioned a longer stacktrace also containing "OSError: [Errno 9] Bad file descriptor" - you still get that, right?

Also, can you please show the first line (shebang) of your `/Users/m2habert/bin/umpv`? I assume it's `#!/usr/bin/env python`, right?

I also edited your post to put the stacktrace in triple backticks (```) so it's rendered right.

**Comment by m2habert** [comment]
stacktrace: Yes, you are right! There's actually this longer stackertrace, I've just noticed using ":message", but I did not manage to replicate it yet.

shebang: yes, it is   :     #!/usr/bin/env python

**Comment by The-Compiler** [comment]
Okay, let's try to find a smaller example of this.

If you create the following python script:

```python
#!/usr/bin/env/python
import subprocess
subprocess.check_call(['mpv', 'http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4'])
```

And `chmod +x` it:

- Does it run when run from the shell?
- Does it run when run from qutebrowser?

**Comment by m2habert** [comment]
@ shell did not work:
got the Error:
-bash: /Users/m2habert/¶bin/tesla: /usr/bin/env/python: bad interpreter: Not a directory

**Comment by The-Compiler** [comment]
Whoops, sorry, my bad - that should be `#!/usr/bin/env python` with a space.

**Comment by m2habert** [comment]
Something changed, don't know exactly what. It fixed itself...

 umpv now works and so does 'relative' paths, both the regular " ~/ " home folder abbreviation, as the personal written in the bash profile.

It must be related with the computer restart I did last thursday. Anyway, the problem is gone.

(The only caveat being how slow it takes to the vid to actually start playing... an average of 15s. When I "pipe" the url to the mpv app using a launcher (LaunchBar) it opens in seconds)

**Comment by The-Compiler** [comment]
What about launching `umpv URL` from a terminal?

**Comment by sebastian-frysztak** [comment]
Regarding mpv's slow launch: I recommend [this](https://bbs.archlinux.org/viewtopic.php?pid=1578424#p1578424) piece of advice. It improved the situation a lot in my case.

**Comment by m2habert** [comment]
Thanks @sebastian-frysztak , will try. 

@The-Compiler  Launching from the terminal is either the same or a bit worse...

**Comment by The-Compiler** [comment]
Okay, so nothing qutebrowser can do about it then :wink: Closing this then!

**Comment by m2habert** [comment]
As I reported previously:
>Something changed, don't know exactly what. It fixed itself...

>umpv now works and so does 'relative' paths, both the regular " ~/ " home folder abbreviation, as the personal written in the bash profile.

>It must be related to the computer restart I did last thursday. Anyway, the problem is now Something changed, don't know exactly what. It fixed itself...

I now believe something goes on and off with :spawn in the Mac UNIX scenario.


I'm setting a new issue for the sake of tidyness and clarity in #

**Comment by gerrywastaken** [comment]
For anybody else running into this. The only way I was able to set the environment PATHs so that qutebrowser picket them up was via the

sudo launchctl config user path <path> command followed by a restart.

e.g.
sudo launchctl config user path /User/myname/bin:/usr/local/bin:/otherrandompath/bin

NOTHING else worked. Not /etc/paths or even this which is specificially about getting paths working in qutebrowser:
https://www.bounga.org/tips/2020/04/07/instructs-mac-os-gui-apps-about-path-environment-variable/

For some strange reason using getenv inside Emacs (launched from Spotlight) did pick up the environment variables from those methods.
