### ISSUE TITLE
Can't paste an image from clipboard under MacOS

### ISSUE THREAD

**Issue by m2habert** [The-Compiler/qutebrowser#2022]
`qB v0.8.2
Mac OS 10.11.2`

I tried pasting images on both Telegram and gMail sites to no avail.

¿Maybe related to the Qt WebKit under-development and fixed under the Qt WebEngine?

**Comment by The-Compiler** [comment]
Does that work in other browsers? When I try to paste an image on web.telegram.org using `Ctrl-v` on Linux, only the file path is pasted.

**Comment by m2habert** [comment]
It works in Firefox (which I, before QB, used exclusively due to my
Vimperator veneration).

I've just checked in Safari and it doesn't work there, though (neither with
Telegram nor gMail).

 Very odd: ¿how can one use gMail without image pasting? I'm totally
dependant on this feature...

**Comment by The-Compiler** [comment]
So how exactly do you paste the images? Do you just press Cmd-v or something while in a telegram chat?

**Comment by Elronnd** [comment]
...can't you just create an attachment of your image?

**Comment by m2habert** [comment]
> So how exactly do you paste the images? Do you just press Cmd-v or something while in a telegram chat?


Yes. OS X has a "copy selected area as image to the clipboard" built in, but I thought that Windows and Linux similar utilities were pretty common.

(It's one of those things that, if I've totally incorporated in my workflow, added to my perception that I'm pretty late in "getting in the know" about the newest software trends, I end up concluding that it is the Law all over. Really shocked that Safari didn't implement this...)



> ...can't you just create an attachment of your image?

Not sure I understand the question: yes, I can, but it slows things up a lot. Again, I didn't think much of it: as QB is a vim-like browser, I assumed most of its users were former Vimperator | Pentadactyl fans, thus FFx users. 

And, following the similar "luv-vim, hate-mouse" assumption, Telegram's interface is pretty "hint unfriendly" (gMail way better): it forces you to reach for the mouse if you want to attach something. In a colaborative chat the image pasting would be surely missed.

**Comment by The-Compiler** [comment]
Ah! That explanation helped, I could test this in other browsers now with actual image data instead of a file copied to clipboard.

This doesn't work with QtWebKit indeed, but works just fine with the QtWebEngine backend (which is not available yet on OS X though), so I'm closing this.

**Comment by m2habert** [comment]
When you say...

>QtWebEngine backend (which is not available yet on OS X though)

... ¿do you mean it is not available due to no clear method (which will hopefully be addressed by you in a near future) or is it due to a shortcoming / probable bug by the QT team (making it uncertain for us OS X users)?  

I've noticed  #1692, but don't really know what to make of it.

**Comment by The-Compiler** [comment]
I don't know what exactly causes it, it might be a bug in qutebrowser's packaging stuff, or in PyInstaller, or something else. But let's continue the discussion in that bug.

**Comment by Lilith-In-Starlight** [comment]
This also happens on windows

**Comment by The-Compiler** [comment]
@Lilith-In-Starlight Unless you're using qutebrowser with the QtWebKit backend (which is long dead and full of security issues), this isn't the same issue you're seeing - so please indeed open a new issue with the information from the issue template.
