### ISSUE TITLE
when tab closes, return to last used tab.

### ISSUE THREAD

**Issue by exo66** [The-Compiler/qutebrowser#2025]
i almost never want to go to the tab to the right, and i expect that goes for many people.

**Comment by blyxxyz** [comment]
That's a setting already. You can run `:set tabs select-on-remove previous`, or set `select-on-remove` to `previous` in qute://settings. You can also set it to `left`.

**Comment by The-Compiler** [comment]
FWIW selecting the right tab is also the default in Firefox/Chromium :wink:

**Comment by exo66** [comment]
sorry, and thanks for showing me how to do it.
