### ISSUE TITLE
[webengine] Clicking on links or buttons doesn't do anything

### ISSUE THREAD

**Issue by zuglufttier** [The-Compiler/qutebrowser#2028]
Sometimes, I find links or buttons that don't do anything when I click on them, an example: http://www.dhl.de/en.html
Clicking on the button next to the input field for the tracking number will do nothing.

~ % qutebrowser --version
qutebrowser v0.8.1
Git commit: v0.8.0-1450-gd5a3d2e (2016-10-13 11:30:51 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.4.20 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.7.6-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

Paths:
download: /home/zlt/Downloads
data: /home/zlt/.local/share/qutebrowser
config: /home/zlt/.config/qutebrowser
cache: /home/zlt/.cache/qutebrowser
runtime: /run/user/1000/qutebrowser
system_data: /home/zlt/.local/share/qutebrowser

**Comment by The-Compiler** [comment]
I probably can't reproduce this without a tracking number, but I'm guessing the last point mentioned in https://bbs.archlinux.org/viewtopic.php?pid=1658790#p1658790 will fix this :wink: If not, feel free to reopen!
