### ISSUE TITLE
Invalid suggested file name when downloading from Mega

### ISSUE THREAD

**Issue by abbradar** [The-Compiler/qutebrowser#2029]
For example: https://mega.nz/#!XkZGhT7S!7OzMHW3eYCXPCSJwleczg3nAv7M1sSnirnxvpVsdDgQ -- I would have expected to be advised `TWRP-recovery-gemini-test3.img` but instead I get `mega.nz.html`.

Unrelated: qutebrowser crashes on `qute:version` for me, I'll come up with more info later.

**Comment by The-Compiler** [comment]
If I remember correctly @Kingdread and I looked at this some while ago, and unfortunately we can't come up with a better name with the infos we get from QtWebKit.

When downloads are implemented with QtWebEngine, I'd expect it to work there though.
