### ISSUE TITLE
Use https for links in the docs and elsewhere

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#2039]
Just installed `qutebrowser v0.8.2` on a VM. It seems like it [tries](https://github.com/The-Compiler/qutebrowser/blob/8dab1cf58ac26655419e6fb0a1aab655771e6fa5/qutebrowser/app.py#L332)   to open http://www.qutebrowser.org/quickstart.html the first time you run it, but that link is dead.
Should it open the local quickstart guide at `qute://help/quickstart.html` instead?

**Comment by The-Compiler** [comment]
That works fine here, how is it "dead" for you? Loading the remote quickstart file is intentional.

**Comment by rcorre** [comment]
It only works if I explicity use `https:`. I think it's because I'm behind a proxy.

**Comment by The-Compiler** [comment]
Yeah, sounds like your proxy is breaking non-HTTPS connections in some way then?!

Anyways, that link should be changed to HTTPS, and while I'm at it, various others (e.g. in the docs) too.

**Comment by HolySmoke86** [comment]
I noticed that 3 of the 5 default host blocking lists aren't accessible via https. I'm not sure as to how bad that is.

**Comment by The-Compiler** [comment]
I'd guess it's sad, but not bad - it means someone in a privileged network position could change the lists, but they could block sites anyways...
