### ISSUE TITLE
Update dependency install  instructions for OSX

### ISSUE THREAD

**Issue by edrex** [The-Compiler/qutebrowser#2043]
The current instructions don't work because both the bottle and pip builds of pyqt5 exclude qtwebkit.

To get a working env on OSX I had to built Qt and PyQt from source:

```
brew install qt5 --with-qtwebkit
brew install -s pyqt5
```

This took about two hours on my machine, but allows using Qt 5.7.

**Comment by The-Compiler** [comment]
The `--with-qtwebkit` flag was added to Homebrew pretty recently, but I agree that'd be the better way to install things now. Do you want to work on a pull request?
