### ISSUE TITLE
[UI] Tab closing should default to showing the tab on the left

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2062]
Opening a link which creates a new tab, results in a tab on the right of the originating tab.

Consequently, closing that new tab should result in showing the originating tab on the left.

Currently in version `0.8.2`, after closing, an unrelated tab at the right is shown, which is utterly confusing.

**Comment by The-Compiler** [comment]
The default of selecting the right tab is also what other browsers (Firefox, Chromium, and probably more) do, so I'd guess most people (including me) find behavior different to that confusing.

However, you can simply do `:set tabs select-on-remove left` if you prefer that :wink:

**Comment by stroobandt** [comment]
Excellent!
Oops… I overlooked that setting.
At least others can equally find this answer now.
