### ISSUE TITLE
[UI] Eliminate odd extra keystroke when hint matches uniquely

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2064]
When performing for example a `:quickmark-load` and typing the first characters of the quickmark name,
the hinting will often uniquely match.

At this point, I still need to hit either <kbd>Tab</kbd> + <kbd>Enter</kbd> or <kbd>↓</kbd> + <kbd>Enter</kbd>, whereas just hitting <kbd>Enter</kbd> would be quicker and, above all, more intuitive.

Seen on version `0.8.2`.

**Comment by The-Compiler** [comment]
From context I'm assuming you mean the completion, as hinting is referring to the `f` feature :wink:

Closing this as a duplicate of #623.

**Comment by stroobandt** [comment]
Thanks, still learning the `qutebrowser` vocabulary…

**Comment by NoctuaNivalis** [comment]
I'm not sure this was a dupplicate. The linked issue is about commands, this issue is more general. It'd be useful to have the unique matching for quickmarks and history completion as well (with separate configuration).

**Comment by The-Compiler** [comment]
Right! I reopened #623.
