### ISSUE TITLE
MathJax formulas appear larger than in other browsers.

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2066]
[MathJax](http://www.mathjax.org/) formulas appear larger than in other browsers. Too large.
Compare this for [example](http://hamwaves.com/lpda/en/index.html).

Seen in version `0.8.2`.

**Comment by lahwaacz** [comment]
Looks fine for me - can you post a screenshot? Also note that MathJax provides couple of options in right-click menu under "Math Settings -> Zoom Factor" and completely custom scale factor in "Math Settings -> Scale All Math", all persisting across page reloads.

**Comment by stroobandt** [comment]
qutebrowser 0.8.2
![qutebrowser](https://i.imgur.com/zjEzRrc.png)

versus Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
![Chromium](https://i.imgur.com/xxH76de.png)

I am talking default zoom levels here, without changing anything to the MathJax zoom factor. Good to know, though! Never had such an issue with any other browser, and I tested many.

**Comment by The-Compiler** [comment]
FWIW I don't see a difference with the example formula on https://www.mathjax.org/

Either way, I'm afraid there isn't anything qutebrowser can do about it as this is entirely handled by the backend - however, the upcoming QtWebEngine backend is based on Chromium, so with that it should look like there.

**Comment by stroobandt** [comment]
@lahwaacz The `Scale All Math…` solution, set to 75% seems to resolve the issue.
Moreover, it remains persistent on a per site basis over browser sessions.
This is done by setting a cookie for the site containing the MathJax math.

This implies that the scaling factor needs to be manually set to 75% for each and every site containing MathJax.
We probably need to talk to the MatJax developers about recognizing qutebrowser and setting the corrected scaling factor.

**Comment by stroobandt** [comment]
@lahwaacz MathJax's [browser compatibility page](http://docs.mathjax.org/en/latest/misc/browser-compatibility.html) states that WebKit browsers are not systematically tested. They do so, however for Safari.
