### ISSUE TITLE
Edit a local file in the external editor

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2068]
For local web development purposes, it might be handy to have a command (or even right click option) to open local files (or links to these) in the external editor.

For example, [my static site](http://hamwaves.com/it/en/index.html) has on every page a link to the pertaining [Markdown source code](http://hamwaves.com/it/en/it.md). This `.md` file can easily be edited locally with an editor launched from many other browsers, which is quite handy.

Seen in version `0.8.2`

**Comment by The-Compiler** [comment]
So how would that link map to a local file?

**Comment by stroobandt** [comment]
Good question! Right now, in Firefox and [Pale Moon](https://www.palemoon.org/), I simply click on the _local file_ link. In `Preferences → Applications`, the respective content types Markdown document `text/markdown` and `text/x-markdown` both point to `Use GVim (default)`.
I work on Xubuntu LTS 16.04.

**Comment by stroobandt** [comment]
Another way would be via `:download` and then <kbd>Ctrl</kbd> + <kbd>x</kbd>, whereby instead of downloading a copy to `/tmp`, the original local file would be opened.

This would happen then automatically in the pertaining external editor via the `xdg-open` MIME mechanism.

**Comment by The-Compiler** [comment]
I still don't follow - where is there a "local file" link?

FWIW I think the easiest way to do this in qutebrowser would be writing an [userscript](https://github.com/The-Compiler/qutebrowser/blob/master/doc/userscripts.asciidoc) which then does whatever you want after either you spawning it via hints, or you spawning it on one of your pages directly.

I'm closing this for now as I don't think there's anything new qutebrowser should implement for this to be possible.

**Comment by stroobandt** [comment]
With _local file_ I mean a file sitting somewhere on your hard drive, possibly under `~/public_html/`.
To say it in other words, a `file://` URI.

I definitely have to look into spawning userscripts.
When I come up with a solution, I will post it here for any other lost soul.

**Comment by stroobandt** [comment]
@The-Compiler Almost there with a simple: `bind <ctrl-e> spawn /usr/bin/gvim {url}`.
If it were not for `gvim` nagging me with the following warning:

    W13: Warning: File "..." has been created after editing started             
    [O]K, (L)oad File:

After which, `Load` is the right answer to continue editing the existing file.
The question is now how to get rid of that warning?

**Comment by stroobandt** [comment]
>[**\*W13\* 
>Warning: File "{filename}" has been created after editing started**](http://vimdoc.sourceforge.net/htmldoc/message.html)
>
>You are editing a file in Vim when it didn't exist, but it does exist now.
>You will have to decide if you want to keep the version in Vim or the newly
created file.  This message is not given when ['buftype'](http://vimdoc.sourceforge.net/htmldoc/options.html#'buftype') is not empty.

However, I am still clueless about how to use `buftype`, though…

**Comment by stroobandt** [comment]
Asking for help over at <http://vi.stackexchange.com/q/10080/3168>
