### ISSUE TITLE
:edit-url empty when web-history-max-items = 0

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2069]
The command `:edit-url` results in an empty editor screen when `web-history-max-items = 0`.
Works though with `web-history-max-items = 1`.
Seen in version `0.8.2`.

**Comment by The-Compiler** [comment]
I don't see how the two would be related, and I can't reproduce this.

Can you please reproduce this (ideally after starting qutebrowser with `--temp-basedir`) and then run `:report` so I get debug logs?

**Comment by stroobandt** [comment]
I will test again. It might be something else causing this.

**Comment by stroobandt** [comment]
It must have been something else. I can no longer repoduce it.
Indeed, it has nothing to do with history.
