### ISSUE TITLE
Integrate PDF.js

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#207]
We could use pdf.js to display PDFs in-browser.

See https://github.com/foxhead128/nimbus/commit/85c78a4eeecd4ae0c6f67f6376b13893c4c54df9 for inspiration.

**Comment by arbitrary-dev** [comment]
I think it's a bad idea to bloat such a qute browser to look like swiss knife.

**Comment by The-Compiler** [comment]
I have to admit I don't really understand the reasoning about "bloat". I'd like the functionality myself, but of course it'll be configurable - and then why bother? If you don't want it, disable it - the few bytes more of Python/Javascript on your harddisk won't hurt anyone ;)
