### ISSUE TITLE
Crash using WebEngine: host has null char

### ISSUE THREAD

**Issue by sim590** [The-Compiler/qutebrowser#2070]
I got a crash using WebEngine backend with the following command:
```
env QUTE_QTBUG54419_PATCHED=1 qutebrowser --backend webengine
```

I am using the patched packages listed on this [page](https://github.com/The-Compiler/qutebrowser/blob/49f8fa6d76b1508e8f01ca0dee16aebdf64c1072/doc/stacktrace.asciidoc#archlinux). The stderr showed this:
```
[1028/215126:ERROR:host_port_pair.cc(65)] Host has a null char: 0%00%00%00%00%00%00%00%00%00
```

I was

- trying to access my router entering the ip address. The page never loaded and I had to retry multiple times until it
  froze for a few seconds (then crashed);
- I was having connectivity issues at the same time
- browsing may be 10+ other pages;

**Version info**
```
qutebrowser v0.8.1
Git commit: v0.8.0-1479-gebe656f (2016-10-20 07:30:13 +0200)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.2.109 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.8.4-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version:

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

Paths:
config: /home/simon/.config/qutebrowser
runtime: /run/user/1000/qutebrowser
cache: /home/simon/.cache/qutebrowser
system_data: /home/simon/.local/share/qutebrowser
download: /home/simon/Téléchargements
data: /home/simon/.local/share/qutebrowser
```

**Comment by The-Compiler** [comment]
See [QTBUG-55828](https://bugreports.qt.io/browse/QTBUG-55828) which will be [fixed](https://codereview.qt-project.org/#/c/171109/) in the next Qt release.
