### ISSUE TITLE
Enabling additional SSL root certificates.

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2072]
Error loding page: <https://test.eid.belgium.be>
SSL handshake failed.

This probably has to do with the fact that I need to [enable additional SSL root certificates](http://eid.belgium.be/en/using_your_eid/need_help/problemen_met_de_installatie) in `qutebrowser`.
The question is where and how?

This is for the Belgian eID. However, Citrix VPN connections to a university/company LANs also tend to require additional root certificates. Hence, it is a more general problem.

**Comment by haasn** [comment]
I would naively assume that webkit simply uses your system-wide SSL certificates (from `/usr/share/ca-certificates`)

**Comment by paretje** [comment]
But, just adding the root CA's to qutebrowser or your OS won't suffice to login, as there is no plugin loading the client certificate from your eid. Opening the test page in another browser without eid will result in a similar error.

Maybe the Chromium extension could be used, in the future, using WebEngine, if/when qutebrowser will/would support the WebExtension API.

**Comment by The-Compiler** [comment]
As for certificates, @haasn is right - however this also seems to require a client certificate? None of the current backends (QtWebKit/QtWebEngine) supports that so far...

@paretje is there a Chromium extension? I can only find a Firefox one...

After [QTBUG-54877](https://bugreports.qt.io/browse/QTBUG-54877)/[QTBUG-56206](https://bugreports.qt.io/browse/QTBUG-56206) are implemented upstream, [those instructions](https://visibilityspots.org/chromium-eid.html) for Chromium might just work with qutebrowser as well...

Either way, I don't think there's anything qutebrowser can do here, so I'm closing this.

**Comment by paretje** [comment]
@The-Compiler I had done a quick check, as I personally use Firefox for eid, and I found https://chrome.google.com/webstore/detail/eid-chrome-extension/bkbdaodnaecdijpajecpncpdomgcoakc. But indeed, now that I give it a proper look, it's clearly not official.
