### ISSUE TITLE
Treat {hint-url} as "visited" after :hint links spawn ... command

### ISSUE THREAD

**Issue by brianbuccola** [The-Compiler/qutebrowser#2073]
I have the following binding:

```
hint links spawn mpv {hint-url}
    ;x
```

This lets me press `;x`, which triggers hinting, and then any link that I pick will be opened using the video player mpv.

**My question**: Is it somehow possible to treat such links as "visited" after I've run `;x` on them, so that their link color gets changed appropriately? This would be useful because, when I return to a page containing videos, it would be nice to know which ones I've already watched.

The only workaround I know of is to open the link in a new tab, hit `x`, where `x` is bound as follows...

```
spawn --detach mpv {url}
    x
```

...and then close the tab, which is obviously not as efficient. Thanks!

**Comment by The-Compiler** [comment]
It's not possible, but adding some option to `:hint` to add the hinted URL to the history shouldn't be hard.

**Comment by Raihid** [comment]
@brianbuccola Does #2129 solve this?

**Comment by The-Compiler** [comment]
I think it does, so I'm closing this :wink:

**Comment by brianbuccola** [comment]
Yes, thank you! Just one minor comment: after hinting, the link doesn't immediately change color--it only changes after refreshing the page; by contrast, opening a link in a new tab immediately changes the link color once the page finishes loading.

**Comment by The-Compiler** [comment]
I don't think there's anything I can do about that I'm afraid - coloring the links is handled by the backend.

**Comment by brianbuccola** [comment]
Not a big deal at all. Thanks again to both of you!
