### ISSUE TITLE
Google search by image not working

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2074]
That [Google search by image](https://www.google.com/imghp) thingie (a clickable camera icon in the search field) is not visible, and by consequence, not functioning.

Seen on version `0.8.2`

**Comment by stroobandt** [comment]
Nor is this more direct [search by image link](https://www.google.com/imghp?sbi=1) working properly.

**Comment by The-Compiler** [comment]
Blame Google for that one - it works when you use `:set network user-agent` to set it to something like Chrome... However, then things like GitHub will break.

FWIW it works fine with the default user agent with the upcoming QtWebEngine backend.
