### ISSUE TITLE
Dowloand of pics generating corrupted files

### ISSUE THREAD

**Issue by m2habert** [The-Compiler/qutebrowser#2078]
qB v0.8.2
Mac OS 10.11.2

Tested <;d> with pictures in a Wikipedia page, but the files generated get error messages whenever I try to open them (Firefox: "The image "file///Users/path/etc/etc.jpg" cannot be displayed because it contains errors.").

Tried the same with the (mouse-clickable) context menu ("Save link...") and got the same result.

**Comment by The-Compiler** [comment]
How can I reproduce this? I tried to download the logo from [the Python wikipedia page](https://en.wikipedia.org/wiki/Python_(programming_language)) without any issues.

**Comment by m2habert** [comment]
Dunno... maybe it's a Mac thing.

(The python logo works fine for me as well: it's actually a vector .svg file.  The Python's creator's photo, on the other hand... same result: corrupted)

**Comment by The-Compiler** [comment]
Please try to be more specific (i.e. post links ideally) when reporting issues like this, to be sure we're on the same page :wink:

When I download GvR's photo (which downloads [this link](https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Guido_van_Rossum_OSCON_2006.jpg/220px-Guido_van_Rossum_OSCON_2006.jpg)) I get a working file, with md5sum 7935ade97b5507387815183d6a517427.

Do you get something different?

**Comment by m2habert** [comment]
I get a  "File/Guido_van_Rossum_OSCON_2006.jpg" corrupted file

(here : 
![file guido_van_rossum_oscon_2006](https://cloud.githubusercontent.com/assets/7454005/19839458/4f9619ec-9ec9-11e6-8608-accf6d94e09d.jpg)
)

**Comment by The-Compiler** [comment]
Hmm, that's actually a HTML file, odd.

How exactly do you download it? If you do `:download https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Guido_van_Rossum_OSCON_2006.jpg/220px-Guido_van_Rossum_OSCON_2006.jpg`, do you also get a corrupted file?

**Comment by m2habert** [comment]
I get a positive!

here : 
![220px-guido_van_rossum_oscon_2006](https://cloud.githubusercontent.com/assets/7454005/19839571/87975296-9ecb-11e6-9263-cf3fdaf41b42.jpg)

**Comment by The-Compiler** [comment]
Okay - I think I see the issue now!

The image is actually a link to [this page](https://en.wikipedia.org/wiki/Python_(programming_language)#/media/File:Guido_van_Rossum_OSCON_2006.jpg) which is still a website, and not the image.

What `;d` does is to download that link, it doesn't recognize images and let you download that (maybe that should be a separate hint mode?).

In the right click menu, there's "Save image" which gives you the actual image, and "Save link" which gives you the HTML page (named `.jpg` because that's what wikipedia names that page...).

I don't think anything is wrong here then :wink:

**Comment by m2habert** [comment]
(
>Hmm, that's actually a HTML file, odd.

Speaking of which, whenever I use < ;d > with a "page" link, I get an html file, simple, easy, fast, no pics and ready to go: the simple and heavenly functional perfection I never get with other browsers.

But... QB does not put an ".html" as a filetype, it comes with no extension. Just the filename, no dot, no extension: ¿Is that a feature or a bug?
)

**Comment by m2habert** [comment]
> What ;d does is to download that link, it doesn't recognize images and let you download that (maybe that should be a separate hint mode?).

It certainly would be useful.

**Comment by The-Compiler** [comment]
> But... QB does not put an ".html" as a filetype, it comes with no extension. Just the filename, no dot, no extension: ¿Is that a feature or a bug?

Hmm, I've never really thought of using `;d` to download things other than actual downloads - I usually use it on index pages like e.g. http://qutebrowser.org/releases/v0.8.2/ where it'd be wrong to add any extension... So I'm not sure how qutebrowser could detect that it has to add an extension other than doing a good guess based on the downloaded contents.

> It certainly would be useful, methinks.

I added it to #521.
