### ISSUE TITLE
One redirect isssue.

### ISSUE THREAD

**Issue by coco101000000000** [The-Compiler/qutebrowser#2088]
qutebrowser version is 0.82
isssue1 address is http://weibo.com/335969990?is_hot=1
issue 2 address is http://weibo.com/logout.php?backurl=%2F

Issue1: When we visitor chinese weibo ,It will take the visitor to a visitor detect address for checking visitor's session. The detect system using P3P to set cookie for protecting. then it take visitor reback to the preview address. But qute support not well.so qute take visitor to home page.

Issue2: If you login in qute. Then you want to logot it stay logout addree in loop.
![_20161103164713](https://cloud.githubusercontent.com/assets/21169660/19960049/6c8ffbd4-a1e5-11e6-917e-65c5351075b4.png)
![_20161103164826](https://cloud.githubusercontent.com/assets/21169660/19960052/6d958f6c-a1e5-11e6-95ef-6744437f7990.png)

**Comment by The-Compiler** [comment]
For issue 1, I tried opening that link in Chromium and Firefox, and for both I land on the main page with http://www.weibo.com/login.php too...

**Comment by coco101000000000** [comment]
I use google chrome and Firefox,the correct display way be in picture.

![_20161104112605](https://cloud.githubusercontent.com/assets/21169660/19993564/a9da3d46-a281-11e6-914e-64a394c03ec9.png)

**Comment by coco101000000000** [comment]
May be I know why. I tried again and found that when I use browser privary mode to visitor the address ,it will redirect to "http://www.weibo.com/login.php " too. May be qute cookie manage has some bug.

**Comment by The-Compiler** [comment]
Can you please try doing `:set content cookies-accept all` (instead of the default `no-3rdparty`) and see if that helps?

**Comment by coco101000000000** [comment]
The first i doing " :set content cookies-accept all " and it work,but when i close and re-open browser,it go wrong again. I repeate above operator some times and still wrong.

I check qute's coookie found that qute didn't saving webo's cookie correct.some saving and some lost.
I screenshot a  picture here and append some data here for tesing.
I'm sure the problem is from cookie saving.
![_20161104151907](https://cloud.githubusercontent.com/assets/21169660/19997619/dbfdaac6-a2a2-11e6-8f42-87d3571f534c.png)
![_20161104152616](https://cloud.githubusercontent.com/assets/21169660/19997650/0ce86608-a2a3-11e6-9e5f-594786855ecb.png)

**Comment by coco101000000000** [comment]
Data from chrom 

SCF=Aiz6-QFvzlmy8MPH076geEWkyJObv94zj4vr0r5azWvSI93P8XEa51uESZtsVMFmrcYhszi7IHzQwfA51weV8sA.; expires=Mon, 02-Nov-2026 07:01:18 GMT; domain=.weibo.com; path=/
SUHB=0QS4BNziX601WM; expires=Mon, 02-Nov-2026 07:01:18 GMT; domain=.weibo.com; path=/
un=909124951@qq.com; expires=Mon, 02-Nov-2026 07:01:18 GMT; domain=.weibo.com; path=/
SUB=_2AkMvRnUqdcNhrAJZmP8Xz2vlaohH-jzEiebBAn7uJhMyAxgv7gYWqSUDMEjQPfDGcxhSZa0KUfAvT0cflw..; expires=Mon, 02-Nov-2026 07:01:18 GMT; domain=.weibo.com; path=/
SUBP=0033WrSXqPxfM72wWs9jqgMF55529P9D9WWOCHYk2RWv50u0UYreGx8D5JpV2h.71K2ESh.fe-WpMC4odcXt; expires=Mon, 02-Nov-2026 07:01:18 GMT; domain=.weibo.com; path=/
YF-Page-G0=27b9c6f0942dad1bd65a7d61efdfa013; expires=Mon, 02-Nov-2026 07:01:18 GMT; domain=.weibo.com; path=/

**Comment by The-Compiler** [comment]
Can you please try with another QtWebKit based browser like Otter Browser?
See [otter-browser-win32-weekly135.zip](https://sourceforge.net/projects/otter-browser/files/otter-browser-weekly135/otter-browser-win32-weekly135.zip/download)

(please use that older weekly 135, as it's closer to what qutebrowser is based on currently)

If it doesn't work there either, it's probably an issue with the QtWebKit backend and will hopefully work when the new backend is the default (see #666)

**Comment by coco101000000000** [comment]
I try  doing ":set content cookies-accept all" ,it solve the issue 2. but issue 1 still work wrong. I try it when download completely

**Comment by coco101000000000** [comment]
Otter Browser  has the problem too.

**Comment by The-Compiler** [comment]
Unfortunately then this is a QtWebKit issue and there isn't really anything else I can do - however it should work in the future with the new QtWebEngine backend.
