### ISSUE TITLE
Duplicate key chain <ctrl-pgdown> on fresh installation from git

### ISSUE THREAD

**Issue by edio** [The-Compiler/qutebrowser#2094]
checked out from git, built, installed. On launch I get an error described in the subject.

**Comment by The-Compiler** [comment]
See #1835, closing this one as a duplicate :wink:

I'm pretty sure you had some old `~/.config/qutebrowser/keys.conf` lying around though, either from using a release earlier, or from trying qutebrowser some time ago - could that be possible?

**Comment by edio** [comment]
Thanks! I've checked for ~/.qutebrowser, but it is actually inside XDG_CONFIG_HOME :) Sorry for confusion.
