### ISSUE TITLE
(X)ubuntu LTS 16.04: qutebrowser can't find a suitable pdf.js installation

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2095]
> If you have installed a pdf.js package and qutebrowser still can't find it, please send us a report with your system and the package name, so we can add it to the list of supported packages.

    qutebrowser v0.8.2
    Platform: Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
    Desktop: xubuntu

As for the pdf.js package location:

    $ dpkg -L xul-ext-pdf.js
    …
    /usr/share/xul-ext/pdf.js
    …

**Comment by Kingdread** [comment]
Yeah, seems like this path is not searched by qutebrowser. Could you try and add `/usr/share/xul-ext/pdf.js/content/` to the path list in [`qutebrowser/browser/pdfjs.py line 99-107`](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/pdfjs.py#L99-L107) and see if pdf.js works then? Then we can add the path for the next release.

**Comment by The-Compiler** [comment]
Ubuntu has two pdfjs packages, `xul-ext-pdf.js` and `libjs-pdf` - I thought there was some reason `xul-ext-pdf.js` didn't work, but if it does actually work, I'm happy to add that path.

**Comment by stroobandt** [comment]
@Kingdread I tried your suggestion. This resulted in a `pdf.js` instance starting in the browser. However, apart from the controls, this instance remained black without any PDF content.

**Comment by stroobandt** [comment]
@The-Compiler You are right! The package `libjs-pdf` works out of the box, without any modifications. What lead me to this, is the fact that `libjs-pdf` does not show up anywhere when searing for "pdf.js" in the Synaptic package manager. This issue can easily be resolved by improving the documentation about this point.

**Comment by stroobandt** [comment]
…or by making `libjs-pdf` a dependency in the `.deb` package!

**Comment by The-Compiler** [comment]
A dependency would be wrong (because it's not one). It's already added as `Suggests:`. I also added a hint ot the error page now.
