### ISSUE TITLE
Qutebrowser becomes visually frozen until ':' menu is used in xmonad,herbstluftwm

### ISSUE THREAD

**Issue by frank604** [The-Compiler/qutebrowser#2096]
Steps to reproduce:

-Qutebrowser is on workspace 1
-Switch focus to any other workspace
-Switch focus back to workspace 1

Issue: qutebrowser is visually 'frozen' and behaves as if the WM has not focused it.  This means that if you are watching youtube, the audio will still play but visually it will be 'frozen'.  Same goes for text input.  After you open and close ':' menu, all changes (if writing text) and video will 'resume'.

This issue does not happen in DWM regardless of current git version of qutebrowser r10652.6019e09-1 or 0.8.2. 

This issue is not apparent in another QT app such as otter.

Below is a copy paste of the irc chat:

> 13:44    frank604| The-Compiler: Hi, I lost my irc logs and wasn't able to follow up to see 
>                     if the issue lies with qutebrowser or xmonad or something else.  If 
>                     qutebrowser is in workspace 1, I switch focus to workspace 2 in xmonad, 
>                     and return to workspace 1, qutebrowser will seem frozen until I open the 
>                     ':' window.  I appreciate your feedback as always :)
>  13:45  The-Compil| frank604: I've now seen that too sometimes, thought it was about me 
>                     switching to a 9 year old laptop :P
>  13:45  The-Compil| no idea what's going on unfortunately...
>  13:46    frank604| The-Compiler: thanks for the feedback.  is that 9 year old laptop 
>                     running xmonad? 
>  13:47  The-Compil| nope, herbstluftwm
>  13:48    frank604| Ah, yes.  I remember reading in chat someone experienced the same in 
>                     herbstluftwm. I'll continue to dig.  
> 14:07       fiete| also experienced that today while watching a series on amazon prime
>  14:07       fiete| few weeks ago just hitting the spacebar twice fixed it, but today I had 
>                     to hit :
>  14:07  The-Compil| fiete, frank604: can you try reproducing with an older release?
>  14:07  The-Compil| FWIW I usually do fullscreen/unfullscreen
>  14:08       fiete| The-Compiler: yeah will try tomorrow
>  14:11    frank604| The-Compiler: how far back do you want me to go?  
>  14:12  The-Compil| frank604: I've only heard this pop up recently, so v0.8.2 would probably 
>                     be enough
>  14:16    frank604| 0.8.2 still seeing it, cleared ~/.config/qutebrowser as well
>  14:16    frank604| strange behavior though.  first workspace swap unfreezes after a second
>  14:16    frank604| but swaps after that it remains 'frozen' visually only
>  14:17       fiete| i think that it is not windowmanager related but related to loosing focus
>  14:21    frank604| I only noticed this when I switched from dwm to xmonad this week.  It 
>                     does feel like qutebrowser is unable to tell wm it is focused (active) 
>                     or wm is unable to signal to qutebrowser that it is in focus.  Just my 
>                     amateur guess.
>  14:23  The-Compil| frank604: and you're sure it's fine with dwm still?
>  14:23  The-Compil| frank604, fiete: intel graphics by any chance?
>  14:23    frank604| yes
>  14:23    frank604| sorry, yes to intel, i'll restart into dwm to verify.  one moment
>  14:24    frank604| before I go to dwm, in xmonad on 0.8.2, if i stay in workspace 2 
>                     (terminals) for a few minutes and go back to workspace 1(qutebrowser), 
>                     the issue doesn't show
>  14:25       fiete| The-Compiler: yeah intel graphics here
>  14:25  The-Compil| starting to wonder if it's that
>  14:25  The-Compil| both on Arch?
>  14:25       fiete| gentoo here
>  14:25  The-Compil| FWIW:
>  14:26    frank604| arch here, and now i'm in dwm.  bug doesn't show
>  14:26  The-Compil| hmm, weird
>  14:26    frank604| still on 0.8.2 clean configs
>  14:26       fiete| perhaps dwm handles focus stuff different than hlwm or xmonad
>  14:26  The-Compil| I wonder if you see the same with other Qt applications too
>  14:26    frank604| fiete, what are you using de/wm? just curious
>  14:26       fiete| hlwm
>  14:27       fiete| The-Compiler: so you think i should try to reproduce with otter?
>  14:27    frank604| The-Compiler: recommend a qt application i'll test.  
>  14:28  The-Compil| otter-browser sounds like a good reproducer, yeah
>  14:30       fiete| hm otter conflicts with my qt-5.7 installation
>  14:30       fiete| or at least the ebuild
>  14:31    frank604| i'm compiling otter right now, almost there
>  14:37    frank604| otter is fine
>  14:37    frank604| in dwm and xmonad
>  14:42  The-Compil| that's weird...
>  14:42  The-Compil| Can you please open an issue with the information we have so far? Right 
>                     now I have no idea what could be wrong, and I need to sleep ;)
>  14:49    frank604| Sleep well! Will do.
>

**Comment by The-Compiler** [comment]
I can reproduce this - toggling fullscreen also makes it go away.

Are you both using `--backend webengine` by any chance?

cc @fiete201

**Comment by frank604** [comment]
Yes, I forgot to test with qtwebkit.  Should I?

**Comment by The-Compiler** [comment]
Please do! If it works with that, it'd also explain why Otter worked.

**Comment by fiete201** [comment]
I only use --backend webengine since months :-D

**Comment by frank604** [comment]
Issue does not exist when running on qtwebkit.  r10652.6019e09-1

**Comment by The-Compiler** [comment]
I can't reproduce this with Qt 5.7.1 anymore.
