### ISSUE TITLE
Add delay to successful hint choice when hint mode = number

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [The-Compiler/qutebrowser#2107]
As soon as you follow a link by typing some of the text in it, qutebrowser interprets your keypresses, so if it followed a link while you were typing a word, the rest of the letters get interpreted.

E.g., I'm following a link to "Options", so I start typing that word, then it might follow the link after the first three letters "opt", so then it will go into input mode when I press i straight after.

So maybe adding a <x> second delay before interpreting keypresses, after following a link in numbered-hints mode, could solve this issue?

**Comment by The-Compiler** [comment]
See the `hints -> auto-follow-timeout` [setting](https://github.com/The-Compiler/qutebrowser/blob/master/doc/help/settings.asciidoc#hints-auto-follow-timeout) :wink:

**Comment by sfgasdfsafggfgg** [comment]
haha! thanks!
