### ISSUE TITLE
Closing tabs does not update list of buffers in :buffer (QtWebEngine)

### ISSUE THREAD

**Issue by 5225225** [The-Compiler/qutebrowser#2109]
```
qutebrowser v0.8.4
Git commit: v0.8.0-1773-gd8d7b42 (2016-11-10 09:03:56 +0100)
```

If you open two tabs, then use `:buffer`, the auto completion will have both of them be shown. If you then close one of them using `d`, the auto completion will be out of date until you open a new tab or refresh a tab.

**Comment by The-Compiler** [comment]
I just happened to implement the basics needed to make this work in the `webengine-prompts` branch, so this will be fixed by 22c0085ac344e9e68c1be2d0cb0b5971fa462d6f once that's merged.
