### ISSUE TITLE
RFC: Get rid of --datadir/--confdir/--cachedir?

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#2115]
I'm thinking about getting rid of the `--datadir`/`--confdir`/`--cachedir` arguments, as we have `--basedir` and `--temp-basedir` already, which should probably be sufficient?

At the very least I want to get rid of being able to pass empty values to not store that kind of data at all, but ideally I think we'd get rid of them entirely. Is there a reason why we shouldn't?

**Comment by dragonmaus** [comment]
I realise that this is a "dead'n'gone" issue, but having a single directory option makes it impossible to comply with the XDG specification on systems that do not automatically do so (read: Windows).

More specifically, I need my config, cache, and data directories to be in different locations, but I cannot with the current options.

**Comment by The-Compiler** [comment]
@dragonmaus Can you elaborate on why you need that?

**Comment by dragonmaus** [comment]
@The-Compiler I have a fairly restrictive* setup at work, with multiple drives that have specific purposes and limitations. This includes a backed up, size-limited "home" drive (where I point XDG_CONFIG_HOME), and a "scratch" drive that is not backed up for volatile and working data (where I point XDG_CACHE_HOME and XDG_DATA_HOME).

* meaning that I cannot create links or aliases in the filesystem
