### ISSUE TITLE
QWebEngine focus issues

### ISSUE THREAD

**Issue by cosminadrianpopescu** [The-Compiler/qutebrowser#2116]
With QtWebEngine, on some sites, the focus is lost from the main widget after opening a link in another tab. For example, go to `https://duckduckgo.com/?q=squid&ia=videos`, then click on `<Shift-F>`, open any link, then go back to the `duckduckgo` tab. The focus is lost. You cannot do anymore `j`, `k` and when trying to follow another link (do again `f` or `<Shift-F>`). The hints are displayed but cannot be followed. 

After some investigation, in `webenginetab.py` the `_event_target` function appears to be returning another `_widget` instance after following a link in a new tab. If I add this line:

```
    def _event_target(self):
        if not self._focus_widget:
            self._focus_widget = self._widget.focusProxy()
        return self._focus_widget
```

the problem is fixed, but I don't fully understand `focusProxy` and I don't exactly know what impact this would have.

You have attached my `qute:version` page.
[-tmp-file.txt](https://github.com/The-Compiler/qutebrowser/files/586640/-tmp-file.txt)

**Comment by The-Compiler** [comment]
I can't reproduce this - but interestingly, the new tab always opens in the background, even with `background-tabs` set to false.

I don't think your fix will work - I had something similar first, but then stuff broke when loading e.g. a new page (as the `focusProxy` changed).

Also, your qute:version file only contains "Once upon a time..." :laughing:

**Comment by cosminadrianpopescu** [comment]
[version.txt](https://github.com/The-Compiler/qutebrowser/files/588036/version.txt)

**Comment by cosminadrianpopescu** [comment]
Sorry. I uploaded again the version file. 

I am on a manjaro linux, and on `duckduckgo` with `qtwebengine` I always lose focus after the first follow hint in a new tab. This also happens on other sites, but I thought that `duckduckgo` is the most common. As soon as the proxy will work, I will be able to also test the `qtwebengine` on a windows environment. 

It might be also related with my desktop environment? I am using i3 window manager, which is probably not that common.

**Comment by The-Compiler** [comment]
I'd say i3 is pretty common with qutebrowser users :wink: FWIW I'm on another tiling WM ([herbstluftwm](http://www.herbstluftwm.org/))

Can you reproduce this with `--temp-basedir` and then do `:report` so I get the debug log?

**Comment by cosminadrianpopescu** [comment]
done

**Comment by NoctuaNivalis** [comment]
> I can't reproduce this - but interestingly, the new tab always opens in the background, even with background-tabs set to false.

Wait, for me the new tab always opens in the foreground, even with background-tabs set to true.

(And on topic, I can't reproduce this)

**Comment by The-Compiler** [comment]
FWIW with today's [changes](https://github.com/The-Compiler/qutebrowser/commit/5de07246be9e0c34ebdad8a6da297b50ee6b2826) on how clicks are handled with QtWebEngine, `background-tabs` is respected correctly for me.

@cosminadrianpopescu did that change anything for you by any chance? How exactly are you switching tabs?

**Comment by cosminadrianpopescu** [comment]
With the latest update it's ok for me also. Thank you.
