### ISSUE TITLE
WebEngine: crash when opening link in new tab

### ISSUE THREAD

**Issue by sebastian-frysztak** [The-Compiler/qutebrowser#2119]
[qutelog.txt](https://github.com/The-Compiler/qutebrowser/files/589985/qutelog.txt)
It doesn't happen all the time, but I reproduced it twice. It only happens when I use middle-click, never with hints.

**Comment by edi9999** [comment]
I happen to have the same issue, but it seems to be reproducible everytime

If I hit f, and then any two keys, I get the same error

**Comment by The-Compiler** [comment]
Reproduced by hinting something which is not a link (which sets `override_target` for the tab) and then middle-clicking (which uses the `override_target` which was set before but never reset).

Not sure what a good solution would be yet...
