### ISSUE TITLE
q<Fn> tries to record macro

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#2125]
I'm not sure if this is solved in #2113, but currently when doing `q<Fn>` I get `Recording macro ''...`

cc @blyxxyz

**Comment by blyxxyz** [comment]
I can't reproduce it on either branch. I remember that another laptop got a `XF86WakeUp` KeyPress event when pressing Fn, though. Can you use `xev` to check what kind of X events Fn sends?

I can record macros for other weird keys, like `XF86AudioMute`. Ignoring them would be better.

**Comment by The-Compiler** [comment]
Yep, `XF86WakeUp` indeed.
