### ISSUE TITLE
Feature request: ability to use completion history with :spawn

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [The-Compiler/qutebrowser#2127]
For example, I type something like `:spawn mpv` then press tab and it shows me the completion list for the history. This way I can easily watch a video in my history without having to go to the url/search for the video again.

**Comment by The-Compiler** [comment]
You can already enter `:spawn` and then press `ctrl-p`/`ctrl-n` for the command history. That's unrelated to the completion though, and I don't think the completion for `:spawn` should have a history separate from that :wink:

**Comment by The-Compiler** [comment]
On a second thought, this could be generalized for any commands when we have composable completions (on which @rcorre is working on currently) - so I added it to #32.
