### ISSUE TITLE
[webengine] Qutebrowser not redisplaying when changing desktops in insert mode or with a youtube video

### ISSUE THREAD

**Issue by jgkamat** [The-Compiler/qutebrowser#2131]
This has been a bug for me ever since I started using the webengine version of qutebrowser. It's a little tough to explain, so here's a youtube video: https://www.youtube.com/watch?v=QI0na4CCdqc&feature=youtu.be

Essentially, the browser freezes when I switch desktops on bspwm under certain conditions. Maybe this could be fixed by forcing a refresh when focus is received?

Steps to reproduce:
1. Enter insert mode
2. Switch away from qutebrowser to a new desktop
3. Switch back to qutebrowser
4. Try to insert text

Or:
1. Play youtube video
2. Switch away
3. Switch back

I can 'unfreeze' the browser by:
1. Opening the completion tab somehow (eg: `o`)
2. Entering Insert mode
3. Sometimes, j/k works, but not always.

In a simple test (without insert mode, plain webpage), this issue does not occur. 

I can only reproduce this on the webengine backend, this is not an issue with qtwebkit.

Let me know if I can provide any more information about this, here's my qute://version:

```
qutebrowser v0.8.4
Git commit: v0.8.0-1851-gd115475 (2016-11-16 22:35:20 +0100)

CPython: 3.5.2+
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
Webkit: no
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.7.0-1-amd64-x86_64-with-debian-stretch-sid, 64bit
Frozen: False
Imported from /home/jay/.virtualenvs/qutebrowser/local/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian

Paths:
config: /home/jay/.config/qutebrowser
download: /home/jay/Downloads
cache: /home/jay/.cache/qutebrowser
runtime: /run/user/1000/qutebrowser
data: /home/jay/.local/share/qutebrowser
system_data: /home/jay/.local/share/qutebrowser
```

PS: Thanks for the work on qtwebengine, qutebrowser is fantastic!

**Comment by The-Compiler** [comment]
I've seen that happen too with herbstluftwm, and got reports of it happening with xmonad too. It's probably a QtWebEngine bug though, but no idea what causes it.

FWIW I usually fullscreen/unfullscreen it via my WM's keybindings.

**Comment by haasn** [comment]
I get bugs in xmonad where qutebrowser stops responding/repainting after switching to workspaces until I resize the window (even if only by 1 pixel)

Also only happens with qtwebengine.

**Comment by gnosticscrounger** [comment]
I can confirm the exact same bug happens to me too (bspwm)

**Comment by The-Compiler** [comment]
https://bugreports.qt.io/browse/QTBUG-57416

**Comment by The-Compiler** [comment]
https://bugreports.qt.io/browse/QTBUG-57416?focusedCommentId=339175&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-339175 says this could be fixed in Qt 5.7.1

**Comment by The-Compiler** [comment]
I don't see this anymore with Qt 5.7.1.

**Comment by haasn** [comment]
> I get bugs in xmonad where qutebrowser stops responding/repainting after switching to workspaces until I resize the window (even if only by 1 pixel)

Still happens to me on 5.7.1, still only with webengine (so it's not a huge priority for me). It might be site-dependent, the specific site that triggers the issue for me is the `netdata` dashboard. An example can be found here:

http://london.my-netdata.io/default.html

**Comment by jgkamat** [comment]
@haasn sorry, I'm not able to reproduce it either on 5.7.1 anymore either (bspwm). The website you gave (and youtube videos/insert mode) seem to work normally for me. There's another person in the QTBug who says 5.7.1 didn't fix it, so maybe the but still exists but only triggers under very specific circumstances?
