### ISSUE TITLE
Time zones are not applied correctly

### ISSUE THREAD

**Issue by zuglufttier** [The-Compiler/qutebrowser#2133]
Hi,

some web sites show date and time and ask the browser for this, eg: http://browserspy.dk/date.php

If I visit the site with firefox `Time-Zone offset` says `-60 minutes`, qutebrowser however `0 minutes`.

This results in different outputs for `Time and date`, everything else is identical.

Using current version from git an Arch Linux.

**Comment by The-Compiler** [comment]
With the QtWebEngine backend I assume?

**Comment by zuglufttier** [comment]
Correct!

**Comment by The-Compiler** [comment]
That's a Qt bug, fixed upstream in Qt 5.7.1 - see [QTBUG-55125](https://bugreports.qt.io/browse/QTBUG-55125).
