### ISSUE TITLE
Release tarball v0.8.4 has outdated changelog

### ISSUE THREAD

**Issue by torsava** [The-Compiler/qutebrowser#2135]
The source tarball for the [latest release—v0.8.4](https://github.com/The-Compiler/qutebrowser/releases/tag/v0.8.4)—contains an outdated changelog. The newest entry therein is:

    v0.8.3 (unreleased)

**Comment by The-Compiler** [comment]
That's what I get for doing releases in the middle of the night :laughing:

Nothing I can do about this now, but updating the changelog is in my release checklist, so things should look better with v0.8.5/v0.9.0.

Thanks for letting me know though!
