### ISSUE TITLE
Rare scrolling issue on some pages

### ISSUE THREAD

**Issue by troubas** [The-Compiler/qutebrowser#2137]
Qutebrowser seems to be unable to guess height of the following page: https://www.bsi.bund.de/DE/Themen/ITGrundschutz/ITGrundschutzKataloge/Inhalt/_content/m/m06/m06076.html
Qutebrowser version: `v0.8.0-1852-gc5cacbc (2016-11-21 06:22:38 +0100)`

---

*edited by @The-Compiler to fix the broken URL*

**Comment by The-Compiler** [comment]
That's with `--backend webengine`, right?

**Comment by The-Compiler** [comment]
Ah, nevermind - I can reproduce it with both QtWebKit and QtWebEngine. Not sure what magic that page does...

**Comment by troubas** [comment]
Can you point me to the calculation height of the current websites height?

**Comment by The-Compiler** [comment]
@troubas For QtWebKit, it simply [queries Qt's scroll bar](https://github.com/The-Compiler/qutebrowser/blob/97d23144f7d98f87a346df035eeb9040e05368dc/qutebrowser/browser/webkit/webview.py#L213-L241).

For QtWebEngine, it [gets the data via Javascript](https://github.com/The-Compiler/qutebrowser/blob/4407ef032af44f13e9724ab20483288962abec75/qutebrowser/javascript/scroll.js#L74-L99), and then [calculates the percentage](https://github.com/The-Compiler/qutebrowser/blob/97d23144f7d98f87a346df035eeb9040e05368dc/qutebrowser/browser/webengine/webenginetab.py#L253-L284) in Python.

**Comment by troubas** [comment]
@The-Compiler Thanks. very convienient!

So it turns out Chromium has the same issue, Firefox does not.

According to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight) the `scrollHeight` property is supposed to be a
> measurement of the height of an element's content, including content not visible on the screen due to overflow.

Making this a bug in the QtWebengine/QtWebkit?

Whereas [this](https://github.com/hashchange/jquery.documentsize) project proclaims the expected behaviour somewhere along the lines of 'scrollHeight is the viewport of a div and not the size of its content'.

Not sure anymore what `scrollHeight` is supposed to represent. But I think there is no easy fix for this issue at the moment.

From my side we can close this issue.

_Offtopic Question_
When there are multiple divs with `overflow: scoll` and a fixed height qutebrowser does tend to get confused. Is there a way to select (without using the mouse) which div one wants to scroll in?
Because even though I can't jump around on the page I can at least scroll it (Once I click in the area that I wan't to scroll in).

**Comment by The-Compiler** [comment]
I'm going to believe MDN rather than some random project :laughing: 

I think the issue basically is that there are various nested div's on the page, and the inner div is actually scrollable. That'd mean qutebrowser would have to iterate through all div's and see if any of them is scrollable, which is probably not feasible, so I'm closing this.

As for your question, what does "tend to get confused" mean? Unfortunately you can't select what to scroll with the keyboard, for a similar reason (it'd have to find a scrollable div). I added that to https://github.com/The-Compiler/qutebrowser/issues/521#issuecomment-263498314 though.
