### ISSUE TITLE
Youtube video page capturing keyboard input when not in input mode (Webengine)

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [The-Compiler/qutebrowser#2138]
Using the WebEngine backend, if you goto a youtube video page and press `j`, the embedded video reduces volume and the page doesn't scroll. I think this should only happen when explicitely in input mode.

**Comment by The-Compiler** [comment]
This happens with both backends, and is because hjkl simply emulate cursor keypresses. You can rebind them to use `:scroll-px` instead. That'll scroll, but it doesn't work on some pages with multiple scrollable div's.

**Comment by sfgasdfsafggfgg** [comment]
ah ok, thanks
