### ISSUE TITLE
[[feature]] – Ability to Scroll Page without Moving Cursor in Caret Mode

### ISSUE THREAD

**Issue by WammKD** [The-Compiler/qutebrowser#2143]
A thing I often use while reading from a web browser is highlighting part of the text and then using <shift> and the arrow keys to move the highlight along as I read, in a similar way as using your finger as you read from a book.

In most minimal browsers (I've used Uzbl and Luakit the most), this can be done in Insert mode. While I can do the same in Caret mode for Qutebrowser, there's no way to scroll the page downward (or upward). The arrow keys move the cursor but that loses the position you were at in reading and changing back to Normal mode – and then Caret mode, again – often resets the cursor's position.

 I couldn't find any commands that did that in Caret mode and other page-scrolling commands (such as :scroll-page) didn't work in Caret mode.

**Comment by The-Compiler** [comment]
Things like `:scroll-page` or `:scroll` won't work as they simply emulate keypresses, and QtWebKit will handle them differently in caret mode.

However, `:scroll-px` works fine (but has some issues on pages with multiple scrollable div's, which is why `:scroll` is used by default), so you can do:

```
:bind --force --mode=caret <Ctrl-j> scroll-px 0 50
:bind --force --mode=caret <Ctrl-k> scroll-px 0 -50
```

Hope that helps! We might want to add that as a default binding, though `Ctrl-j` is alread occupied as an alternative to enter to yank chars...

**Comment by WammKD** [comment]
That's perfect! I was able to make a binding for scrolling and for jumping a whole page, which was really cool.

I was also able to use it for another issue I was having regarding Insert vs Normal mode. If you aren't too busy and don't mind me asking – I was curious –, was there any reason you chose to use `:scroll` (namely, since it emulates keypresses)? I mostly ask since, in a lot of other minimalist browsers, the Normal mode restricts any interaction with the webpage and, by `:scroll` emulating keypresses, you can often end up interacting with the web-page.

An easy example is YouTube; I always hate it when I load a page and then try to scroll down but it ends up lowering the volume or some such on the video. By using Normal mode as a split from interacting with the web page and allowing Insert mode to be a sort of interaction entry, you get more control but the current setup seems to sort of blend the two.

**Comment by The-Compiler** [comment]
#669 and the issues linked from there have some more details.

We can revisit that for QtWebEngine, but at least with QtWebKit, I think emulating keypresses is the better trade-off.

Also I'm closing this issue as it's solved :wink:
