### ISSUE TITLE
Pass integration

### ISSUE THREAD

**Issue by arkhan** [The-Compiler/qutebrowser#2153]
Hello,

It's posible to integrate [www.passwordstore.org](www.passwordstore.org) to qutebrowser like [passff](https://github.com/nwallace/passff.git)

Thank's

**Comment by lamarpavel** [comment]
Take a look at https://github.com/The-Compiler/qutebrowser/pull/873

**Comment by The-Compiler** [comment]
As @lamarpavel mentioned, the `password_fill` userscript should work.

As soon as there's a plugin API (see #30) there'll also be a plugin for that.
