### ISSUE TITLE
Unable to use PipeLight

### ISSUE THREAD

**Issue by SteveDeFacto** [The-Compiler/qutebrowser#2158]
qutebrowser v0.8.4

Most other browsers I've used will load pipelight. However, QuteBrowser doesn't appear to work with it. The allow-plugins option is set to true.

**Comment by The-Compiler** [comment]
How can I test this in other browsers? When I install `pipelight` and open https://www.microsoft.com/silverlight/iis-smooth-streaming/demo/ I still get the "Install Silverlight" banner.

**Comment by The-Compiler** [comment]
FWIW even with `sudo pipelight-plugin --enable silverlight` I can't get things to work in e.g. Firefox.

**Comment by The-Compiler** [comment]
Any updates, @SteveDeFacto?

**Comment by The-Compiler** [comment]
Well then ¯\_(ツ)_/¯ :wink:
