### ISSUE TITLE
XF86Back and XF86Forward buttons do not work with WebEngine backend

### ISSUE THREAD

**Issue by Zekario** [The-Compiler/qutebrowser#2166]
qutebrowser v0.8.4
Git commit: 34v0.8.0-1937-g5746337
The media keys for navigating forward and backward in the history do not appear to work when using the WebEngine backend. They work as expected when using the WebKit backend.

**Comment by The-Compiler** [comment]
I implemented and tested that some weeks ago, but it's possible this broke somehow, as there's no automated test for it :wink:

Unfortunately I don't have a mouse with those buttons ready right now - can you please reproduce it with `--temp-basedir --backend webengine` and do `:report` after that?

**Comment by Zekario** [comment]
@The-Compiler I did that, and the log said 

DEBUG    keyboard   basekeyparser:_debug_log:112 No special binding found for back.

or

DEBUG    keyboard   basekeyparser:_debug_log:112 No special binding found for forward.

I will try binding 'back' and 'forward', and likely edit this comment to say whether or not simply binding them in the configuration works.

**Comment by lahwaacz** [comment]
My mouse issues "click events" as buttons 8 and 9 and that works fine in qutebrowser. As far as I know, XF86* are only keyboard symbols, never mouse buttons. It should be possible to bind those with `:bind <back> back` and `:bind <forward> forward`.

**Comment by Zekario** [comment]
@lahwaacz That fixed it for me, thanks. I wonder why it works without needing to be bound in WebKit... Does it and the WebEngine backend have different default keybindings?

**Comment by The-Compiler** [comment]
Ah, right - I somehow thought of mouse buttons here :wink:

It's possible QtWebKit somehow handles those keys by itself while QtWebEngine does not. I guess qutebrowser should just add those bindings by default.
