### ISSUE TITLE
Monospace fonts not shown

### ISSUE THREAD

**Issue by tudurom** [The-Compiler/qutebrowser#2170]
Monospace fonts are replaced with sans-serif.

![Screenshot](http://pub.iotek.org/p/ggw3Mv9.png)

[Version information](http://hastebin.com/ceyivevede.txt).

**Comment by The-Compiler** [comment]
This is probably related to the Qt bug mentioned in #1648 too, though I'll need to take a closer look.

Does `:set fonts web-family-fixed Monospace` help?

**Comment by tudurom** [comment]
Yes, it helps indeed. Thank you very much!
