### ISSUE TITLE
Don't remember temporary download directory

### ISSUE THREAD

**Issue by swalladge** [The-Compiler/qutebrowser#2173]
I have the following settings:

storage -> download-directory = ""
storage -> prompt-download-directory = true
storage -> remember-download-directory = true

I noticed something unusual about the suggested download directory:

1. run `:download` to open the download prompt
2. note the suggested download location is my home directory or something
   'normal'
3. type `<c-x>` to open the file instead of save
4. later run `:download` again on some page
5. note the suggested download location is `/tmp/qutebrowser-download-xxxxxx/`

I believe this to be a result of the `remember-download-directory` option remembering where the previously downloaded (opened) file was downloaded to (the temp dir) and suggesting that. 

The behaviour should be that it only remembers the download location of the previously _downloaded_ file (not downloaded to a temporary location to be opened).

**Comment by The-Compiler** [comment]
What version and backend are you seeing this with? I can't reproduce this, neither with QtWebKit nor QtWebEngine.

**Comment by swalladge** [comment]
Version is latest git master, and backend QtWebEngine. I can't redproduce either with the qtwebkit backend.

Did some more testing - I can reproduce it reliably with urls for pdf files, but not with html pages. I have pdf.js enabled in settings, but iirc it's not implemented for the webengine backend yet, so opening a pdf opens a blank page and the download prompt - then the page doesn't auto-close once it's downloaded.

**Comment by The-Compiler** [comment]
So when I use `C-x` on the automatic download prompt, I can't do `:download` on the same page (as it's an invalid URL). When I then do `:download` on a different page, I still can't reproduce this.

Can you please reproduce this with `--temp-basedir` and then do `:report` and mention this issue?

**Comment by swalladge** [comment]
Reproduced and reported. I also did the same thing and screen-recorded it - see https://nextcloud.walladge.net/s/gMabrbax8qSnd2X

**Comment by The-Compiler** [comment]
Oh, my bad! I just got confused between `/tmp/qutebrowser-basedir-*` and `qutebrowser-downloads-*` :blush: 

I can indeed reproduce it now, relevant part of the logs:

```
12:22:37 DEBUG    prompt     prompt:ask_question:151 Asking question <qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-im0_cjpa/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.buildeazy.com/plans/test.pdf</b>' title='Save file to:'>, blocking True, loops [], queue deque([])
[...]
12:22:38 DEBUG    commands   command:run:524 Calling qutebrowser.mainwindow.prompt.PromptContainer.prompt_open_download(<qutebrowser.mainwindow.prompt.PromptContainer win_id=0>, None)
12:22:38 DEBUG    downloads  downloads:_set_filename:605 Setting filename to /tmp/qutebrowser-downloads-8lghmrl0/tmpqd1ly8vstest.pdf
[...]
12:22:38 DEBUG    prompt     prompt:ask_question:188 Ending loop.exec_() for <qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-im0_cjpa/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.buildeazy.com/plans/test.pdf</b>' title='Save file to:'>
[...]
12:22:38 DEBUG    downloads  webenginedownloads:_on_state_changed:54 State for <qutebrowser.browser.webengine.webenginedownloads.DownloadItem basename='tmpqd1ly8vstest.pdf'> changed to DownloadCompleted
12:22:38 DEBUG    downloads  webenginedownloads:_on_state_changed:61 Download tmpqd1ly8vstest.pdf finished
12:22:38 DEBUG    downloads  downloads:open_file:526 Opening /tmp/qutebrowser-downloads-8lghmrl0/tmpqd1ly8vstest.pdf with the system application
[...]
12:22:41 DEBUG    prompt     prompt:ask_question:151 Asking question <qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-downloads-8lghmrl0/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.buildeazy.com/plans/test.pdf</b>' title='Save file to:'>, blocking True, loops [], queue deque([])
```

cc @Kingdread

**Comment by Kingdread** [comment]
I guess the problem is that the webengine downloads just use [`self._set_filename`](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/webengine/webenginedownloads.py#L98-L99) to handle temporary downloads. `_set_filename` in turn [always remembers the last used directory](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/downloads.py#L603). webkit [doesn't do this](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/qtnetworkdownloads.py#L227-L228). Though I'm not sure yet why this only happens with PDF files and not with `:download`.

I guess I'll just add a flag to `_set_filename`.
