### ISSUE TITLE
eBay checkout with PayPal not working with WebEngine

### ISSUE THREAD

**Issue by vktec** [The-Compiler/qutebrowser#2177]
At eBay checkout, selecting the PayPal payment option works fine with WebKit, but not with WebEngine.

With WebKit, the PayPal login page opens in a new tab, as it's supposed to; with WebEngine, about:blank is opened in a new tab instead.

I've tested this with `qutebrowser --temp-basedir` (worked) and `qutebrowser --backend webengine --temp-basedir` (didn't).

## How to reproduce:

Add an item to your eBay cart, go to checkout, select PayPal as payment option.

## Version info:

```
qutebrowser v0.8.4
Git commit: v0.8.0-1922-gcaf1950 (2016-12-06 20:28:18 +0100)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.8.11-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
runtime: /run/user/1000/qutebrowser
config: /home/vktec/.config/qutebrowser
download: /home/vktec/Downloads
system_data: /home/vktec/.local/share/qutebrowser
data: /home/vktec/.local/share/qutebrowser
cache: /home/vktec/.cache/qutebrowser
```

**Comment by The-Compiler** [comment]
I'd rather not try to buy something on eBay to reproduce this  :wink:

Could you please try to reproduce it with Qt 5.7.1 which got released a few days ago? I think this is caused by the workaround for a bug in Qt 5.7.0, so I'd expect it to be fixed now.

**Comment by The-Compiler** [comment]
Any update, @vktec?

**Comment by vktec** [comment]
Oops, sorry. I'll test again now.

**Comment by vktec** [comment]
Yep, it appears to be working now.
