### ISSUE TITLE
Feature request: tab completion in prompt mode

### ISSUE THREAD

**Issue by JonathanReeve** [The-Compiler/qutebrowser#2179]
When downloading a file, I'd like to be able to type the path as in a shell, with tab-completion. So that if I want to download a file to /home/me/a-really-really-long-dir-name/, I can just start typing and press <tab>. What I like about Vimperator is that you can download a website, PDF, or other location with just the command-mode command `:w /path/to/download/to`.

**Comment by The-Compiler** [comment]
In the current git master, there is already some kind of tab completion, however currently tab just cycles through the directories, without looking at what you already typed after the last slash. Improving that is tracked in #2104.

You can also use `:download -d /path/to/download/to` with qutebrowser, but that currently doesn't have any filename completion at all. That's tracked in #32 though.
