### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#218]
For @regines, on Twitter suddenly the arrow keys didn't work anymore, on f2dcb8f.

Maybe the focus was set wrong? We were in normal keymode...

IIRC, switching tabs solved it.

Report: http://paste.the-compiler.org/view/raw/f017d8fd

**Comment by The-Compiler** [comment]
Same on http://grml.org/ - see http://paste.the-compiler.org/view/02134715

**Comment by The-Compiler** [comment]
http://paste.the-compiler.org/view/d6e9cef3

**Comment by The-Compiler** [comment]
And http://femfreq.tumblr.com/post/109319269825/one-week-of-harassment-on-twitter

**Comment by The-Compiler** [comment]
Also on Tiny Tiny RSS, see http://paste.the-compiler.org/view/b58669a2

**Comment by The-Compiler** [comment]
http://chicagotransitproject.com/

**Comment by The-Compiler** [comment]
https://mega.co.nz/#sync

**Comment by The-Compiler** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-overview.html

**Comment by The-Compiler** [comment]
Unfortunately f49dba6 also caused some new issues, like j/k selecting results on DuckDuckGo or h/l switching images on Imgur...

Some other issues:

- Scrolling up/down on http://www.salzburg.com/nachrichten/welt/wirtschaft/sn/artikel/erfinder-des-www-warnt-vor-abschaffung-der-netzneutralitaet-171052/ doesn't work at all, left/right works
- Scrolling on "Impressum und Rechtliche Hinweise" on http://www.asiagourmet.at/ doesn't work with j/k (#1209 maybe?)

**Comment by lamarpavel** [comment]
Another example where scrolling doesn't work with hjkl (it does work with the touch pad and when in visual mode):

http://gpuopen.com/compute-product/hip-convert-cuda-to-portable-c-code/

**Comment by lahwaacz** [comment]
Another one is http://www.csfd.cz/ (sorry for the non-English page).
When loaded, scrolling with `j`/`k` does not work and the cursor inside search box is blinking. After pressing `Esc`, the cursor stops blinking and `j`/`k` scrolling starts working. I have `forward-unbound-keys = none`, which means that `Esc` is not forwarded to the webview?

**Comment by troubas** [comment]
Propably also in this category: `hj` doesn't work on an opened option html tag while arrows do work. It would be nice to select an option without having to switch to the mouse.

**Comment by The-Compiler** [comment]
@troubas FWIW what you can do is to enter insert mode (`i`) and start typing the beginning of an option.

**Comment by troubas** [comment]
@the-compiler that's actually worth alot. thanks.

Date: Fri, 3 Jun 2016 04:15:45 -0700

**Comment by The-Compiler** [comment]
Closing this - #1354 is still worth a try, but other than that, scrolling seems to work okay nowadays.
