### ISSUE TITLE
PyQt5 required. libQt5Core.so.5 not found.

### ISSUE THREAD

**Issue by funghetto** [The-Compiler/qutebrowser#2181]
I get this error when I start qute even if PyQt5 should be installed:

bash-4.3$ pip3 -vvv install PyQt5
Requirement already satisfied: PyQt5 in /usr/lib64/python3.5/site-packages
Requirement already satisfied: sip in /usr/lib64/python3.5/site-packages (from PyQt5)

I'm on Slackware 64bit.

**Comment by The-Compiler** [comment]
Can you please show the output of the following?

- `which pip3`
- `which python3` (assuming you start qutebrowser via `python3 -m qutebrowser`)
- `python3 --version`
- `python3 -c "from PyQt5 import QtCore"`

**Comment by funghetto** [comment]
$ which pip3
/usr/bin/pip3
$ which python3
/usr/bin/python3
$ python3 --version
Python 3.5.2
$ python3 -c "from PyQt5 import QtCore"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory

**Comment by The-Compiler** [comment]
So the error says that it didn't find the Qt5 .so file. However, that should come with PyQt if you install it via `pip`. Maybe it's picking up a different PyQt installation somehow?

What about `python -v -c 'import PyQt5; print(PyQt5.__file__)` ?

**Comment by funghetto** [comment]
Ops, hat Qt in /opt
