### ISSUE TITLE
Strange black flash on ATI multihead

### ISSUE THREAD

**Issue by MichaelMackus** [The-Compiler/qutebrowser#2184]
v0.8.4

Getting a strange black flash on the second screen when spawning a new qutebrowser. I don't get a flash when opening a new window, only when spawning a new process (e.g. dmenu or terminal).

**Comment by The-Compiler** [comment]
This smells more like a Qt/driver issue than a qutebrower one. Some questions:

- What distribution is this on?
- What Qt version? (`qutebrowser --version` will tell you)
- If your distribution packages it, does `qutebrowser --temp-basedir --backend webengine` (with qutebrowser from git) change anything?
- Do you get the same when running `python3 scripts/testbrowser.py qutebrowser.org`?

**Comment by MichaelMackus** [comment]
@The-Compiler actually, now that I think more about this, this is almost definitely a QT bug. I'm on Ubuntu 14.04 on my work computer, and the QT in the repos is out of date (and qtwebengine is not compiling properly, either). I'll close for now and update once I've tried a new(er) QT version.
