### ISSUE TITLE
Feature: Try https first, fall back to http

### ISSUE THREAD

**Issue by mguentner** [The-Compiler/qutebrowser#2185]
When `:open`ing an url like `:open example.org`, qutebrowser should first try to load `https://example.org` and then `http://example.org` if the first request failed.

See [1] for an example for this feature (request).

[1] https://www.eff.org/https-everywhere

**Comment by The-Compiler** [comment]
There's #335 for HTTPS everywhere already. However, note it does not take the approach you describe here but uses a list of URL rewrites - see its [FAQ](https://www.eff.org/https-everywhere/faq#why-use-a-whitelist-of-sites-that-support-https-why-cant-you-try-to-use-https-for-every-last-site-and-only-fall-back-to-http-if-it-isnt-available).
