### ISSUE TITLE
Enhancement: remove any direct XCB calls to allow running on Wayland without XWayland

### ISSUE THREAD

**Issue by tidux** [The-Compiler/qutebrowser#2186]
Right now if you attempt to run Qutebrowser under a Wayland compositor without XWayland running, there is an attempted QXcb call which fails, and then the program fails.

**Comment by The-Compiler** [comment]
qutebrowser doesn't use XCB in its own code - so this should be reported to [Qt's bugtracker](https://bugreports.qt.io/). However, I thought (never tested it myself) that it works fine without XWayland with the QtWebKit backend (not with QtWebEngine, as Chromium doesn't).

**Comment by tidux** [comment]
I've tested this with both backends and had the same issue.  If this is a Qt issue it's common to both, or in Qt itself.

**Comment by tidux** [comment]
Upstream bug found: https://bugreports.qt.io/browse/QTBUG-51631
