### ISSUE TITLE
Captcha is not supported

### ISSUE THREAD

**Issue by Chinggis6** [The-Compiler/qutebrowser#2195]
Those captchas where it requires you to select three correct pictures described or so is not supported in the browser.

**Comment by sfgasdfsafggfgg** [comment]
Are you using the webkit backend or the webengine backend?

**Comment by Chinggis6** [comment]
Probably not, can you please explain me how to do that?

**Comment by sfgasdfsafggfgg** [comment]
you're running with webkit then, try running `qutebrowser --backend webengine`

**Comment by Chinggis6** [comment]
Yeah, fortunately I could already figure that out reading the qutebrowser article on Arch Linux wiki, and found downloaded the package from https://pkgs.org/fedora-25/fedora-x86_64/python3-qt5-webengine-5.7-1.fc25.x86_64.rpm.html, what made me to downgrade other packages relating to Python.

Now I wander how can I avoid typing `--backend webengine` on dmenu (i3wm) everytime.

Could'nt find anything userful on configs (.config/qutebrowser/). I am not sure if alias (on fish shell) would work for dmenu.

Any help would be appreciated.

**Comment by sfgasdfsafggfgg** [comment]
In `qutebrowser.desktop` in your desktop directory, change the `Exec=qutebrowser %u` line to `Exec=qutebrowser --backend webengine %u`.

If you don't have this .desktop file, copy it from `/usr/share/applications/qutebrowser.desktop`.

**Comment by Chinggis6** [comment]
It doesn't work. I tried to copy it both to `~` and `~/Desktop`, and also hide it by prepending `.` with no successes.

Also, <kbd>Ctrl</kbd>+<kbd>Shift</kbd> seems to be gone along with the old engine as I cannot open a link in a new tab (hopefully without leaving the existing and switching to the newly opened tab, what I want) now with `webengine`.

**Comment by sfgasdfsafggfgg** [comment]
ah, try putting it in `~/.local/share/applications/`

**Comment by The-Compiler** [comment]
I just have a binary in `/usr/local/bin/qutebrowser` which runs the real `qutebrowser` with `--backend webengine`. A better way to set this and maybe even QtWebEngine by default will follow somewhen next year with v0.10.0 though :wink:

If you prefer staying with QtWebKit, you can also use `:set network user-agent` and select a Chromium user agent and the captchas will start to work... thanks Google. 😒

**Comment by Chinggis6** [comment]
Please also consider removing the scrollbar that shows up when running the `webengine` backend. It is not compliant with the minimalistic design of the browser. I personally don't use webengine, and use firefox instead alongside qutebrowser when I have to deal with captcha and stuff that the former cannot do.

**Comment by The-Compiler** [comment]
It should already be hidden on v0.9.0 (or git master)

**Comment by sfgasdfsafggfgg** [comment]
@Chinggis6 `:set ui hide-scrollbar true`

**Comment by Chinggis6** [comment]
No such option there (version v 8.4), moreover I copied to .local/share/applications/ the qutebrowser.desktop file, still doesn't work :(

I don't know why. I still have to manually type the web engine and see the scrollbar :'(

**Comment by The-Compiler** [comment]
As I said above:

> It should already be hidden on v0.9.0 (or git master)

so please update :wink:
