### ISSUE TITLE
I really miss the "--confdir" parameter in v0.9.0

### ISSUE THREAD

**Issue by bitraid** [The-Compiler/qutebrowser#2196]
It was very useful for me to have the config file in a costum dir. Can we have that option back?

**Comment by The-Compiler** [comment]
You can set `$XDG_CONFIG_HOME` or use `--basedir` - does one of those two work for you?

**Comment by bitraid** [comment]
I use this feature on Windows systems where XDG_CONFIG_HOME does not work. basedir includes the cache and history, and i wouldn't want that. But i could use symlinks if thats too much trouble. Thanks.

**Comment by The-Compiler** [comment]
Hmm, I might think about bringing it back - out of curiosity, what was your usecase for having the config in a different location with data/cache still being at the default location?

**Comment by bitraid** [comment]
I have made a portable setup of a collection of programs for windows, which run under ConEmu, trying to somehow emulate my linux i3 setup. All the configuration files for the look and feel of the programs (conemu, far manager, qutebrowser,etc) are inside the common installation directory, while the cahe, history, etc are in %appdata% of each user.
