### ISSUE TITLE
Search to switch to tab

### ISSUE THREAD

**Issue by code-hunger** [The-Compiler/qutebrowser#2198]
It'd be nice if we could have some way to filter out open tabs just like the history/bookmarks search, but instead of history items we'd have a list of URLs of the open tabs, and Enter would go to the chosen tab instead of loading the page anew.

One of the primary reasons I use qutebrowser (instead of chromium which I used previously) is that I can safely have 50 tabs open without performance issues.  
Then there comes the problem that I want to go to a specific tab but don't remember its exact number so I have to cycle through the tabs seeking it.

An analogous feature is implemented in vim by the Ctrl-P plugin.

**Comment by The-Compiler** [comment]
You mean like the `:buffer` command / `gt`?

**Comment by code-hunger** [comment]
I feel stupid :D 
Yes, `:buffer`. Never knew that before.

**Comment by jcmuller** [comment]
Would it be possible to also show if the url is already open on an existing tab when the `:open` auto complete dialog is shown?

**Comment by jgkamat** [comment]
Juan C. Muller writes:

> Would it be possible to also show if the url is already open on an existing 
> tab when the :open auto complete dialog is shown?

Yes this should be possible. I was actually planning on working on this 
myself, but if you have some free time I'm happy to review it as well
