### ISSUE TITLE
--qt-name removed?

### ISSUE THREAD

**Issue by dazWiLLiE** [The-Compiler/qutebrowser#2200]
I see that you removed --qt-name, but give no example how to archive the same thing now?

In i3wm, I use qutebrowser on different desktops (and monitors) for different stuff. So it is important to know which qutebrowser instance to put where, resize, float or no float etc.

In newsbeuter for instance I have: `qutebrowser --qt-name newsbeuter %u`,
and in i3: `for_window [class="qutebrowser" instance="newsbeuter"] bla bla bla`

I've tried: `--qt-arg name "test"`, `--qt-arg WM_NAME "test"` etc, which doesn't work.

**Comment by The-Compiler** [comment]
`--qt-arg name "test"` should work fine - are you sure you're trying with a new instance (i.e. with a different `--basedir` or `--temp-basedir`)?

**Comment by dazWiLLiE** [comment]
Strange, now it worked. Oh well, thanks anyway.
