### ISSUE TITLE
No "save to" file browser with :download -m

### ISSUE THREAD

**Issue by stroobandt** [The-Compiler/qutebrowser#2204]
First bug of 2017 and a Happy New Year!
Seen on version 0.9.0:

The command `:download` evokes a nice and handy "save as" file browser.
This is not the case with `:download -m`, nor `:download --mhtml`.

**Comment by The-Compiler** [comment]
Indeed - `_download_mhtml` in `commands.py` calls `downloads.get_filename_question` which sets `PromptMode.text` by default.

@Kingdread do you remember why that was originally? Did we do it that way to avoid dealing with `DownloadTarget` objects in `_download_mhtml`?

**Comment by Kingdread** [comment]
I think [that's exactly it](https://github.com/The-Compiler/qutebrowser/pull/1626/files#diff-f9fd7981a0a2daceb49d44be7dd0290bR765):

```
+        # We set the mode here so that other code that uses ask_for_filename
+        # doesn't need to handle the special download mode.
+        q.mode = usertypes.PromptMode.download
```

Though I now think that this should be changed, especially because of the new download prompt.

**Comment by stroobandt** [comment]
@Kingdread Oh yes! Changing this would make `:download -m` so much more useful.
Thanks for looking that up.
