### ISSUE TITLE
Doesn't update to Version 0.9 in Fedora

### ISSUE THREAD

**Issue by Chinggis6** [The-Compiler/qutebrowser#2216]
`dnf update qutebrowser` results in Nothing to do.

My version is 0.8.4

Please release an RPM binary file for Fedora 25 as well, and/or update the repository (@System/Updates).

https://github.com/The-Compiler/qutebrowser/releases/tag/v0.9.0

**Comment by The-Compiler** [comment]
We don't do any distro package releases (except for Debian because it's not in the repo there).

A Fedora-Bug is auto-opened on a new release though, see https://bugzilla.redhat.com/show_bug.cgi?id=1409371
