### ISSUE TITLE
Text cursor/caret gets placed one or two characters from the beginning of the text after selecting an input using hints

### ISSUE THREAD

**Issue by pkill-nine** [The-Compiler/qutebrowser#2220]
qutebrowser v0.9.0
Git commit: v0.8.0-2055-gad01adbc8 (2017-01-01 17:32:32 +0000)
Backend: Webengine

I think either all the text in the input should be selected, or the text cursor/caret should be at the end of the text.

**Comment by The-Compiler** [comment]
Moving to the end of the field isn't implemented with QtWebEngine yet. So this is currently expected (and working fine with QtWebKit).
