### ISSUE TITLE
open-editor doesn't work

### ISSUE THREAD

**Issue by drselump14** [The-Compiler/qutebrowser#2222]
qutebrowser v0.8.4

launch open editor from insert mode result errors like below 

`Error while spawning editor: The process failed to start` 

Using default gvim command

any help would be appreciated

**Comment by The-Compiler** [comment]
What happens if you launch `gvim` in a terminal?

**Comment by drselump14** [comment]
Thanks for the reply. very appreciated.

Launch `gvim` from terminal will launch macvim succesfully.

**Comment by The-Compiler** [comment]
What does `which gvim` and `echo $PATH` say in the terminal? What does `:debug-pyeval os.environ["PATH"]` say? So you're on OS X?

**Comment by drselump14** [comment]
Thanks for the response.

`which gvim` -> `/Applications/MacVim.app/Contents/MacOS/Vim -g`

`:debug-pyeval os.environ["PATH"]` -> `Traceback (most recent call last):
  File "qutebrowser/misc/utilcmds.py", line 195, in debug_pyeval
  File "<string>", line 1, in <module>
NameError: name 'os' is not defined`

**Comment by The-Compiler** [comment]
What about `echo $PATH` in the terminal? And please try `:debug-pyeval __import__('os').environ['PATH']` instead.

**Comment by drselump14** [comment]
`echo $PATH` -> /usr/local/sbin:/Users/dr_selump14/.rbenv/shims:/Users/dr_selump14/.rbenv/bin:/Users/dr_selump14/Qt5.5.1/5.5/clang_64/bin:/Library/TeX/texbin:/Users/dr_selump14/.rbenv/shims:/usr/local/heroku/bin:/Users/dr_selump14/.rbenv/bin:/usr/local/opt:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/X11/bin:/usr/texbin:/usr/local/rvm/bin:/Users/dr_selump14/skripsi/AWS-ElasticBeanstalk-CLI-2.5.1/eb/macosx/python2.7:/usr/local/iverilog/bin:/Users/dr_selump14/.local/bin::/Users/dr_selump14/.fzf/bin


`debug-pyeval __import__('os').environ['PATH']` -> `'/usr/bin:/bin:/usr/sbin:/sbin'`

**Comment by The-Compiler** [comment]
So OS X (like any unix) searches binary in `$PATH`. Apparently that is set correctly in your shell, but not in the environment qutebrowser is started.

Not sure how that path got set - maybe it should be in `.profile` instead of `.bashrc` if it's set there manually, but I have no idea.

Anyways - either find out how to have that `$PATH` for qutebrowser as well, or set `general -> editor` to the full path `/Applications/MacVim.app/Contents/MacOS/Vim -g`.

Closing this as it's not a qutebrowser issue, but let me know if that helped!

**Comment by drselump14** [comment]
@The-Compiler thank's .. it works, it opens the editor successfully .. but, when I save the text, it won't return the text to editor again.

**Comment by The-Compiler** [comment]
did you add the `-g`?

**Comment by drselump14** [comment]
Ok.. it works... yeeay ...

Last question: is it possible to use <Ctrl-w> to remove word when inside insert mode?
The `rl-unix-word-rubout` looks like only work on command,prompt mode.

Thanks a lot for your kindness

**Comment by The-Compiler** [comment]
Unfortunately not, because someone needs to implement those movements in javascript so they work on the page - see #68

**Comment by drselump14** [comment]
Ok, everything is clear now...
You saved my time a lot.

Thanks

**Comment by yorkbai** [comment]
@drselump14   I meet same problem .  add 
alias gvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'
export PYTHONPATH="/Applications/MacVim.app/Contents/MacOS:$PYTHONPATH"

in /etc/profile and source it . got same error "Error while spawning editor: The process failed to start" , have other setting that I missing? 

osx10.11.6  qb1.3.1  zsh

**Comment by toofar** [comment]
That should be `["/Applications/MacVim.app/Contents/MacOS/Vim", "-g", "-f", "{file}", "-c", "normal {line}G{column0}l"]`, so the `-g` is a seperate argument, not part of the command path.

**Comment by yorkbai** [comment]
@toofar  thanks a lot!  it working now!

**Comment by The-Compiler** [comment]
Let me add why the other things didn't work:

- `alias` only works in the shell (it's a bash feature, not a system-wide thing)
- `PYTHONPATH` only says where Python is searching for Python modules - you'd want to set `PATH` instead, which is where executables are searched.

**Comment by snuffop** [comment]
Emacs Needful   :set editor.command ["emacsclient", "-c", "{file}"]
