### ISSUE TITLE
swipe/scroll/zoom touch support

### ISSUE THREAD

**Issue by Xananax** [The-Compiler/qutebrowser#2223]
Very very very *very* low importance, but it'd be cool if Qute could allow scroll/zoom through finger touches.

I realize this can seem to go a bit against the idea of a keyboard-driven browser, but as far as I'm concerned, I'm less interested in purity and more in actual efficiency/comfort. Since I've gotten a touch screen, which I first deemed to be without any use (it just came with, I didn't specifically pick a touch screen), I find myself sometimes reaching for the screen to scroll while reading. It's sometimes more natural to:  

- precisely scroll with a finger than trying to approximate the wanted level with key strokes
- scanning a long page; swiping and letting the page scroll, stopping it when you see something interesting is pleasant and comes naturally.

I can't say I miss this more than a second per week, but eh. In case it's easy, it'd be cool.

**Comment by The-Compiler** [comment]
This used to work fine for me (on a x1 Yoga) with the QtWebEngine backend, out of the box. However, it doesn't anymore right now it seems. Odd.

**Comment by The-Compiler** [comment]
This works fine for me again since I uninstalled `xf86-input-wacom` and only rely on `-evdev` and `-libinput`. So consider that implemented, even though not by me! 😆

**Comment by Xananax** [comment]
I don't understand, how do you manage wacom support without `xf86-input-wacom`?

**Comment by The-Compiler** [comment]
From what I understand (and I might be wrong here), there are two parts:

- A `wacom` kernel module, which talks to the hardware and creates `/dev/input/event*` devices
- A X driver which reads those events, which can be either the more generic evdev (which I seem to need for finger-scrolling/zooming to work), or the more specific wacom (which I seem to need for my eraser button to work...)

**Comment by Xananax** [comment]
So what you're saying is I the trade off is we either get touch events or an eraser?

**Comment by The-Compiler** [comment]
I'm saying that was the situation for me, yours might be different :wink:
