### ISSUE TITLE
Documentation could do with an explanation about quickmarks vs. bookmarks

### ISSUE THREAD

**Issue by Anaphory** [The-Compiler/qutebrowser#2226]
I think I once stumbled upon it, but I have forgotten what the difference between quickmarks and bookmarks is, apart from the fact that they have different names and are stored in different files (with very similar, but complementary formats: `bookmarks/urls` seems to have `URL Title`, while `quickmarks` has `Title URL`). Oh, and: While `:bookmark-add` has a default argument “This Page”, Quickmarks have two separate commands for “A specified page” and “This Page”.

When should I use which of the two, what is the difference, and how am I supposed to find out?

**Comment by lahwaacz** [comment]
There is #882 about this.

**Comment by Anaphory** [comment]
Ah, good. That points me to the technical discussion, but with nowadays equal searchability of labels/titles, equal accessibility through `:open`, etc., hasn't helped me understand the difference.

**Comment by The-Compiler** [comment]
The point @lahwaacz was likely trying to make is that the plan is to unify them into one. I agree the documentation could be clearer about the distinction in the meantime, because this is coming up from time to time

**Comment by The-Compiler** [comment]
There is an entry in the FAQ now, thanks to @Akselmo!
