### ISSUE TITLE
Revoked SSL certificates don't get caught

### ISSUE THREAD

**Issue by abbradar** [The-Compiler/qutebrowser#2228]
To reproduce: https://revoked.badssl.com/

Presumably we should check certificate against some CRL -- not sure if we can make Qt do this or need to do this by ourselves.

qutebrowser 0.9.0

**Comment by The-Compiler** [comment]
This would be needed to be implemented by the backend, as (at least with QtWebEngine, but possibly also with QtWebKit) there's no API to get the needed certificate information.

For QtWebKit/QtNetwork, there's [QTBUG-12812](https://bugreports.qt.io/browse/QTBUG-12812) about OCSP which hasn't really seen much attention for the past 6 years, so I won't open a bug for CRL support for that...

For QtWebEngine, I just opened [QTBUG-58059](https://bugreports.qt.io/browse/QTBUG-58059).

**Comment by benaryorg** [comment]
Just a little heads up:
CRLs are not used by browsers nowadays anymore.
CRLSets is a proprietary revocation mechanism for either Firefox or Chrome, not sure which one.
OCSP is used for checking certificate revocation status in real-time.
OCSP is usually implemented using soft-fail, meaning if the OCSP responder cannot be reached the certificate is treated as valid.
OCSP is used by all modern browsers.
There is also OCSP stapling which removes most of the disadvantages from OCSP.

**Comment by The-Compiler** [comment]
From what I've gathered from Chromium's [Security FAQ](https://www.chromium.org/Home/chromium-security/security-faq#TOC-What-s-the-story-with-certificate-revocation-) and elsewhere, it looks like Chromium has no way to enable hard-fail for OCSP, and its primary mechanism are [CRLSets](http://dev.chromium.org/Home/chromium-security/crlsets) - so I'm guessing the same would be the case for QtWebEngine.
