### ISSUE TITLE
Mixed HiDPI?

### ISSUE THREAD

**Issue by nabsiddiqui** [The-Compiler/qutebrowser#2229]
It is becoming increasingly common to plug laptops, etc. into HiDPI displays. Is there any way to change the DPI settings automatically based on the monitor plugged in? Firefox, for instance, has this add on: https://addons.mozilla.org/en-us/firefox/addon/autohidpi/

**Comment by lahwaacz** [comment]
This is done by the Qt configuration, not qutebrowser. See `QT_AUTO_SCREEN_SCALE_FACTOR` here: https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by nabsiddiqui** [comment]
Ok thank you.  I run a script that activates when I hotplug a monitor so I will see how to change this command line wise.

Is there a way to implement something like this for the zoom level perhaps though?

**Comment by lahwaacz** [comment]
Why? The entire point of the DPI configuration is to avoid manual zooming...

**Comment by nabsiddiqui** [comment]
The QT setting would result in a DPI for all applications rather than just the browser, which could be different.  For instance, a user may reasonably want larger text but not necessarily icons(or vice versa).

**Comment by The-Compiler** [comment]
Environment variables are per application, you can set it for qutebrowser only. I don't think we should have a setting or anything for the zoom doing something different on different screens.

**Comment by lahwaacz** [comment]
Also I don't get why you mention enlarging text, but not icons. If you configure the per-screen DPI correctly, the application (both text and icons) should look the same on all screens. That is, the size of the objects, measured in inches rather than pixels, should be the same.
