### ISSUE TITLE
quickmark-save opens prompt in all windows

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#2231]
`quickmark-save` shows a prompt in every qutebrowser window, even though it only applies to the window you had focused when you ran it. This is mostly a minor cosmetic issue, though I guess it could be confusing.

**Comment by The-Compiler** [comment]
All prompts show up in all windows now, this is intended. This is because some prompts (like download filenames with QtWebEngine) don't have a window associated with them, so I decided to show all prompts globally and cut down on complexity instead of implementing global *and* per-window prompts.
