### ISSUE TITLE
Empty columns in github projects

### ISSUE THREAD

**Issue by lisael** [The-Compiler/qutebrowser#2237]
```
qutebrowser v0.9.1
```

Github kanban feature (projects link at the top of this page) doesn't work in qute. The columns are empty even if they have contents.

EDIT: Thanks for this great piece of software :)

**Comment by The-Compiler** [comment]
This seems to be a QtWebKit issue - it works fine with the future QtWebEngine backend (which you can try with `--backend webengine` if you're on a distribution which packages it) as well as with the new unofficial QtWebKit (which isn't fully supported by qutebrowser currently).

**Comment by lisael** [comment]
It works, thanks. I'm a newcomer, qute is great, I hope I'll be able to adapt my workflow to qute soon and make it my primary browser.
