### ISSUE TITLE
Qutebrowser sometimes hardlocks when nm-applet connects/changes wifi connection

### ISSUE THREAD

**Issue by robcross** [The-Compiler/qutebrowser#2239]
I haven't been able to find a way to reproduce this 100%, but when I switch wireless connections a couple times, qutebrowser will just hard lock.

I think it only happens when using nm-applet, maybe it has something to do with a dbus message? There's some warning in the log and it might happen when the "connection enabled/disabled" notification pops up. It's hard to pin down the exact moment it freezes.

It seems to happen more often when qutebrowser is on a desktop other than the current one. I'm using awesomewm for my window manager.

I'm running debian testing, with the new webengine packages from unstable.

I've attached logs and a backtrace like you said in irc.

[19817.txt](https://github.com/The-Compiler/qutebrowser/files/715230/19817.txt)
[backtrace.txt](https://github.com/The-Compiler/qutebrowser/files/715231/backtrace.txt)

qute:version
----------------
```
qutebrowser v0.9.1
Git commit: v0.9.0-29-gd9389ff0a (2017-01-17 08:31:23 +0100)

CPython: 3.5.3rc1
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.4
pygments: 2.1.3
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.8.0-2-amd64-x86_64-with-debian-stretch-sid, 64bit
Frozen: False
Imported from /home/robert/.local/src/qutebrowser/qutebrowser
OS Version: 

--- /etc/os-release ---
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian

Paths:
system_data: /home/robert/.local/share/qutebrowser
cache: /home/robert/.cache/qutebrowser
runtime: /run/user/1000/qutebrowser
data: /home/robert/.local/share/qutebrowser
download: /home/robert/Downloads
config: /home/robert/.config/qutebrowser
```

**Comment by robcross** [comment]
Just an update, nm-applet isn't _the_ cause, but I can expedite a hard lock if I cycle it a lot.

Here is a debug log and the all threads backtraces you requested from irc.
[4231.txt](https://github.com/The-Compiler/qutebrowser/files/719967/4231.txt)
[backtraceallthread.txt](https://github.com/The-Compiler/qutebrowser/files/719966/backtraceallthread.txt)

**Comment by The-Compiler** [comment]
You mentioned in IRC that you're seeing this in other Qt applications as well, and unfortunately I really don't have the time to track this down currently, as it looks like some Qt issue... I suggest you open a bug at https://bugreports.qt.io/ - if you do, please link it here!
