### ISSUE TITLE
Missing options for downloads UI

### ISSUE THREAD

**Issue by ersi-dnd** [The-Compiler/qutebrowser#2240]
`downloads-position` top | bottom 

I would like to add: off

**Comment by The-Compiler** [comment]
what's the point in not seeing running downloads?

**Comment by ersi-dnd** [comment]
All toolbars can be hidden. Looks like the downloads toolbar is the only one that cannot be hidden. 

As to seeing the running downloads, I have `confirm-quit = downloads`

Maybe add another way to see and manage running downloads: In the popup (that thing which shows up by pressing o) add the section Downloads along with History and Bookmarks etc. What do you think?

**Comment by ersi-dnd** [comment]
Or maybe add something like `:download-manage` or `:downloads`

**Comment by The-Compiler** [comment]
See #1059 - looking at that issue description this is basically a duplicate.
