### ISSUE TITLE
How to make Ctrl-W behave like Ctrl-Backspace

### ISSUE THREAD

**Issue by MichaelMackus** [The-Compiler/qutebrowser#2241]
I tried changing the `keys.conf` and it didn't seem to work?

**Comment by The-Compiler** [comment]
What did you edit exactly? What do you expect `ctrl-backspace` to do?

**Comment by MichaelMackus** [comment]
I want `ctrl-backspace` to behave exactly like `ctrl-w` in insert/command mode. For example, when I hit Ctrl-W by default it erases the entire word - I want it to delete parts of the word like `ctrl-backspace` (and VIM) does.

I tried editing the `keys.conf` from:

```
rl-kill-word
    <alt-d>

rl-unix-word-rubout
    <ctrl-w>
    <alt-backspace>
```

To:

```
rl-kill-word
    <ctrl-w>
    <alt-d>

rl-unix-word-rubout
    <alt-backspace>
```

But then `ctrl-w` doesn't do anything.

Any ideas?

**Comment by The-Compiler** [comment]
Those `rl-*` commands are for the command/prompt mode only, so this won't work in insert mode (see #68).

In command/prompt mode, this should do what you want though. Did you quit qutebrowser before editing the file? FWIW you can also do `:bind -f <ctrl-w> rl-kill-word` inside qutebrowser instead.

**Comment by MichaelMackus** [comment]
Yes, I tried that (restarted qutebrowser) and then Ctrl-W did nothing. I think the `rl-kill-word` is broken, since `alt-d` doesn't work on my maching either. I'm running Ubuntu 14.04 if that helps.

I tried the bind, but that didn't work either - `Ctrl-W` still is doing the same as before (deleting the entire URL string).

I just rebuilt qutebrowser from Git a few weeks ago, so my browser should be relatively up to date.

**Comment by The-Compiler** [comment]
`rl_kill_word` deletes forward from the cursor to the end of the word (i.e. `foo|bar` -> `foo`). That doesn't sound like what you want. :wink:

**Comment by MichaelMackus** [comment]
Is there a reverse to `rl-kill-word`? I don't seem to see any equivalent in the keys.conf file...

**Comment by The-Compiler** [comment]
That'd be `rl-unix-word-rubout`, which is what `ctrl-w` is bound to by default (blame readline for the names 😆).

You probably just want to bind `ctrl-backspace` to that if I'm understanding what you want properly, but I'm starting to get a bit confused :wink:

**Comment by MichaelMackus** [comment]
No, that doesn't do what I want.

`rl-unix-word-rubout` deletes the *entire* word (including parenthesis). So if my cursor is at the end of 

`https://github.com/The-Compiler/qutebrowser`

And I hit `Ctrl-W` the entire URL goes away. What I want it to read after I press `Ctrl-W` is:

`https;//github.com/the-compiler/`

Just like VIM...

**Comment by The-Compiler** [comment]
Okay, after re-reading things I think I figured out what I misunderstood.

I think you want to map `ctrl-w` to `rl-backward-kill-word`, i.e. this: `:bind -f -m command,prompt <ctrl-w> rl-backward-kill-word`.

Does that help? Sorry again for all the confusion.

**Comment by MichaelMackus** [comment]
I get `Invalid command 'rl-backward-kill-word'`. Hmm. Using qutebrowser `v0.8.4`.

**Comment by The-Compiler** [comment]
Please update :wink:

**Comment by MichaelMackus** [comment]
That worked, thank you
