### ISSUE TITLE
Enhancement: In history completion, prioritise urls that are one level above others

### ISSUE THREAD

**Issue by pkill-nine** [The-Compiler/qutebrowser#2244]
For example: I have visited a subreddit, and I've visited posts in that subreddit. If I've visited posts in that subreddit more recently than the subreddit itself, they appear at the top of the history completion when I put `:open <subreddit name>`, when I just want to visit the subreddit itself.

To illustrate:
 - Visit `reddit.com/r/qutebrowser`
 - Open a post in the subreddit.
 - type in the command bar `:open qutebrowser`
 - Ideally, the first option would be `reddit.com/r/qutebrowser` but since the post was visited more recently it appears closer to the top of the history completion.

**Comment by neeasade** [comment]
https://github.com/The-Compiler/qutebrowser/issues/601

**Comment by pkill-nine** [comment]
ah thanks, I'll close this issue
