### ISSUE TITLE
Can't use hint links spawn (conflicts ?)

### ISSUE THREAD

**Issue by temporaaa** [The-Compiler/qutebrowser#2245]
I would like to use some shortcuts to run differents commands. Something like that :

```
hint links spawn mpv {hint-url}
    00
hint links spawn mpv --ytdl-format 18 {hint-url}
    01
hint links spawn mpv --ytdl-format 17 {hint-url}
    02
hint links spawn mpv --ytdl-format 140 {hint-url}
    03
```

But only 00 is working correctly, I'm not sure why.
Same issue if i use "0p", nothing happen and it seems the "p" is apparently captured for another command. ("pp" for example.)

**Comment by The-Compiler** [comment]
You can't bind numbers because they are used to pass a count to a command (like `2T` to select the second tab). While this could work with leading zeroes, it'd complicate the code quite a bit, so I'm afraid you'll need to find some other key :wink:

**Comment by pkill-nine** [comment]
You can bind numbers after a non-numeric character however, e.g. `\01` would work.

**Comment by temporaaa** [comment]
Numbers for count, ok i got it !
Thanks pkill-nine, i changed with p0, p1, p2... and it works fine.
I'm not sure why 0 doesn't work, but nevermind. I guess i was just unlucky with this choice.
Keep up the good work !
