### ISSUE TITLE
Automatically Run Script on Open Specific Page

### ISSUE THREAD

**Issue by Jumblemuddle** [The-Compiler/qutebrowser#2247]
Is there a way to automatically run a binding after opening a matching page?
E.g. Whenever I open any youtube video, MPV is automatically started, and the tab is closed?

**Comment by The-Compiler** [comment]
Not yet - but after #35/#1155 and/or #30 there will be, so I'd suggest you subscribe to those :wink:

**Comment by Jumblemuddle** [comment]
@The-Compiler Great, thanks! :)
