### ISSUE TITLE
Segfault with python-sip, sip 4.19

### ISSUE THREAD

**Issue by throwaway217** [The-Compiler/qutebrowser#2248]
Both stable and git output Segmentation fault (core dumped) when started after the 4.19 update. Downgrading the packages to 4.18.1 solves the problem.

**Comment by The-Compiler** [comment]
This is an Archlinux bug - looks like they updated sip without updating to the corresponding PyQt.

**Comment by The-Compiler** [comment]
Looks like this is fixed now.
