### ISSUE TITLE
Temporary session

### ISSUE THREAD

**Issue by cptMikky** [The-Compiler/qutebrowser#2252]
Hi,

would be nice to have a "temporary session" option like dwb had: `dwb -t` started a new temporary session which was destroyed upon browser exit. I know about `-r` option and how I can wrap qutebrowser in a shell script that would create a temp session but it's not that convenient and might cause unexpected results if not supported by qutebrowser internally.

 -cM.

**Comment by lahwaacz** [comment]
`qutebrowser --temp-basedir` should do what you want.
