### ISSUE TITLE
Crash trying to use PAC proxy

### ISSUE THREAD

**Issue by kiryl** [The-Compiler/qutebrowser#2257]
With 0.9.1 when I specify "proxy = pac+http://autoproxy.<foo>.tld" I see this:

1:30:15 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/qutebrowser/browser/network/proxy.py", line 70, in queryProxy
    if p.type() != QNetworkProxy.NoProxy:
AttributeError: type object 'PACFetcher' has no attribute 'type'
QMutex: destroying locked mutex

**Comment by The-Compiler** [comment]
#2207 should fix this hopefully - I'm busy with exams the past few weeks, but it should make it into a v0.9.2 sometime soon.

**Comment by The-Compiler** [comment]
#2207 is in now.
