### ISSUE TITLE
Feature request: hint mode based on control contents

### ISSUE THREAD

**Issue by rr-** [The-Compiler/qutebrowser#2260]
Coming from Vimperator, I would be happy to see a hinting mode that resembles that of Vimperator's. I think it'd also provide an indirect solution to #674.

I tried to use `word` mode but in practice it sticked irrelevant dictionary words all over the place.

Note that technically Vimperator doesn't simply use the control content by itself - it combines it with the number hinting so that you can still target controls via numbers alone if you want, plus you can mix letters and numbers. This lets you hit <kbd>C</kbd> to filter targetable links down to **C**omments and Sear**c**h, and then hit <kbd>2</kbd> to proceed to search - super comfortable and good for muscle memory.

**Comment by pkill-nine** [comment]
This already exists, it's the `number` mode

**Comment by The-Compiler** [comment]
Yep - closing this :wink:

**Comment by rr-** [comment]
I'm sorry, I haven't realized you can press "normal" keys in that mode too.
