### ISSUE TITLE
Hang on loading page https://www.psi.ch/pa/job-opportunities/

### ISSUE THREAD

**Issue by yantar92** [The-Compiler/qutebrowser#2264]
Page loads up to 75% and browser hangs. Can only kill it with kill -9.
I tried to turn off javascript, webgl and css-regions. It did not help. The only change is that page was loaded to 98% before hang.

For both cases debug output is the following:

22:26:32 DEBUG    modes      modeman:_eventFilter_keypress:191 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=4 url='https://www.psi.ch/'>)
22:26:32 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: None
22:26:33 DEBUG    webview    tabbedbrowser:on_title_changed:507 Changing title for idx 4 to 'https://www.psi.ch/pa/job-opportunities'
22:26:33 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://www.psi.ch/pa/job-opportunities')) (tab 4)
22:26:33 DEBUG    webview    tabbedbrowser:on_title_changed:499 Ignoring title change to ''.
22:26:33 DEBUG    webview    tabbedbrowser:on_title_changed:507 Changing title for idx 4 to '| Paul Scherrer Institut (PSI)'

Version info:

qutebrowser v0.9.1
Git commit: 

CPython: 3.4.5
Qt: 5.6.2
PyQt: 5.5.1

sip: 4.18
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: no
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.4.39-gentoo-x86_64-Intel-R-_Core-TM-_i5-5200U_CPU_@_2.20GHz-with-gentoo-2.3, 64bit
Frozen: False
Imported from /usr/lib64/python3.4/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"

--- /etc/gentoo-release ---
Gentoo Base System release 2.3

Paths:
runtime: /tmp/runtime-yantar92/qutebrowser
system_data: /home/yantar92/.local/share/qutebrowser
config: /home/yantar92/.config/qutebrowser
cache: /home/yantar92/.cache/qutebrowser
data: /home/yantar92/.local/share/qutebrowser
download: /home/yantar92/Downloads

**Comment by Penaz91** [comment]
Tested it and the page loads perfectly on Gentoo Kernel 4.9.6 with PyQt-5.7.1and qtcore-5.7.1-r1 using the qtWebEngine backend. Slower loading speed but still works with the QtWebKit backend (version 5.7.1).

These are my infos:
qutebrowser v0.9.1
Git commit: v0.9.0-46-g95aeb8632 (2017-01-27 09:19:10 +0100)

CPython: 3.4.5
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19
colorama: no
pypeg2: 2.15
jinja2: 2.9.4
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.6-gentoo-x86_64-Intel-R-_Core-TM-_i5-2430M_CPU_@_2.40GHz-with-gentoo-2.3, 64bit
Frozen: False
Imported from /usr/lib64/python3.4/site-packages/qutebrowser
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID="Gentoo"

--- /etc/os-release ---
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"

--- /etc/gentoo-release ---
Gentoo Base System release 2.3

Paths:
download: /home/penaz/Downloads
system_data: /home/penaz/.local/share/qutebrowser
cache: /home/penaz/.cache/qutebrowser
runtime: /var/run/user/1000/qutebrowser
config: /home/penaz/.config/qutebrowser
data: /home/penaz/.local/share/qutebrowser

**Comment by The-Compiler** [comment]
Loads fine here with both backends too - so you don't get any other output with `--debug`, correct? Can you please send a `SIGUSR1` to the process (`kill -USR1 pid`) and show the output you get then?

**Comment by yantar92** [comment]
kill -USR1 gives:

Current thread 0x00007fc36c000700 (most recent call first):
  File "/usr/lib64/python3.4/site-packages/qutebrowser/browser/webkit/webview.py", line 241 in paintEvent
  File "/usr/lib64/python3.4/site-packages/qutebrowser/app.py", line 122 in qt_mainloop
  File "/usr/lib64/python3.4/site-packages/qutebrowser/app.py", line 112 in run
  File "/usr/lib64/python3.4/site-packages/qutebrowser/qutebrowser.py", line 169 in main
  File "/usr/lib/python-exec/python3.4/qutebrowser", line 11 in <module>

Full debug output from opening the new tab till hang:

22:48:13 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: <qutebrowser.mainwindow.statusbar.command.Command>
22:48:13 DEBUG    modes      modeman:_eventFilter_keypress:166 got keypress in mode KeyMode.command - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='command' warn=True>
22:48:13 DEBUG    commands   command:run:509 command called: command-accept
22:48:13 DEBUG    commands   command:run:524 Calling qutebrowser.mainwindow.statusbar.command.Command.command_accept(<qutebrowser.mainwindow.statusbar.command.Command>)
22:48:13 DEBUG    save       savemanager:mark_dirty:72 Marking command-history as dirty.
22:48:13 DEBUG    modes      modeman:leave:289 Leaving mode KeyMode.command (reason: cmd accept)
22:48:13 DEBUG    statusbar  text:set_text:55 Setting normal text to ''.
22:48:13 DEBUG    statusbar  bar:set_mode_active:236 Setting command_active to False
22:48:13 DEBUG    completion completer:schedule_completion_update:222 Scheduling completion update.
22:48:13 DEBUG    completion completer:schedule_completion_update:219 Ignoring update because there were no changes.
22:48:13 DEBUG    statusbar  bar:_hide_cmd_widget:269 Hiding cmd widget
22:48:13 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: <qutebrowser.mainwindow.mainwindow.MainWindow>
22:48:13 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: <qutebrowser.mainwindow.statusbar.text.Text text=''>
22:48:13 DEBUG    modes      tabbedbrowser:on_mode_left:570 Left status-input mode, focusing <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=3 url='https://github.com/The-Compiler/qutebrowser/issues/2264'>
22:48:13 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: <qutebrowser.browser.webkit.webview.WebView tab_id=3 url='https://github.com/The-Compiler/qutebrowser/issues/2264'>
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.command was left.
22:48:13 DEBUG    commands   command:run:509 command called: open ['-t', 'https://www.psi.ch/pa/job-opportunities/']
22:48:13 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.openurl(<qutebrowser.browser.commands.CommandDispatcher>, 'https://www.psi.ch/pa/job-opportunities/', False, False, True, False, None)
22:48:13 DEBUG    url        urlutils:get_path_if_valid:360 Checking if 'https://www.psi.ch/pa/job-opportunities/' is a path
22:48:13 DEBUG    url        urlutils:is_url:245 Checking if 'https://www.psi.ch/pa/job-opportunities/' is a URL (autosearch=naive).
22:48:13 DEBUG    url        urlutils:is_url:267 Contains explicit scheme
22:48:13 DEBUG    url        urlutils:is_url:286 url = True
22:48:13 DEBUG    url        urlutils:fuzzy_url:193 URL is a fuzzy address
22:48:13 DEBUG    url        urlutils:fuzzy_url:196 Converting fuzzy term 'https://www.psi.ch/pa/job-opportunities/' to URL -> https://www.psi.ch/pa/job-opportunities/
22:48:13 DEBUG    webview    tabbedbrowser:tabopen:377 Creating new tab with URL PyQt5.QtCore.QUrl('https://www.psi.ch/pa/job-opportunities/'), background False, explicit True, idx None
22:48:13 DEBUG    init       networkmanager:__init__:139 Initializing NetworkManager
22:48:13 DEBUG    init       networkmanager:__init__:144 NetworkManager init done
22:48:13 DEBUG    webview    tabbedbrowser:_get_new_tab_idx:439 new-tab-position last -> opening new tab at -1, next left: 3 / right: 4
22:48:13 DEBUG    webview    tabbedbrowser:on_title_changed:507 Changing title for idx 9 to 'https://www.psi.ch/pa/job-opportunities/'
22:48:13 DEBUG    webview    webpage:acceptNavigationRequest:478 navigation request: url https://www.psi.ch/pa/job-opportunities/, type NavigationTypeOther, target ClickTarget.normal override None
22:48:13 DEBUG    webview    browsertab:_set_load_status:587 load status for <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=9 url=''>: LoadStatus.loading
22:48:13 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_status_changed('loading') (tab 9)
22:48:13 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_started() (tab 9)
22:48:14 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: <qutebrowser.browser.webkit.webview.WebView tab_id=9 url=''>
22:48:14 DEBUG    modes      tabbedbrowser:on_current_changed:587 Current tab changed, focusing <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=9 url=''>
22:48:14 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
22:48:14 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
22:48:14 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
22:48:14 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
22:48:14 VDEBUG   webview    browsertab:_log_scroll_pos_change:338 Scroll position changed to PyQt5.QtCore.QPoint()
22:48:14 DEBUG    modes      modeman:_eventFilter_keypress:191 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: True --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=9 url=''>)
22:48:14 DEBUG    modes      modeman:_eventFilter_keyrelease:211 filter: True
22:48:18 DEBUG    webview    tabbedbrowser:on_title_changed:507 Changing title for idx 9 to 'https://www.psi.ch/pa/job-opportunities/'
22:48:18 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://www.psi.ch/pa/job-opportunities/')) (tab 9)
22:48:18 DEBUG    webview    tabbedbrowser:on_title_changed:499 Ignoring title change to ''.
22:48:18 DEBUG    webview    tabbedbrowser:on_title_changed:507 Changing title for idx 9 to '| Paul Scherrer Institut (PSI)'
22:48:19 DEBUG    save       savemanager:mark_dirty:72 Marking history as dirty.
22:48:19 DEBUG    webview    tabbedbrowser:on_title_changed:507 Changing title for idx 9 to 'Paul Scherrer Institut (PSI) :: Offene Stellen'

**Comment by The-Compiler** [comment]
Okay, so somehow Qt hangs up while painting. I probably can't do much about it (other than telling you to install QtWebEngine and use `--backend webengine` 😆) but I'm curious:

Can you install `gdb`, do `gdb /usr/bin/python3`, then `r -m qutebrowser`, make it hang, press `ctrl-c`, do `bt` in the gdb shell, and show the stacktrace here?

**Comment by yantar92** [comment]
Here it is:

#0  0x00007fffdfa05273 in ?? () from /usr/lib64/libfontconfig.so.1
#1  0x00007fffdfa05873 in ?? () from /usr/lib64/libfontconfig.so.1
#2  0x00007fffdfa05bbf in ?? () from /usr/lib64/libfontconfig.so.1
#3  0x00007fffdfa05d0a in ?? () from /usr/lib64/libfontconfig.so.1
#4  0x00007fffdfa0676d in FcFontMatch () from /usr/lib64/libfontconfig.so.1
#5  0x00007fffe1d80efe in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#6  0x00007fffe1d815cd in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#7  0x00007fffede577ec in ?? () from /usr/lib64/libQt5Gui.so.5
#8  0x00007fffede581b9 in QFontDatabase::findFont(QFontDef const&, int) () from /usr/lib64/libQt5Gui.so.5
#9  0x00007fffede3f55e in QFontEngineMulti::loadEngine(int) () from /usr/lib64/libQt5Gui.so.5
#10 0x00007fffede3fd2f in QFontEngineMulti::ensureEngineAt(int) () from /usr/lib64/libQt5Gui.so.5
#11 0x00007fffede4020b in QFontEngineMulti::stringToCMap(QChar const*, int, QGlyphLayout*, int*, QFlags<QFontEngine::ShaperFlag>) const () from /usr/lib64/libQt5Gui.so.5
#12 0x00007fffede61e78 in QTextEngine::shapeText(int) const () from /usr/lib64/libQt5Gui.so.5
#13 0x00007fffede628ed in QTextEngine::shape(int) const () from /usr/lib64/libQt5Gui.so.5
#14 0x00007fffede756c3 in QTextLine::layout_helper(int) () from /usr/lib64/libQt5Gui.so.5
#15 0x00007fffede7686b in QTextLine::setLineWidth(double) () from /usr/lib64/libQt5Gui.so.5
#16 0x00007fffe86451ed in ?? () from /usr/lib64/libQt5WebKit.so.5
#17 0x00007fffe93be8e9 in ?? () from /usr/lib64/libQt5WebKit.so.5
#18 0x00007fffe93c1920 in ?? () from /usr/lib64/libQt5WebKit.so.5
#19 0x00007fffe93c5c9b in ?? () from /usr/lib64/libQt5WebKit.so.5
#20 0x00007fffe93c73d0 in ?? () from /usr/lib64/libQt5WebKit.so.5
#21 0x00007fffe93c7fb4 in ?? () from /usr/lib64/libQt5WebKit.so.5
#22 0x00007fffe93dbdf9 in ?? () from /usr/lib64/libQt5WebKit.so.5
#23 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#24 0x00007fffe936ff36 in ?? () from /usr/lib64/libQt5WebKit.so.5
#25 0x00007fffe93dc0f4 in ?? () from /usr/lib64/libQt5WebKit.so.5
#26 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#27 0x00007fffe93915cb in ?? () from /usr/lib64/libQt5WebKit.so.5
#28 0x00007fffe93baf79 in ?? () from /usr/lib64/libQt5WebKit.so.5
#29 0x00007fffe93dc080 in ?? () from /usr/lib64/libQt5WebKit.so.5
#30 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#31 0x00007fffe93915cb in ?? () from /usr/lib64/libQt5WebKit.so.5
#32 0x00007fffe93baf79 in ?? () from /usr/lib64/libQt5WebKit.so.5
#33 0x00007fffe93dc080 in ?? () from /usr/lib64/libQt5WebKit.so.5
#34 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#35 0x00007fffe938ecc9 in ?? () from /usr/lib64/libQt5WebKit.so.5
#36 0x00007fffe93baecb in ?? () from /usr/lib64/libQt5WebKit.so.5
#37 0x00007fffe93dc080 in ?? () from /usr/lib64/libQt5WebKit.so.5
#38 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#39 0x00007fffe93915cb in ?? () from /usr/lib64/libQt5WebKit.so.5
#40 0x00007fffe93baf79 in ?? () from /usr/lib64/libQt5WebKit.so.5
#41 0x00007fffe93dc080 in ?? () from /usr/lib64/libQt5WebKit.so.5
#42 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#43 0x00007fffe93915cb in ?? () from /usr/lib64/libQt5WebKit.so.5
#44 0x00007fffe93baf79 in ?? () from /usr/lib64/libQt5WebKit.so.5
#45 0x00007fffe93dc080 in ?? () from /usr/lib64/libQt5WebKit.so.5
#46 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#47 0x00007fffe93915cb in ?? () from /usr/lib64/libQt5WebKit.so.5
#48 0x00007fffe93baf79 in ?? () from /usr/lib64/libQt5WebKit.so.5
#49 0x00007fffe93dc080 in ?? () from /usr/lib64/libQt5WebKit.so.5
#50 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
---Type <return> to continue, or q <return> to quit---
#51 0x00007fffe93915cb in ?? () from /usr/lib64/libQt5WebKit.so.5
#52 0x00007fffe93baf79 in ?? () from /usr/lib64/libQt5WebKit.so.5
#53 0x00007fffe93dc080 in ?? () from /usr/lib64/libQt5WebKit.so.5
#54 0x00007fffe9304465 in ?? () from /usr/lib64/libQt5WebKit.so.5
#55 0x00007fffe9304cb9 in ?? () from /usr/lib64/libQt5WebKit.so.5
#56 0x00007fffe93615d0 in ?? () from /usr/lib64/libQt5WebKit.so.5
#57 0x00007fffe85c2ffc in ?? () from /usr/lib64/libQt5WebKit.so.5
#58 0x00007fffe85c441d in ?? () from /usr/lib64/libQt5WebKit.so.5
#59 0x00007fffe81ceedb in QWebFrameAdapter::renderRelativeCoords(QPainter*, int, QRegion const&) () from /usr/lib64/libQt5WebKit.so.5
#60 0x00007fffe2bd320e in QWebFrame::render(QPainter*, QFlags<QWebFrame::RenderLayer>, QRegion const&) () from /usr/lib64/libQt5WebKitWidgets.so.5
#61 0x00007fffe2bd3231 in QWebFrame::render(QPainter*, QRegion const&) () from /usr/lib64/libQt5WebKitWidgets.so.5
#62 0x00007fffe2be0105 in QWebView::paintEvent(QPaintEvent*) () from /usr/lib64/libQt5WebKitWidgets.so.5
#63 0x00007fffe2c239d0 in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtWebKitWidgets.so
#64 0x00007ffff7a40f6a in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
#65 0x00007ffff7a42b93 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
#66 0x00007ffff7986629 in ?? () from /usr/lib64/libpython3.4m.so.1.0
#67 0x00007ffff7957098 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
#68 0x00007ffff796f4dd in ?? () from /usr/lib64/libpython3.4m.so.1.0
#69 0x00007ffff7957098 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
#70 0x00007ffff7a39ff7 in PyEval_CallObjectWithKeywords () from /usr/lib64/libpython3.4m.so.1.0
#71 0x00007ffff1cb0ea0 in ?? () from /usr/lib64/python3.4/site-packages/sip.so
#72 0x00007fffea70c969 in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtGui.so
#73 0x00007fffe2c238f2 in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtWebKitWidgets.so
#74 0x00007fffee3c2eae in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#75 0x00007fffe2be16cc in QWebView::event(QEvent*) () from /usr/lib64/libQt5WebKitWidgets.so.5
#76 0x00007fffe2c23fab in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtWebKitWidgets.so
#77 0x00007fffee371bbc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#78 0x00007fffee379622 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#79 0x00007fffeeb73ebe in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtWidgets.so
#80 0x00007ffff56580b8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#81 0x00007fffee3bb96a in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /usr/lib64/libQt5Widgets.so.5
#82 0x00007fffee3bbfc0 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/libQt5Widgets.so.5
#83 0x00007fffee382cb0 in ?? () from /usr/lib64/libQt5Widgets.so.5
#84 0x00007fffee3831f9 in ?? () from /usr/lib64/libQt5Widgets.so.5
#85 0x00007fffee3ab69f in QWidgetPrivate::syncBackingStore() () from /usr/lib64/libQt5Widgets.so.5
#86 0x00007fffee3c2f5e in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#87 0x00007fffeeabcd3b in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtWidgets.so
#88 0x00007fffee371bbc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#89 0x00007fffee379622 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#90 0x00007fffeeb73ebe in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtWidgets.so
#91 0x00007ffff56580b8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#92 0x00007ffff5659e73 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQt5Core.so.5
#93 0x00007ffff56aae63 in ?? () from /usr/lib64/libQt5Core.so.5
#94 0x00007ffff40aad5d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#95 0x00007ffff40ab040 in ?? () from /usr/lib64/libglib-2.0.so.0
#96 0x00007ffff40ab0ec in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#97 0x00007ffff56ab247 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#98 0x00007ffff5655f9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#99 0x00007ffff565e30c in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#100 0x00007fffeeb7288b in ?? () from /usr/lib64/python3.4/site-packages/PyQt5/QtWidgets.so
#101 0x00007ffff7a40f6a in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
---Type <return> to continue, or q <return> to quit---
#102 0x00007ffff7a40e04 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
#103 0x00007ffff7a40e04 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
#104 0x00007ffff7a40e04 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
#105 0x00007ffff7a42b93 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
#106 0x00007ffff7a42c3b in PyEval_EvalCode () from /usr/lib64/libpython3.4m.so.1.0
#107 0x00007ffff7a373ea in ?? () from /usr/lib64/libpython3.4m.so.1.0
#108 0x00007ffff7a40f6a in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
#109 0x00007ffff7a42b93 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
#110 0x00007ffff7a40a79 in PyEval_EvalFrameEx () from /usr/lib64/libpython3.4m.so.1.0
#111 0x00007ffff7a42b93 in PyEval_EvalCodeEx () from /usr/lib64/libpython3.4m.so.1.0
#112 0x00007ffff7986629 in ?? () from /usr/lib64/libpython3.4m.so.1.0
#113 0x00007ffff7957098 in PyObject_Call () from /usr/lib64/libpython3.4m.so.1.0
#114 0x00007ffff7a87641 in ?? () from /usr/lib64/libpython3.4m.so.1.0
#115 0x00007ffff7a87ffb in Py_Main () from /usr/lib64/libpython3.4m.so.1.0
#116 0x0000000000400b16 in main ()

**Comment by The-Compiler** [comment]
So apparently it hangs in `libfontconfig.so` while trying to find some font... you might be able to find out more if you can build that with debugging symbols if you want to - but I'm closing this, as it's definitely not a qutebrowser bug, and probably not even a Qt one.

(also: please use ``` on its own line before/after code blocks in the future - I edited your post, but now this issue references every other one from #1 to #116 :laughing:)

**Comment by yantar92** [comment]
Updating PyQt and switching to QtWebEngine backend solved the problem:

```
PyQt: 5.7.1
sip: 4.19
PyQt5.QtWebEngineWidgets: yes
```

> (also: please use ``` on its own line before/after code blocks in the future
Oops)
