### ISSUE TITLE
Blurry notifications window on Facebook.com

### ISSUE THREAD

**Issue by ddickstein** [The-Compiler/qutebrowser#2268]
I'm running qutebrowser 0.8.4 (version currently available in Homebrew) on OS X 10.12.2.  When I load facebook.com my notifications and message popup windows appear blurry.  Compare the two screenshots from qutebrowser and chrome.

<img width="431" alt="qutebrowser" src="https://cloud.githubusercontent.com/assets/802511/22506808/4a825e7c-e837-11e6-81c9-2f2b5f7a5f71.png">
<img width="432" alt="chrome" src="https://cloud.githubusercontent.com/assets/802511/22506807/4a818c22-e837-11e6-8169-8799f30e8cc5.png">

The screenshot on its own looks clearer than the browsing experience, perhaps because this popup is perceptibly blurry compared to the clearer page beneath it.

**Comment by The-Compiler** [comment]
This is a rendering issue from the backend, which means there isn't anything I can do about it. However, once there's a build with QtWebEngine (the new backend) for OS X, things like these will probably improve a lot.
