### ISSUE TITLE
set colors webpage.bg no longer applies to about:blank

### ISSUE THREAD

**Issue by Al-Caveman** [The-Compiler/qutebrowser#2271]
I used to 

> set colors webpage.bg = black

, so that my entire experience is night friendly. It used to work perfectly fine when I was using Qt libraries version 5.5.1, until I updated to 5.7.1 after which "about:blank" is always white.

As a workaround, I am using a startup page that has an empty black HTML page. But the problem is that every time I startup Qutebrowser, or every time I open a new tab, the tab/page is initially white, and then transforms into black. In other words, I always get a white flash when I open a tab.

This problem did not exist when I was using 5.5.1, as the setting above was forcing "about:blank" to start in the specified colour.

---

qutebrowser v0.9.1
Git commit: 

CPython: 3.4.5
Qt: 5.7.1 (compiled 5.6.2)
PyQt: 5.7.1

sip: 4.19
colorama: 0.3.3
pypeg2: 2.15
jinja2: 2.8
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: no
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.4.39-gentoo-x86_64-Intel-R-_Core-TM-_i7-5600U_CPU_@_2.60GHz-with-gentoo-2.3, 64bit
Frozen: False
Imported from /usr/lib64/python3.4/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"

--- /etc/gentoo-release ---
Gentoo Base System release 2.3

Paths:
cache: /home/caveman/.cache/qutebrowser
runtime: /tmp/runtime-caveman/qutebrowser
download: /home/caveman/Downloads
data: /home/caveman/.local/share/qutebrowser
config: /home/caveman/.config/qutebrowser
system_data: /home/caveman/.local/share/qutebrowse

**Comment by The-Compiler** [comment]
As mentioned in IRC this is a QtWebKit vs. QtWebEngine thing. This is already tracked in #666, and unfortunately I don't know if there's any way to make this work.

**Comment by Al-Caveman** [comment]
@Chinggis6 the problem with that is that, every time I open a new blank tab, it starts white, and then as it loads the index.html page it becomes black. In other words, every time I open a new blank tab, I see a white blink! This causes eye discomfort at night when lights are close (specially that I have a global CSS for night-mode browsing).

**Comment by The-Compiler** [comment]
This should work fine with the newest master
