### ISSUE TITLE
Context menu affects cursor behaviour (webengine)

### ISSUE THREAD

**Issue by WorMzy** [The-Compiler/qutebrowser#2272]
Very minor issue, but opening the context menu by right-clicking on any white space or text element results in the mouse cursor not switching to a pointer cursor over hyperlinks, instead remaining as a default cursor. Left-clicking on the page (again, on any whitespace or text element) restores the correct behaviour. Right-clicking on images and hyperlinks does not trigger this behaviour, but text, textboxes, textareas, and blank space do. Only regular hyperlinks appear to be affected (e.g. cursor still turns into a caret over textboxes, pointer over javascript anchors, etc.)

**Version info**

qutebrowser v0.9.1
Git commit: v0.9.0-52-gba2f4fb1b (2017-02-01 13:08:11 +0100)

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.7.1

sip: 4.19
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: Breeze::Style
Platform: Linux-4.9.6-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/wormzy/.config/qutebrowser
data: /home/wormzy/.local/share/qutebrowser
system_data: /home/wormzy/.local/share/qutebrowser
cache: /home/wormzy/.cache/qutebrowser
download: /home/wormzy/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by lahwaacz** [comment]
I think not switching to a pointer cursor over hyperlinks when a context menu is active is the right behaviour, since links can't be clicked until the context menu is killed (by left-clicking anywhere). FWIW, for me it does not seem to depend on the element where the right-click occurs - I always get the same behaviour, which I think is the correct one. It is also how webkit behaves (for me).

**Comment by WorMzy** [comment]
Sorry, I should have clarified, the behaviour occurs after the context menu is closed. So to reproduce:

- Right-click on an affected element (see above) to open the context menu
- Left-click to exit the context menu (either on a context menu item, or outside of the context menu)
- Hover over a hyperlink

**Comment by The-Compiler** [comment]
Reported upstream as [QTBUG-58603](https://bugreports.qt.io/browse/QTBUG-58603).
