### ISSUE TITLE
Hint issues with Qt 5.8

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#2273]
Various hint tests are failing with Qt 5.8, and when trying by hand with `tests/end2end/data/hints/html/simple.html` I see the following behavior:

- Hint works once
- I go back with `H`
- Hint is broken (only changes cursor)
- I click somewhere on the page
- Hint works again

So far I couldn't figure out why the hell clicking makes a difference... 😟

**Comment by lahwaacz** [comment]
I've noticed very similar behaviour on the Arch wiki pages:

- Start e.g. on [this page](https://wiki.archlinux.org/index.php?title=Installation_guide&diff=454087&oldid=453272)
- Hint for the "Newer edit" link
- Then on the next page, and the next... until hinting the link does not work

I'm not sure after how many pages it stops working. For sure with `:back` it is each time, for every link I've encountered so far.

One workaround is to click somewhere on the page, another way (for the "Newer edit") is to use `]]` (i.e. `:navigate next`).

**Comment by The-Compiler** [comment]
I can't find a working solution for this no matter what I try... 😢 

Maybe it's time to give hint activation a bigger overhaul, also fixing things like #1613 and maybe #2265, as well as some gripes @haasn had IIRC.

Here are some ideas on how it could be handled:

- If the element is either a button, or a link (`a` with `href`) with `normal` target, call [click](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click) on it via javascript (contrary to that documentation, that seems to work fine for links).
- If it's an `a` element and it's requested to open it in a new (fg/bg) tab or window, get the link from the `href` and open it. This means no JS click handlers will be executed, but I guess that's not necessarily worse than pretending the user did a control-click when they used hinting
- If it's a `textarea` or text `input`, call `focus()` on it in javascript and enter insert mode
- Probably a lot more special casing for area/other inputs/link/frames/etc. etc.
- If we can't figure out any of those (quite common) special cases, simulate a simple click on it (either via Qt or in JS), and hope for the best.

How does this sound? It'd solve a variety of subtle issues and stop emulating mouse clicks, but at the same time I bet it'll cause new corner cases...

**Comment by The-Compiler** [comment]
I implemented this now and it seems to work quite well so far... time will tell what new corner cases we'll find 😆

**Comment by jgkamat** [comment]
I _think_ I've found a regression in this commit, I'll report it in a seperate issue.
