### ISSUE TITLE
Feature request: bookmark tags

### ISSUE THREAD

**Issue by JonathanReeve** [The-Compiler/qutebrowser#2274]
One of my favorite features of vimperator, and some other vim-like browsers, is bookmark tags. These allow me to organize my bookmarks according to category, without having to create mutually-exclusive categories. One browser (I forget whether it was dwb, luakit, or something else) just allowed you to do something like `:bookmark tag1,tag2`. Then these tags would be autocompleted later. 

I can *almost* already do this by using the title field as if it were a tag, i.e. `:bookmark-add {url} tag1`, which is then fairly easily searchable. But sometimes I need the title of the page to remember what it was, and `:bookmark-add {url} {title} tag1` doesn't seem to work.

**Comment by The-Compiler** [comment]
This is tracked as part of #882.
