### ISSUE TITLE
High number of wakeups when unused due to infinite "poll"

### ISSUE THREAD

**Issue by pedromj** [The-Compiler/qutebrowser#272]
Hi,

I have noticed (using strace [*]) that qutebrowser is using some infinite "poll" and it implies that there is a high number of unnecessary wakeups (powertop) and high CPU usage even when it is not being used.

Regards,
Pedro

[*] In case it is useful, the output of strace has this form:

```
poll([{fd=8, events=POLLIN}, {fd=13, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}], 4, 7) = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=13, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}], 4, 7) = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=13, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}], 4, 8) = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=13, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}], 4, 7) = 0 (Timeout)
poll([{fd=8, events=POLLIN}, {fd=13, events=POLLIN}, {fd=15, events=POLLIN}, {fd=17, events=POLLIN}], 4, 7) = 0 (Timeout)
```

**Comment by The-Compiler** [comment]
5.4.1 [has been released](http://blog.qt.io/blog/2015/02/24/qt-5-4-1-released/) and I see 1-2 polls per second now. Seems like this has been fixed :)
