### ISSUE TITLE
Renumber hints when filtering them in number mode.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#308]
Requested by `skrzyp` in IRC.

When setting `hints->mode` to `number`, we should renumber the hints when the text is filtered, just like 
vimperator does it.

Screenshots: https://imgur.com/a/SbDks

**Comment by lahwaacz** [comment]
When the number of hints on a page is reduced by typing a text and then a number is entered, also the previously hidden hints starting with the same digits are shown again. This will complicate things, if it's not a conflicting approach altogether...

**Comment by The-Compiler** [comment]
Hm yeah, that doesn't sound intentional and I'm fine with getting rid of that behaviour.

**Comment by lahwaacz** [comment]
I think I solved this issue in [1c3a045](https://github.com/lahwaacz/qutebrowser/commit/1c3a04513bfc1e833219c5aa87fa83c35f6c6c84). I haven't considered `scattered = false`, but on second thought the scattered layout does not make sense with numeric hints. Perhaps its effect should be limited to the letter mode?

**Comment by giodamelio** [comment]
Awesome. This was the one big thing keeping my from using qutebrowser!
