### ISSUE TITLE
Position marks (like m/' in vim)

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#310]
It'd be useful to mark a position using `mX` (X being a letter) and then recall it using `'X`.

Like in vim, capital letters should be remembered even across sites -> remember URL and position, jump to tab where URL is open or re-open it.

Also, the `'` position (recalled using `''`) should be set on any operation which jumps (`gg`/`G`/searching/clicking anchor).

**Comment by rcorre** [comment]
I may try to tackle this. I was thinking about jumplist (`c-o`/`c-i`), but I think `''` would satisfy 90% of what I want (I just pressed `G`, how do I get back?).

The lettered marks relate to #882, as the obvious keybinding would be `m`, which is taken by quickmarks (for now?). Of course `set-position-mark` could be unbound by default for now. (for vim users)

**Comment by The-Compiler** [comment]
I agree `''` and `'x` are probably the most needed ones.

Even with #882 the `m` binding would still exist I think. I think we should stick to using dwb bindings by default, and dwb uses ` (backtick) to set marks.

**Comment by lamarpavel** [comment]
Reading through the linked threads again I get the feeling that position marks and quickmarks could be the same thing with the position being an optional addition to regular quickmarks.
I might be overlooking something, but if not, then instead of adding position marks we could just enhance quickmarks (to take an optional scroll position).
This would also solve keybinding problems because we wouldn't need to bind any new commands.

**Comment by rcorre** [comment]
That depends on how 'light' you want quickmarks to be. Currently they open a prompt, which could slow you down. I'd expect bookmarks to be a persistent thing that requires a bit more effort to set up; creating a bookmark would open a prompt to enter optional things like a title, keyword, or position. A quickmark would be dumb and fast -- two keypresses and that's it. `mm` sets a tab-local mark at my current position immediately with no prompt. `mM` does the same but is global across tabs.

**Comment by lamarpavel** [comment]
What do you mean by "global [quickmark] across tabs"?

**Comment by rcorre** [comment]
Maybe 'tab' wasn't the right term, url is maybe more analagous to a buffer in
vim.

To give an example:

I visit websiteA, navigate within the page and press `ma`, then `mA`. I then
navigate to websiteB. Pressing `'a` will navigate nowhere, as that mark was
local to websiteA. Pressing `'A` will open websiteA and move to the position I
saved, as `A` is global.

Then again, maybe applying vim logic doesn't really work here, and we need our
own concept of what these mean, if we need them at all.

I'm imagining local marks being useful while reading a long article on a single
page, and global marks as an alternative to keeping many tabs open. 

I'll admit I make light use of marks in vim, I can rarely remember more than a
few, if that.

**Comment by lamarpavel** [comment]
Okay, that makes sense. I'm not yet convinced that these use cases justify the added friction of having to learn and remember another differentiation in marks. I find myself already pausing to think whether or not I should create a bookmark or quickmark for the page I'm at and which ones were mapped to which key. It's a set of features I use occasionally, but not often enough to really memorize details. So the thought of more details isn't particularly thrilling to me (:

**Comment by rcorre** [comment]
>  find myself already pausing to think whether or not I should create a bookmark or quickmark

That's why the current 'quickmarks' should be merged with bookmarks (IMHO) regardless of whether we decide to implement this.

Then IF we decided to add these marks (the new quickmarks?), the decision would be:

1. Do I want it to persist across sessions? -> bookmark
2. Do I want it to have a name/keyword? -> bookmark
3. Do I want to create it quickly and temporarily? -> quickmark

**Comment by l29ah** [comment]
I just want to have a vim{,perator} feel, where 'm' takes a following letter as an argument. The current behaviour confuses me a lot as i frequently switch between qutebrowser, vimperator, vim and zathura. I don't insist on it being enabled by default, but i think vimperator-like preset would be liked by lots of vi-accustomized people.

**Comment by rcorre** [comment]
Hmm... so `m<x>` keybindings may be a bit complicated. We'd need to add the concept of 'pass along the next keypress to the command. I guess this would be similar to `count` -- a property set in `register` that changes the behavior of the `KeyParser`. That or just add a lot of bindings:

    bind ma set-mark 'a'
    bind mb set-mark 'b'
    ...
    bind mz set-mark 'z'

**Comment by The-Compiler** [comment]
I definitely wouldn't call them quickmarks, that's just bound to cause confusion. I'd say jumpmarks or scrollmarks.

> I just want to have a vim{,perator} feel, where 'm' takes a following letter as an argument. The current behaviour confuses me a lot as i frequently switch between qutebrowser, vimperator, vim and zathura. I don't insist on it being enabled by default, but i think vimperator-like preset would be liked by lots of vi-accustomized people.

For (the current) quickmarks, you mean? See #711.

> Hmm... so `m<x>` keybindings may be a bit complicated. We'd need to add the concept of 'pass along the next keypress to the command'. I guess this would be similar to `count` -- a property set in `register` that changes the behavior of the `KeyParser`.

Another possibility would be to add a dedicated `KeyMode` for them, so `m` (or whatever keybinding it ends up being) would simply be `:enter-mode quickmarks` (or scrollmarks, or whatever)
