### ISSUE TITLE
Add keyboard cheatsheet to :help

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#329]
The [keyboard cheatsheet](http://qutebrowser.org/img/cheatsheet-big.png) should be included in `:help` so people have an offline copy and it's easily available.

**Comment by Permafacture** [comment]
As part of getting `:help` to work without asciidoc, I could work on including the image in the package.  I have included data files in a pip installable project (python 2 though) before:  https://github.com/Permafacture/pygmaps-ng

**Comment by Permafacture** [comment]
I can do this, but I'll wait to see what happens with asciidoc first.

**Comment by The-Compiler** [comment]
`asciidoc2html.py` could probably copy the image (or even render the `.png` from the `.svg`) for releases, then this should work.

Setting the priority to high as this affects Debian packaging.
