### ISSUE TITLE
:jseval command

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#334]
A `:jseval` command to evaluate javascript on the current page (similiar to `:pyeval`) would be nice.

**Comment by lcartercondon** [comment]
This is somewhat similar to the Greasemonkey and quickmark enhancement issues, but only as a first step. If the porting is done to QtWebEngine then all that is needed is connecting this to the runJavaScript function in the WebEngineView, I'm not sure about QtWebKit though (although I assume it would be fairly similar). 

As mentioned in the Greasemonkey issue this would only really make sense when JS is enabled.

**Comment by The-Compiler** [comment]
It's basically the same for QtWebKit as well.

It's trivial to implement, I just didn't need it so far and it's a good issue to leave open as something to start for new contributors :)

**Comment by The-Compiler** [comment]
Closed via #699.
