### ISSUE TITLE
HTML5 fullscreen on youtube broken

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#350]
Need to test with Qt 5.3.2, this might be a regression.

**Comment by The-Compiler** [comment]
https://bugreports.qt.io/browse/QTBUG-43625

**Comment by The-Compiler** [comment]
According to the upstream bug this seems to be a missing feature rather than a bug - closing this, as it's rather unlikely this will appear in QtWebKit...

**Comment by sim590** [comment]
This webkit issue affects other browsers. How is it unlikely to be fixed. Isn't QtWebKit project developped to support new features? Shouldn't HTML5 functionnality support be a primary goal? I must say that I don't know alot about QtWebKit project.

**Comment by The-Compiler** [comment]
QtWebKit is deprecated, so it'll only get security fixes unless someone contributes to it. Things will probably better when there's a QtWebEngine backend for qutebrowser (see #666) - QtWebEngine is the maintained successor and based on Chromium.

I suggest using a video player like [mpv](http://mpv.io/) to watch videos - see 9. in the [FAQ](https://github.com/The-Compiler/qutebrowser/blob/master/FAQ.asciidoc) for details.

**Comment by sim590** [comment]
> QtWebKit is deprecated, so it'll only get security fixes unless someone contributes to it. Things will probably better when there's a QtWebEngine backend for qutebrowser (see #666) - QtWebEngine is the maintained successor and based on Chromium.

Good news! If this means pages will be rendered as good as Chromium can, I can't wait for this. Oh, and what a number for referencing this issue!

> I suggest using a video player like mpv to watch videos - see 9. in the FAQ for details.

Yes, I've red the FAQ. That's what I've been doing. Thank you.

**Comment by The-Compiler** [comment]
I can't wait either! Unfortunately there are some other things I'll need to take care of first - writing lots of tests, mainly - so I can see what breaks :wink:. I hope I'll have something testable for Qt 5.6 in December.

And yep, the number definitely is funny - at least I can easily remember it without looking it up all the time :laughing:

**Comment by bchretien** [comment]
Side note concerning the FAQ: it could be useful to add that an extra package may be required to directly play the YouTube video in mpv (e.g. [youtube-dl](https://www.archlinux.org/packages/community/any/youtube-dl/) on Arch).

**Comment by The-Compiler** [comment]
@bchretien Done - thanks for the suggestion!

**Comment by funeralismatic** [comment]
```
 % >  qutebrowser --version
qutebrowser v0.5.1
Git commit: v0.5.0-233-g959e96f (2016-01-27 06:41:00 +0100)

CPython: 3.4.3
Qt: 5.5.1, runtime: 5.5.1
PyQt: 5.5.1
```
fullscreen unavaliable on youtube.
