### ISSUE TITLE
Flashing HTML5 video on Youtube

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#351]
Since Qt 5.4, the background on Youtube HTML5 videos flashes about once per second.

**Comment by The-Compiler** [comment]
There was now a patch posted to the bug: https://codereview.qt-project.org/#/c/102971/

Allan Sandfeld Jensen (the QtWebKit maintainer) said he thought it was only an optimisation but it might fix the issue - is there anyone here who can easily compile QtWebKit with that patch and try if it goes away? I don't really have the toolchain ready to do that easily at the moment.

**Comment by mrabault** [comment]
I have that problem  with YouTube too. However, Dailymotion works perfectly. I'll perhaps compile QtWebKit with the patch if I find the time.

**Comment by The-Compiler** [comment]
I'm not set up to test patches but didn't test this one yet.

@mrabault are you on 64bit Arch by any chance? If so, I could build and share a package.

**Comment by mrabault** [comment]
Yep, Arch 64-bit. I'd definitely be interested in a package, that's the only problem I have with qutebrowser, everything else sounds nice (except the Vimeo thing but to be frank, I don't use it that often and I could use mpv).

**Comment by The-Compiler** [comment]
5.4.1 was [released upstream](http://blog.qt.io/blog/2015/02/24/qt-5-4-1-released/) a few days ago and fixes this issue for me.
