### ISSUE TITLE
Downloads should remember last path

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#37]
If the user has set an absolute path for a download, the next time when the prompt shows, the same path should be pre-filled.

**Comment by Carpetsmoker** [comment]
I was thinking of adding 2 "special" values to the `download-directory` setting:

- `%remember%` - Remember last path
-  `%remember_persist%` - Remember last path, and persist this to the session

whadayathink?

**Comment by Carpetsmoker** [comment]
I just saw https://github.com/The-Compiler/qutebrowser/issues/277, so maybe:

- `download-directory` -> A path
- `download-dialog` -> `always-ask`, `auto-download`, `remember-last`, `remember-last-session`
