### ISSUE TITLE
FR: Enter/RET on link found in a `/` search should follow link

### ISSUE THREAD

**Issue by fosskers** [The-Compiler/qutebrowser#401]
DWB does this, and it would be convenient to have.

**Comment by mgraham** [comment]
+1

**Comment by Carpetsmoker** [comment]
I added some code to do this; but parsing the current selection as HTML seems to be difficult. There's no obvious way to get a `QWebElement` or the like, and using `QDomDocument` also doesn't seem to work.

My second idea was to get the coordinated of the current selection, and simulate a mouse click (this is perhaps better, since this will make JS links and the like work), but I couldn't figure out how to do that either ...

**Comment by The-Compiler** [comment]
I'd probably do something based on Python's [xml.etree](https://docs.python.org/3.4/library/xml.etree.elementtree.html#module-xml.etree.ElementTree).

I just played with it a bit and it seems to work at least for the most common case:

```
>>> import xml.etree
>>> elem = xml.etree.ElementTree.fromstring('<a href="http://www.example.com/">blah</a>')
>>> elem.attrib['href']
'http://www.example.com/'
```

**Comment by antoyo** [comment]
I did some work [here](https://github.com/antoyo/qutebrowser/commit/6ca541d359b5d1d3cd088efc65683cce6bbb35cc) but there is still an issue: when the user is pressing the control key, the link is not opened in a new tab.
Do you have any idea to fix this issue?

**Comment by The-Compiler** [comment]
@antoyo Oh, nice! I didn't consider using Javascript to do that... Of course a downside would be that it doesn't work when JS is disabled, but it's better than nothing :smile:

Some thoughts:

* Please open a WIP pullrequest, it's hard to keep up with things when it's buried in some issue :smile:
* Maybe a fallback for when JS is disabled (using the method mentioned above) could be added?
* What does this do when there's something other than a link selected, or with no selection at all?
* Try setting `widget.page().open_target = usertypes.ClickTarget.tab` and see if that opens it in a new tab.

**Comment by The-Compiler** [comment]
Closing this as the PR is merged - thanks @antoyo!
