### ISSUE TITLE
:open Requires Argument?

### ISSUE THREAD

**Issue by htylo** [The-Compiler/qutebrowser#403]
In luakit, `:open -t` with no URI opens `about:blank` in a new tab. I can't remember if this is default behaviour or something I changed, all I know is *I feel lost* without it :)

Is a setting for default URI when `:open` is used without args a sane thing to implement?

Further thoughts:
* It might be saner to implement as 3 different defaults:
    * When `open` is used (current tab), complain.
    * When `open -t [-b]` is used, open one particular page (`about:blank`, or something else)
    * When `open -w` is used, open another particular page (the homepage, or something else)

**Comment by The-Compiler** [comment]
@htylo - Do you really think it should be that sophisticated? I wonder if it'd be enough to just open `about:blank` hardcoded in any case.

@fosskers - I think opening a new tab by default will be annoying - do you think doing `:open -t` then `:set` is too verbose?

**Comment by The-Compiler** [comment]
This has been closed a while ago already in 561ebd07f99d1b22a91cafd73d7381f8814a16ba - now you can set `general -> default-page` and `:open -[twb]` without argument will open that.
