### ISSUE TITLE
Decide where to use : for commands

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#406]
e.g. for `set-cmd-text` a `:` is needed, but for some hint commands not

**Comment by krobelus** [comment]
Once #615 is fixed, the hint target 'run' can be replaced by 'fill' followed by command-accept if I'm not mistaken
Also 'run' is probably not needed anyway since one can just use a userscript instead, I think it can be removed.

**Comment by The-Compiler** [comment]
`:run` still could be useful for some purposes, so as it works, I don't see why it should be removed - the other solutions sound like inconvenient workarounds :wink:

**Comment by krobelus** [comment]
Well, removing would have been the easiest solution ;)
Other than that I think the startchar should be required.

**Comment by The-Compiler** [comment]
Overview of the current situation:

What | Requires startchar | Using `/` or `?` would make sense
-----|--------------------|----------------------------------
key config | no | no
`set-cmd-text` | yes | yes
`:hint` with fill target | yes | yes
`:hint` with run target | no | no
`:bind` | no | no
`:later` | no | no
`:repeat` | no | no

For everything except filling the commandline, using `/` or `?` doesn't make sense, and using the `search` command instead is equivalent.

So the current behaviour actually makes sense, because `set-cmd-text` and `:hint` with the fill target actually *interact with the commandline* - so `:` basically is used for the commandline, and no prefix for everywhere else.

-> closing this.
