### ISSUE TITLE
Fonts are slimmer than webkit browsers such as dwb/luakit/etc.

### ISSUE THREAD

**Issue by isene** [The-Compiler/qutebrowser#423]
Screenshots show the comparison between qutebrowser and dwb.

Relevant settings:

Qutebrowser:
    _monospace = Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream
    Vera Sans Mono", "Andale Mono", "Liberation Mono", "Courier New", Courier,
    monospace, Fixed, Consolas, Terminal
    completion = 10pt ${_monospace}
    tabbar = 10pt ${_monospace}
    statusbar = 10pt ${_monospace}
    downloads = 10pt ${_monospace}
    hints = bold 12px Monospace
    debug-console = 8pt ${_monospace}
    web-family-standard =
    web-family-fixed =
    web-family-serif =
    web-family-sans-serif =
    web-family-cursive =
    web-family-fantasy =
    web-size-minimum =
    web-size-minimum-logical =
    web-size-default =
    web-size-default-fixed =

Dwb:
    minimum-logical-font-size=11
    sans-serif-font-family=sans-serif
    fantasy-font-family=serif
    default-monospace-font-size=11
    serif-font-family=serif
    default-font-family=sans-serif
    cursive-font-family=serif
    font=sans-serif 9
    monospace-font-family=monospace
    minimum-font-size=11
    default-font-size=11
![dwb](https://cloud.githubusercontent.com/assets/390340/5564578/90f86a96-8ec9-11e4-96bf-4a971aeec263.png)
![qute](https://cloud.githubusercontent.com/assets/390340/5564579/90fa4c8a-8ec9-11e4-81bc-45cebaca7a8e.png)

**Comment by The-Compiler** [comment]
Apart of the titles (which seem to be due to google serving different things?) it looks the same for me:

![2015-01-03-160907_1366x768_scrot](https://cloud.githubusercontent.com/assets/625793/5602741/f8e6b4bc-9362-11e4-9ed0-f53c8328a7d3.png)

so I'm not sure if this is something I actually should report as a bug upstream. What do you think?

**Comment by isene** [comment]
Odd - what could make the difference between my two images, then?

**Comment by The-Compiler** [comment]
No idea, I don't really know much about fonts... My config is just a default archlinux font config.

**Comment by isene** [comment]
Yup - I suggest closing this issue, crossing fingers and see what emerges. I could always reopen this if it doesn't change through this. In any case - my new font setup handles this in the meantime.
