### ISSUE TITLE
Crash when "é" in download name

### ISSUE THREAD

**Issue by Grulfen** [The-Compiler/qutebrowser#427]
qutebrowser crashes when I try to download a file with a "é" in the name. It does not crash when I changed it to a normal "e".

**Comment by The-Compiler** [comment]
Do you happen to have a link where I can test this? It happened for you on Google Drive, right?

It works fine when I download http://qutebrowser.org/bug-tests/tést - can you confirm that?

Report: http://paste.the-compiler.org/view/41c048d0

Log:

```
16:27:02 DEBUG    downloads  downloads:set_filename:406 Setting filename to Circuitos eléctricos.pdf
16:27:02 ERROR    misc       app:_exception_hook:514 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/browser/downloads.py", line 407, in set_filename
    if os.path.isfile(self._filename):
  File "/usr/lib/python3.4/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 36: ordinal not in range(128)
```

**Comment by Grulfen** [comment]
Yes, it happened on google drive, but I can repoduce it anywhere. The download link you posted make the browser crash for me.

**Comment by The-Compiler** [comment]
What does `locale` in a terminal say for you?

I can reproduce this when setting `LC_ALL=C`. I'm not sure what's the best way to fix this though...

**Comment by Grulfen** [comment]
My locale prints:

LANG=C
LC_CTYPE=C
LC_NUMERIC=C
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=C
LC_MESSAGES=C
LC_PAPER=C
LC_NAME=C
LC_ADDRESS=C
LC_TELEPHONE=C
LC_MEASUREMENT=C
LC_IDENTIFICATION=C
LC_ALL=

And I tried changing it to en_US.UTF8 and that makes it so that the browser doesn't crash anymore.

**Comment by The-Compiler** [comment]
Now qutebrowser will replace such chars with a question mark instead.

However you should really fix your system to use proper locales, see https://wiki.archlinux.org/index.php/Configuring_locales
