### ISSUE TITLE
Invalid value

### ISSUE THREAD

**Issue by underr** [The-Compiler/qutebrowser#441]
Installed it from the AUR package qutebrowser-git.
When I open it, it crashes in this error: 
`ERROR: Invalid value 'http://www.malwaredomainlist.com/hostslist/hosts.txt,http://someonewhocares.org/hosts/hosts,http://winhelp2002.mvps.org/hosts.zip,http://malwaredomains.lehigh.edu/files/justdomains.zip,http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext,' - values may not be empty!
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/config.py", line 125, in init
    config_obj = ConfigManager(confdir, 'qutebrowser.conf', app)
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/config.py", line 234, in __init__
    self._validate_all()
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/config.py", line 371, in _validate_all
    opt.typ.validate(interpolated)
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/configtypes.py", line 1181, in validate
    raise configexc.ValidationError(value, "values may not be "
qutebrowser.config.configexc.ValidationError: Invalid value 'http://www.malwaredomainlist.com/hostslist/hosts.txt,http://someonewhocares.org/hosts/hosts,http://winhelp2002.mvps.org/hosts.zip,http://malwaredomains.lehigh.edu/files/justdomains.zip,http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext,' - values may not be empty!`

**Comment by ml-** [comment]
Related:
https://github.com/The-Compiler/qutebrowser/issues/439
https://github.com/The-Compiler/qutebrowser/issues/438

Fix (pending Pull request):
https://github.com/The-Compiler/qutebrowser/pull/440/files

**Comment by underr** [comment]
Thanks for the fix, closing this because it seems it'll be resolved soon.

**Comment by The-Compiler** [comment]
That's embarrassing... Sorry! :blush:. The fix is now merged.

I also added an unit test validating the default config so I should notice this earlier in the future.
