### ISSUE TITLE
Closing a single tab should open about:blank

### ISSUE THREAD

**Issue by thiagowfx** [The-Compiler/qutebrowser#444]
Currently issuing a `tab-close` ('d' hotkey) when only a single tab is opened results in nothing (=the tab remains open).

A more natural behavior would be to either:

1. To close the browser.
2. or to replace the current tab (=the unique one opened) with a about:blank page, or similar.

I find that the second action is more natural. It is also (for example) the behavior adopted by luakit.

**Comment by peterlvilim** [comment]
In dwb I belive the result is the browser closes.

**Comment by The-Compiler** [comment]
You can already customize that behaviour with the `tabs->last-close` setting (`blank`/`close`/`ignore`). I personally prefer the qutebrowser behaviour (`ignore`), but of course it's debatable whether the default should be changed.

**Comment by The-Compiler** [comment]
I just checked with a clean config in dwb - the behaviour is the same as in qutebrowser (`ignore`). I also don't think many people changed this, so I think the default makes sense this way. Of course opinions differ, but that's what options are for :)

**Comment by thiagowfx** [comment]
Ops, I missed this config option, sorry for that. In fact, I see that it is complete already (blank/close/ignore are all the options you could _a priori_ want from deleting a single tab).

About its default value: well, *I* personally find strange the ignore behavior. If you pressed 'd', you want something to happen. We could try to make a small list. From my head:

- Chromium/Chrome: close
- Firefox: close
- Opera (at least old versions): blank
- LuaKit: blank
- dwb: ignore

You see, it is just a matter of taste and opinion. But I won't insist on that, I'll just change my config file.
