### ISSUE TITLE
Add documentation for userscripts.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#450]
After #448 is finished, we should add some documentation about userscript and variables:

* `QUTE_URL`
* `QUTE_TITLE`
* `QUTE_MODE`
* `QUTE_SELECTED_TEXT`
* `QUTE_SELECTED_HTML`
* `QUTE_USER_AGENT`

**Comment by angelic-sedition** [comment]
I think it might be better to call them something other than userscripts (or maybe to call them "qutebrowser userscripts") so as not to cause confusion with greasemonkey userscripts.

**Comment by The-Compiler** [comment]
I got the term from [dwb](http://portix.bitbucket.org/dwb/) where they are called userscripts as well. I now added a sentence to the documentation pointing out they are unrelated.

If you see another place where this could be improved, please let me know! But I'd rather like to keep the term userscripts (as dwb users are familiar with it), and call the greasemonkey scripts greasemonkey consistently.
