### ISSUE TITLE
Checkboxes and Radio Buttons don't appear

### ISSUE THREAD

**Issue by aguynamedryan** [The-Compiler/qutebrowser#459]
I absolutely love this browser.

However, when I visit a page that has checkboxes or radio buttons, e.g. http://www.nngroup.com/articles/checkboxes-vs-radio-buttons/ the check boxes and radio buttons don't appear at all and I can't interact with them.

I'm running qutebrowswer under Mac OS X 10.10.1

qute:version output:
qutebrowser v0.1.1
Git commit: 

CPython: 3.4.2
Qt: 5.4.0, runtime: 5.4.0
PyQt: 5.3.2
SIP: 4.16.3
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.7.3
pygments: 2.0.1
Webkit: 538.1
Harfbuzz: system

Frozen: False
Platform: Darwin-14.0.0-x86_64-i386-64bit, 64bit
OS Version: 10.10.1, x86_64

**Comment by underr** [comment]
Running a pretty recent version and it's working just fine here.

**Comment by The-Compiler** [comment]
That is unfortunately an (OS X only) Qt bug: https://bugreports.qt.io/browse/QTBUG-42948

There's no solution at the moment unfortunately.

It seems downgrading to Qt 5.3 would be a workaround, though that has other issues...

Can you try starting with `--qt-style fusion` and see if it still happens then?

**Comment by aguynamedryan** [comment]
@The-Compiler when I start with `--qt-style fusion` the checkboxes and radio buttons appear and seem to work perfectly.  Thanks for the workaround!

**Comment by The-Compiler** [comment]
Thanks for testing! I guess it makes sense to switch the default style on OS X then. Non-native look is still better than non-functional checkboxes after all ;)

**Comment by RickCogley** [comment]
Hi - I'm getting this same problem now, and here's my version info pastebin: 

https://paste.the-compiler.org/view/4f73cbb6

How can I add that start switch mentioned above to the dmg version of qutebrowser?

**Comment by The-Compiler** [comment]
@RickCogley The underlying reason is likely very different in your case, see [QTBUG-70715](https://bugreports.qt.io/browse/QTBUG-70715). It was fixed in Qt 5.12, a qutebrowser release using that should follow in the next two weeks or so.

**Comment by RickCogley** [comment]
thanks @The-Compiler, indeed that appears to be it. I'll look forward to the update!
