### ISSUE TITLE
Ability to toggle settings

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#47]
Some ideas:
- [ ] `:set --cycle` to cycle setting between multiple values - for example, you could bind a key to `:set --cycle tabs position right top`.
- [ ] ~~Maybe also some special `PREVIOUS` value which goes back to the previous state.~~
- [x] bool settings toggleable with `:set sect opt!`
- [ ] ~~When saving last state (see bullet 2) we could also toggle between "false-value" and "last truth-y value" for settings which are nearly boolean (several true but one false state)~~

**Comment by haasn** [comment]
Oops, I'm very sorry about “stealing” this - I completely missed the “work in progress” label.

**Comment by m2habert** [comment]
¿Too late to add an idea? I've thought of 

`:set foo bar {toggle}`

**Comment by The-Compiler** [comment]
To toggle boolean values, there's `:set foo bar!` already - no point in adding a different ~~[bikeshed color](http://shed.bike)~~ syntax now :wink:

**Comment by m2habert** [comment]
... and `!` it's obviously more "vimish". Sorry, totally forgot.
