### ISSUE TITLE
Open flash video issues

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#473]
- [x] Vimeo videos don't play
- [x] Embedded youtube videos don't load

**Comment by mrabault** [comment]
I have the same problem with Vimeo. YouTube and Dailymotion still work fine (except for the flashing in YouTube vids).

**Comment by The-Compiler** [comment]
Seems like there's an [upstream WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=138606) (but not QtWebKit) for the Vimeo issue.

**Comment by The-Compiler** [comment]
Vimeo is still broken in Qt 5.5 beta.

**Comment by The-Compiler** [comment]
vimeo: https://bugreports.qt.io/browse/QTBUG-47269

**Comment by The-Compiler** [comment]
Embedded youtube videos work fine here - tried with http://scratchbook.ch/2015/06/26/softwareentwicklung/

**Comment by The-Compiler** [comment]
FWIW Vimeo seems to work fine now

**Comment by tgy** [comment]
Vimeo does not work for me. I'm on mac OS 10.13.5 (High Sierra) with

```
qutebrowser v1.3.3
Git commit: ad9b50601-dirty (2018-06-21 23:30:51 +0200)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.0
PyQt: 5.10

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: Secure Transport, macOS High Sierra (10.13)

Style: QWindowsStyle
Platform: Darwin-17.6.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.13.5, x86_64

Paths:
auto config: /Users/viovene/Library/Preferences/qutebrowser
cache: /Users/viovene/Library/Caches/qutebrowser
config: /Users/viovene/.qutebrowser
data: /Users/viovene/Library/Application Support/qutebrowser
runtime: /var/folders/d9/c026wqfd69d4v4__gg3dfn0h0000gq/T/qutebrowser

Uptime: 19:07:40
```

**Comment by The-Compiler** [comment]
@tgy See https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#on-macos:

> The binary release ships with a QtWebEngine built without proprietary codec support. To get support for e.g. h264/h265 videos, you’ll need to build QtWebEngine from source yourself with support for that enabled.
