### ISSUE TITLE
import firefox bookmarks from Mozilla server (Firefox sync)

### ISSUE THREAD

**Issue by tex** [The-Compiler/qutebrowser#485]
Hi,

Is it possible to import / export bookmarks from / to Mozilla server?

I use Firefox on my phone and bookmark synchronization is very useful.

**Comment by The-Compiler** [comment]
I agree it would be useful - but I don't use Firefox sync at all, so I won't do this unfortunately, and I don't think it should go into the core.

Two places where this would make sense:

* A separate script, similiar to [scripts/importer.py](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/importer.py) which imports Chrome/Chromium bookmarks.
* A plugin, when there's a plugin API - see #30 

As said - I won't do it myself, but I'd gladly accept contributions for that!
