### ISSUE TITLE
Back and Forward not working on reddit

### ISSUE THREAD

**Issue by Gadileth** [The-Compiler/qutebrowser#493]
When browsing **reddit**, `H` and `L` for going back and forward in history does not work. 

Haven't found the reason yet.

**Comment by The-Compiler** [comment]
Weird - this smells like an upstream Qt issue, but I can't reproduce it in any other Qt based browser (my own minimal example, Otter and the Qt demo browser).

Looking at Wireshark, it really seems to just load the same page again. Pressing `H` two or three times fast goes back, but then it seems going forward doesn't work which is weird.

**Comment by The-Compiler** [comment]
If I delete `~/.local/share/qutebrowser/blocked-hosts` it goes away, so it seems to be related to the adblocker somehow.

Console output:

```
INFO: Request to pixel.redditmedia.com blocked by host blocker.
INFO: Request to www.google-analytics.com blocked by host blocker.
INFO: Request to static.adzerk.net blocked by host blocker.
ERROR: Error while loading http://static.adzerk.net/reddit/ads.html?sr=gifs,loggedout&bust2#http://www.reddit.com: Request blocked by host blocker.
```

**Comment by The-Compiler** [comment]
The blocking of `static.adzerk.net` seems to be the issue. It also happens on 0134646c6753f309af01ebecc10e879ae5198825 which was the first commit with an adblocker.

I'll take a closer look at why this is happening tomorrow.
