### ISSUE TITLE
Add support for the Destop Notifications API

### ISSUE THREAD

**Issue by traverseda** [The-Compiler/qutebrowser#503]
Not high priority, and I expect it will be up for a while. [MDN on notifications](https://developer.mozilla.org/en/docs/Web/API/notification).

[qtwebkit bug report on the issue](https://bugs.webkit.org/show_bug.cgi?id=35503)

**Comment by The-Compiler** [comment]
Actually this seemed quite easy to implement, as we just have to handle the permission requests and Qt will handle the rest. Also we get geolocation as well by implementing that!

**Comment by traverseda** [comment]
Awesome. I love low-hanging fruit.
