### ISSUE TITLE
Invalid history entry - %20 character gets changed to normal whitespace in history

### ISSUE THREAD

**Issue by rikn00** [The-Compiler/qutebrowser#508]
Visiting web site with a %20 whitespace in url gets logged to history badly. %20 character changes to normal whitespace which causes an invalid history entry error when starting qutebrowser.
```
Error while initializing: Invalid history entry '1423686505 http://wiki.cyanogenmod.org/w/Devices#vendor="Sony Ericsson";'
```
I didn't look for other sites using %20 in url but this is reproduceable on http://wiki.cyanogenmod.org/w/Devices#vendor=; by selecting a vendor with a whitespace in its name. Then close qutebrowser and it doensn't start again. Clearing this bad line from history file naturally fixes this. This happens on freshly-updated git but on older one too.

I also noted that when using "open based on open url" (go) the url is showed with all %22 and %20 characters in place. Statusbar on the other hand shows %22 as %22 but %20 is showed as a whitespace. So I think the change of character might happen when a url is changed to another format/type (I don't know if this happens in code, just a wild guess).

**Comment by The-Compiler** [comment]
Gah! I noticed this issue a few days ago when I was working on sessions - but I only thought it'd affect some history entries, not cause qutebrowser to not start at all. Then I forgot to fix it... (I really should find a good CLI client for github issues, so I open even more :D)

Usually QtWebKit-stuff gives me the URLs as [QUrl](http://doc.qt.io/qt-5/qurl.html) internally, which has various ways to be represented as a string (string/displayString/encoded).

However for the thing I use for the history ([QWebHistoryInterface](http://doc.qt.io/qt-5/qwebhistoryinterface.html)) I get the URL as a string, so I have to find out how to parse these entries properly... I assumed they were percent-encoded.

For 'go', I have a QUrl, so I could probably do something more sensible there.

**Comment by The-Compiler** [comment]
I opened a separate issue for the handling of that URL in the statusbar and related features (yanking, `go`): #509 - it seems weird and I'll have to take a closer look when I get time for that.
