### ISSUE TITLE
Add support for running qutebrowser twice with a different basedir.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#510]
For development, it'd be nice if we could launch qutebrowser with `--basedir` or so pointed to a different directory, and being able to run it twice this way. We should adjust the `QLocalServer` path accordingly - maybe add the base path as a checksum or so?

**Comment by Ram-Z** [comment]
This should be achievable by running:

```
XDG_CONFIG_HOME=/path/to/config XDG_DATA_HOME=/path/to/data qutebrowser
```

**Comment by The-Compiler** [comment]
Yeah, the problem is currently qutebrowser prevents being runned twice, no matter what those directories are.
