### ISSUE TITLE
Allow setting different X11 WM_CLASS for different windows.

### ISSUE THREAD

**Issue by Ram-Z** [The-Compiler/qutebrowser#514]
It would help a lot setting specialized window manager rules for qutebrowsers windows.

**Comment by The-Compiler** [comment]
Unfortunately, Qt [doesn't seem to expose an API](http://stackoverflow.com/a/11851378/2085149) to set  `WM_CLASS`. The only thing you could affect would be the title, but I guess that's ugly as well, right? Closing this for now, sorry...

**Comment by Ram-Z** [comment]
`QApplication.setApplicationName()` will set the `WM_CLASS`. I'm not familiar enough with PyQt to know if this can be set for each window though. Will look into it and report back.

**Comment by The-Compiler** [comment]
That'd have a lot of other implications though, like where config files are stored, etc. :-/

**Comment by Ram-Z** [comment]
Indeed, and I couldn't find anything that would set that for windows. :(

**Comment by Ram-Z** [comment]
`RESOURCE_NAME=new-name qutebrowser` works for the entire application. `qutebrowser -name new-name` should work as well but `argarse` intercepts -name and throws an error.

According to the standard [icccm standard](http://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.5) WM_CLASS contains two strings, one that names the particular instance of the application that owns the window and one that names the general class of applications the window belongs to. Setting different WM_CLASS strings for windows of the same instance is therefor not wanted. I guess what I need to make this work is being able to launch multiple instances of qutebrowser.
