### ISSUE TITLE
Better handling of sessions

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#523]
(edited based on feedback):

- [x] `:session-save` without argument always saves to `default`
- [x] `:session-save` prints where it saved to.
- [x] Auto-saving (on quit) saves to the last loaded session - e.g. when starting with `-r foo` and then using `:session-load bar`, auto-saving saves to `bar`.
- [x] Maybe add a `--tmp` or so switch to `:session-load` so it doesn't affect the session in which stuff is saved?
- [x] Add a `--clear` argument to `:session-load` to close all existing windows.
- [x] The default session never gets deleted.
- [x] We add a `session = ...` to the `state` file. If not present (or empty), no session has been saved and none should be loaded. If it's a session name, that gets loaded on the next start (unless `-r`/`-R` is given).
- [x] Add an `-R` argument to not load a session even if a load is scheduled.

Also see #572.

```
<oed> The-Compiler: the default session file seems to be deleted once the browser loads
<oed> is this intended?
<iggy> I noticed it too (mostly because I was making the browser crash and I had to keep putting a non-empty default session file down to test)
<The-Compiler> oed, iggy: yeah, currently the default session is deleted after it's loaded and then created again on shutdown if requested. Open to other suggestions - maybe a flag in the state file to see if it should be loaded, and it's never automatically deleted?
<iggy> the only problem I have with it is... crashes, you lose everything
<The-Compiler> iggy: yeah, soon there should be a recovery session for that :)
<The-Compiler> iggy: but maybe it's still unexpected, that could be true
<oed> shouldn't the recovery session just be the default session?
<The-Compiler> oed: hmm, interesting approach, didn't think of that... Though that could be confusing then, when the user wants to quit without saving their changes to the default session and it's still saved?
<oed> The-Compiler: I don't really get why you would want saving to be handled manualy
<oed> but maybe thats just me
<The-Compiler> I don't want my browser to auto-reopen whatever was open when I closed it
<The-Compiler> I sometimes use my laptop at home and at work :P
<oed> but then you use a different session right?
<oed> autosave to the session you are currently using?
<The-Compiler> oh, qutebrowser doesn't do that, it probably should!

<Ram-Z> hm... why is the default session deleted on app.py:288 ?
<Ram-Z> it doesn't make any sense to me, when I load a different session I don't want my default session to be deleted
<The-Compiler> Ram-Z: ugh, good point.
<The-Compiler> Ram-Z: originally I planned to just load the default session if it's there (and then delete it)
<The-Compiler> Ram-Z: I probably should never delete it, and instead set a flag to see whether it should be loaded or not
<Ram-Z> yeah, makes sense to keep it around
<Ram-Z> oh... there's also another issue I noticed...
<Ram-Z> when I open a session with -r session1 I'd expect :session-save to save to that session instead of the default one
<Ram-Z> so session-save should be aware of what session was last loaded, and save to that session
```

**Comment by The-Compiler** [comment]
Some proposals for the first part:

* `:session-save` without argument always saves to `default`.
* Auto-saving saves to the last loaded session - e.g. when starting with `-r foo` and then using `:session-save bar`, auto-saving (and `:wq`?) save to `bar`.
* Maybe add a `--tmp` or so switch to `:session-load` so it doesn't affect the session in which stuff is saved?
* The default session never gets deleted.
* We add a `session = ...` to the `state` file. If not present (or empty), no session has been saved and none should be loaded. If it's a session name, that gets loaded on the next start (unless `-r` is given).

**Comment by iggy** [comment]
Looks good. Maybe a reserved keyword to -r (```-r _blank```) to not load the session saved as default.

**Comment by Ram-Z** [comment]
IMHO `:session-save` should save the current session because without arguments I would assume it acts on the current context which is the last loaded session. 

But as long as there is a way to save the current session which is independent of its name I'm OK with it. All that is really needed is a command that I could alias to say `:w` which would save to the current session. `:session-save --current` or `:session-save $current_session`.

> Auto-saving saves to the last loaded session - e.g. when starting with `-r foo` and then using `:session-save bar`, auto-saving (and `:wq?`) save to `bar`.

I suppose you meant `:session-load bar`

**Comment by The-Compiler** [comment]
> Looks good. Maybe a reserved keyword to -r (```-r _blank```) to not load the session saved as default.

I think I'll do the same dwb does here, and add an `-R`/`--override-restore` option for that.

> IMHO `:session-save` should save the current session because without arguments I would assume it acts on the current context which is the last loaded session. 
>
> But as long as there is a way to save the current session which is independent of its name I'm OK with it. All that is really needed is a command that I could alias to say `:w` which would save to the current session. `:session-save --current` or `:session-save $current_session`.

I have to think about this again. It seems there are both people who prefer the default session, and people who prefer saving the active session.

I think if people use sessions just as "sophisticated bookmarks", saving to the last loaded one might be surprising.

Let's say I have some news I wanted to read saved in the `news` session, then I go to work, at some later I load the `news` session (with, for example, some qutebrowser stuff already open) and read my news. Now when I just want to do a quick save (for example because I need to restart qutebrowser), I wouldn't expect `:save-session` to overwrite my `news` session.

> > Auto-saving saves to the last loaded session - e.g. when starting with `-r foo` and then using `:session-save bar`, auto-saving (and `:wq?`) save to `bar`.
> 
> I suppose you meant `:session-load bar`

Indeed - corrected.

**Comment by The-Compiler** [comment]
I first implemented this like in my proposal in the first post, but found it weird to use because `:wq`/quitting saved to a different session than `:session-save`.

I now added a new `general -> session-default-name` option. When empty (the default), everything (quitting/`:wq`/`:session-save`) saves to the last loaded session (or `default` if none was loaded).  When a name is given, the session is saved to that name instead.

@iggy / @Ram-Z: Can you test it and tell me if it fits your workflow and feels right? :smile:
