### ISSUE TITLE
Youtube video completely black

### ISSUE THREAD

**Issue by eubr** [The-Compiler/qutebrowser#529]
![Image of the bug](http://i.imgur.com/exhGwx7.png)

Using master, installed with python setup.py install before reading the INSTALL file, if it's relevant I'll reinstall it the proper way.

Happens with any video.

**Comment by The-Compiler** [comment]
Do you have the necessary codecs installed? If you tell me which distribution you're on I might be able to tell you the exact package names. Though this should probably be added to INSTALL as well.

**Comment by eubr** [comment]
I *think* I do (on chromium/firefox youtube works). I'm on Arch Linux.

**Comment by The-Compiler** [comment]
Chromium/Firefox both ship their own codecs with the browser - QtWebKit thinks they don't belong in a browser when you can just use the OS codecs (and so do I, FWIW).

Try installing these packages:

```
gst-libav gst-plugins-bad gst-plugins-base gst-plugins-base-libs gst-plugins-good gst-plugins-ugly
```

**Comment by The-Compiler** [comment]
Any update, @eubr?

**Comment by eubr** [comment]
@The-Compiler sorry, I worked on windows for a few days and I haven't booted arch yet. I will update this later.

**Comment by eubr** [comment]
I didn't have some of those, I installed them and now youtube works. Thank you.
