### ISSUE TITLE
j/k do not scroll on some sites while <up>/<down> do

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#534]
I've noticed that on some sites, I am unable to scroll vertically with the `j` and `k` keys.
This most often happens on sites that have more complex UI where only a section of the page scrolls while other elements remain static.
However, on [some pages](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-overview.html), it is possible to scroll with the `up` and `down` keys on the keyboard, so keyboard scrolling is clearly possible.
It would be nice to be able to use `j` and `k` on such sites rather than switching to `up` and `down`.

**Comment by rcorre** [comment]
On the linked page, you have to click inside the document before any scrolling works. After that, `up` and `down` scroll but `j` and `k` do not.

**Comment by The-Compiler** [comment]
See #218 - I've seen this on various pages, but didn't have time to take a closer look at why this is happening yet. I suspect it's an upstream Qt bug, but I should spend some time looking at why this is happening before I'll report it upstream.
