### ISSUE TITLE
Terrible performance viewing large files on Github

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#535]
Qutebrowser hangs extensively while viewing previews of large files on github like [this one](https://github.com/nim-lang/packages/blob/master/packages.json).
I have noticed this on both Linux and Windows.

**Comment by The-Compiler** [comment]
This is an upstream Qt bug, reported by me as [QTBUG-40559](https://bugreports.qt.io/browse/QTBUG-40559) some while ago. It should've improved a lot with the [patch](https://codereview.qt-project.org/#/c/103250/) which was posted, which will be in Qt 5.5, [planned for May](http://wiki.qt.io/Qt-5.5-release).
