### ISSUE TITLE
[feature-request] support of both system clipboards

### ISSUE THREAD

**Issue by shibumi** [The-Compiler/qutebrowser#537]
Hello,
I am using rxvt-unicode as standard-terminal. I can't copypaste stuff there with CTRL+c and CTRL+v and I must use a click on the mouse-wheel to paste something. Is it possible to change the standard clipboard of qutebrowser?

There are 2 different system-clipboards. Everytime when I want to paste an url into my terminal I must do the following:

press 'yy'
paste the url somewhere via CTRL+v
recopy it with CTRL+a and CTRL+c

when this is done I can copypaste the url with click on the mousewheel in my terminal..

so support for both systemwide clipboards would be awesome. thx 

regards

Chris

**Comment by The-Compiler** [comment]
You can use `yY` to yank to primary selection instead. Of course you can remap this easily:

```
:unbind yY
:unbind yy
:bind yY yank
:bind yy yank -s
```

(or edit `keys.conf` by hand)

**Comment by shibumi** [comment]
thx awesome!

**Comment by r8b7xy** [comment]
ctrl-c/yy and for handling the urxvt use alt+ctrl+v/c
