### ISSUE TITLE
XI_BadDevice when USB keyboard/mouse is disconnected

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#538]
Several people (@V155, @Jahkeup, maybe more) experienced segfaults in Qt when disconnecting USB keyboards/mice.

Reports:

* http://paste.the-compiler.org/view/f32a2852
* http://paste.the-compiler.org/view/66dbf2ec

Output:

```
DEBUG    webview    webpage:acceptNavigationRequest:545 acceptNavigationRequest, url about:blank, type NavigationTypeOther, hint target None, open_target ClickTarget.normal
The program 'python3' received an X Window System error.
This probably reflects a bug in the program.
The error was 'XI_BadDevice (invalid Device parameter)'.
  (Details: serial 3963 error_code 129 request_code 131 minor_code 48)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

(weird) backtrace: http://paste.the-compiler.org/view/44592c0d

Apparently it's not reproducible in otter, and breaking on `gdk_x_error` like suggested doesn't seem to work,. with `-sync` and `--sync` given.

There's also [QTBUG-40820](https://bugreports.qt.io/browse/QTBUG-40820) but that should already be fixed for some time.

I've not been able to reproduce it in some simple tests, so no idea what's going on there...

**Comment by The-Compiler** [comment]
@V155, @Jahkeup are you still having issues with Qt 5.5?

**Comment by V155** [comment]
Can't reproduce it anymore

**Comment by The-Compiler** [comment]
Assuming it's fixed then, thanks!
