### ISSUE TITLE
Adopting pytest

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#550]
We're switching from `unittest` to [pytest](http://pytest.org/latest/) as a part of [adopt pytest month](http://pytest.org/latest/adopt.html) - pytest will give us:

* Nice/colored output by default
* More features and less insanity
* [Nicer testing API](http://pythontesting.net/framework/pytest/pytest-introduction/)
* Many interesting plugins
    - [timeout](https://pypi.python.org/pypi/pytest-timeout)
    - [sugar](http://pivotfinland.com/pytest-sugar/)
    - [qt](https://pypi.python.org/pypi/pytest-qt) (only Qt4 though...)
    - [catchlog](https://pypi.python.org/pypi/pytest-catchlog) / [capturelog](https://pypi.python.org/pypi/pytest-capturelog)
    - [sourceorder](https://pypi.python.org/pypi/pytest-sourceorder) / [ordering](https://github.com/ftobia/pytest-ordering)
    - [cov](https://pypi.python.org/pypi/pytest-cov)
    - [localserver](https://pypi.python.org/pypi/pytest-localserver)
* No HTML output :( - but maybe we could port @ionelmc's [nose-htmloutput](https://github.com/ionelmc/nose-htmloutput) at some point?

Some things we might like to tackle:

- [x] Adjust `tox.ini` and the [buildbot](http://qutebrowser.org:8010/waterfall?reload=5) to use pytest as the existing unittest tests already run.
   -  [x] Use [pytest-cov](https://pypi.python.org/pypi/pytest-cov) and integrate it into buildbot - there are some posts for nose ([1](http://www.codelord.net/2010/05/09/python-nose-test-coverage-on-buildbot/), [2](http://copypasteprogrammer.blogspot.ch/2010/03/buildbot-and-nose-test-coverage.html)) which might be useful)
- [x] Adjust existing tests to use pytest's features:
   - [x] [assert](http://pytest.org/latest/assert.html#assert-with-the-assert-statement)
   - [x] [fixtures](http://pytest.org/latest/fixture.html#fixture)
   - [x] ...
- [x] Start using [pytest-qt](https://pypi.python.org/pypi/pytest-qt) for GUI testing once it's ported to Qt5.

**Comment by The-Compiler** [comment]
pytest seems a lot nicer.

I've signed up for the [adopt pytest month](http://pytest.org/latest/adopt.html). qutebrowser doesn't really fill the "*has more than one core developer*" prerequisite, but I was encouraged to sign up anyways.

**Comment by nicoddemus** [comment]
Hi!

@hackebrot and I will be your pytest helpers. Nice to meet you! :smile: 

Raphael and I would like to hear from you what would be the first thing about your test suite you would like us to tackle? Our guess is that you would like to get some GUI testing done using [pytest-qt](https://github.com/pytest-dev/pytest-qt), is that correct? If so, can you point which of the widgets you feel are simple enough for us to start writing tests for?

I have already cloned the repository (on Windows) and managed to execute the entire test suite, first using `unittest` and then using `pytest` (without any modifications on the code), so we're off to a good start. :smile:

Cheers, :beers:

**Comment by iggy** [comment]
As @The-Compiler mentioned above, pytest-qt is for qt4 only. Qutebrowser is written around pyqt5. So you'll maybe want to start somewhere else. Thanks for the help :)

**Comment by nicoddemus** [comment]
Oh don't worry about it, I will port pytest-qt to PyQt5 today (should be simple), so we can move this discussion onward regardless. :smile:

**Comment by The-Compiler** [comment]
Awesome, thanks in advance for helping! :)

I adjusted the first post to point out some things we could tackle - I'll look at the first one (getting pytest integrated in the buildbot) today hopefully.

I also think it'd help much to adjust the [existing tests](https://github.com/The-Compiler/qutebrowser/tree/master/qutebrowser/test) to make use of pytest's features, so I get a feeling of when to use what, and get rid of that ugly unittest API - but I realize that can be tedious work, so feel free to work on something else if you prefer :)

For the GUI testing, I think the [statusbar widgets](https://github.com/The-Compiler/qutebrowser/tree/master/qutebrowser/mainwindow/statusbar) would be a good start. [textbase.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/statusbar/textbase.py), [percentage.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/statusbar/percentage.py) and [progress.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/statusbar/progress.py) are very simple, [text.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/statusbar/text.py) and [url.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/statusbar/url.py) do a bit more, and the others are more complex. I think [bar.py](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/mainwindow/statusbar/bar.py) (the whole statusbar) would profit from tests a lot, as the handling of the various widgets and when to show what is rather tricky.

qutebrowser also supports being started and accepting commands via a FIFO (primarly used for [userscripts](https://github.com/The-Compiler/qutebrowser/blob/master/doc/userscripts.asciidoc)), but I imagine that could also be used for some more sophisticated "blackbox" tests where qutebrowser actually runs fully with some HTTP server (e.g. [pytest-localserver](https://pypi.python.org/pypi/pytest-localserver)) running, then is "used" via that FIFO, and the HTTP server is examined to make sure the right URLs were opened. See #172 for the general idea. This however needs some more work so qutebrowser can communicate exceptions/errors via exit status, and a second test instance with a different basedir can run (#510) - I'm working on that in the [smoke branch](
https://github.com/The-Compiler/qutebrowser/commits/smoke).

**Comment by hackebrot** [comment]
Hi! :wave: 

Thank you for your replies @iggy and @The-Compiler.

I just set up the environment on Ubuntu and ran the suite both with `unittest` and `pytest`:

```bash
unittests: commands succeeded
congratulations :)
```

From my experience it takes a few days to get a better understanding of a new project. Starting from the modules you pointed out I suggest that @nicoddemus and I will get back to you once we have a plan on how to get going.

I also joined your IRC channel on Freenode.

Very much looking forward to working with you on `qutebrowser`! :smiley:

**Comment by The-Compiler** [comment]
Thanks to you too, @hackebrot!

Also it might be worth mentioning this was my first big Python project, and my first GUI project - so if anything looks weird or in need of a refactoring to you, please let me know so I can clean things up!

Also, I'm happy to report the [buildbot](http://qutebrowser.org:8010/waterfall) uses pytest now, and everything still works (including coverage with pytest-cov).

**Comment by pfctdayelise** [comment]
Hey, just wanted to mention this in case it proves useful for screenshot type GUI testing. http://stackoverflow.com/questions/13364868/in-pytest-how-can-i-figure-out-if-a-test-failed-from-request

**Comment by nicoddemus** [comment]
FWIW, this is the approach we use at work: http://stackoverflow.com/questions/29261009/carrying-out-unit-testing-in-python-on-a-method-that-implements-imagedraw/29268346#29268346

I might create a plugin for that, if I get the time. :smile:

Cheers,
