### ISSUE TITLE
Sending an escape key to the running webpage

### ISSUE THREAD

**Issue by akirak** [The-Compiler/qutebrowser#551]
It would be nice if qutebrowser provides a way to send an escape key to the running webpage, especially for a better integration with [Trello](https://trello.com). 

Trello refuses to run on qutebrowser by default, but you can use it by faking the user agent string, e.g.:

    user-agent = Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36

One issue with using Trello on qutebrowser is that qutebrowser does not seem to provide a way to send an escape key to its inner webpage. Esc is the only shortcut to close a modal window of Trello without mouse, and as it terminates the passthrough mode of qutebrowser, I cannot close modal windows of Trello via keyboard. I always have to rely on mouse and it is annoying. Trello is a popular web application (developed by Fog Creek), and there may be even other similar situations where a keyboard-friendly web application fails to run elegantly on the excellent keyboard web browser. It would be useful to have a solution to this problem. 

I think adding a command like `sendkey <key>` that submits an arbitary key sequence to the inner page can be a workaround to this issue, but I just long for a solution anyway.

**Comment by oed** [comment]
I've thought about this issue aswell. Now that there are quite a lot of webapps that mimic vim keybindings it's common that you want to press esc without actually leaving insert mode in qute.

**Comment by The-Compiler** [comment]
I don't really know what a proper solution for this would be.

You can always unbind <kbd>Esc</kbd> in passthrough mode so only <kbd>Ctrl+[</kbd> gets you out of that - but if that was a default I guess people wouldn't be able to get out of passthrough mode easily anymore...

This would mean this change to `keys.conf`:

```ini
[!normal]

leave-mode
    <Ctrl-[>

[!normal,passthrough]

leave-mode
    <Escape>

[normal]
...
```

Maybe <kbd>Ctrl-V</kbd> should only pass through the next key (like in Pentadactyl), and <kbd>Ctrl-Z</kbd> should be permanent passthrough? In Pentadactyl you can also undo a <kbd>Ctrl-Z</kbd> using <kbd>Esc</kbd>, but maybe instead pressing <kbd>Ctrl-Z</kbd> again should get you out from the permanent passthrough mode?

A `:fake-key` command or so would indeed be nice, I'll open a separate issue for that.

**Comment by mgraham** [comment]
Maybe by default in normal mode, Escape could just send Escape?  

That means that in normal passthrough mode, you could close a modal by pressing Escape twice.

**Comment by Carpetsmoker** [comment]
As a FYI: Using Trello in `dwb` is annoying, because your cards always close when you hit `<Esc>` (even if you're not in insert mode). So when typing `o<Esc>` or some such makes you lose your card... :-/

**Comment by The-Compiler** [comment]
@mgraham: That sounds like a good solution actually, except that escape is already used for clearing search results. I think after the `:fake-key` (or `:send-key`) command mentioned above is implemented, I'll bind escape to `fake-key <Escape>;;search` or so by default.

@Carpetsmoker I remember this from when I was using dwb as well - for qutebrowser, when a key is bound in some way, the website will never get it.

**Comment by The-Compiler** [comment]
There's now the `:fake-key` command, so you can add something like `;;fake-key <Escape>` to your binding if you like that behaviour.

I'd like to keep the default behaviour as-is, for the reasons @Carpetsmoker outlined.
