### ISSUE TITLE
Consumes a large amount of memory when displaying the search result of DuckDuckGo

### ISSUE THREAD

**Issue by akirak** [The-Compiler/qutebrowser#552]
Qutebrowser uses more than 3 GB of memory when it displays a search result of DuckDuckGo. It doesn't happen when running a search via other browsers e.g. Firefox. The operating system is Arch Linux, the package is qutebrowser-git from AUR, the qutebrowser version is 0.1.3, and PyQt is 5.4.1. Is this a bug of qutebrowser or QtWebKit?

**Comment by The-Compiler** [comment]
This is a QtWebKit bug, already reported upstream as [QTBUG-44523](https://bugreports.qt.io/browse/QTBUG-44523).

I'm annoyed by it myself as well, but there's nothing I can do at the moment I'm afraid :-/

**Comment by The-Compiler** [comment]
There just was a patch posted upstream which hopefully will be part of Qt 5.4.2: https://codereview.qt-project.org/#/c/108782/

**Comment by akirak** [comment]
Thank you for your information.
