### ISSUE TITLE
Do content-sniffing for HTML

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#566]
When opening a local HTML file without `.html` extension, qutebrowser downloads the file instead of opening it.

Instead we should detect it's HTML and open it accordingly.

Ressources:
- [WhatWG MIME Sniffing Standard](https://mimesniff.spec.whatwg.org/#tag-terminating-byte)
- [Arora's implementation](https://github.com/Arora/arora/blob/master/src/webpage.cpp#L354-L375)
- [Eric's implementation](http://die-offenbachs.homelinux.org:48888/hg/eric/file/f9e3b6472b44/Helpviewer/HelpBrowserWV.py#l2480)

**Comment by The-Compiler** [comment]
Fixing this would mean changing `qutebrowser.browser.webpage.on_unsupported_content` to sniff the reply in the `else` branch, and then use `self.display_content` accordingly.

**Comment by l29ah** [comment]
I'd argue that it would make sense to view every file specified on the command line, as it should be much easier to implement and user must be knowing what is he doing when he does this. In fact, he won't ever want to "download" a local file.

**Comment by l29ah** [comment]
// in fact i'm upset that mutt can't view html in qutebrowser because it doesn't append ".html" to the temporary file's name

**Comment by The-Compiler** [comment]
Fair enough - though it still would need to set some kind of mimetype for them, and I'm not sure if it's a good idea to set `text/html` for everything local even if it's something completely different.

As a workaround, I think you can write a wrapper script which renames the file and launches qutebrowser on it, and then launch that from mutt.

**Comment by spaceone** [comment]
I wouldn't do this. I would always look at the Content-Type response header because this is the correct way to do things.
There is also a unofficial HTTP header `X-Content-Type-Options` which might have the value `nosniff` to prevent browsers (IE / Chrome) for doing such thing. Plus the Content-Disposition header should be evaluated.

**Comment by The-Compiler** [comment]
I don't think *local* files have HTTP headers :wink:

**Comment by The-Compiler** [comment]
Looks like qutebrowser does the right thing with QtWebEngine here, and I don't want to implement that for QtWebKit only.

**Comment by The-Compiler** [comment]
Another reason to not do this: Chromium disabled mime sniffing for local files (without .html extension) for security reasons: https://bugs.chromium.org/p/chromium/issues/detail?id=777737
