### ISSUE TITLE
Height of tabs and status panels

### ISSUE THREAD

**Issue by arbitrary-dev** [The-Compiler/qutebrowser#570]
There is a need for height parameter in config for tabs and status panels.

**Comment by The-Compiler** [comment]
I don't like the idea to set a *height* as at least the statusbar can get multi-line, but I think there should be a setting to add some padding. Right now it just adopts the font height.

See #407 for that - I started working on it but it didn't work right yet, and right now I'm busy with some other things.

**Comment by arbitrary-dev** [comment]
In what conditions does statusline turns out to be a status-multi-line? My problem is that having an identical fonts for tabs and status I get different heights of these panels, here's the pic:

![clientshot_2015-03-22](https://cloud.githubusercontent.com/assets/6984946/6768462/2ddf8212-d08e-11e4-864a-f6676d8395b3.png)

**Comment by The-Compiler** [comment]
Right now it's probably only for prompts like SSL-errors, or javascript issues (and it's also a bit broken). But still I'd like to keep the possibility open to display multiline text for other things too. Maybe it could always be a multiple of a height setting, or ignore the height-setting when it's multiline though.

And you're right, the statusbar is a bit higher here as well. I can't really say why, widget sizing is a rather complex topic...

**Comment by arbitrary-dev** [comment]
My proposal is that statusbar must be always a line, and all notifications (multiline or not) go into an additional widget above the statusline. This will provide a consistency in design,

As for sizing, I assume that problem is in padding being applied to statusbar but not to tabs.

**Comment by marcosrdac** [comment]
> In what conditions does statusline turns out to be a status-multi-line? My problem is that having an identical fonts for tabs and status I get different heights of these panels, here's the pic:
> 
> ![clientshot_2015-03-22](https://cloud.githubusercontent.com/assets/6984946/6768462/2ddf8212-d08e-11e4-864a-f6676d8395b3.png)

I'm sorry... But which font is that? :o

**Comment by jgkamat** [comment]
Also, padding can be configured with tabs.padding and statusbar.padding.

**Comment by arbitrary-dev** [comment]
>But which font is that? :o

[uushi](https://github.com/phallus/fonts)
