### ISSUE TITLE
TinyTiny RSS 

### ISSUE THREAD

**Issue by bacardi55** [The-Compiler/qutebrowser#574]
QuteBrowser doesn't displayb ttrss over https. (from @The-Compiler, it works over http, I didn't check).
Same URL/app works on other browser (firefox, chromium, dwb, uzbl, …).

This is the JS errors I got. Might be related.
![qutebrowser-ttrss-jserror](https://cloud.githubusercontent.com/assets/311143/6799490/9e7a572a-d216-11e4-86d3-85a4ad1f6a30.png)

I'll try to investigate later this week.

**Comment by The-Compiler** [comment]
Full javascript error message:

```
Exception: TypeError: undefined is not a function (evaluating 'dojo.require("fox.FeedTree")')
Function: init()

Additional exception caught while trying to show the error dialog.

Exception: TypeError: undefined is not an object (evaluating 'T_messages[msg]')
Function: exception_error()

The error will be reported to the configured log destination.
```

**Comment by The-Compiler** [comment]
Still broken with Qt 5.5 beta.

**Comment by The-Compiler** [comment]
Closing this as it'll probably be fixed by QtWebEngine and it's unlikely there's anything I can do to make it work with QtWebKit.
