### ISSUE TITLE
Change style of link cursor in spatial navigation?

### ISSUE THREAD

**Issue by mgraham** [The-Compiler/qutebrowser#578]
With spatial navigation, there is a cursor that goes from link to link.  Is there any way of styling it so it is more obvious?

**Comment by The-Compiler** [comment]
I can't think of a good way to do that I'm afraid. Spatial navigation is fully handled by QtWebKit (the only thing I'm doing is basically `QWebSettings.globalSettings().setAttribute(QWebSettings.SpatialNavigationEnabled, True)`), and it doesn't expose any API to customize it.

**Comment by mgraham** [comment]
Ok, thanks!
