### ISSUE TITLE
Hints mode for forms?

### ISSUE THREAD

**Issue by mgraham** [The-Compiler/qutebrowser#580]
Is there any way to have a hints mode just for forms, like Vimium's 'gi'?

**Comment by The-Compiler** [comment]
There are currently various extended hint modes (see [the cheatsheet](http://qutebrowser.org/img/cheatsheet-big.png) and `:help :hint`) - but a form hinting mode still needs to be added, see #222 for that.

Also I think `gi` focuses the first input (as opposed to showing hint labels) - see #219 for that.
