### ISSUE TITLE
Handling of ampersands in window title.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#599]
In #301 / 1af7112ea4e35f0b59f75381e8e04dd656b3dafb we fixed handling of `&` in tab titles.

Now in the *window* title, http://qutebrowser.org/bug-tests/issue-301.html displays `foo&&bar`.

/cc @iggy

**Comment by The-Compiler** [comment]
I pushed a fix to the `issue-599` branch. @iggy, I'd be glad if you can visit the page and confirm it says `foo&bar` in both tab and window title on that branch :)

**Comment by iggy** [comment]
It does. As I mentioned in IRC, I've upgraded to a newer distro and qt version. I think I was on Ubuntu 14.10 before.
