### ISSUE TITLE
maximum-pages-in-cache seems to be ignored

### ISSUE THREAD

**Issue by ff2000** [The-Compiler/qutebrowser#602]
First off I think the comment in qutebrowser.conf could be more specific: this is NOT a setting-per-webview/tab (what I thought in the first place because history is pre page) but a global one, at least the setter is a static function.

Nevertheless this does not work for me. I set it to 5 but still going back and forward reloads the page with all its issues: web forms are re-sent, have to wait quite some time before the page gets usable again, etc.

I think this is a webkit issue but wanted to make sure first. Probably I need to tune some other values to make this take effect. e.g. object-cache, where I have absolutely no idea which values to set there... Do they affect the same cache? Are there three different caches? Should Min - under pressure - be greater that Max - no pressure? How does this relate to total capacity?

I am using Qt-5.4.1 and PyQt5-5.4.1 on python-3.4.

**Comment by The-Compiler** [comment]
I'm going to be honest - for most of those questions, I have no idea either :laughing:

The descriptions are more or less copied verbatim from [the QWebSettings docs](http://doc.qt.io/qt-5/qwebsettings.html#setMaximumPagesInCache). I basically just exposed these QtWebKit settings because it was easy to do so.

I use the defaults, and sometimes get a page cache, sometimes not. See [this WebKit blog post](https://www.webkit.org/blog/427/webkit-page-cache-i-the-basics/) for some scenarios where it's disabled.

I'll make it clear this is a global cache in the docs and then close this, because it seems to me like it's working like intended - and if not, that'd probably be a QtWebKit bug.

**Comment by ff2000** [comment]
Florian Bruhin wrote:
> I'm going to be honest - for most of those questions, I have no idea either :laughing:
> 
> The descriptions are more or less copied verbatim from [the QWebSettings docs](http://doc.qt.io/qt-5/qwebsettings.html#setMaximumPagesInCache). I basically just exposed these QtWebKit settings because it was easy to do so.
Yeah, I noticed that :)

> 
> I use the defaults, and sometimes get a page cache, sometimes not. See [this WebKit blog post](https://www.webkit.org/blog/427/webkit-page-cache-i-the-basics/) for some scenarios where it's disabled.
Yes, I read the link. https and iframes and onaly partially loaded pages were mentioned as potentially problematic. But it even didn't cache it for http without iframes. The only site where it seems to use the cache is github. That's why I had the hope (and still have) that tuning those capacity values might help here. Will dive into the sources and hope I can get some more insight...

> I'll make it clear this is a global cache in the docs and then close this, because it seems to me like it's working like intended - and if not, that'd probably be a QtWebKit bug.
Thx, should help other people to get the setting right :)

And I will open a QTBUG if diving the sources doesn't help...

**Comment by ff2000** [comment]
Concerning caches:
* There are asserts so that cacheMinDeadCapacity <= cacheMaxDead <= totalCapacity.
* defaults: minDead=0, maxDead=total=8MB - no idea how ideal that is
* Setting each to 350 MB did not help to make pagesInCache work as expected.
* What makes QtWebKit properly store pages in cache is disabling JavaScript :(
* QtWebEngine has similar issues, here disabling JavaScript doesn't help. But disabling Plugins does...

If you think this is the correct way to do it jump in and shout "YES!" - otherwise I will go and report those two issues upstream ;)

**Comment by The-Compiler** [comment]
> There are asserts so that cacheMinDeadCapacity <= cacheMaxDead <= totalCapacity.

I probably should add that to the config validation as well then.

> What makes QtWebKit properly store pages in cache is disabling JavaScript :(

Maybe an unload event handler? From the linked page:

> Since the unload event’s purpose is to allow “important work when a page is closed,” all major browsers refuse to put such pages in their Page Cache, causing a direct negative impact on the user experience.

> QtWebEngine has similar issues, here disabling JavaScript doesn't help. But disabling Plugins does...

From the same page too:

> For example, plug-ins contain native code that can do just about anything it wants so WebKit can’t “hit the pause button” on them.

So I'm going to say everything is working as expected... can you see those pages being cached in Chromium or Firefox?

**Comment by ff2000** [comment]
Florian Bruhin wrote:
> > Since the unload event’s purpose is to allow “important work when a page is closed,” all major browsers refuse to put such pages in their Page Cache, causing a direct negative impact on the user experience.
 
> > For example, plug-ins contain native code that can do just about anything it wants so WebKit can’t “hit the pause button” on them.
 
> So I'm going to say everything is working as expected... can you see those pages being cached in Chromium or Firefox?

Of course Firefox and google-chrome behave as expected, otherwise I would not have reported this issue.
Major news sites are really a pain for me to browser because they usually are full of large images and have a layout that needs its time to render. My internet connection is not the fastest, and that's something modern web admins don't optimise their sites for, so huge images are somthing I struggle with quite often. Having to wait 10-20 seconds after each history-back isn't nice...
As I think you speak german - try spiegel.de and focus.de as examples.

And I noticed now that even after turning off JavaScript (and even plugins and images) not everything is working as in the two "major browsers" I tested:
go to forums.gentoo.org, enter a search term in the box in the top right corner, click on a search result, quickly go back - MEH ;)
(the form gets resent, but the forum admins seem to dislike too many searches so they entered a time limit within that you can't send new searches...)
You may want to inspect the sources - I couldn't see anything special... no "unload" handler, no single <script>, ...
QtWebEngine shows the same behaviour here.
I think I also have to install webkit-gtk and epiphany to see how those behave.

**Comment by ff2000** [comment]
Reported upstream:
https://bugreports.qt.io/browse/QTBUG-45399

As I mentioned there webkit-gtk (tested only v2.8.0) just works fine. So this is a Qt-Bug.

**Comment by The-Compiler** [comment]
Thanks!
