### ISSUE TITLE
Expose new/undocumented QWebSettings attributes

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#612]
It seems there are some new attributes for QWebSettings which I didn't notice before!

## Documented attributes

- [x] `QWebSettings::CSSGridLayoutEnabled` (*not implemented as it seems broken*)

> This setting enables support for the CSS 3 Grid Layout module. This CSS module is currently only a draft and support for it is disabled by default.

- [x] `QWebSettings::ScrollAnimatorEnabled` (*depends on #669*)

> This setting enables animated scrolling. It is disabled by default.

- [x] `QWebSettings::CaretBrowsingEnabled` (*see visual branch*)

> This setting enables caret browsing. It is disabled by default.

- [x] `QWebSettings::NotificationsEnabled` (*not needed because we can ignore them already*)

> Specifies whether support for the HTML 5 web notifications is enabled or not. This is enabled by default.

- [x] `QWebSettings::Accelerated2dCanvasEnabled` (*not needed because it needs an OpenGL viewport*)

> Specifies whether the HTML5 2D canvas should be a OpenGL framebuffer. This makes many painting operations faster, but slows down pixel access. This is disabled by default.

*Not available with Qt 5.2!*

## Undocumented attributes

* [x] `WebGLEnabled` (`<carewolf> webgl should work`)
* [x] `CSSRegionsEnabled` (`<carewolf> well, okay. It appears to be a bit wrong. It works globally - if it works`)
* [x] `HyperlinkAuditingEnabled` - see the [WhatWG spec](https://html.spec.whatwg.org/multipage/semantics.html#hyperlink-auditing)
* [x] `WebAudioEnabled` (`<carewolf> webaudio is not enabled by default, and won't work anyway`) *Not available with Qt 5.2!*

Also see #597

## Stuff to do

- [x] Expose all settings which make sense to the user.
- [x] Make sure everything is backwards-compatible with Qt 5.2
- [x] Maybe expose caret browsing as its own mode (see #609)
- [x] Contribute to Qt to add documentation
   - `WebGLEnabled`
   - `HyperlinkAuditingEnabled`
   - `CSSRegionsEnabled`

**Comment by The-Compiler** [comment]
https://codereview.qt-project.org/112442

**Comment by Jumblemuddle** [comment]
@The-Compiler Is there a way to enable QWebSettings::CSSGridLayoutEnabled manually?

**Comment by The-Compiler** [comment]
@Jumblemuddle Sorry for the late answer! I don't think you can, but it's probably time to take a fresh look at this with QtWebKit 5.212. I opened #3687 for that.

**Comment by Jumblemuddle** [comment]
@The-Compiler Actually, it appears to be work according to http://css3test.com/.
I've recently run updates, though I'm not sure what changed exactly.
```
» qutebrowser --version                                                                                           ~
qutebrowser v1.1.1
Git commit:
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.9.2
```

**Comment by The-Compiler** [comment]
You're running QtWebEngine, while this issue is about QtWebKit. With QtWebEngine, CSS grid is supported starting with Qt 5.10 (Chromium 61) but not Qt 5.9 (Chromium 56).

**Comment by Jumblemuddle** [comment]
That makes sense. Thanks for the clarification!
