### ISSUE TITLE
Feature Request - more bindings in hint mode

### ISSUE THREAD

**Issue by mgraham** [The-Compiler/qutebrowser#613]
Often I've got the hints displayed, and I'll think: "oh, I want to open that in a new tab.  Or a background tab".  

So I have to press `<esc>` and then re-enter the different hints mode.

I'd like to be able to bind special keys to do the following while in hint mode:
* follow link in new tab
* follow link in background tab
* toggle rapid hints mode on/off

**Comment by The-Compiler** [comment]
I was going to say you can already do that, and when testing that I found #614 and #615 :worried:

So, once #615 is fixed, you'll be able to do something like this in your `keys.conf`:

```
[hint]
...
leave-mode;;hint -r links tab-bg
```

**Comment by The-Compiler** [comment]
#615 is now fixed, so the binding above should work. Any opinion on default bindings, @mgraham?

**Comment by mgraham** [comment]
Awesome - works well!

One small issue is that you can't bind ordinary keys like numbers and punctuation in hintmode, even though hints can't contain numbers or punctuation.

I added a few small related feature requests: #635 and #636

**Comment by r8b7xy** [comment]
I think that those bindings should be added by default
```
leave-mode;;hint --rapid links tab-bg
    <Ctrl-r>

leave-mode;;hint links
    <Ctrl-f>

leave-mode;;hint all tab-bg
    <Ctrl-b>

**Comment by The-Compiler** [comment]
That makes sense - I'll reopen the issue to add those.

**Comment by The-Compiler** [comment]
I've now added those bindings - also, `:hint` now automatically leaves the mode when hinting while in hint mode, so the `leave-mode;;` part is unneccesary.
