### ISSUE TITLE
No indication or message when using spawn.

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#616]
Spawning a process such as mpv doesn't indicate anywhere in the UI that it has actually occurred.

Vimperator (and Pentadactyl with effort) for example will print `Executing: command --options arguments` in the status bar, subsequently stored in `:messages`.

This is useful to know what exactly happened especially since some hints can overlap in non-intuitive ways.

**Comment by The-Compiler** [comment]
I agree - similiar to `:session-load`, it should probably print what it's done, and have a `-q`/`--quiet` option to suppress the message.
