### ISSUE TITLE
Spawned processes close with the browser.

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#617]
The processes spawned are not disowned and terminate when the parent exits, the browser in this case.

This makes it difficult to spawn a video that loops from local cache and close or restart the browser if needed.

**Comment by The-Compiler** [comment]
I can't reproduce this - when I do `:hint links spawn firefox {hint-url}` or `:spawn gedit`, in both cases the processes stay open when I close qutebrowser.

**Comment by Earnestly** [comment]
`firefox` will detach itself, as will `gedit`.  Try with something simpler like `mpv` or `llpp`

**Comment by The-Compiler** [comment]
I'm afraid I can't reproduce it with mpv either - can you confirm something like `:spawn mpv http://qutebrowser.org/31c3.webm;;later 5000 quit` quits mpv after 5 seconds?

Are you using `qutebrowser-git` or v0.1.4 (i.e. `qutebrowser`)?

**Comment by Earnestly** [comment]
I'm using qutebrowser directly from git, `g1061932`.

Hm, it seems to not be doing it now either.  I must have been doing something odd which I can't fathom anymore.

Closing this as a case of personal derp :-P
