### ISSUE TITLE
Many commands undocumented in the manual.

### ISSUE THREAD

**Issue by Earnestly** [The-Compiler/qutebrowser#618]
`qutebrowser(1)` doesn't discuss any of the internal commands such as `spawn` or `open` and the options they take.

Various bindings within `keys.conf` use them but their use can only be guessed, such as `open -t` being assumed as opening a new tab.

**Comment by The-Compiler** [comment]
I don't want to clutter the manpage with all the interal commands/settings, and instead have a built-in help, similiar to what e.g. vim does - see `:help`.

The quickstart opened on the first run mentions this, and every command can also be started with `--help` - where would you expect such an information? Maybe I should add it to the `RESOURCES` section in the manpage?

**Comment by Earnestly** [comment]
Where is qutebrowser loading the help pages from?  Is it local?

**Comment by The-Compiler** [comment]
Yeah - it'll install them as python "package data", i.e. it'll end up in `/usr/lib/python3.4/site-packages/qutebrowser/html/doc/`, and `qute://help` will read from there.

**Comment by Earnestly** [comment]
Ah, so it is.  I missed that when looking.

Then that's fine but like `vim.1` it might be worth making a note of `:help` and its usage.  Vim describes it in the `DESCRIPTION` almost straight away.
