### ISSUE TITLE
opening a new tab with F-hint does not honor background-tabs setting

### ISSUE THREAD

**Issue by dmeulen** [The-Compiler/qutebrowser#621]
I might be missing something, but opening links with F-key does not open links in the background with setting background-tabs = true . Opening links with the middle mouse button does open tabs in the background.

**Comment by The-Compiler** [comment]
<kbd>F</kbd> basically is already a keybinding which explicitely says "I want to open links via hint in a new foreground tab". You can use <kbd>;b</kbd> to open hints background-tabs.

As you're not the first one with this issue, I wonder if `:hint` should have a `tab-auto` mode which honors `background-tabs`, and <kbd>F</kbd> should be bound to that instead. What's your opinion on this?

**Comment by dmeulen** [comment]
Well, like most of us users have a Vimperator/Pentadactyl kind of background where pressing <kbd>F</kbd> does open in a background tab when Firefox is told to do so. It also saves you an extra keystroke ;-).

Having a setting in the config for background-tabs in my opinion should do just that, whenever you open a new tab open it in the background. So yes I think `:hint` should have a `tab-auto` mode and have <kbd>F</kbd> bound to that.

**Comment by rcorre** [comment]
I just ran into this and was suprised that `F` did not respect the `background-tabs` setting.
Actually, I was pretty sure it _did_ until recently, though I could be mis-remembering.

> As you're not the first one with this issue, I wonder if :hint should have a tab-auto mode which honors background-tabs, and F should be bound to that instead. What's your opinion on this?

I think this makes sense -- the easiest way to open a tab (`F`) should respect your 'preferred' behavior, and more complex commands (`;b`) are used to deviate from that behavior.

I almost never want a forground tab. If I want to read something **now**, I open it in the current tab. If I want to read it **later**, I use a background tab.

**Comment by The-Compiler** [comment]
<kbd>F</kbd>/`:hint tab` now respect `background-tabs`, and `:hint tab-fg`/<kbd>;f</kbd> can be used to force a foreground tab. I don't think it ever respected the setting before - though a bug was fixed where links sometimes opened in the same tab instead of a new one.
