### ISSUE TITLE
Font on github is smaller

### ISSUE THREAD

**Issue by natedalliard** [The-Compiler/qutebrowser#625]
Hey guys,

the font on github.com is smaller when I use qutebrowser than it is on chromium for example. I added a screenshot. In the first place I tought, hat I haven't installed all necessary fonts, but than github should be display smaller fonts even on chromium. 

I use Arch Linux and I've just installed ttf-dejavu and ttf-inconsolata. Maybe as I already said, I have to install some more fonts.

![2015-04-09-174059_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/7070526/da8e914c-dedf-11e4-8cfc-62887df063f8.png)

Ah and the zoom is in both browser at 100%, so that is not the problem.

**Comment by The-Compiler** [comment]
See #252 - it seems installing the microsoft fonts (e.g. `ttf-ms-fonts`) helps, as this is an issue with the "clean" font.

I'm not sure if this actually is a bug in Qt or not, and Chromium just happens to have a different font fallback mechanism.

**Comment by natedalliard** [comment]
Thanks - that solved the problem!

**Comment by shaggytwodope** [comment]
@The-Compiler Maybe it could be added to optdepends in the pkgbuild?

**Comment by The-Compiler** [comment]
@shaggytwodope meh... Then you'd have to add a lot of fonts there if you want everything to work properly ;)

**Comment by shaggytwodope** [comment]
@The-Compiler Indeed fair point, maybe as a post install message? In any case I'm prolly just crazy lol.
