### ISSUE TITLE
Show keys to press in SSL error messages

### ISSUE THREAD

**Issue by Linuus** [The-Compiler/qutebrowser#630]
Hi!

I just installed your qutebrowser on OSX using Homebrew. On many sites I visit I get this SSL error
![skarmavbild 2015-04-11 kl 23 33 04](https://cloud.githubusercontent.com/assets/379823/7103429/4e2026e8-e0a7-11e4-8a34-53e34fce208b.png)

Working sites: DuckDuckGo, Github
Not working: Wikipedia, Google, Youtube and more.

Do you know how to fix this issue?

**Comment by Linuus** [comment]
Ok, when typing `:open https://www.google.com` it fails with the message above. If I just run `:open google.com` it works. I guess it's because the cert and domain is not quite matching up.

But can it be avoided? I mean, in Chrome for instance, it redirects me to a proper, secure, url.

**Comment by The-Compiler** [comment]
There are various kinds of weird SSL errors and I don't really know what I can do about them yet...

Can you reproduce this every time? For me on Debian using `:open https://www.google.com` works just fine. Could you share exact URLs to where you have those issues on Wikipedia/Youtube as well?

**Comment by Linuus** [comment]
Just an update.
If I go to ":open google.com" it works but when I click on the link to log in, I get a link looking like this `https://accounts.google.com/ServiceLogin?hl=sv&continue=http://www.google.se/` and it fails with the SSL error again.

**Comment by bchretien** [comment]
Note: this message expects "y" to continue, else it stops and displays the handshake issue. However the default appears to be "n", which is chosen if hitting enter for example. Displaying:

```
SSL errors - continue? [yN]
```

or something similar to highlight the default option may help users like me who for some reason hit enter without really thinking...

**Comment by The-Compiler** [comment]
Now that there's `keyconfig.get_reverse_bindings_for` this should be straightforward.
