### ISSUE TITLE
New Search Performed; Old Search Remains Highlighted

### ISSUE THREAD

**Issue by NoSuck** [The-Compiler/qutebrowser#638]
![DEFINITELY Not Image of Yaktocat](https://nosuckdotorg.files.wordpress.com/2015/04/qutebrowser-double-highlights.png)

Steps to reproduce problem:

1. Search term A in tab 1.
2. Search term B in tab 2.
3. Search term B in tab 1.

... Presto!

**Comment by The-Compiler** [comment]
Confirmed.

**Comment by The-Compiler** [comment]
This happens because there's a `SearchRunner` per mainwindow currently - it probably should be per-page instead.
