### ISSUE TITLE
SSL Handshake Error

### ISSUE THREAD

**Issue by lluixhi** [The-Compiler/qutebrowser#641]
Hi, when I try and login to my UC Berkeley account, I get an error stating:

"SSL Handshake Failed"

The website is: https://auth.berkeley.edu/cas/login

**Comment by The-Compiler** [comment]
Works fine here - my guess is the certificate isn't in your distributions certificate store. What distribution are you on?

Can you post the output of `openssl s_client -connect auth.berkeley.edu:443` please?

**Comment by lluixhi** [comment]
That's odd. I was able to connect in firefox and chromium, but I'm running into an issue here.
I'm running Gentoo.

CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
5541836263789471414:error:1408D06E:SSL routines:SSL3_GET_KEY_EXCHANGE:bad dh p length:/var/tmp/portage/dev-libs/libressl-2.1.6/work/libressl-2.1.6/ssl/s3_clnt.c:1278:
---
Certificate chain
 0 s:/C=US/postalCode=947201500/ST=California/L=Berkeley/street=200 California Hall #1500/O=University of California at Berkeley/OU=IST-CalNetIdM/CN=auth.berkeley.edu
   i:/C=US/ST=MI/L=Ann Arbor/O=Internet2/OU=InCommon/CN=InCommon RSA Server CA
 1 s:/C=US/ST=MI/L=Ann Arbor/O=Internet2/OU=InCommon/CN=InCommon RSA Server CA
   i:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
 2 s:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGfDCCBWSgAwIBAgIRAJ1pIi9FLVhhhnLTSndFj9kwDQYJKoZIhvcNAQELBQAw
djELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYDVQQHEwlBbm4gQXJib3Ix
EjAQBgNVBAoTCUludGVybmV0MjERMA8GA1UECxMISW5Db21tb24xHzAdBgNVBAMT
FkluQ29tbW9uIFJTQSBTZXJ2ZXIgQ0EwHhcNMTUwMzMwMDAwMDAwWhcNMTgwMzI5
MjM1OTU5WjCB0DELMAkGA1UEBhMCVVMxEjAQBgNVBBETCTk0NzIwMTUwMDETMBEG
A1UECBMKQ2FsaWZvcm5pYTERMA8GA1UEBxMIQmVya2VsZXkxIjAgBgNVBAkUGTIw
MCBDYWxpZm9ybmlhIEhhbGwgIzE1MDAxLTArBgNVBAoTJFVuaXZlcnNpdHkgb2Yg
Q2FsaWZvcm5pYSBhdCBCZXJrZWxleTEWMBQGA1UECxMNSVNULUNhbE5ldElkTTEa
MBgGA1UEAxMRYXV0aC5iZXJrZWxleS5lZHUwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQC5B3fCR/JibXDMvhj+PR1Vffexk2aehLa8QwJwopD+iKI/q52g
wr5tkFUWpTMhIGrRnKpZkBfrIgBWWajrnbMnvFQhhE97eR00BTXMjdFAAKtVHcgi
DcSSXUqM3fvJ2CZDN3qorBr2MphQxXnkBnocTZbQxRFwqNyS/jbiGAfxAFRfJ5WX
w1JzQUb+Kd5kQwqX5xZBW6EUUzXWBA3fSm/o0wpGaKC2DlHpr/rEx5sfhHW119mU
XgFNKa4PCgy0pA2nvlB9RiQX4KjVw/HwfPZJpVNv17RSlc9qle4hg2Om5gK4KKGW
MAytBlfEH4A/po9AFExj8+4Mn0PPNrtAy+BjAgMBAAGjggKoMIICpDAfBgNVHSME
GDAWgBQeBaN3j2yW4luHS6a0hqxxAAznODAdBgNVHQ4EFgQUvSZg+SkvisMMoSJt
HcuDaSxO/n4wDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYw
FAYIKwYBBQUHAwEGCCsGAQUFBwMCMGcGA1UdIARgMF4wUgYMKwYBBAGuIwEEAwEB
MEIwQAYIKwYBBQUHAgEWNGh0dHBzOi8vd3d3LmluY29tbW9uLm9yZy9jZXJ0L3Jl
cG9zaXRvcnkvY3BzX3NzbC5wZGYwCAYGZ4EMAQICMEQGA1UdHwQ9MDswOaA3oDWG
M2h0dHA6Ly9jcmwuaW5jb21tb24tcnNhLm9yZy9JbkNvbW1vblJTQVNlcnZlckNB
LmNybDB1BggrBgEFBQcBAQRpMGcwPgYIKwYBBQUHMAKGMmh0dHA6Ly9jcnQudXNl
cnRydXN0LmNvbS9JbkNvbW1vblJTQVNlcnZlckNBXzIuY3J0MCUGCCsGAQUFBzAB
hhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMIH+BgNVHREEgfYwgfOCEWF1dGgu
YmVya2VsZXkuZWR1giBuY2FzLW9mZnNpdGUuY2FsbmV0LmJlcmtlbGV5LmVkdYIb
bmNhcy1wMS5jYWxuZXQuYmVya2VsZXkuZWR1ghtuY2FzLXAyLmNhbG5ldC5iZXJr
ZWxleS5lZHWCG25jYXMtcDMuY2FsbmV0LmJlcmtlbGV5LmVkdYIbbmNhcy1wNC5j
YWxuZXQuYmVya2VsZXkuZWR1ghtuY2FzLXA1LmNhbG5ldC5iZXJrZWxleS5lZHWC
EW5jYXMuYmVya2VsZXkuZWR1ghhuY2FzLmNhbG5ldC5iZXJrZWxleS5lZHUwDQYJ
KoZIhvcNAQELBQADggEBABPlpau6vl1lrDkHQrWgzx0suiv7wBUMtQuRymujMj13
SgLLnR+FNP+rn6Qv9re734a3mKJvje1JJsFC4Am/EfipDFMIspZc02l3Op/ZzbSc
2vaW8AcUhgxWtIQx5YtZmdhih9c45Bj93RT+HFwqyH8CzTEFv/NbqAxIH4p+yhrK
4y7UNbaOZVlk7aU3Gf59j+LW9qBT0f5UZHRVOKpaJvFdbCtklSLVba+uQAAZOZKN
cX1bsraKqL4MFs7G/mL8vGuXZdgjNEnsPSZSt1gCpSxx/Ge23XWZVcyh9NGoTcRv
5POd9AjGf6iHc3SlReWgVs4bOEnAsOy4ij8KswQwkLU=
-----END CERTIFICATE-----
subject=/C=US/postalCode=947201500/ST=California/L=Berkeley/street=200 California Hall #1500/O=University of California at Berkeley/OU=IST-CalNetIdM/CN=auth.berkeley.edu
issuer=/C=US/ST=MI/L=Ann Arbor/O=Internet2/OU=InCommon/CN=InCommon RSA Server CA
---
No client certificate CA names sent
---
SSL handshake has read 6349 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 55313CD5DC3FA4CF2579E2E5CC86B126DC8C0BC90D2FB5E163CED4AE054C6631
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1429290190
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
---

**Comment by The-Compiler** [comment]
Yeah, Firefox/Chromium ship their own sets of certificates which I'd rather avoid.

I want to look into using their certificate store in qutebrowser if one of them is installed though... I thought there was an issue for that, but it seems there wasn't - I opened #642 for that, so I'm closing this now.
