### ISSUE TITLE
Use the SSL certificate store of Chromium/Firefox

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#642]
There should be an option to use the certificate store of Chromium or Firefox if available, if that's possible.

That way we could avoid SSL errors for pages with no certificates in the system store.

Example pages:
- https://gametwist.de
- https://drakulastream.eu
- https://eurosport.yahoo.de

**Comment by The-Compiler** [comment]
It seems the [requests library](http://docs.python-requests.org/en/latest/) either uses [certifi](https://pypi.python.org/pypi/certifi/) or a [vendored bundle](https://github.com/kennethreitz/requests/blob/master/requests/cacert.pem).

Both use the [Mozilla CA store](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/) via [curl](http://curl.haxx.se/docs/caextract.html).

**Comment by jagajaga** [comment]
Another example page https://www.tinkoffinsurance.ru/

**Comment by The-Compiler** [comment]
QtWebEngine essentially does that, and I won't implement this for QtWebKit.
