### ISSUE TITLE
Open multiple URLs with :open

### ISSUE THREAD

**Issue by jpambrun** [The-Compiler/qutebrowser#645]
I would find it very useful if I could open multiple ULRs in separate tabs using :open. I could then set an alias for news sites. 
```
news = open -t site1.com, site2.com, etc..
```
Great software btw. thx.

**Comment by The-Compiler** [comment]
You can already separate commands using `;;`, so you can add an alias to `open -t site1.com;;open -t site2.com` - that's a bit more verbose, but I'd like to avoid adding another special separator.

You could also abuse sessions - store all your news sites in a session, set `general -> session-default-name` to `default` so you don't accidentally override it, and then use `:session-load news`.

**Comment by jpambrun** [comment]
Suggestion one dosen't work. It just searches for 'site1.com;;open -t site2.com'.

**Comment by The-Compiler** [comment]
Whoops, you're right - sorry!

The problem there is you'd need to find a separator which is guaranteed to never be used in URLs, and also not used commonly in search terms. And that might be hard...

I think it's best to wait for the new config format (#499), then it should be easy to make it possible to add an alias to a list of commands.

**Comment by The-Compiler** [comment]
I just discovered `;;` with `:open` actually *does* work (and nobody complained because an URL/search term with `;;` yet), but not with aliases, which *is* a bug... sorry!

I opened #956 for that.

**Comment by marvinwaters** [comment]
by linksopen.com, you can open multiple links at once, just with a single click
