### ISSUE TITLE
AssertionError when saving session while closing a lot of windows

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#650]
Reported by @teto on cc738fa with Qt/PyQt 5.2.1:

> I just closed my parent "container" in i3 (i3wm.org) while watching a youtube video. This must have closed all my qutebrowser *tabs* (ie, I configure qutebrowser to use windows instead of tabs). Without looking at the backtrace I guess the crash could be due to a race condition

Exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.1.4-py3.4.egg/qutebrowser/app.py", line 859, in on_last_window_closed
    self.shutdown(last_window=True)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.1.4-py3.4.egg/qutebrowser/app.py", line 883, in shutdown
    load_next_time=True)
  File "/usr/local/lib/python3.4/dist-packages/qutebrowser-0.1.4-py3.4.egg/qutebrowser/misc/sessions.py", line 201, in save
    assert data is not None
AssertionError
```

config:

```ini
[general]
save-session = true
[tabs]
hide-always = true
tabs-are-windows = true
```

log:

```
18:44:52 DEBUG    destroy    mainwindow:closeEvent:383 Closing window 23
18:44:52 DEBUG    destroy    webview:shutdown:309 Shutting down <qutebrowser.browser.webview.WebView url='…' tab_id=23>.
18:44:52 DEBUG    destroy    mainwindow:closeEvent:383 Closing window 0
18:44:52 DEBUG    destroy    webview:shutdown:309 Shutting down <qutebrowser.browser.webview.WebView url='…' tab_id=0>.
18:44:52 DEBUG    destroy    app:shutdown:875 Shutting down with status 0, session None...
18:44:52 DEBUG    sessions   sessions:save:198 Saving session default to /home/teto/.local/share/qutebrowser/sessions/default.yml...
18:44:52 ERROR    misc       app:_exception_hook:605 Uncaught exception
```

**Comment by The-Compiler** [comment]
I now tried reproducing this by doing `:repeat 20 open -t cmpl.cc` with those settings and then using `:quit` or closing all windows via my windowmanager with

```bash
sleep 1; while (($(hc attr tags.focus.curframe_wcount) != 0)); do hc close; done
```

**Comment by The-Compiler** [comment]
The assert happens when `SessionManager._last_window_session` is `None`, i.e. `save_last_window_session()` was never called.

That gets called in `MainWindow.closeEvent()` and then later `QApplication.lastWindowClosed` gets emitted which leads to that assertion.

So either `MainWindow.closeEvent()` got not called before `lastWindowClosed` was emitted (which is unlikely, because a closeEvent could also ignore the closing of a window), or the `if len(objreg.window_registry) == 1:` condition was false when closing the *last* window - maybe windows get removed from the window registry via a singleshot `QTimer`?

**Comment by The-Compiler** [comment]
@teto - if you can reliably reproduce this issue, can you please confirm it's fixed?

**Comment by teto** [comment]
I haven't looked for a way to reproduce this but if the bug reappears I will reopen it.
