### ISSUE TITLE
Support for alternate keyboards

### ISSUE THREAD

**Issue by fosskers** [The-Compiler/qutebrowser#652]
Hi there, I've recently come to switch to the [Colemak](http://colemak.com/) keyboard layout. Since the keys are all mapped to different places, the navigation keys and link suggestions are no longer ergonomic. Can this be changed somewhere/does qutebrowser support keyboard layouts other than QWERTY? 

Thanks.

**Comment by The-Compiler** [comment]
Cool! I'm learning Colemak as well at the moment (on an [ErgoDox](http://deskthority.net/wiki/ErgoDox)) :smile:

You can remap all keys as you like using the `:bind` command or by editing `~/.config/qutebrowser/keys.conf`. For the hints (what I think you mean with link suggestions), you can do something like `:set hints chars arstdhneio`.

I don't think there's a ready `keys.conf` for colemak by anyone, so that'll be some work - but I'd be glad about it as well when I finally switch over, and I think it'd be something good to add to the [misc folder](https://github.com/The-Compiler/qutebrowser).

**Comment by fosskers** [comment]
Excellent, `keys.conf` and `:set hints` were exactly what I was looking for.

**Comment by kalbasit** [comment]
@fosskers did you ever create the bindings? can you share them if so?

**Comment by fosskers** [comment]
I didn't - I use Firefox with *Vim Vixen* now.

**Comment by mschilli87** [comment]
@The-Compiler: Did you ever switch away from QWERTY in the end? :wink:

**Comment by The-Compiler** [comment]
Well, it hasn't ended yet, but I haven't so far :laughing:

**Comment by tmplt** [comment]
@The-Compiler I don't have a `~/.config/qutebrowser/keys.conf`. Is there a way to generate it?

**Comment by toofar** [comment]
@tmplt that isn't a thing anymore. Bindings are managed via the bindings.commands setting: https://qutebrowser.org/doc/help/settings.html#bindings.commands
You can poke at that settings from config.py, there is an example here: https://gitlab.com/jgkamat/qutemacs/-/blob/master/qutemacs.py

**Comment by The-Compiler** [comment]
@tmplt Also see the top of the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc) for a bit more context on what `keys.conf` was and how it was replaced in v1.0.0.

**Comment by shonfeder** [comment]
Hi! I've just set up a minimal set of binding tweaks for my colemak-dh layout,
and thought I'd share here in case it's useful. 

Added to my `config.py`:

```python
config.bind('m', 'scroll left', mode='normal')
config.bind('n', 'scroll down', mode='normal')
config.bind('e', 'scroll up', mode='normal')
config.bind('i', 'scroll right', mode='normal')


config.bind('M', 'back', mode='normal')
config.bind('I', 'forward', mode='normal')
config.bind('E', 'tab-prev', mode='normal')
config.bind('N', 'tab-next', mode='normal')

config.bind('K', 'search-prev', mode='normal')
config.bind('k', 'search-next', mode='normal')
config.bind('l', 'undo', mode='normal')
config.bind('u', 'mode-enter insert', mode='normal')

# caret mode
config.bind('m', 'move-to-prev-char', mode='caret')
config.bind('n', 'move-to-next-line', mode='caret')
config.bind('e', 'move-to-prev-line', mode='caret')
config.bind('i', 'move-to-next-char', mode='caret')

config.bind('M', 'scroll left', mode='caret')
config.bind('N', 'scroll down', mode='caret')
config.bind('E', 'scroll up', mode='caret')
config.bind('I', 'scroll right', mode='caret')

config.bind('f', 'move-to-end-of-word', mode='caret')

c.hints.chars = 'artgmneio'
```

I expect some additional tweaks will be needed.

The basic remaping strategy is taken from  https://github.com/wbolster/emacs-evil-colemak-basics
