### ISSUE TITLE
Styling and options for desktop notifications

### ISSUE THREAD

**Issue by mgraham** [The-Compiler/qutebrowser#654]
Is there any way to make desktop notifications persistent?  Right now, a little bubble comes up and then it goes away after a few seconds.  This makes it very easy to miss notifications, if you happen to be looking away from your screen when they occur.

Also, is there any way to style notifications?  If I could make them blink or flash to grab my attention, that would be great.

**Comment by The-Compiler** [comment]
Unfortunately the notifications are entirely handled by Qt (otherwise they wouldn't look that ugly :wink:), the only part I have to handle in qutebrowser is [the permissions](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/webpage.py#L321-L366).

Makes it easier for me, but that means there's no way for me to influence their look&feel I'm afraid.

**Comment by mgraham** [comment]
That sucks.  And I guess there's no way to hook an external program into the notification thingy either?  I suppose I could try injecting some custom javascript into the page somehow...

**Comment by The-Compiler** [comment]
Now I feel bad for telling you something is impossible and then finding out the contrary for the second time already :smiles:

@Emdek from [otter browser](https://github.com/OtterBrowser/otter-browser) just chimed in and showed me the [QupZilla/qtwebkit-plugins](https://github.com/QupZilla/qtwebkit-plugins/) repo - I just tried it out: When building and installing that (which will build a QtWebKit platform plugin and install it to `/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so` or similiar), qutebrowser uses DBus to send notifications - on my system, that boils down to [dunst](https://github.com/knopwob/dunst) showing them, but that should be customizable like you want it to :smile:

**Comment by mgraham** [comment]
Heh - awesome! I will check that out!  Thank you!

**Comment by mgraham** [comment]
I built it ok, and it appears to have installed intself to /usr/lib/x86_64-linux-gnu/qt5/plugins/webkit/libqtwebkitplugins.so.

Now I have no idea how to wire it up.  Notifications still look the same as they did.  Any advice?

I seem to have gotten scudcloud to work with dunst, so maybe I'll try using that for a while.  Scudcloud is basically just an the slack site embedded in an app.  I'll lose all the qutebrowser niceties within slack of course, but there are some advantages to a stand-alone app anyway.

Thanks for the pointer to dunst!

**Comment by The-Compiler** [comment]
My first thought was you maybe built it for Qt4 rather than Qt5, but looking at the path that seems to be fine... I didn't have to do anything other than installing that file and it was automatically picked up.

Maybe @nowrep (who wrote the plugin) has time to help and has an idea why it doesn't work for you? :smile:

**Comment by nowrep** [comment]
@mgraham Try it now. If it doesn't help then you must be installing it to the wrong directory (maybe you are building qtwebkit-plugins with different Qt version than qutebrowser).

**Comment by mgraham** [comment]
@nowrep - thanks for looking into it!  Now I get a bunch of compile-time errors regarding a missing qwebkitplatformplugin.h, which I gather was removed in the last commit.  What project should that file come from?

**Comment by nowrep** [comment]
It's from QtWebKit

**Comment by The-Compiler** [comment]
If you're on Debian it seems you need to install `libqt5webkit5-dev` to get it.

**Comment by mgraham** [comment]
I had to fiddle with src/Makefile to get it to work, but that did the trick! Thank you both!

I added an issue ([#6](https://github.com/QupZilla/qtwebkit-plugins/issues/6)) for this in the [qtwebkit-plugins](https://github.com/QupZilla/qtwebkit-plugins/) project.

**Comment by The-Compiler** [comment]
I just looked into the Qt 5.5 [changelog](https://wiki.qt.io/New_Features_in_Qt_5.5) and it seems this behavior is now the default for all notifications:

> On supported desktops, the xcb plugin now uses the D-Bus based org.kde.StatusNotifier protocol for system tray icons, and org.freedesktop.Notifications for notifications.

**Comment by mgraham** [comment]
Nice!

**Comment by The-Compiler** [comment]
FWIW I now packaged `qtwebkit-plugins` in the Archlinux AUR: https://aur.archlinux.org/packages/qtwebkit-plugins-git/

**Comment by anhtuann** [comment]
I installed the aur package but I wasn't able to make it work. `dbus-monitor` doesn't show anything when I trigger a notification. Does it work with qutebrowser v1.0.3 ?

**Comment by pkillnine** [comment]
The WebEngine backend (the default one) currently doesn't support notifications, however support for them is being added: see #3010 and https://codereview.qt-project.org/#/c/205716/

**Comment by anhtuann** [comment]
Yes but in the meantime, I wanted to use qtwebkit which already implements desktop notifications. Problem is that it doesn't seem to work on new qtwebkit

**Comment by anhtuann** [comment]
Actually it works now with qtwebkit.
