### ISSUE TITLE
Allow desktop notifications per-site?

### ISSUE THREAD

**Issue by mgraham** [The-Compiler/qutebrowser#655]
We've just started using slack.com.  Every time I go to the site, I have to enable desktop notifications.  Is there any way to enable notifications for a single site without enabling them for all sites?

**Comment by The-Compiler** [comment]
Per-domain settings (see #27) are on the roadmap, and probably the next thing I'll do after the config reorganisation (#499) and many non user-visible changes/refactorings.

Then the desktop notification setting sure will be one which can be set per-domain.

For now the best thing you can do is to enable them globally, and hope no page annoys you with them (or lets turn them off on the page's side).

**Comment by mgraham** [comment]
Ok.  But - it looks like at this point the only options for :set content notifications are "ask" and "false" :)

**Comment by The-Compiler** [comment]
Oh! I remember not adding a `true` because some standard said it's probably a bad idea, especially for Geolocation.

Then again that makes sense for Notifications - and it's qutebrowser, so the user should be allowed to shoot in their feet :wink:.

I'll reopen this and take a look at it later.
