### ISSUE TITLE
can qutebrowser display kanjis?

### ISSUE THREAD

**Issue by shibumi** [The-Compiler/qutebrowser#661]
Hello,
I have some trouble with kanjis and qutebrowser? Can qutebrowser display them? Qutebrowser just display dots instead of the kanjis... how can I thix this?

**Comment by The-Compiler** [comment]
That should work just fine - where exactly are you having trouble and what distribution are you on? E.g. 漢字 displays fine for me.

**Comment by The-Compiler** [comment]
Any update, @shibumi?

**Comment by shibumi** [comment]
Sorry for my late answer. I have problems on Wikipedia.de for example this article:

http://de.wikipedia.org/wiki/Man%E2%80%99y%C5%8Dsh%C5%AB

when you scroll down you can see a table with: Kanbun | japanische lesung | ....
normally there are kanjis or hiragana in the left  2 tables but with qutebrowser there arent..

I am running archlinux with qutebrowser

**Comment by The-Compiler** [comment]
This looks fine here on Debian as well:

![japan](https://cloud.githubusercontent.com/assets/625793/7586279/a70e835a-f8ab-11e4-86b7-53d70b66073d.png)

I'll try on Arch later today. Can you please show the output of `fc-list`?

**Comment by The-Compiler** [comment]
With Arch, I first got no kanji:

![kanji1](https://cloud.githubusercontent.com/assets/625793/7615714/b6e6d0c6-f99f-11e4-927a-d5b602db76a1.png)

But after installing a font which provides kanji (I tried `ttf-hanazono` in `[community]`) it looks good:

![kanji2](https://cloud.githubusercontent.com/assets/625793/7615727/d892daf8-f99f-11e4-8260-899691ccd0c1.png)

I'm closing this for now as I guess you're just missing a font - if installing `ttf-hanazono` doesn't help, please show the output of `fc-list` and show a screenshot so I can investigate this.

**Comment by fosskers** [comment]
I have always been able to see them, but typing them is a different matter (#420).
