### ISSUE TITLE
Make command keys (:/?) configurable

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#672]
Those are currently [hardcoded](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/keyinput/modeparsers.py#L66-L68) - they should be bound to a command like everything else.

**Comment by The-Compiler** [comment]
As a workaround, doing `:bind ; set-cmd-text :` is possible (note that other `;...` bindings should be unbound with `;` so there's no delay after pressing `;`)

**Comment by The-Compiler** [comment]
This is currently hardcoded in `keyinput.modeparsers.NormalKeyParser._handle_single_key`. Hopefully all it takes is deleting that and adding new default bindings for `:`, `/` and `?` to the respective `:set-cmd-text` commands.

**Comment by haasn** [comment]
I was thinking about implementing this. I think there are two approaches:

1. Adding an option to change the magic string (trivial)
2. Separating them to actual commands (as suggested)

The former would fix the problem, but the latter would be the intended solution I guess?

**Comment by The-Compiler** [comment]
The latter, yeah - though it should still be easy, as `:set-cmd-text` already exists. I'm fine with the statusbar still showing `:` and `/` as that's just a common thing to show.

However I wanted to propose that one for @knaggita and @nanjekyejoannah from RGSoC, mind leaving it for them? :wink:

**Comment by haasn** [comment]
Sure thing. I have no use for this feature ;)
