### ISSUE TITLE
New keybindings get messed up

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#675]
I now had this multiple times while playing with the visual branch already, and now again after merging it to master and doing `:restart`.

The key config looks like this:

```
[caret]

rl-backward-delete-char
    v
    <Space>
    <Ctrl-Space>

enter-mode normal
    c
    j
    k
    l
    h
    e
    w
    b
    ]
    [
    }
    {
    0
    $
    gg
    G
    Y
    y
    <Return>
    <Ctrl-J>

scroll left
    H
    L

scroll down
    J

scroll up
    K
```

Which makes no sense at all, and I don't know how this happens...

@artur-shaik have you ever seen something like this happen?

Also see #515 though that wasn't `keys.conf`.

**Comment by The-Compiler** [comment]
I tried to reproduce by checking out 8e41797 (pre-visual) and upgrading/restarting/... multiple times, but no luck...

**Comment by artur-shaik** [comment]
No, I have never seen this, and can not reproduce this.

**Comment by The-Compiler** [comment]
I've never seen this anymore.
