### ISSUE TITLE
Not respecting no-cache headers for XHR responses

### ISSUE THREAD

**Issue by tomxtobin** [The-Compiler/qutebrowser#680]
I'm not sure if this is really an upstream WebKit bug or not, but a bug in qutebrowser's handling of XHR responses just caused [an issue with RethinkDB they were kind enough to work around](https://github.com/rethinkdb/rethinkdb/issues/4174). An excerpt from there:

> Looks like this is due to absolutely stubborn caching of XHR responses. No combination of Cache-Control: no-cache, Pragma: no-cache, or Expires headers could convince these browsers not to cache the POST request that creates a new connection. I ended up adding a random query parameter to the url to finally fix it.

Is there anything qutebrowser can do to either fix or mitigate this?

**Comment by The-Compiler** [comment]
This WebKit bug could be related maybe?

[Bug 134105 - XHR requests incorrectly cached/combined/coalesced](https://bugs.webkit.org/show_bug.cgi?id=134105)

Though even if I'd report this for Qt, unfortunately I think chances it'll be fixed are rather low...

If you can find/write some kind of test page, I can take a look if there's anything I can do to work around the issue.

**Comment by deontologician** [comment]
That webkit issue looks like what I was seeing.

**Comment by tomxtobin** [comment]
@The-Compiler Would that [jsfiddle demo](http://jsfiddle.net/D5s5M/2/) on the WebKit bug you linked help?

**Comment by The-Compiler** [comment]
That helps indeed, thanks! Somehow I missed that.

Some initial observations:

* It happens even without a `QNetworkDiskCache` set
* It even happens in WebKit2GTK browsers (Midori)

I'll have to see if I can do something in `QNetworkAccessManager`, but probably not.

**Comment by The-Compiler** [comment]
I don't think I can do anything here, so I'm closing this. It'll probably magically go away once there's a QtWebEngine backend (see #666).
