### ISSUE TITLE
Spawning a command raises the dead!

### ISSUE THREAD

**Issue by cym13** [The-Compiler/qutebrowser#688]
A program executed through the shell using :spawn turns into a zombie

To reproduce, in qutebrowser

    :spawn echo "Zombies! Zombies everywhere!"

then in a real shell

    $ ps -ef | grep defunct
    cym13     2814 31367  0 21:23 ?        00:00:00 [echo] <defunct>

What's fun is that there is never more than one Zombie, summoning another one digs the grave of the first:

    :spawn echo "Haunter, I choose you!"
    $ ps -ef | grep defunct
    cym13     2843 31367  0 21:23 ?        00:00:00 [echo] <defunct>

Note in the previous output that the pid is different, so it corresponds to the second echo and the first is gone.

My version infos follow:

qutebrowser v0.2.1
Git commit: v0.2.0-282-g534dbfc (2015-05-27 08:51:24 +0200)

CPython: 3.4.3
Qt: 5.4.1, runtime: 5.4.1
PyQt: 5.4.1
SIP: 4.16.7
colorlog: no
colorama: no
pypeg2: 2.15
jinja2: 2.7.3
pygments: 2.0.2
yaml: 3.11
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2a 19 Mar 2015

Frozen: False
Platform: Linux-4.0.4-2-ARCH-x86_64-with-arch, 64bit
OS Version: arch

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

**Comment by The-Compiler** [comment]
Props for the title :laughing:

I can reproduce this - I think it'll be resolved by #646, so I guess I should do that rather sooner than later.

Other workarounds I found with a quick search:

- Call `.poll()` on the `subprocess.Popen` object periodically (e.g. with a `QTimer`)
- Use `signal.signal(signal.SIGCHLD, signal.SIG_IGN)` to ignore all `SIGCHLD`s, but that could have other consequences with Qt code.

**Comment by The-Compiler** [comment]
`:spawn` now uses `QProcess` (just like `:spawn --userscript`) and the zombies are gone :smile:
