### ISSUE TITLE
hints: Focus hints

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#69]
There should be a "focused" hint and keybindings to select the previous/next hint (like dwb does).

**Comment by The-Compiler** [comment]
Nobody seems to want this, including myself :wink:

**Comment by lahwaacz** [comment]
FWIW, the first point in #1305 is basically the same proposal.

**Comment by The-Compiler** [comment]
Oh, right! I see how it could make sense with word hints, so let's track this there.

**Comment by lahwaacz** [comment]
I think it would make much sense even with numeric hints and in rapid hinting, regardless of the hint style :wink:
