### ISSUE TITLE
Make it easier to see a page is using https

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#691]
There is no obvious way to see that a current page is secure (using https) other than paying very close attention to URL. Right now the URL in the statusbar is always green. Even for http:// pages.

In dwb, the URL is in green if it's https, white otherwise. This is still not great IMHO, but would be better. Changing the background colour of the statusbar to light green (like insert mode now) for https, and some other colour (light blue perhaps) is better IMHO.

Opinions?

**Comment by lamarpavel** [comment]
>Opinions?

I would go one step further and say let the user configure what secure means and allow definition of differnt levels of "secure", which can then be identified with different colours, as per the user  config. Example:

- **https with untrusted certificate**: *very bad*
- **https with trusted certificate but TLS <= 1.1**: *bad*
- **https with trusted certificate and TLS >= 1.2**: *okay*

and then there is a fourth level that meets at least the *okay* demands but is also restricted by user specified specific key exchange algorithms. For example I would set ECDH with curve ed25519 and DH with SHA2 as the requirements to show a site as *secure*:

- **https with trusted certificate and TLS >= 1.2 and ECDH_curve25519 or DH_SHA2**: *secure*

Standard config might be less strict for level 4 and maybe not colour all of them differently. I would colour them red, orange, cyan and green from worst to best level.

User configuration should entail both background and foreground colour, but there is already an open issue for this afaik.

**Comment by Carpetsmoker** [comment]
You already get a confirmation when you're offered an invalid certificate; for example [on this page](https://lists.connman.net/mailman/confirm/connman). Not sure about older TLS versions, but a setting could be made for this to show a similar confirmation.

However, this seems like an entirly different issue to me. My point is that it's not very obvious to see if you've landed on http://github.com or https://github.com

**Comment by lamarpavel** [comment]
>However, this seems like an entirly different issue to me. My point is that it's not very obvious to see if you've landed on http://github.com or https://github.com

I guess that was not very clear, but I agree with that. However, changing the background colour should be subject to user config and right now, since we can not define the foreground color, it would become hard to read depending on your config. So I would say this issue (bringing the connection status to attention) is somewhat dependant on [this issue](https://github.com/The-Compiler/qutebrowser/issues/587).

Once I thought that far, I figured "why not go one step further and let the user configure what level of security to base the attention prompt on".

I did not mean to derail your thread.

**Comment by kirelagin** [comment]
Right, just letting users choose bg and fg colours for https and non-https pages is enough, IMO.
Since #587 is fixed, this should be easy now.

**Comment by neeasade** [comment]
I would like to do this one.

I see that in [url.py](https://github.com/The-Compiler/qutebrowser/blob/d8e58b58869f696fafd0b314740afc94af918e2b/qutebrowser/mainwindow/statusbar/url.py#L56) there are different foreground cases for url type(warn, error, success..). I would add here normal.https and success.https perhaps?

And around [here](https://github.com/The-Compiler/qutebrowser/blob/12a11a5931f2775bd74c012ecb214d80f8b93078/qutebrowser/config/configdata.py#L875-L881) in configdata.py, add statusbar.https.{fg,bg}? 

or would this be a pending thing based on the config rewrite incoming?

**Comment by The-Compiler** [comment]
@neeasade Sounds good! I think being able to customize the URL color is okay for now, we can always get more sophisticated later.

The setting would probably be `statusbar.url.fg.success.https` [around here](https://github.com/The-Compiler/qutebrowser/blob/12a11a5931f2775bd74c012ecb214d80f8b93078/qutebrowser/config/configdata.py#L945-L966). `statusbar.fg` etc. are for the foreground color of things other than the URL in the statusbar.

Thanks for looking at this!

**Comment by The-Compiler** [comment]
Closing this thanks to @neeasade!
