### ISSUE TITLE
Auto-fill forms

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#695]
A useful feature present in the old Opera presto browser is the ability to auto-fill in form fields.

![2015-05-29-143145_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1032692/7882617/a300a04c-060f-11e5-9201-e8d33b6ed1f6.png)

The easiest would be to always shows this information as a auto-fill option. Or we could try  some matching for the `name` attribute and/or associated `label`.

Somewhat related to https://github.com/The-Compiler/qutebrowser/issues/180 (but I would say it's a separate feature).

**Comment by The-Compiler** [comment]
qutebrowser itself will probably provide the filling heuristics (i.e. `:fill-field` as discussed in #180).

For the rest, that'd be a perfect candidate to be implemented as a plugin. I added it to the list in #30, so I'm closing this now.
