### ISSUE TITLE
Fast forward

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#696]
Opera (presto version) had a *very* useful feature where it tried to "magically" figure out what the "next" page is, and go to that if you've reached the bottom of the current page. This is called "fast forward".

The [issue for Otter](https://github.com/OtterBrowser/otter-browser/issues/343) has some useful background information and some code snippets.

**Comment by The-Compiler** [comment]
qutebrowser can already do this via [the `:navigate` command](https://github.com/The-Compiler/qutebrowser/blob/master/doc/help/commands.asciidoc#navigate), bound to `[[`/`]]` by default.

Do you think this is enough, or should it also be bound to space when scrolled down as mentioned in that otter issue?
