### ISSUE TITLE
Using scroll_page just after opening qutebrowser results in "ERROR: Current URL is invalid"

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#701]
As the title says:

Steps to reproduce:

- Open a tab
- Close qutebrowser
- Start it again, press (for example) `<C-d>`

You see the error `ERROR: Current URL is invalid`. It seems to take a full page load for `scroll_page` to work. This *only* seems to be the case when starting qutebrowser. However, pressing `<C-d>` when just opening a new tab (with `:open -t`) sometimes results in this error:

	WARNING: QIODevice::write: device not open
	File "/home/martin/src/qutebrowser/qutebrowser/utils/log.py", line 306, in qt_message_handler
		stack = ''.join(traceback.format_stack())

This doesn't seem to be the case with all sites, but on https://decorrespondent.nl/ I can reproduce it fairly reliable.

**Comment by The-Compiler** [comment]
I can't reproduce this so far - I tried opening http://cmpl.cc/ and then used `:wq` to save the session and restarted it - `<C-d>` then works right away for me.

As for the error message, I've also seen this but I guess it's some Qt issue... I added it to #100.

**Comment by Carpetsmoker** [comment]
Fixed it in `scroll_page_navigate` branch; only occured there it seems.

**Comment by The-Compiler** [comment]
Reopening this as it seems like the fix is just a workaround (see my comment there)

**Comment by Carpetsmoker** [comment]
Not sure if it's worth to have issues about feature branches (when I reported this I thought I was on master).
