### ISSUE TITLE
Going back/forward after cloning a tab doesn't work in GitHub Issues

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#708]
Going back/forward after cloning a tab doesn't work in GitHub Issues. The URL in the stsatusline changes, but the page stays the same. It works fine in the original tab.

I suspect this is because the issues are loaded via AJAX and the uses then `History` API to update the URL, but I didn't investigate.

**Comment by The-Compiler** [comment]
I can reproduce this - it seems like this is some issue with how the history is serialized/deserialized in `browser/tabhistory.py` - for some reason it seems to work in Otter Browser though, where I basically got the code from.

**Comment by The-Compiler** [comment]
This seems to work fine now, no idea why.
