### ISSUE TITLE
Excessive RAM consumption on page

### ISSUE THREAD

**Issue by rcorre** [The-Compiler/qutebrowser#709]
I tried visiting [this Lifehacker article](http://lifehacker.com/how-to-choose-the-best-mechanical-keyboard-and-why-you-511140347http://lifehacker.com/how-to-choose-the-best-mechanical-keyboard-and-why-you-511140347), and qutebrowser quickly began consuming near 100% of my system's RAM.

This doesn't seem to happen with `allow-javascript` and `allow-plugins` set to false.

**Comment by The-Compiler** [comment]
This is a [known Qt bug](https://bugreports.qt.io/browse/QTBUG-44523) which was [fixed for Qt 5.4.2](https://codereview.qt-project.org/#/c/108782/) which should be released [next week hopefully](http://lists.qt-project.org/pipermail/releasing/2015-May/001952.html).
