### ISSUE TITLE
No documentation on how to set new search engines

### ISSUE THREAD

**Issue by ersi-dnd** [The-Compiler/qutebrowser#710]
I don't see any documentation on how to add search engines. I tried making this addition to qutebrowser.conf

DEFAULT = https://duckduckgo.com/?q={}
g https://duckduckgo.com/?q=!g%20{}
u http://www.youtube.com/results?search_query={}
w https://en.wikipedia.org/w/index.php?search={}&title=Special:Search
d http://dictionary.reference.com/browse/{}?s=t
y http://search.yahoo.com/news/search?c=&p={}

but the added search engines are unrecognised. They don't work in the address bar and they do not show up in qute:settings

**Comment by ersi-dnd** [comment]
By the way, I think that a better place to store search engine definitions would be somewhere separate from the conf file. DWB has it right.

**Comment by r8b7xy** [comment]
duckduckgo = https://www.duckduckgo.com/?q={}
ddg = ${duckduckgo}

**Comment by ersi-dnd** [comment]
@r8b7xy What does this mean? Is that a solution? I don't see how.

**Comment by lamarpavel** [comment]
In the config file (~/.config/qutebrowser/qutebrowser.conf) you will find a section named [searchengines] where the following explanation can be found:

```
[searchengines]
# Definitions of search engines which can be used via the address bar.
# The searchengine named `DEFAULT` is used when `general -> auto-search`
# is true and something else than a URL was entered to be opened. Other
# search engines can be used by prepending the search engine name to the
# search term, e.g. `:open google qutebrowser`. The string `{}` will be
# replaced by the search term, use `{{` and `}}` for literal `{`/`}`
# signs.
```

What r8b7xy posted can be placed below that and will allow you to type

```o ddg test```

where o triggerst ```:open```.

**Comment by The-Compiler** [comment]
@ersi-dnd - see what @lamarpavel and @r8b7xy said - have you seen the documentation in the config file? If not, where would you've expected the documentation?

**Comment by ersi-dnd** [comment]
Yes, I have seen that in the config file - obviously, because this is where I added my own search engines. The problem is this: 

1. I read and understand how the searching from the address bar is supposed to work, but there is no hint how to add my own search engines. In addition to what that text says, I want it to say also something like: To add a new search engine, do (a) and (b).
2. I pasted the way how I added my own search engines in the config file. This did not work. Can anyone tell me why it's not working? What did I do wrong? Because, as far as I understand, I did not go against anything in the instructions. Since I did not go against anything in the instructions, it follows that the instructions are incomplete.
3. DWB has a separate file for search engines, just like Qutebrowser and DWB both have a separate file for quickmarks. I mean separate from the config file. And I think this is how it should be - separate.

Thank you very much for the replies.

**Comment by The-Compiler** [comment]
It seems you forgot the ` = `. The `DEFAULT` line has it, your lines don't.

I really can't see how I'd improve that documentation - there's a good example with the default engine, so I don't see how adding another (basically equal) example would help.

I happen to disagree that it should be separate - it's a configuration just like others after all.

**Comment by Carpetsmoker** [comment]
Pehaps the defaults can be expanded?

	DEFAULT = https://duckduckgo.com/?q={}
	w = http://en.wikipedia.org/w/index.php?search={}&title=Special:Search

.... more?

**Comment by The-Compiler** [comment]
They used to be, until @error800 and @flvi0 convinced me it'd be better to remove them (see #542 and #533). :wink:

**Comment by ersi-dnd** [comment]
@The-Compiler Thanks. It was indeed = sign. I copied the search engines from DWB and then launched Qutebrowser. Qutebrowser complained about %s that had to be replaced with {} but it didn't complain about =. These are the little differences of format between Qutebrowser and DWB.

But why have searchengines in config file when quickmarks are separate?

**Comment by The-Compiler** [comment]
Because search engines are a configuration option (it's something you'd typically change in some configuration GUI in a browser), and quickmarks are an entirely different thing.

With the YAML config migration (see #499) it might be possible to split the configuration across files like you want to (I'm not sure yet though).

There's no way to add search engines similiar to `gs` in dwb where you can select a field - see #13, though that's not really important for me right now. (PRs welcome of course!).

**Comment by ersi-dnd** [comment]
The reasons why I am asking about file separation are these:

1. DWB has them separate. I suppose you emulate DWB interface most, so it makes sense to be kind of compatible.
2. Speaking of compatibility, it would make sense to literally have the same format too. Not a requirement of course, but it would make migration more convenient to pay attention how others have implemented things and then document the differences.
3. Ease of restoration. One of the toughest cases in a program's profile is a messed up main config file. When the user is only learning the program and messes the config file up so hopelessly that it has to be deleted, then the more things are in the config file, the harder it will be to restore step by step. Search engines are a distinct entity from settings - just like quickmarks - and to me they look out of place in the config file. In Opera I have about hundred search engines. If I were to repeat this with Qutebrowser, think how heavy the config file would be, and when it gets corrupted, I'd have to meticulously extract the search engines from the file and then begin restoring.

**Comment by The-Compiler** [comment]
Regarding 1./2.: qutebrowser will be compatible with dwb where I think it makes sense both from an user- and from a code perspective, and won't otherwise. I've had people suggest all commands should be named the same as in vim - well, they won't, qutebrowser does not *equal* vim.

Regarding 3: Let's hope that doesn't happen. I recommend storing configs in a git (or other VCS) repo anyways.

As said, I'll look at this again with #499 and see what will make sense in that context, but definitely not before that.

**Comment by Carpetsmoker** [comment]
http://bikeshed.com/

**Comment by ddickstein** [comment]
The settings page only seems to have a single line input for search engines, so it's unclear how to paste the multiple lines of configurations described in the above conversation.  The config file seems to change with updates from the settings page, and changes don't seem to be reflected there.  (Config file I'm editing is `~/Library/Preferences/qutebrowser/qutebrowser.conf` on OS X).

**Comment by The-Compiler** [comment]
@ddickstein You should be able to quit qutebrowser and then edit that file. Or use `:set searchengines name url`.

**Comment by worldpe** [comment]
I tried 
`:set url.searchengines cg https://rateyourmusic.com/charts/top/release/all-time/ge:{}/u:followed_by:WhereAreWeSeeing/excl:ratings/`

but get told it's an unrecognized argument.

**Comment by toofar** [comment]
@worldpe try `:config-dict-add url.searchengines cg ...`. This ticket is quite old ;)

**Comment by worldpe** [comment]
That worked, thank you. Maybe this could be listed on the settings page under the search engine settings.

**Comment by The-Compiler** [comment]
`:config-dict-add` can be useful for any setting which is a dictionary - I don't think it makes sense to mention it everywhere, that seems quite noisy to me.
