### ISSUE TITLE
Disable sending referer header

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#712]
Make a option to disable sending the referrer header for reasons of privacy.

It should accept 3 values:

- Always send
- Never send
- Only send for the same domain (this should probably be the default?)

(I'll code this later).

**Comment by The-Compiler** [comment]
The place to add this would be `browser/network/networkmanager.py:createRequest` - see other lines with `setRawHeader` there.

**Comment by lamarpavel** [comment]
I would just like to thank you, @Carpetsmoker, for putting so much effort in security and privacy issues.

It would also make sense to do this with a whitelist per domain, once https://github.com/The-Compiler/qutebrowser/issues/27 is complete.

**Comment by The-Compiler** [comment]
Opening this again since #731 isn't merged yet :wink:

**Comment by Carpetsmoker** [comment]
Do we need issues for things that have a pull request? It seems sort of redundant to me...

**Comment by The-Compiler** [comment]
I prefer to close issues when the PRs are merged - otherwise people get mails about the issue they subscribed to being closed, and wonder why it still doesn't work :wink:

Also when people open an issue, they might search for similar issues first, but not for PRs.

**Comment by The-Compiler** [comment]
Closing this now that #731 is merged :smile:
