### ISSUE TITLE
Any way to serialise keybind definitions?

### ISSUE THREAD

**Issue by ersi-dnd** [The-Compiler/qutebrowser#715]
DWB has something like this: 

set -t ui hide-statusbar true ; set -t tabs hide-always true

i.e. two (or more) actions in sequence that can be triggered by one keybind.

Any way to do it in Qutebrowser?

**Comment by The-Compiler** [comment]
From `keys.conf`:

```
[...]
# `Shift-` to match a key pressed with shift.  You can bind multiple commands
# by separating them with `;;`.
```

(this is actually the same as in dwb)

**Comment by ersi-dnd** [comment]
Thanks. But how about a | function like in Opera? In Opera, this separated commands that worked like "if not, then" i.e. as a toggle. This way, for example Reload | Stop could be bound under the same key.

**Comment by The-Compiler** [comment]
Can you open a separate issue for that please? I'm not convinced yet, but let's continue the discussion there.

**Comment by ersi-dnd** [comment]
Well, in my opinion it's the same issue - serialisation of actions. You have one operator with which to serialise: 

`;;` translates as `and` 

Now I am asking about an `or`
