### ISSUE TITLE
GTK theme background color is used

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#719]
Reported by rebornmechanics in the [crunchbang forums](http://crunchbang.org/forums/viewtopic.php?pid=426679#p426679):

> Sometimes it draws the background of websites in a way that black font is unreadable for instance.

> The help page for instance. I can't pin down where the issue stems from exactly. But whenever a website does not provide a background color, qutebrowser does not default to white like other browsers do, but instead uses colors from my gtk2 theme.

![screen](https://cloud.githubusercontent.com/assets/625793/7913555/3417d39e-0871-11e5-9dfd-c75850cb20f1.png)

Probably an upstream issue but I didn't check yet.

**Comment by ff2000** [comment]
That's just the usual behaviour in any browser: If the website doesn't specify a bg-color it picks the one from the colorscheme. If I use kde's dark breeze I get the very same look.
It gets problematical if the website specifies a (text) color - usually black - but not a bg-color. Similar issues arise in forms. The qt.io bug tracker is such a case...
Workaround: Use a user stylesheet to set background to white ;) (which IMHO is what webdesigners usually expect)
This usually works:
```
html, body, input, textarea { background-color: white; color: black; }
```

Regarding qutebrowsers builtin (help)pages: It's up to you to specify a readable combination of bg/fg color.

**Comment by Carpetsmoker** [comment]
FYI: As far as I can find, there is nothing in the HTML or CSS spec about default colours, but a white background does seem to be the *de facto* default.

**Comment by The-Compiler** [comment]
@ff2000 oh, this is good to know - how do other browsers handle this though? Do they pick the theme color, or do they force white?

For the docs, I'm just using the default asciidoc theme - but I plan to switch to Sphinx/reST anyways (and asciidoc seems dead).

**Comment by ff2000** [comment]
@The-Compiler AFAIK qupzilla is the only browser that cares about dark themes. The solution there should (of course) also work for qutebrowser:
https://github.com/QupZilla/qupzilla/blob/v1.8/src/lib/webtab/webtab.cpp#L98
firefox doesn't care, also google chrome AFAIR had problems.

**Comment by The-Compiler** [comment]
Thanks for the pointer, @ff2000! I did something similar in 1bf036d, except not using style sheets (as they are buggy with QWebView in older Qt versions) and with a configurable color.
