### ISSUE TITLE
gC doesn't copy all data (and causes a server error)

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#726]
See the screenshots from the web inspector. In the original the form data is present, in the cloned tab it isn't (causing the server to error out).

The form has `enctype="multipart/form-data" method="post"`.

Original: ![original](https://cloud.githubusercontent.com/assets/1032692/7957284/66bca9ac-09e6-11e5-92e7-c87dcdc435c6.png)

Cloned: ![cloned_tab](https://cloud.githubusercontent.com/assets/1032692/7957288/6c215fbe-09e6-11e5-80a6-33bc1bbbded4.png)

**Comment by The-Compiler** [comment]
I can reproduce this with http://httpbin.org/forms/post

before cloning:

```json
  "form": {
    "comments": "", 
    "custemail": "", 
    "custname": "hello world", 
    "custtel": "", 
    "delivery": ""
  }, 
```

after cloning:

```json
  "form": {
    "\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001": ""
  }, 
```

**Comment by Carpetsmoker** [comment]
Related: the HTTP verb isn't saved in the history; it's always a GET.

**Comment by The-Compiler** [comment]
How can I reproduce that? Do you mean the back/forward history, or from sessions?

When submitting http://httpbin.org/forms/post I get to http://httpbin.org/post with a post request (doing a get will show "method not allowed". Then I visit another site and go back, and still see a post request.

**Comment by Carpetsmoker** [comment]
Sorry, I meant from sessions. When I open the above page with the POST request, do `:q` and start qutebrowser again, the page errors out. The inspector shows a GET, not a POST.

**Comment by The-Compiler** [comment]
For the issue with the corrupted data, I now opened https://github.com/OtterBrowser/otter-browser/issues/838 as I got that code from Otter, it's also broken there, and @Emdek might be more familiar with that code than I am.

As for the other issue, I'll look into that later or tomorrow.

**Comment by The-Compiler** [comment]
I opened https://github.com/OtterBrowser/otter-browser/issues/839 for the other issue as I can reproduce that in Otter as well.

It can be reproduced in qutebrowser by doing a POST to httpbin and then using `:restart`.

I'm locking this issue for now - if you have any more information, I think it makes more sense to report them in the otter bugs above, so all is in one place.

**Comment by The-Compiler** [comment]
Whoops, I never meant to lock this issue, not sure how that happened.

I finally reported this upstream as [QTBUG-47889](https://bugreports.qt.io/browse/QTBUG-47889).
