### ISSUE TITLE
Unable to enable JavaScript in qute:settings

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#727]
Once you've disabled JavaScript, you can't re-enable it in `qute:settings`. Probably because this page uses JS to save the settings? You need to use `:set`.

IMHO always enabling JS for `qute:` links would be acceptable.

**Comment by The-Compiler** [comment]
Your explanation is correct - however I wonder if it makes sense to add a workaround for that, as `qute:settings` will be revamped to be a real widget soon-ish (see #724).

Domain-wide settings aren't a thing yet, so I don't know yet how that'd be implemented correctly so javascript gets disabled when another page gets loaded again.

@iggy - do you happen to have time to look into this? :smile:

**Comment by Carpetsmoker** [comment]
> qute:settings will be revamped to be a real widget soon-ish

Perhaps a warning is also sufficient for now. I disabled JS to test something, then "re-enabled" it. After that it took me a while to discover that the source of my JS problems were that it wasn't in fact re-enabled.

**Comment by The-Compiler** [comment]
I can't be bothered to check how I could fix this in the javascript part, so I changed the python part so there's a warning when js is turned off, and `qute:settings` refuses to turn JS off.

Clearly not the best solution, but it's temporary, so I don't care :tongue:

**Comment by iggy** [comment]
Sucky part is... I originally had a `<noscript>` section in the original iterations of this feature and lost it somewhere :/

**Comment by The-Compiler** [comment]
@iggy Good part is that this `<noscript>` actually was there - I just never tested it I think and didn't notice... :blush:

I now reverted that part of the change and made the noscript contents stand out a bit more.
