### ISSUE TITLE
Headers in web inspector don't match what is actually being sent

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#730]
See screenshot; for example, there is no `Dnt` in the web inspector, and the `Referer` has a different value (!).

Also in Otter browser. Not sure if this is an upstream bug, or if we're setting the headers "wrong".
At the very least this should be documented :-)

![2015-06-04-010110_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1032692/7973437/8dcccc60-0a55-11e5-92d0-d7027983d651.png)

**Comment by The-Compiler** [comment]
Weird... It also looks good with Wireshark:

```
GET /headers HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
DNT: 1
X-Do-Not-Track: 1
Accept-Language: en-US,en
Cookie: _ga=GA1.2.671419664.1423723855
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Host: httpbin.org

```

I wonder where the inspector is getting this information from...

**Comment by Carpetsmoker** [comment]
The difference seems to be that the User-Agent is set with `QWebPage.userAgentForUrl()`; and not with `QNetworkAccessManager.setRawHeader()`.

**Comment by The-Compiler** [comment]
Reported upstream: https://bugreports.qt.io/browse/QTBUG-47266

I'll also add a note to the docs for `:inspector`.
