### ISSUE TITLE
New color options (#707) breaks input context menu.

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#750]
Since merging #707, the context menu in the statusbar looks different.

old:

![old](https://cloud.githubusercontent.com/assets/625793/8105581/bce00f90-103a-11e5-9cb3-0689ebceefb8.png)

new:

![new](https://cloud.githubusercontent.com/assets/625793/8105584/c18b2cb4-103a-11e5-9f82-44ef1cec1b1d.png)

While it looks quite good, it doesn't show disabled items, etc.

I think the stylesheet should be adjusted to not style `*`, and instead only style specific statusbar items. Maybe the stylesheet syntax makes it possible to set "tags"/classes on widgets somehow?

@ProtractorNinja - I'd be glad if you could look at this :wink:

**Comment by ProtractorNinja** [comment]
Oops! I didn't realize that the statusbar has more sub-widgets. I'll fix this straightaway.

**Comment by ProtractorNinja** [comment]
I opened a [new PR](https://github.com/The-Compiler/qutebrowser/pull/751) with my fix.
