### ISSUE TITLE
:spawn-ing commands with flags

### ISSUE THREAD

**Issue by smalltock** [The-Compiler/qutebrowser#759]
I can't use :spawn to run a command with flags because :spawn picks up the flags instead.

For example:
`:spawn screen -d -m mpv https://soundcloud.com/aliceoliviamusic/free-dl-i-see-fire-ed-1`
![jej](https://cloud.githubusercontent.com/assets/3895638/8200378/166c7408-1479-11e5-9408-fa6ad8a330da.png)

Enclosing the flag in quotes doesn't change the outcome. Escaping the `-` just passes the backslash to the command, breaking the flag.

My idea:
`:spawn` shouldn't look for flags after the program name (`screen`).

**Comment by The-Compiler** [comment]
You could use `:spawn -- screen ...` to tell qutebrowser to not split the arguments - but I agree it makes more sense for `:spawn` to take arguments literally, so I changed it to behave that way.

**Comment by lamarpavel** [comment]
Since 6dbdea0ee3fa52d08cc135dba65924792b38395c ```:spawn mpv {url}``` results in ```ERROR: Command exited with status 2``` while ```:spawn mpv EXAMPLE``` works with EXAMPLE being the URL of the current tab (tested with youtube).

**Comment by The-Compiler** [comment]
Whoops - thanks for pointing that out, @lamarpavel! Should be fixed with 59cdbd7.

**Comment by lamarpavel** [comment]
Confirmed working, thanks.

**Comment by smalltock** [comment]
Same here. Thanks
