### ISSUE TITLE
Install could cp qutebrowser.desktop into ~/.local/share/applications

### ISSUE THREAD

**Issue by teto** [The-Compiler/qutebrowser#761]
Any reason for not doing so ? dmenu for instance does not find a qutebrowser match withtout the .desktop for instance.

**Comment by The-Compiler** [comment]
That's a job for distribution packages - e.g. the [Arch PKGBUILD](https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qutebrowser#n40) does this already.

A `setup.py` never should install stuff system-wide in some way - otherwise, that'd break in virtualenvs, on Windows/OS X, etc. etc.
