### ISSUE TITLE
Characters not rendered at all if the font doesn't support it.

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#762]
Characters not rendered at all if the font doesn't support it; they show up as a space. They should be replaced by some sort of glyph which shows that the character is missing (note that the character itself should **not** be replaced, just the glyph used for rendering).

TrueType fonts should have a ".notdef" glyph as the first glyph (...not sure how we can use this from Qt). Note that it does work as expected in the tab bar and statusline. it also works as expected in history completion, 

Example in various browsers (bottom-right is midori, [url to page](http://ja.stackoverflow.com/questions/7661/googleplay%E3%81%AB%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%97%E3%81%9F%E3%82%A2%E3%83%97%E3%83%AA%E3%81%8C%E9%9F%B3%E3%81%8C%E5%87%BA%E3%81%AA%E3%81%84)).

![2015-06-17-163952_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1032692/8211721/fc13c312-150f-11e5-83b5-9f18ffa39034.png)

Note: otter browser & qupzilla do the same thing.

**Comment by The-Compiler** [comment]
Hm, I'm pretty sure I've seen those boxes before. How can I reproduce this?

**Comment by Carpetsmoker** [comment]
[test page from screenshots](http://ja.stackoverflow.com/questions/7661/googleplay%E3%81%AB%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%97%E3%81%9F%E3%82%A2%E3%83%97%E3%83%AA%E3%81%8C%E9%9F%B3%E3%81%8C%E5%87%BA%E3%81%AA%E3%81%84).

**Comment by The-Compiler** [comment]
Ah, I can reproduce it after removing `ttf-hanazono` which I installed to test some bug a while ago...

Since it seems to be a QtWebKit issue and I'm tired of reporting bugs upstream just to have them ignored, I'm afraid I'll just ignore this - sorry! :unamused: 

Things will get better with the QtWebEngine backend though!
