### ISSUE TITLE
tox -e mkenv doesn't work on Debian jessie

### ISSUE THREAD

**Issue by mrjovanovic** [The-Compiler/qutebrowser#779]
I'm running Debian jessie, and I can't seem to get `tox -e mkenv` to work by default. The only thing that happens is that I get `ERROR: unknown environment 'mkenv'`.

I followed the instructions in the INSTALL doc, and installed `python3-pyqt5 python3-pyqt5.qtwebkit python-tox` fine. This happens with both the release and the cloned git repo.

**Comment by The-Compiler** [comment]
The environment is called `mkvenv`, not `mkenv` (note the `v`) :wink:

Is this wrong in the documentation somewhere? I grepped for `mkenv` in the repo and didn't find anything.

**Comment by mrjovanovic** [comment]
Oh, jeez, I'm an idiot. I'm so sorry. I can't believe that slipped my eyes so many times. I read through the tox docs, the install docs again, checked the repos to see if Debian was doing anything funny. Ah!

My fault for typing things out instead of copy-pasting. I do apologize.

**Comment by The-Compiler** [comment]
No worries, such things happen sometimes. :)
