### ISSUE TITLE
Move developer scripts to a subfolder

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#783]
The `scripts` folder is getting quite cluttered - scripts I use for developing only should be in a subfolder.

**Comment by Permafacture** [comment]
Perhaps related to this, when I pip installed qutebrowser, I got a directory called scripts in my `python3.4/dist-packages/` directory, with the development scripts in it, which doesn't seem right.  I know the recomneded install isn't with pip, but the project does have a setup.py and pip install does work except for this off directory (and it doesn't build the docs, but will change when the docs are bundled).  

Just a note.

**Comment by The-Compiler** [comment]
Whoops, good catch! I think that has been like this since v0.1, and nobody ever noticed :laughing:

I fixed it in the above commit.
