### ISSUE TITLE
History completion by title

### ISSUE THREAD

**Issue by kirelagin** [The-Compiler/qutebrowser#786]
After I hit `o` it would be nice if I could find the page I need by typing its title, not url.
Also, fuzzy completion (#785) should match on url and title simultaneously.

**Comment by The-Compiler** [comment]
There are two parts of this:

- The logic for the completion to consider the second column when filtering - @antoyo is working on this as a part of #681.
- Making the history (and maybe quickmarks as well) actually *store* the title. This is a bit more involved than it sounds, as qutebrowser is currently using [QWebHistoryInterface](http://doc.qt.io/qt-5/qwebhistoryinterface.html) to get URLs to add to the history - this is made for exactly that purpose, but it doesn't give us the title. @toofar wanted to look into that in #531 but I haven't heard back so far.

**Comment by Carpetsmoker** [comment]
Re: actually storing the title. I took a looksee at this, and it seems to me that the  `QWebHistoryInterface()` is just not enough. There is no way to add parameters to the `addHistoryEntry()` call for example, which you need to add a title.

Another useful addition would be to store if the user typed the address, or if we stored it through navigation. And possible some other things.

Otter does this btw (`core/HistoryManager.cpp`). It's not terribly complicated.

Thoughts?

**Comment by magnetophon** [comment]
+1 on this one too!  :)

**Comment by kepi** [comment]
I would love to see this one too. Postponing my transition to QB as I can't live without this future :)

**Comment by The-Compiler** [comment]
This is now implemented and will be released as part of v0.7.0.
