### ISSUE TITLE
Don't bind backspace by default

### ISSUE THREAD

**Issue by Permafacture** [The-Compiler/qutebrowser#789]
Shift+H makes sense.  I keep hitting backspace rapidly several times thinking I'm in insert mode, and thus go back several pages.  Users would have to know about H and L inorder to get back from this mistake anyways, so why not just encourage using H and L and let users bind backspace if they want to?

**Comment by The-Compiler** [comment]
I think I added backspace because there was someone who was used to it and wanted it - I don't think we should [bikeshed](http://bikeshed.com/) about default bindings at this point.

After all, if it's in your way, it's also just an `:unbind <Backspace>` away :wink:

**Comment by The-Compiler** [comment]
This topic just came up again in the `#qutebrowser` IRC channel and some other people agreed the binding is annoying - so I now removed it. :smile:
