### ISSUE TITLE
:noh command to un-highlight after search

### ISSUE THREAD

**Issue by Permafacture** [The-Compiler/qutebrowser#790]
Search with `/` highlights the matches.  In vim I use noh when I'm done with a search and the highlighting is annoying.  I miss having this in qute.

**Comment by The-Compiler** [comment]
There's already the `:search` command which gets invoked when you do `/` - you can clear the highlights using `:search` without arguments (bound to `<Escape>` by default).

I don't think it makes sense to add a dedicated command for that.
