### ISSUE TITLE
Enforce 100% test coverage for perfect modules

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#792]
For the perfect modules in #660 we should have something which enforces 100% coverage to be sure we don't accidentally add something without a test.

**Comment by lamarpavel** [comment]
Could this even be done automatically? All I can think of is some script (possibly a git-hook) to check all changed files against a whitelist with "perfect modules" and then prints a notice/warning after pulling (in case of a git-hook) or when running tox that for this module the tests might be "out of sync".

But that requires manual intervention by someone (probably the owner of the repo) each time these files are changed. I have never heard of any such system in software development. Admittedly though, I have never worked in a TDD-environment.

**Comment by The-Compiler** [comment]
I'm thinking of just integrating it with my [buildbot](http://qutebrowser.org:8010/waterfall?reload=5) and [Travis](https://travis-ci.org/The-Compiler/qutebrowser) (for pullrequests).

The tests are already run there with [coverage.py](http://nedbatchelder.com/code/coverage/) to determine what part of the code is actually exercised by the tests - see an [example report](http://www.qutebrowser.org/coverage/archlinux/729/index.html).

So there's a whitelist of perfect modules (the ones with 100% coverage currently, basically) - and if coverage for any of those ever drops below that, an additional step checks that and errors.
