### ISSUE TITLE
:hint spawn with flags doesn't work

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#797]
Running `:hint all spawn -v echo` doesn't work because `:hint` tries to interpret `-v`:

```
DEBUG    commands   command:run:489 command called: hint ['all', 'spawn', '-v', 'echo']
ERROR    message    message:error:277 hint: Unrecognized arguments: -v echo
```

However, using `:hint -- all spawn -v echo` doesn't work either for some reason...

```
DEBUG    commands   command:run:489 command called: hint ['all', '--', 'spawn', '-v', 'echo']
[...]
DEBUG    procs      guiprocess:start:134 Starting process.
[...]
ERROR    message    message:error:277 Error while spawning command: The process failed to start.
```

For the first issue: Probably `@cmdutils.register` should have a new argument (`ignore_late_args` or `pass_args` or so?) which passes arguments like `maxsplit=x`, but still splits normally. This would also be useful for `:spawn` and maybe more which actually *need* splitting (see 6dbdea0).

**Comment by The-Compiler** [comment]
For the second case, it's trying to run `-v echo`...

**Comment by The-Compiler** [comment]
As mentioned by @Ambrevar in #795, a workaround is to create a script in your `$PATH` which wraps the thing you want to run:

```bash
#!/bin/bash
exec foo --blah "$@"
```

**Comment by The-Compiler** [comment]
Note to self: `:hint links spawn ...` isn't the `:spawn` command - it's a hint mode

**Comment by sim590** [comment]
This bug makes it impossible to do `hint links spawn --userscript  fooscript {hint-url}`. Not being able to call userscript with `hint links` is considerable. For instance, I wanted to do `hint links spawn --userscript  view_in_mpv {hint-url}`.

**Comment by sim590** [comment]
A possible workaround/feature for youtube specific issue would be to let the user configure a userscript to be called when opening a certain type of URL. For youtube videos, one could specify `view_in_mpv` userscript. Then, when pressing `F`, the tab would open with video already running in mpv.

**Comment by The-Compiler** [comment]
@sim590 FWIW, I don't see how spawning the `view_in_mpv` userscript with hints makes sense. The whole point of that script is to remove the video from the page, which isn't something which needs to be done when using hints. Why not just `:hint links spawn mpv {hint-url}`?

I've never thought about the idea you posted, and to be honest I'm not sure it makes a lot of sense. I think if anything, something like dwb's `autoquvi

**Comment by cryptopsy1** [comment]
:hint links spawn /script.sh , where script.sh just echos a word to a file, doesn't work, it is +x like it should be
script.sh contains echo "open -t http://www.dict.cc/?s=$QUTE_SELECTED_TEXT" > /tmp/hh
error something like, the process failed to start, for :hint links userscript /script.sh

**Comment by cryptopsy1** [comment]
:hints links userscript /script.sh , doesn't work with the error " error while spawning userscript. the process failed to start"

cat /script.sh :
#!/bin/bash
#echo "$QUTE_URL" > /tmp/.0/hh # doesn't work
#echo "$1" > /tmp/.0/hh  #doesn't work
echo $1 > /tmp/.0/hh  #works
