### ISSUE TITLE
Freeze when giving large counts to movement keys.

### ISSUE THREAD

**Issue by Ban3** [The-Compiler/qutebrowser#801]
Version:
qutebrowser-git from AUR
Git commit: v0.3.0-33-g11e88fb (2015-07-06 13:18:05 +0200)

CPython: 3.4.3
Qt: 5.4.2, runtime: 5.4.2
PyQt: 5.4.2

Steps to Reproduce:
1. Use a large count with a movement key on any web page, e.g. "3333333333333j"

Actual Results:
qutebrowser freezes with a very high CPU usage.

Expected Results:
Pentadactyl and cVim just move to the end of the page and stop there.

**Comment by The-Compiler** [comment]
The way scrolling in qutebrowser currently works is by faking up/down key presses. In yoru case, that means 3333333333333 down keypresses got sent :wink:.

I now changed it so qutebrowser aborts when it reaches the bottom of the page (or top/left/right) - let's hope that doesn't break anything in some corner case!

**Comment by Ban3** [comment]
Yeah, I  thought it was doing that. This specific corner case is at least fixed now, thanks.
