### ISSUE TITLE
Installation guide for Fedora and family.

### ISSUE THREAD

**Issue by zwarag** [The-Compiler/qutebrowser#804]
Could you guys help me get qutebrowser running on fedora?
If I get this to work I'd even try to make a package for fedora or at least edit your installation guide lines to include fedora.

**Comment by Carpetsmoker** [comment]
Do you have a specific problem or something that's unclear?

**Comment by The-Compiler** [comment]
I have no idea about Fedora I'm afraid - @V155, can you help?

The first thing to check would be if you can get the needed dependencies, especially Qt and PyQt >= 5.2.0.

If so, you should be able to follow [the Debian instructions](https://github.com/The-Compiler/qutebrowser/blob/master/INSTALL.asciidoc#on-debian--ubuntu) and substitute the package installation with their equivalents on Fedora.

**Comment by zwarag** [comment]
I managed to do a little bit and found some of the equivalent packages for fedora/centos.
But I get this error when I try to `tox -e mkvenv`:

    mkvenv develop-inst-noop: /home/kavan/git/qutebrowser
    mkvenv runtests: PYTHONHASHSEED='1535404212'
    mkvenv runtests: commands[0] | /home/kavan/git/qutebrowser/.venv/bin/python scripts/link_pyqt.py --tox /home/kavan/git/qutebrowser/.venv
    Did not find sip in /usr/lib/python3.4/site-packages!
    ERROR: InvocationError: '/home/kavan/git/qutebrowser/.venv/bin/python scripts/link_pyqt.py --tox /home/kavan/git/qutebrowser/.venv'
    _______________________________________________ summary ________________________________________________
    ERROR:   mkvenv: commands failed

But I'm actually sure that I've - at least - installed python3-sip, because:  
`dnf install python3-sip`  
returns  

    Package python3-sip-4.16.7-2.fc22.x86_64 is already installed, skipping.
    Dependencies resolved.
    Nothing to do.
    Complete!

So after some further digging, the problem seems to be that python3-sip is in `/usr/**lib64**/python3/site-packages/` and not in `/usr/lib/python3/site-packages/`.  
Then I tried to `ln -s` that sip, but it just says that it misses `/usr/lib/python3.4/sites-packages/PyQt5`  

My understanding of linux per se ain't enought to troubleshoot what happening here. All I know is that I have 64 lib's installed not not the 32 ones.  

Any idea how I should proceed?

**Comment by The-Compiler** [comment]
Fun... can you please show the output of these commands?

* `python3 -c 'import sip; print(sip.__file__)'`
* `python3 -c 'import PyQt5; print(PyQt5.__file__)'`
* `python3 -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())`'
* `python3 -c 'import sys; print(sys.prefix); print(sys.version)'`
* `python3 -c 'import platform; print(platform.architecture())'`

**Comment by zwarag** [comment]
* python3 -c 'import sip; print(sip.__file__)'

/usr/lib64/python3.4/site-packages/sip.so

* python3 -c 'import PyQt5; print(PyQt5.__file__)'

/usr/lib64/python3.4/site-packages/PyQt5/__init__.py

* python3 -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'

/usr/lib/python3.4/site-packages

* python3 -c 'import sys; print(sys.prefix); print(sys.version)'

/usr
3.4.2 (default, Jan 12 2015, 12:13:20) 
[GCC 4.9.2 20150107 (Red Hat 4.9.2-5)]

* python3 -c 'import platform; print(platform.architecture())'

('64bit', 'ELF')

**NOTE:**  
I'm doing this all in a KVM virtual machine to be sure that my own system is not somehow affecting the installation process. Otherwise I couldn't be 100% sure if the installation guide would work on every machine.

**Comment by The-Compiler** [comment]
Looks like Fedora does something funny to `distutils.sysconfig.get_python_lib()` to return the directory in `/usr/lib` instead of `lib64`...

There are already a lot of workarounds for my [get_python_lib()](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/link_pyqt.py#L135-L161) function in `link_pyqt.py`, so I think I'll just rewrite it so it's based on something like `import sip; os.path.dirname(sip.__file__)` instead.

That'll take me a few days however as I'm currently busy with other things - in the meantime, you could do `virtualenv .venv --system-site-packages --python=/usr/bin/python3` and `./.venv/bin/pip install qutebrowser` instead.

**Comment by zwarag** [comment]
Thank you very much The-Compiler.
Unfortunatly I'm still not able to install it properly, so I wait till you do your thing and then I'll give it another run. I've added qutebrowser to my watch list. So I will see when you do that push.

**Comment by The-Compiler** [comment]
@zwarag I now changed the script in the `link-pyqt` branch - could you please test if that works on Fedora? That'd  mean something like:

```
git pull
git checkout link-pyqt
tox -e mkvenv
```

**Comment by zwarag** [comment]
Sorry to tell you that it still does not work.
I get this message:

    mkvenv develop-inst-noop: /home/kavan/qutebrowser
    mkvenv runtests: PYTHONHASHSEED='2320464359'
    mkvenv runtests: commands[0] | /home/kavan/qutebrowser/.venv/bin/python scripts/link_pyqt.py --tox /home/kavan/qutebrowser/.venv
    Did not find sip in /usr/lib/python3.4/site-packages!
    ERROR: InvocationError: '/home/kavan/qutebrowser/.venv/bin/python scripts/link_pyqt.py --tox /home/kavan/qutebrowser/.venv'
    ________________________________________________________________________ summary ________________________________________________________________________
    ERROR:   mkvenv: commands failed

If it helps/interests you, I'd write you a Vagrant file to set up the environment and figure out what happens.

**Comment by zwarag** [comment]
Dude, it worked like a charm.

**Comment by The-Compiler** [comment]
Glad to hear - I pushed the new script to master.

Do you want to submit a pull request for `INSTALL.asciidoc` to add a Fedora section? If not, could you let me know what you had to do to install the prerequisites? Thanks!

**Comment by zwarag** [comment]
Yes, it just werks ™.
I'll write you that installation guide I promised as a pull request.
Just give me 24, got some work to do right know. 
And I'll test that on CentOS too, just to be sure.

**Comment by The-Compiler** [comment]
Sure, take your time! Thanks!

**Comment by zwarag** [comment]
Did a Pull Request: #817
