### ISSUE TITLE
pypy.js never loads

### ISSUE THREAD

**Issue by Permafacture** [The-Compiler/qutebrowser#805]
http://pypyjs.org/index.html

This is very low priority and almost certainly a webkit issue.

**Comment by The-Compiler** [comment]
I can confirm this, and it seems to be a QtWebKit problem - it loads fine in WebKitGTK based browsers.

This is one of the things I could report upstream but chances are it'll just get ignored :disappointed: 

I'll leave it open for now until I decide to report it upstream, or until there's a QtWebEngine backend (#666) where it should work fine.

**Comment by The-Compiler** [comment]
Reported upstream here: https://bugreports.qt.io/browse/QTBUG-47263
