### ISSUE TITLE
Failed tests when system locale is not english

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#806]
Hello.
The test `test_failing_open` from file `tests/utils/test_qtutils.py` fails when the system locale is not english:

```
    def test_failing_open(self, tmpdir):
        """Test open() which fails (because it's an existant directory)."""
        qf = QFile(str(tmpdir))
        dev = qtutils.PyQIODevice(qf)
        with pytest.raises(OSError) as excinfo:
            dev.open(QIODevice.WriteOnly)
        errors = ['Access is denied.',  # Linux/OS X
                  'Is a directory']  # Windows
>       assert str(excinfo.value) in errors
E       assert 'est un dossier' in ['Access is denied.', 'Is a directory']
E        +  where 'est un dossier' = str(OSError('est un dossier',))
E        +    where OSError('est un dossier',) = <ExceptionInfo OSError tblen=2>.value
```

Thanks to fix this error.

**Comment by The-Compiler** [comment]
This only happened with systems with an older `tox` version (< 2.0.0) as 2.0.0 isolates the `LC_ALL` environment variable - but I adjusted the tests in the above commit to check the numerical error instead of the string.

Thanks for the report!

**Comment by antoyo** [comment]
I have `tox` version 2.1.1, so it is probably not caused by the version. Anyway, thanks for fixing this issue.
