### ISSUE TITLE
How to prevent new windows from being focused ?

### ISSUE THREAD

**Issue by teto** [The-Compiler/qutebrowser#818]
Hi,

I've configured tabs to be opened as new windows ( tabs-are-windows = true) but everytime I open a new tab (i.e. window), my window manager (www.i3wm.org) focuses that window even with  "background-tabs = true ". I would like to keep the focus on my current tab/window.

Here is an excerpt of my config
```
 background-tabs = true                                                                                                              
  select-on-remove = right
  new-tab-position = right
  new-tab-position-explicit = last
  last-close = ignore
  hide-auto = false
  hide-always = true
  wrap = true
  movable = true
  close-mouse-button = middle
  position = north
  show-favicons = true
  width = 20%
  indicator-width = 3
  indicator-space = 3
  tabs-are-windows = true
  title-format = {index}: {title}
  mousewheel-tab-switching = true
```
I am using "Git commit: v0.3.0-5-g1672399 (2015-06-28 23:20:56 +0200)"

**Comment by The-Compiler** [comment]
I tried reproducing this with your settings, but without any luck.

I'm using herbstluftwm, and also told it to not focus new windows (`hc rule focus=off`), and it works like intended, i.e. the old window is focused when a new one is opened (I tried `open -t` and ctrl-clicking on a link).

How are you opening the new tab?

**Comment by teto** [comment]
Apparently this is a problem in my window manager. Thanks to Michael rose on irc  "you can't make them not steal focus in any way whatsoever newly created windows created on a visible workspace are focused".
Here is some reference for future viewers
https://faq.i3wm.org/question/464/prevent-new-windowspopups-from-stealing-focus/

**Comment by eike-f** [comment]
For i3 users:
You can add the line
```no_focus [class="qutebrowser"]```
to your .config/i3/config
to disable focus stealing on background windows.
There is probably room for improvement, because in this way qutebrowser windows never gain focus on creation.
But if I open a link in an email I would actually like the new window to steal focus.

**Comment by sersorrel** [comment]
not to bump an ancient issue, but `no_focus [class="qutebrowser" instance=__focused__]` seems to do exactly what I want: when you middle-click a link in qutebrowser, the new window opens in the background, but if you open qutebrowser from some other application, it takes focus.

**Comment by eike-fokken** [comment]
@sersorrel Nice, thanks a lot!

**Comment by mentalisttraceur** [comment]
I guess ideally, when opening a new window Qutebrowser would somehow *tell* the system if it is supposed to be a foreground or background window, and then the window manager could trust that information in the absence of overriding user configuration.

I'm not sure if that exists, but I'm jotting it down here as a thought in case any of us ever want to look into it.
