### ISSUE TITLE
Typing in one window affects completion in other

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#821]
When there are two windows and both have the completion open, typing in one completion also filters entries in the other one. Probably other stuff (like pressing tab to complete) are also affected?

**Comment by acogneau** [comment]
I noticed that this only occurs when the completions are using the same model. e.g. when you have command completion open in window 1 it won't affect quickmark completion in window 2.

**Comment by acogneau** [comment]
I'm working on this.

**Comment by The-Compiler** [comment]
This is fixed in #883 thanks to @acogneau!

/cc @seir-
