### ISSUE TITLE
Load window icon from theme

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#829]
We should use `QIcon.fromTheme` to get the qutebrowser icon for the window so it could be customized. The default theme search path includes `:/icons` so we could be able to adjust `scripts/dev/gen_resources.py` to put the icon there.

**Comment by funeralismatic** [comment]
```diff
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
@@ -165,11 +165,14 @@ def init(args, crash_handler):
 def _init_icon():
     """Initialize the icon of qutebrowser."""
     icon = QIcon()
+    fallback_icon = QIcon()
     for size in (16, 24, 32, 48, 64, 96, 128, 256, 512):
         filename = ':/icons/qutebrowser-{}x{}.png'.format(size, size)
         pixmap = QPixmap(filename)
         qtutils.ensure_not_null(pixmap)
-        icon.addPixmap(pixmap)
+        fallback_icon.addPixmap(pixmap)
+    qtutils.ensure_not_null(fallback_icon)
+    icon = QIcon.fromTheme('qutebrowser', fallback_icon)
     qtutils.ensure_not_null(icon)
     qApp.setWindowIcon(icon)
```

**Comment by The-Compiler** [comment]
@funeralismatic nice, thanks! If you want proper attribution please open a PR, otherwise I'll probably apply this tomorrow - I need some sleep now :wink:

**Comment by XRevan86** [comment]
It seems like I'll have to do a MR then :-).

**Comment by The-Compiler** [comment]
now I'm confused, are you the same @XRevan86 @funeralismatic or two different people? :laughing:

**Comment by XRevan86** [comment]
@The-Compiler, two different. @funeralismatic requested me to do the thing and so I did.

**Comment by funeralismatic** [comment]
Since February 5th icon from theme not work. Gentoo, python 3.4.

**Comment by The-Compiler** [comment]
@funeralismatic I don't see any commit which possibly could've broken this. Are you sure it's not something on your system?

**Comment by funeralismatic** [comment]
@The-Compiler, I try to find commit and also try to find problems with my system (e.g. no icon for qutebrowser or wrong path to icon theme). All is OK but icon not work for me.

**Comment by The-Compiler** [comment]
So what exactly doesn't work? You get the builtin icon, not the one from the theme?

And it does work if you switch to some older commit again, like 04afcef239faeef304fc013f90e119d3e944e37b where this was added?

**Comment by funeralismatic** [comment]
>So what exactly doesn't work? You get the builtin icon, not the one from the theme?

Yep.

>And it does work if you switch to some older commit again, like 04afcef where this was added?

Yep.
