### ISSUE TITLE
Hangouts in GMail buggy

### ISSUE THREAD

**Issue by rperce** [The-Compiler/qutebrowser#831]
Hangout chat tabs are all weird and flickery, often while interacting with the chat.

**Comment by The-Compiler** [comment]
Google Hangout is unsupported in qutebrowser in general (see #527), and I guess this will work better when there is a QtWebEngine backend (#666).

I'll take a look when I'm back at work (4th August or so) as I don't use GMail otherwise. But this smells like a QtWebKit bug, and since that's deprecated, chances are nobody will care...

If you have a distribution which packages it, can you test via something like `python3 scripts/minimal_webkit_testbrowser.py --webengine gmail.com`?

**Comment by rperce** [comment]
```
╔═(robertp@i-112213)════[504]════(~/bin/lib/qutebrowser)
╚══╡$ python3 scripts/minimal_webkit_testbrowser.py --webengine gmail.com
usage: minimal_webkit_testbrowser.py [-h] [--plugins] url
minimal_webkit_testbrowser.py: error: unrecognized arguments: --webengine
```

So I tried without --webengine and it works, but is just as flickery. 

It appears that when something changes in the hangout (a user reads a new line, starts typing, says something, etc) it sometimes reloads the hangout part of the page (based on the "Loading started / progress / finished" text in console) and flashes. But sometimes it flashes anyways? It looks very much like QtWebKit. My workaround at the moment is doing hangouts throug pickups through weechat, which honestly works pretty well.

**Comment by The-Compiler** [comment]
`--webengine` will only be available if you have `QtWebEngine` available - can you try with that please? Usually the package is called something like `qt5-webengine` or so

**Comment by The-Compiler** [comment]
@rperce Any update? If it works fine with QtWebEngine, I'd like to close this, as it's an upstream issue and it's unlikely anyone will care as QtWebKit is deprecated - so you'll have to wait until qutebrowser does the switch :wink:

**Comment by rcorre** [comment]
I've been using hangouts for awhile and haven't noticed this. 

`qutebrowser 0.3.0-1` and `qt5-webkit 5.5.0-2`.

I did notice that I can use the hangouts tab on mail.google.com and plus.google.com/hangouts, but not hangouts.google.com (claims my browser is unsupported).

**Comment by The-Compiler** [comment]
I'm closing this, as I suspect it'll work fine with QtWebEngine as well.
