### ISSUE TITLE
Closing Last Tab

### ISSUE THREAD

**Issue by smalltock** [The-Compiler/qutebrowser#834]
My config has `last-close= ignore` which worked fine up until recently. The tab closes and gives me a blank screen. See vid related.

http://webm.host/9e5bb/vid.webm

**Comment by The-Compiler** [comment]
I think this accidentally got introduced in #822 by @Carpetsmoker - I'll take a look later today unless he does until then :smile:

**Comment by Carpetsmoker** [comment]
Oops, indeed. :o Thanks for reporting & fixing it :-)
