### ISSUE TITLE
URL-edit incorrectly escapes utf8 sequence for edit

### ISSUE THREAD

**Issue by Ongy** [The-Compiler/qutebrowser#835]
When *:open {url}* is used, qutebrowser escapes printable utf8 characters (for example kanji)

left side shows expected (input via ibus) right side shows current behaviour.

![25 07 15-16 13-17](https://cloud.githubusercontent.com/assets/4039331/8889825/6ce95992-32ea-11e5-9651-8ba856f5d1ea.png)

**Comment by NoSuck** [comment]
I didn't realize this was considered a bug, as I use percent-escaped URLs for sending to universal recipients.  (Not all systems have the right fonts.)

**Comment by The-Compiler** [comment]
@NoSuck Are you using `go` for that? I'd probably use `yy` instead (which probably should copy the encoded text by default, or at least offer a flag to do so).

**Comment by NoSuck** [comment]
@The-Compiler I use the "yank" command, which I've binded to "c" because I'm the bad boy everyone's mommy warned them about.  Here's an example page:

https://ja.wikipedia.org/wiki/%E5%9D%82%E6%9C%AC%E9%BE%8D%E9%A6%AC
https://ja.wikipedia.org/wiki/坂本龍馬

**Comment by The-Compiler** [comment]
I see - that's different from `go` (i.e. the interpretation of `{url}`) then. For `:yank` I guess we can have both behaviors using an argument.

**Comment by Ongy** [comment]
I don't really know how `{url}` is evaluated but I think it would be best to have something like `{url}` and `{escaped url}` (or `{glyphs url}` depending on what should be the default)

@NoSuck just out of curiosity: Is there an actual benefit to it? I don't think most people would try to read the percent-escaped urls, and for click/copy it doesn't matter if the font can display it

**Comment by The-Compiler** [comment]
`{url:pretty}` and `:yank --pretty` was actually implemented some while ago in #1435 and #1436.
