### ISSUE TITLE
Open Quickmarks - Doesnt care about the Name

### ISSUE THREAD

**Issue by ndalliard** [The-Compiler/qutebrowser#838]
Hey, I searched for that, don't know if someone already mentioned that. 

But when I save for example https://duckduckgo.com/ with the name `search` and I then type `search` this Quickmark doesnt pop up. It looks like the intention of the title of the bookmark here is, that I know what I bookmarked there, but it is not included in the completion. 

Maybe a feature for the future? Or did I just miss something here?

**Comment by The-Compiler** [comment]
I'm not sure I understand you correctly - do you mean with `:open`, the completion doesn't filter quickmarks by name?

That's intended - if you want to open a quickmark by name, you'd usually use the `:quickmark-load` command (bound to `b`).

**Comment by highcarbveganTV** [comment]
Argh, nevermind. Thanks!

**Comment by ndalliard** [comment]
Argh, right. Sorry. Never used `:quickmark-load`until today. Thanks!
