### ISSUE TITLE
Statusbar Width of History - A lot of Space

### ISSUE THREAD

**Issue by ndalliard** [The-Compiler/qutebrowser#839]
Is that big space intended or what should be there? 

![Statusbar Qutebrowser](http://i.imgur.com/zoHD9yn.png?1)

It makes a little bit more sense in the case of bookmarks, cause there we have a description. But for the history? I think the width of the url is way to short compared to the space we have available.

Possibly I've overlooked something. Thanks for your great work everyone!

**Comment by The-Compiler** [comment]
See #693 - there are basically two reasons:

- The widths are hardcoded for all completions, and they make a lot more sense for command/settings completion.
- quickmarks and history should have a title as well, but don't have one yet.

Probably a first step would be to make the widths configurable per completion.
