### ISSUE TITLE
Add a way to manage certificates

### ISSUE THREAD

**Issue by dalliard** [The-Compiler/qutebrowser#843]
Is it possible to add individual certificates by my own? Can I do that with OpenSSL? I use Arch Linux as the Distro, maybe I can solve it there and the browser doenst has to have this feature.

**Comment by lamarpavel** [comment]
On arch, you will find certs under /etc/ssl/certs, but I am not sure if qute is checking that. As far as I know, Firefox also installs a curated list of certificates that qute might be using.

In any instance, having a feature in the browser to manage installed certificates would be really cool. Managing them on a system level is fine, but getting feedback from the browser would be really helpful to find out if your manually added certs are actually used. Maybe qute could display certificate sources and let the user search through them somehow with a command such as ```:ssl``` or ```:tls```.

**Comment by The-Compiler** [comment]
qutebrowser/Qt is using openssl and the system certificate store, so yep - you'd have to add it there. I've never done that though.

There's an issue about using the certificate store of Firefox or Chromium in #642 but I haven't investigated whether that's even possible.

With the QtWebEngine/Chromium backend in #666 qutebrowser will use Chromium's network stack and certificate handling, so no idea how you'd do that then...

@lamarpavel - that'd be possible with QtWebKit I think, but maybe not with QtWebEngine. Anyways - I'll rename this issue to track that.

**Comment by lamarpavel** [comment]
[xombrero](https://github.com/conformal/xombrero) has a command `:cert save` that will store the certificate of the current page in its own cache, allowing for a very quick method to locally store certs where they are not modified by anyone but you (they are in the directory ~/.xombrero/certs). Additionally the command `:cert show` will display the certificate of the current page.

Having the ability to store certs in a local cache seems like a good idea. Especially if it's so easy to store them (compared to Firefoxes three-dialog-window-hassle for importing certificates). For sites where security is vital I would like to have know when certificates change. System wide cert storage such as /etc/ssl or the mozilla cache get updated automatically and might hide these changes.

I would like qutebrowser to have such a command and the ability to abort connection when certs differ from my local cache. Should I start a new issue for the latter part?

**Comment by The-Compiler** [comment]
Interesting! I think the latter part is common enough to keep it here - and certificate patrol is also listed as a possible plugin in #30.

**Comment by The-Compiler** [comment]
QtWebEngine has no API for this, so I'm afraid this is not going to happen until that changes.

**Comment by Holzhaus** [comment]
User-local certificates SSL certs are already possible using `~/.pki/nssdb` and `certutil`: http://homepage.rub.de/jan.holthuis/posts/using-burpsuite-with-qutebrowser

**Comment by The-Compiler** [comment]
I just added the mitmproxy certificate in Chromium, and qutebrowser picked it up FWIW.
