### ISSUE TITLE
confirm-quit = downloads acts weird

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#846]
When having a single, *finished* download and quitting, qutebrowser says there are 2 running downloads.

The check simply uses `download_count = download_manager.rowCount()` which might do the wrong thing.

/cc @peterlvilim

**Comment by Carpetsmoker** [comment]
I getting a segfault when setting `ui.confirm-quit=downloads` and quitting while I'm downloading something :o

I don't have it with `--temp`, will investigate later ... But I did notice this in `--debug`, which seems to be the problem:

	21:49:38 DEBUG    statusbar  prompter:ask_question:304 Asking question <qutebrowser.utils.usertypes.Question default=True mode=<PromptMode.yesno: 1> text='Really quit?\n1 download is running.'>, blocking True, loops [], queue deque([])
	21:49:38 DEBUG    statusbar  prompter:ask_question:310 Ignoring question because we're shutting down.

**Comment by The-Compiler** [comment]
Meh. Starting with `catchsegv` and checking the python stacktrace when you run qutebrowser after the segfault might help in checking what's happening.
