### ISSUE TITLE
Favicon sizing is messed up with tabs -> position = left

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#847]
![faviconfail](https://cloud.githubusercontent.com/assets/625793/9084858/d58bd516-3b77-11e5-86c3-a5bf9dbe9f4e.png)

cc @Carpetsmoker

**Comment by Carpetsmoker** [comment]
@The-Compiler I'll make a fix later.

**Comment by The-Compiler** [comment]
Thank you!

**Comment by Carpetsmoker** [comment]
Here's a patch which seems to work well in my initial testing. We now use the
*font* size rather than the *tabbar* size, since the tabbar size is the window
size when it's vertical.

This also works nicer with the new tabs.padding setting (which didn't exist when
I wrote the first patch).


	diff --git i/qutebrowser/mainwindow/tabwidget.py w/qutebrowser/mainwindow/tabwidget.py
	index ea1426a..7b9b98b 100644
	--- i/qutebrowser/mainwindow/tabwidget.py
	+++ w/qutebrowser/mainwindow/tabwidget.py
	@@ -309,13 +309,8 @@ class TabBar(QTabBar):
		def set_font(self):
			"""Set the tab bar font."""
			self.setFont(config.get('fonts', 'tabbar'))
	-
	-    def resizeEvent(self, e):
	-        """Set the favicon size to the tabbar size minus some padding."""
	-        height = e.size().height()
	-        if height != 0 and e.oldSize().height() != height:
	-            height = math.ceil(height - height / 7)
	-            self.setIconSize(QSize(height, height))
	+        size = self.fontInfo().pixelSize() - 1
	+        self.setIconSize(QSize(size, size))

		@config.change_filter('colors', 'tabs.bg.bar')
		def set_colors(self):

**Comment by The-Compiler** [comment]
That approach seems to make more sense, but I'm not 100% happy with it - if you have time to change some things and test, mind opening a PR so we can continue there?

**Comment by The-Compiler** [comment]
Fixed via #849.

**Comment by The-Compiler** [comment]
Oh, I forgot to close this it seems.
