### ISSUE TITLE
What parts of the URL should Ctrl-A increment?

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#850]
Minor thing spotted by @Carpetsmoker - `http://mdweb.arp242.net/test-dir` changes to arp243.net when doing Ctrl-A, which makes little sense.

**Comment by Carpetsmoker** [comment]
Something else I just noticed:

    http://vi.stackexchange.com/questions/1/how-can-i-add-line-numbers-to-vim/5#5

Pressing `<C-a>` increases the `#5` part, which is not what I want. I want to increment the `/5` part.

Some sites *do* use `#` for navigation these days ("web 2.0 done wrong"), but maybe a parameter?

**Comment by The-Compiler** [comment]
In @Kingdread's PR, that'll increment `/5` - I think let's keep it this way and see how it works out in practise. @Kingdread, what do you think? Can you maybe add a test for this scenario?

**Comment by Carpetsmoker** [comment]
After making the above comment, I noticed that what I *really* want is to increment the first number:

/questions/**1**/how-can-i-add-line-numbers-to-vim/5#5

Perhaps navigate should ask which number to increment if there's more than one? Or is that too intrusive? There are many scenarios for the wrong numbers to be incremented, like: `buzzfeed.com/12323-heres-5-reasons-why-you-click-on-clickbait-articles`

**Comment by The-Compiler** [comment]
Hm - yet with something like `http://foo.bar/folder_1/image_3` you'd want `image_4` and not `folder_2`.

I think with many pages with a slug (like your examples), incrementing the number won't even work and give you a 404 - it seems to work on StackExchange, but I don't think it works on many other places.

I indeed think asking would be too intrusive, as `<Ctrl-A>` probably is a feature you use a lot to navigate some page...

I think adding a setting which number to increment makes sense when we have per-domain settings, then you could easily say "increment the first number if on `*.stackexchange.com`". Before that, I think let's just keep the current behavior.

**Comment by Kingdread** [comment]
I think the feature is useful if you have a folder with e.g. a dump of images from a digital camera, they're all numbered sequentially - `IMG_3523.JPG`, `IMG_3524.JPG`, ... so you can quickly navigate through them all. The feature is probably pretty "fragile" when used on other sites which do not expect that kind of navigation, so I think The-Compiler's approach with per-domain settings is probably the best compromise.

**Comment by The-Compiler** [comment]
I'm reopening this - from the Arch BBS:

> Would it be possible 'navigate increment' (incdec_number function) work on full url not only path.
> Number are often in query string rather then path.

I think incrementing in the query too would make sense, no?

**Comment by Kingdread** [comment]
What about a setting? Something like `url_incdec_segments` with values like `host`, `path`, `query`, `anchor`, or any combination of them (`path,query`) - this would be especially useful with per-domain settings

**Comment by The-Compiler** [comment]
Sounds good to me! Do you want to work on that?

**Comment by Kingdread** [comment]
Hm yeah, I'll see what I can do :smile:

**Comment by The-Compiler** [comment]
Closing this as #985 was merged - thanks again, @Kingdread!
