### ISSUE TITLE
Starting Xvfb from tests?

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#851]
I'm sometimes annoyed when running qutebrowser's tests (and I'd like to run all of them) on systems without an X server, as the tests (well, Qt) will call `abort()`.

I think:

* GUI tests should be skipped gracefully if no display was found (how to check for that condition, though? Checking `'DISPLAY' in os.environ` would be a start.)
* Maybe if we're on Linux and `Xvfb` is available, it should automatically be started as part of the tests, e.g. using [pytest-services](https://github.com/pytest-dev/pytest-services).

@nicoddemus @hackebrot what's your take on this?

**Comment by hackebrot** [comment]
I'm afraid I don't really know what to do in this particular case :worried:

**Comment by nicoddemus** [comment]
Here's a few ideas, just to keep the discussion going:

## skipping ##

The main question to me is how to even know if a X server or GUI is available:

1. `"DISPLAY" in os.environ` is a good start, but not always (it's a stretch, but one can export `DISPLAY` without having a X server running);
2. Perhaps there is some function in `QApplication` that can tell us if there's a display available?
3. This one is a little hackish and needs testing, but one could install a temporary `QtMessageHandler`, create a QWidget, and see if `qFatal` was called; this would prevent the `abort()` called by the default handler and would tell us if it is safe to run GUI tests;

Once we find out if there's no X server, all that needs to be done is call `pytest.skip()` in the `qtbot` fixture.

## start Xvfb ##

Seems like a good idea specially that pytest-services has builtin support to it, but perhaps only enable it with a `--xvfb` flag?

**Comment by The-Compiler** [comment]
@nicoddemus Note I opened this in qutebrowser, not pytest-qt - If you're okay with having `pytest-services` as a (optional?) dependency, it's something which could certainly be added to `pytest-qt` as well. Maybe with something like `--xvfb (on|off|auto)`.

Skipping all `qtbot` tests currently isn't enough because of the `app_and_logging

**Comment by nicoddemus** [comment]
> Note I opened this in qutebrowser, not pytest-qt 

Don't worry, I noticed. :smile:

> If you're okay with having pytest-services as a (optional?) dependency, it's something which could certainly be added to pytest-qt as well. Maybe with something like --xvfb (on|off|auto).

I'm not sure it would be a good  fit to add automatic support for it, but a page in the docs with a recipe/howto would certainly be a nice addition.

> Skipping all qtbot tests currently isn't enough because of the app_and_logging fixture which uses qapp, so this is somewhat blocked by #660.

I was thinking that automatic skipping could be a part of `pytest-qt`, as it would work for tests pure pytest suites. As `qutebrowser` itself: If I'm not mistaken one can create a `QApplication` object without an X server, so my feeeling is that `app_and_logging`-dependent tests could execute in an environment without X server without any problems. `qtbot` fixtures are the ones that will usually abort() without an X server.

**Comment by The-Compiler** [comment]
> If I'm not mistaken one can create a `QApplication` object without an X server

You can create a `QCoreApplication`, but not a `QApplication`:

```
$ DISPLAY= python3  
[...]
>>> from PyQt5.QtWidgets import QApplication
>>> QApplication([])
QXcbConnection: Could not connect to display 
[1]    26787 abort (core dumped)  DISPLAY= python3
```

**Comment by nicoddemus** [comment]
I see, thanks.

Given that currently you are still stuck with `app_and_logging` until all tests are converted, which approach do you plan to pursuit? I guess skipping tests is out of question at the moment, as this would skip all tests.

**Comment by The-Compiler** [comment]
The tests are converted already - the issue is still that I want tests to fail if they log unexpected warnings/errors (even with the qWarning thing being in pytest-qt now) and I didn't look at that yet.

My approach is to look at that first, and then come back to this issue :wink:

**Comment by nicoddemus** [comment]
> The tests are converted already

Oh I quickly glanced at the list of checkboxes in #660 and thought those were old-style tests yet, my bad. I remember now that you had already converted the entire test suite. :sweat_smile: 

> My approach is to look at that first, and then come back to this issue :wink:

Cool, if anything else comes to my mind I will make sure to mention it here. :smile:

**Comment by The-Compiler** [comment]
I have a PR at #864 - would be glad about a review! I think starting Xvfb is overkill, but it's already good to be able to run a reduced set of tests without a GUI.

**Comment by The-Compiler** [comment]
I actually really want to start Xvfb from tests, it's annoying to have popping windows when forgetting to add `xvfb-run` :wink:

I tried with `pytest-services`:

```diff
diff --git a/tests/conftest.py b/tests/conftest.py
index a8222b1..f483fe0 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -117,6 +117,11 @@ def pytest_collection_modifyitems(items):
         _apply_platform_markers(item)
 
 
+@pytest.fixture(scope='session', autouse=True)
+def set_up_xvfb(xvfb):
+    pass
+
+
 @pytest.fixture(scope='session')
 def qapp(qapp):
     """Change the name of the QApplication instance."""
@@ -336,3 +341,13 @@ def fail_tests_on_warnings():
     warnings.simplefilter('error')
     yield
     warnings.resetwarnings()
+
+
+@pytest.fixture(scope='session')
+def xvfb_resolution():
+    return (800, 600, 16)
+
+
+@pytest.fixture(scope='session')
+def run_services():
+    return sys.platform.startswith('linux') and 'CI' not in os.environ
diff --git a/tox.ini b/tox.ini
index 1c9da8c..ac3c1e6 100644
--- a/tox.ini
+++ b/tox.ini
@@ -21,6 +21,7 @@ deps =
     pytest-qt==1.7.0
     pytest-mock==0.8.1
     pytest-html==1.6
+    pytest-services
     hypothesis==1.11.4
     coverage==4.0.0
     pytest-cov==2.2.0
```

but ran into https://github.com/pytest-dev/pytest-services/issues/8

I guess I'll try using [xvfbwrapper](https://github.com/cgoldberg/xvfbwrapper) instead.
