### ISSUE TITLE
CSS broken on certain websites

### ISSUE THREAD

**Issue by Derpford** [The-Compiler/qutebrowser#852]
Recently, some websites (for instance, 8chan.co, my bank's website, various imageboards, Kongregate, etc) have had their site formatting completely break. Everything's treated as if it were a simple HTML-only document, which is kind of an eyesore. Attached is a screenshot of the same thread open in both DWB and Qutebrowser.
![screenshot](https://cloud.githubusercontent.com/assets/10187719/9112220/e6dcbf24-3c12-11e5-9dad-8a65c33fedf6.png)

**Comment by The-Compiler** [comment]
Does it look better when you do `R` (shift-r, i.e. `:reload --force`)?

**Comment by Derpford** [comment]
Doesn't appear to change anything. Perhaps it's something with the
formatting of the page? I'll try installing the git version and get back to
you.

**Comment by The-Compiler** [comment]
Can you also try with `--temp-basedir` please?

**Comment by Derpford** [comment]
Using --temp-basedir works. Looks like something in the basedir is messing
with me, then. Maybe I set an option wrong? Should I dump my .cfgs and such
to a pastebin?

**Comment by lamarpavel** [comment]
You can call ```:report``` and in the window that pops up, click on _show log_ and scroll down a bit. There you can see all your settings that differ from default.

You could toggle some of those to find out if there is one particular setting that causes the issue.

**Comment by Derpford** [comment]
Success! I had css-media-type changed. When I changed it back to blank, the
problem was fixed.
I'm a silly user. Thanks for putting up with my silliness.

**Comment by The-Compiler** [comment]
It might also be something corrupted in the cache or so - maybe try removing `~/.cache/qutebrowser` (you can safely remove it without losing anything).

**Comment by The-Compiler** [comment]
Ah - missed your last message. Glad to hear that! No worries - there are a lot of config options, so it's easy to miss something :smile:
