### ISSUE TITLE
Add start time to crash log

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#855]
Sometimes it'd be useful to know for how long qutebrowser did run already.

**Comment by acogneau** [comment]
This can be done using QElapsedTimer at the launch: http://doc.qt.io/qt-4.8/qelapsedtimer.html

**Comment by The-Compiler** [comment]
Thanks! I'd probably have used a `QTime`, but `QElapsedTimer` is the better choice indeed.

(note: I edited your post to point to the Qt5 instead of the Qt4 link)
