### ISSUE TITLE
The misc_checks.py test should check for global .gitignore

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#860]
Hello.
It would be nice if the `misc_checks.py` test does not show untracked files that are in the global `.gitignore` file (`git config --global core.excludesfile '~/.gitignore'`).
Thanks to fix this issue.

**Comment by The-Compiler** [comment]
`misc_checks.py` just calls `git status --porcelain` - but because tox didn't pass the `$HOME` variable to git, I guess it couldn't resolve `~/.gitignore` :smile:
