### ISSUE TITLE
hints too small

### ISSUE THREAD

**Issue by shanemikel** [The-Compiler/qutebrowser#871]
Is there a way to change the hint size?  I'm having trouble with my resolution.

**Comment by The-Compiler** [comment]
You probably want something like `:set fonts hints 'bold 14px Monospace'` - can you share a screenshot how it looks right now, i.e. should the default be changed or is this a problem on your machine?

**Comment by shanemikel** [comment]
Sorry, my issue was posted prematurely.  I haven't had enough time to poke around the configuration yet.  Anyhow, I have it set to 16px and it's perfect now.

**Comment by shanemikel** [comment]
Actually, I've been using this on a small-ish res screen lately too, and I really think the default could be a little bigger (in the interest of speed), but it's not a big deal.  BTW I love this.

**Comment by The-Compiler** [comment]
I just increased the default by 1pt - that's what I'm using myself as I found the default too small too :laughing:
