### ISSUE TITLE
Feature Request: Enhancement for toggle syntax

### ISSUE THREAD

**Issue by smalltock** [The-Compiler/qutebrowser#877]
Now that the `:set tabs hide-always` boolean has been replaced with the non-boolean `:set tabs show` variable, my old trick of binding V to `:set tabs hide-always!` no longer works. I'd like to request the syntax be extended a bit to account for non-boolean variables.

My idea is to do something like this... `:set tabs show!{always,never,othervalue}`... which would cycle the variable through the provided values. I might have time to do this myself on Tuesday.

**Comment by The-Compiler** [comment]
See #47 - a PR is certainly most appreciated!

I'm not sure if I like the syntax... Something like `set --cycle always,never,othervalue tabs show` might make more sense. In #47 I proposed a separate command, but I think it's better to add it to `:set`.
