### ISSUE TITLE
Can't stay logged in on https://baboom.com/

### ISSUE THREAD

**Issue by jplatte** [The-Compiler/qutebrowser#878]
I always click the "Remember me" checkbox on the site, but it never works. I don't get logged out using the site for hours, but once I restart the browser, I have the log in again.

**Comment by The-Compiler** [comment]
As discussed in IRC this works fine in Otter and happens with a clean profile.

**Comment by The-Compiler** [comment]
@jplatte have you ever tried this with QtWebEngine?

**Comment by jplatte** [comment]
I don't think so, no. I also didn't use the service for long, and now I couldn't log in anymore if I wanted to; the page says

> Baboom Service on Hold till further Notice

**Comment by The-Compiler** [comment]
Oh, bummer. I'm closing this then, as there's no way we can reproduce it anymore I guess.
