### ISSUE TITLE
Command for selecting "active" window.

### ISSUE THREAD

**Issue by robomica** [The-Compiler/qutebrowser#881]
I use xdg-open for my program defaults and it would be very nice to be able to set which window new links are opened in, instead of using the newest window every time. Maybe something like the most-recently used window would also be good.

**Comment by The-Compiler** [comment]
Just to make sure I understand you properly - you mean when setting `general -> new-instance-open-target` to `tab` (with `-bg`/`-silent` optionally), right?

As you said it uses the last opened window currently. I'm not sure a setting is needed for that, actually - maybe it should just use the last focused one by default?

**Comment by robomica** [comment]
I believe so, yes. To clarify the comannd I would like would be "this is the window I want externally-opened applications in". I typically have several windows open with different topics or purposes so setting which window a program would open in would keep me from the process of "ok let's copy this random link to a book from a friend out of the window I'm using for email, delete the tab, and paste it into the appropriate one".

**Comment by The-Compiler** [comment]
Ah, I see - any ideas how the UI would look for that?

What about taking the last focused by default, and then adding a `:new-instance-window` (?) command which marks the current window as such - then those links get opened in that window until it's closed?

**Comment by robomica** [comment]
That sounds perfect, actually. Btw thank you for replying so quickly. I really appreciate it.

**Comment by The-Compiler** [comment]
Thanks! Don't expect me to work on this anywhen soon though, as I'm busy with other things and use `new-instance-open-target = window` personally.

Contributions would be much appreciated, though! I'll add the "easy" label as this sounds like a good thing for e.g. a new contributor to get started with.

**Comment by Ram-Z** [comment]
If you use sessions and would like to change which window urls are opened you can change the order of the windows in the session file. The last window is the one new urls will be opened in.

**Comment by The-Compiler** [comment]
@haasn added a new `new-instance-open-target.window` to open links in the most recently focused window (which is now also the default). I think focusing a window is a good enough way to say "open new tabs here now", so I'm closing this unless other people speak up who'd like an explicit command added for this.
