### ISSUE TITLE
Tutanota.de - no login with default user-agent

### ISSUE THREAD

**Issue by sdoubleyou** [The-Compiler/qutebrowser#884]
I use tutanota für mail. I can't use login. The browser "is not supported".
Is it possible to change this without use a nother user-agent?

**Comment by The-Compiler** [comment]
Apparently their [browser detection](https://github.com/tutao/tutanota/blob/master/web/js/util/ClientDetector.js) is broken, or they treat unsupported browsers the same way.

Complain [to them](https://tutanota.uservoice.com/forums/237921-general) or fake your user agent.

Not much qutebrowser can do here. It might get better with the QtWebEngine backend (#666), but I'd still argue the site is broken. At the very least they should provide a way for the user to override the stupid detection.

**Comment by The-Compiler** [comment]
There already [is an issue there](https://tutanota.uservoice.com/forums/237921-general/suggestions/8592022-allow-using-unsupported-browsers) to allow unsupported browsers. Please vote for it! I just gave it three votes, you can do that without signing up.

**Comment by sdoubleyou** [comment]
thx for your information
