### ISSUE TITLE
QuotaExceededError

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#885]
Hello.
I get the following error on some sites and I wonder what option to change to avoid it:

```
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
```

Thanks for your help.

**Comment by The-Compiler** [comment]
The most likely reason is that you have `general -> private-browsing` turned on. With that on, I think websites will have a HTML local storage quota of 0.

If that isn't the case, check the options in the `storage` category. I don't know which one exactly it'd be, though.
