### ISSUE TITLE
Stuttering on navbar when scrolling on sites with fixed navbars

### ISSUE THREAD

**Issue by CheriPai** [The-Compiler/qutebrowser#899]
This occurs on sites with fixed navbars like youtube and soundcloud.

Happens with smoothscrolling both on and off.

When scrolling, the navbar comes down slightly with the page and returns to its original position immediately after. This creates the stuttering effect.

**Comment by The-Compiler** [comment]
This is a bug in the QtWebKit library qutebrowser uses, and it is already reported upstream as [QTBUG-43339](https://bugreports.qt.io/browse/QTBUG-43339).

Unfortunately, QtWebKit is deprecated, so the chances of this getting fixed are low. However, qutebrowser should have a QtWebEngine backend soon (see #666), which is based on Chromium and doesn't have this issue.
