### ISSUE TITLE
Cookies stored despite private-browsing = True

### ISSUE THREAD

**Issue by wes1138** [The-Compiler/qutebrowser#903]
Related:  #43 .  The following might be relevant:

1. I have save-session = true
2. This will NOT happen if cookies-store = false (so #this != #869 )

I would posit that private browsing overriding cookies-store makes for more intuitive behavior.

To reproduce:
1. inspect cookies file (or delete them all)
2. Open qutebrowser with private-browsing = True and cookies-store = true.
3. Visit say, wikipedia.
4. Close all qutebrowser tabs and observe presence of new cookies from wikipedia.

Probably irrelevant, but I have last-close = close, and that is usually how I quit qutebrowser.

**Comment by The-Compiler** [comment]
I can reproduce this via `rm -r foo; python3 -m qutebrowser --basedir foo ':set general private-browsing true' ':set general save-session true' wikipedia.org; cat foo/data/cookies`

I think the CookieJar gets replaced by a in-RAM CookieJar correctly when setting the option when qutebrowser is running and the option gets changed, but not when initializing... :blush: 

I'll take a closer look tomorrow - thanks for the report!

**Comment by wes1138** [comment]
Awesome.  Thanks!

**Comment by The-Compiler** [comment]
This also affects v0.3.0 - I want to fix another bug or two first, but I hope I'll be able to release v0.4.0 this week.
