### ISSUE TITLE
gmail panels are not hinted

### ISSUE THREAD

**Issue by teto** [The-Compiler/qutebrowser#911]
I use gmail tabs ("Principale", "notifications" on the screenshot) to sort my emails but I see no hints to go to them, can that be considered as a problem in qutebrowser (if that goes undetected because of some hellish javascript) or should I change my webmail ?
https://transfer.sh/D3bR5/2015-08-31-144805-1107x93-scrot.png
```
qutebrowser --version 
qutebrowser v0.3.0
Git commit: v0.3.0-44-gc5b75b0 (2015-07-06 17:58:13 +0200)
```

**Comment by The-Compiler** [comment]
both :wink: I switched from GMail's webmail to [mutt](http://www.mutt.org/) and I've been very happy about it.

I added it to #178 which has some related issues as well.
