### ISSUE TITLE
Create Gitter chat

### ISSUE THREAD

**Issue by bb010g** [The-Compiler/qutebrowser#913]
[Gitter.im](https://gitter.im/) is a really nice, free chat service for GitHub projects and orgs. It would be nice to have a place to pass around userscripts, discuss ideas more casually, etc. (Users include Rust, Neovim, Vundle, Opal, Spacemacs, Angular.js, Rails, Meteor, Laravel, Gulp, Bootstrap, Brackets, and more.)

**Comment by The-Compiler** [comment]
There's already an [IRC channel](https://github.com/The-Compiler/qutebrowser#getting-help) with almost 90 people in it - there's also a [webchat](https://webchat.freenode.net/?channels=#qutebrowser) if you really prefer that.

Users: almost every opensource project out there

Let's not force users to use some proprietary service which is - in comparison to IRC - used by very few people.
