### ISSUE TITLE
Folder View

### ISSUE THREAD

**Issue by logankaser** [The-Compiler/qutebrowser#916]
A folder view like firefox or early builds of chrome would be a great feature

something like:

##Up
****
file
file
**directory/**

**Comment by The-Compiler** [comment]
I'm guessing you mean for local directories? This is already implemented in -git, see #859.

There should be a v0.4 release somewhen this week if everything goes well.

**Comment by logankaser** [comment]
Literally the fastest feature implementation of all time. (from my perspective)
