### ISSUE TITLE
Hint mode doesn't reset read hints

### ISSUE THREAD

**Issue by cym13** [The-Compiler/qutebrowser#917]
What happens:
=============

When in hint mode, if part of a hint sequence is typed, then aborted, the
buffer isn't reset so it will be considered the start of the next hint
sequence even if the two don't have anything in common. This often means
following links that weren't the desired ones by accident.

How to reproduce:
=================

In configuration:

    [hint]
    mode  = letter
    chars = tsrnvdljqghfczmwk

(Sorry for the weird config, I can't remember what the default one is and it
 may be of importance so...)

- Go to www.linux.com
- Go in hint mode: "Training" (up in the bar) is “cd”

![linux org](https://cloud.githubusercontent.com/assets/4958985/9653701/bb4c0a76-5225-11e5-8d75-dd33183d7029.png)

- Hit ‘c’ then ‘ESC’ to exit hint mode.
- Go in hint mode
- Hit ‘d’
- You should now be in the "Training" section without ever typing “cd”.

Impact
======

I keep clicking on links that aren't what I had in mind because of that. In
fact this is so frustrating that I wonder wether this can be reproduced
because I can't see how it could have not been already reported if other have
the same problem.

I must add that it hasn't always been the case, I've used qutebrowser for
maybe 6 month now pulling from git every day and this is a quite recent issue.

Version infos
=============

qutebrowser v0.3.0
Git commit: v0.3.0-634-g3a5cd8f (2015-09-03 06:51:15 +0200)

CPython: 3.4.3
Qt: 5.5.0, runtime: 5.5.0
PyQt: 5.5

**Comment by The-Compiler** [comment]
Thanks for the nice bugreport!

I could reproduce this with `--temp-basedir` (i.e. the default config), and bisected it to 57ddd8e95e5d8ff8ad0473e84e58094045e57d6a - /cc @Carpetsmoker 

I guess it was never noticed because it's uncommon to cancel hinting mode after entering a char - at least I never did that, apparently :laughing:

I'll take a look for v0.4, unless @Carpetsmoker wants to.

**Comment by The-Compiler** [comment]
# Logs

## When it was working

### Pressing `f`
```
modes      modeman:enter:255 Entering mode KeyMode.hint (reason: HintManager.start)
```

### Pressing `s` (first hint char)
```
keyboard   basekeyparser:_debug_log:104 Got key: 0x53 / text: 's'
keyboard   basekeyparser:_debug_log:104 No match for 's' (added s)
hints      hints:handle_partial_key:827 Handling new keystring: 's'
modes      modeman:_eventFilter_keypress:206 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='http://www.linux.com/'>)
modes      modeman:_eventFilter_keyrelease:226 filter: True
```

### Pressing esc
```
keyboard   basekeyparser:_debug_log:104 Got key: 0x1000000 / text: '
keyboard   basekeyparser:_debug_log:104 Escape pressed, discarding 's'.
keyboard   modeparsers:_handle_special_key:141 Got special key 0x1000000 text [0m
commands   command:run:484 command called: leave-mode
modes      modeman:leave:298 Leaving mode KeyMode.hint (reason: leave current)
```

### Pressing `f`
```
modes      modeman:enter:255 Entering mode KeyMode.hint (reason: HintManager.start)
```

### Pressing `a` (second hint char)
```
keyboard   basekeyparser:_debug_log:104 Got key: 0x41 / text: 'a'
keyboard   basekeyparser:_debug_log:104 No match for 'a' (added a)
hints      hints:handle_partial_key:827 Handling new keystring: 'a'
```

## Now

### Pressing `f`
```
modes      modeman:enter:255 Entering mode KeyMode.hint (reason: HintManager.start)
```

### Pressing `s` (first hint char)
```
keyboard   basekeyparser:_debug_log:104 Got key: 0x53 / text: 's'
keyboard   basekeyparser:_debug_log:104 No match for 's' (added s)
hints      hints:handle_partial_key:827 Handling new keystring: 's'
modes      modeman:_eventFilter_keypress:206 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='http://www.linux.com/'>)
modes      modeman:_eventFilter_keyrelease:226 filter: True
```

### Pressing esc
```
keyboard   basekeyparser:_debug_log:104 Got key: 0x1000000 / text: '
keyboard   basekeyparser:_debug_log:104 Ignoring, no text char
keyboard   modeparsers:_handle_special_key:141 Got special key 0x1000000 text [0m
commands   command:run:484 command called: leave-mode
modes      modeman:leave:298 Leaving mode KeyMode.hint (reason: leave current)
```

### Pressing `f`
```
modes      modeman:enter:255 Entering mode KeyMode.hint (reason: HintManager.start)
```

### Pressing `a` (second hint char)
```
keyboard   basekeyparser:_debug_log:104 Got key: 0x41 / text: 'a'
keyboard   basekeyparser:_debug_log:104 Definitive match for 'sa'.
modes      modeman:leave:298 Leaving mode KeyMode.hint (reason: followed)
statusbar  text:maybe_reset_text:74 Resetting: 'Follow hint...'
statusbar  text:set_text:59 Setting normal text to ''.
hints      hints:_click:437 Clicking on 'Training' at 137/12
```


# Difference

The significant difference is when pressing esc:

```
keyboard   basekeyparser:_debug_log:104 Escape pressed, discarding 's'.
```

vs.

```
keyboard   basekeyparser:_debug_log:104 Ignoring, no text char
```

**Comment by The-Compiler** [comment]
In fa65f345ac36bbb3e075d682d6c072af9a8bc347 actually @Carpetsmoker moved clearing the keychain to a command instead of hardcoding it, but the keybindings weren't adjusted to actually call that outside of normal mode. With some keybinding migration juggling, that should be okay now :wink:

**Comment by cym13** [comment]
I confirm it is, thanks for the quick fix :smile_cat:

**Comment by Carpetsmoker** [comment]
Wow, how was this not detected earlier? :-/
