### ISSUE TITLE
https://web.whatsapp.com/ does not work

### ISSUE THREAD

**Issue by zuglufttier** [The-Compiler/qutebrowser#918]
The web interface for whatsapp does not work with qutebrowser: https://web.whatsapp.com/

I tried to set different user agents but no avail. If no user agent is set, the webpage just suggests to use something like Firefox, Chrome etc. Is there something I can do about that?

**Comment by The-Compiler** [comment]
I'd rather not get a Facebook/WhatsApp account just to reproduce this - so what exactly "doesn't work" (when you spoof the UA)?

**Comment by zuglufttier** [comment]
The web page just displays a loading animation and that's all, it never comes to an end.

The page should show some kind of login form with a QR code.

**Comment by The-Compiler** [comment]
I see that just fine here:

![wa](https://cloud.githubusercontent.com/assets/625793/9659256/bd0bd722-524f-11e5-8256-a819150891a2.png)

Can you try with `--temp-basedir`? Do you see anything suspicious when you start with `--debug`?

**Comment by zuglufttier** [comment]
`--temp-base` didn't change anything. Odd that it's working with you. Maybe it's the packages from arch linux, I'll try build qutebrowser by myself with the sources from github.

**Comment by The-Compiler** [comment]
I'm on a Qt 5.3.2 on Debian Stable right now though - maybe it doesn't work with 5.5? I'll check on Arch later.

There shouldn't be any difference between the repo and the package (I'm the maintainer of it).

**Comment by zuglufttier** [comment]
OK, great! I tried the most recent release (0.3.0) for windows and it doesn't work there as well.

**Comment by The-Compiler** [comment]
Works fine for me on Arch as well - what exactly are you setting the UA to? I'm trying with the "Chrome 40.0 Linux" option in the completion.

**Comment by zuglufttier** [comment]
The combination of the UA and `--temp-basedir` did the trick. But after scanning the QR code with my phone, the page only shows a loading animation and does not proceed further.

You're supposed to scan the QR code with your phone (which still needs to be connected to the internet) to verify that it's your account. After scanning the QR code, there's some communication between the Whatsapp servers, your browser and your phone. This communication part seems to work as after scanning the code on your phone, the web page changes its state again. The browser just fails to show the normal interface of the web page.

Well, I guess, they rely on something very browser specific. My guess is that they try to make this only work on some software they know very good instead of relying on web standards...

**Comment by zuglufttier** [comment]
Yes, the UA is Chromium 40 Linux. I tried some other UAs but that didn't work, too.

Otter Browser didn't work as well, also with a changed UA. Well, I don't care too much about this ;)

**Comment by Karkus476** [comment]
I'm not sure why this has been closed when it is a perfectly valid issue. When I spoof user agent I am sent to the url https://web.whatsapp.com/browsers.html?missing=cryptoSha256,cryptoAesCbc immediately.

**Comment by Karkus476** [comment]
Update: use--backend webengine

**Comment by rhbrunetto** [comment]
This is still happening with me.
I'm on Ubuntu 16.04 LTS and Qt5 on latest version. The UA is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36`
That works fine usgin `--temp-basedir` but all my browser history disappear.

**Comment by The-Compiler** [comment]
@rhbrunetto that's a WhatsApp bug nowadays, different to what this issue was about - see #4445
