### ISSUE TITLE
Add Flag to Qutebrowser to Open Url in New Tab for Existing Instance

### ISSUE THREAD

**Issue by noctuid** [The-Compiler/qutebrowser#922]
I couldn't find an issue for this, but I apologize if one exists already. Opening urls from an external program in qutebrowser, I noticed that there is no such option (e.g. like `firefox --new-tab <url>`).

**Comment by The-Compiler** [comment]
Do you really need an argument for this, i.e. is this something you sometimes want and sometimes not?

If you always want to open links opened via external tools as tabs: `:set general new-instance-open-target tab`.

**Comment by noctuid** [comment]
Well I wouldn't say that it's necessary, but I think it would be preferable to be able to choose in the `qutebrowser` command since this would allow for external programs to be able to choose a command to use that would behave the same way regardless of the user's qutebrowser configuration. 

For example, emacs' [`browse-url`](http://www.emacswiki.org/emacs/BrowseUrl) has specific settings for most browsers (or a generic setting to add a flag for this purpose) to be choose whether or not to open urls in a new tab.

For me, I'd almost always want to open in a new tab. Even so, I think it would be nice to be able to explicitly specify the behaviour in the program calling qutebrowser.

**Comment by The-Compiler** [comment]
What you can already do is `qutebrowser ':open -t your.url'`, i.e. pass any qutebrowser command as argument - but I see how that'd be inconvenient to do from a script.

What about adding a `--target {auto,tab,tab-bg,tab-silent,tab-bg-silent,window}` option, which (if not set to `auto`) overrides the `new-instance-open-target` config option?

**Comment by noctuid** [comment]
Yes, in the example of the browse-url library, the generic function wouldn't work for that since it just passes in the url as the last arg. Having a `--target` option would be great!

**Comment by MazeChaZer** [comment]
Hi, I would like to take a look at this and try to implement it, if nobody else is working on this right now

**Comment by The-Compiler** [comment]
I don't think anybody else is working on this - so go ahead!

Let me know if you need help!

**Comment by MazeChaZer** [comment]
Ok, I got into the source code today and I think I have a basic understanding how command line arguments are processed. However I'm struggeling because all options are discarded in the ipc connection, including `--target`. Only positional arguments (commands and urls) are sent to the running instance.

There are several options now:

1. Send a target flag via ipc (the ipc "protocol" would have to be changed)
2. Convert the urls to the appropriate `:open` commands if the target flag is set
3. Change the config temporarily (probably not possible)

@The-Compiler, do you already have an idea how to do this? Is any of the suggestions above the way to go?

**Comment by The-Compiler** [comment]
I think the first suggestion makes the most sense - the protocol data is a dict, and unknown arguments get ignored, so that should work fine and even be backwards-compatible with already running instances.

**Comment by MazeChaZer** [comment]
Oh right, I overlooked that a dictionary is used for ipc. This makes things a little easier.

**Comment by The-Compiler** [comment]
Fixed thanks to @MazeChaZer! :smile:

**Comment by noctuid** [comment]
@MazeChaZer Awesome! Thanks.
