### ISSUE TITLE
Update browser list for UA completion

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#923]
The browser list in the completion for `network -> user-agent` is a bit dated - it should probably be updated to show more recent versions.

Ideally there'd be some script to grab this from some list of most common user agents or so, so I can easily update it with every release.

**Comment by averrin** [comment]
Something like this:
https://gist.github.com/averrin/9416a682f80e96c78827 ?

**Comment by lamarpavel** [comment]
I just started work on this and I wonder: How important is the diversity of the list of agents? Pulling the `n` most popular ones means mostly `webkit/chrome`, `webkit/safari` and `gecko/firefox` on either Windows or OSX, but no android, Linux, wget, curl, etc.

Maybe auto-fetch a list of popular user agents and then add a few obscure ones for diversity?
