### ISSUE TITLE
Hints are influenced by page stylesheet if it uses *

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#925]
e.g. with this test case using `* { padding: 10px; }`:

```html
<head>
    <style type="text/css">
        * {
            padding: 10px;
        }
    </style>
</head>

<body>
    <p>
    This hint should look normal:
    <a href="http://www.qutebrowser.org/">test</a>
    </p>
</body>
```

We get this: 
![qutebug1](https://cloud.githubusercontent.com/assets/625793/9701433/47ce7696-5429-11e5-9910-26e69a4849f5.png)

One possibility would be to set padding to 0 with `!important` for the hints:

```diff
diff --git a/qutebrowser/browser/hints.py b/qutebrowser/browser/hints.py
index fdc2014..c7ccf18 100644
--- a/qutebrowser/browser/hints.py
+++ b/qutebrowser/browser/hints.py
@@ -342,6 +342,8 @@ class HintManager(QObject):
             ('font', config.get('fonts', 'hints') + ' !important'),
             ('border', config.get('hints', 'border') + ' !important'),
             ('opacity', str(config.get('hints', 'opacity')) + ' !important'),
+            ('padding', '0 !important'),
+            ('margin', '0 !important'),
         ]
 
         # Make text uppercase if set in config
```

(we might also want to set more - see [CSS reset](https://perishablepress.com/a-killer-collection-of-global-css-reset-styles/))

but that renders the hint at the wrong position:

![qutebug2](https://cloud.githubusercontent.com/assets/625793/9701439/7bb4bca4-5429-11e5-85f1-36c09d947054.png)

**Comment by stereolink** [comment]
Here is an example I found in the wild of this. On this [university journal website](http://www.themaneater.com/), the hints all have a width that extends to the right edge of the page. They have three style sheets linked for that main page ([1](http://themaneater.com/media/style/2009-01/style/960/960.css), [2](http://themaneater.com/media/style/2014-redesign/NEW.css), [3](http://themaneater.com/media/style/2014-redesign/NEWFRONT.css)). The second one has a rule of:
```
body > * {
    padding: 0 2.5%;
    width: 95%;
}
```
