### ISSUE TITLE
Refactor ColorDict/FontDict hacks

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#928]
Currently we have some special mappings in `config/style.py` so we can use a color in a stylesheet and it'll show up as `''`, `'color: foo;` or `background-color: foo;` depending on if it's available and if it ends with `.bg` or `.fg` (and the same for fonts).

This is hacky, and now that we use jinja, we should just use some function from jinja instead.

**Comment by neeasade** [comment]
Considering colordict:

Looking at http://jinja.pocoo.org/docs/dev/templates/ , it looks like something like would be used?:
``` 
{% if not some.color.bg == "" %}
    background-color: {{ some.color.fg }};
{% endif %}
```

would there be a way to change color to not be a dict maybe? would be nice to have a function or something with say `color( [ color | fg | bg ], 'my.color.config') `

For reference: 
``` sh
─── grep -r "color\[" . | wc -l
121
``

**Comment by The-Compiler** [comment]
I actually wonder if the "don't output anything if the config value is empty" semantics are still needed nowadays, I need to dig deeper in the git history :wink:

I *think* none of the config options even allow an empty value, so probably just doing `background-color: {{ some.color.fg }};` will work fine.

**Comment by neeasade** [comment]
oh! Well if that's a case, it should be just a matter of fixing current templates that reply on this, and then changing colordict to just return the color, right?

**Comment by The-Compiler** [comment]
Indeed - for the fonts, I think we can get rid of `FontDict` entirely. Maybe also check the open PRs and see if there's anything changing stylesheets or adding new ones.

Would you like to work on this?

**Comment by neeasade** [comment]
> Would you like to work on this?

yepp, I'll open up a [wip] in a bit, and after that is okay, look though the PR's.

**Comment by The-Compiler** [comment]
Awesome, thank you!

**Comment by neeasade** [comment]
regex I'm using to find files that need replaces:
grep -lEr "^[ ]+{{ font\[" .  | grep -v pyc
grep -lEr "^[ ]+{{ colors\[" .  | grep -v pyc
