### ISSUE TITLE
tempfile.mktemp gone in Python 3.5

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#932]
We use `tempfile.mktemp` to get a name for userscript FIFOs - that got removed in Python 3.5

**Comment by The-Compiler** [comment]
Seems I missed it somehow - it's still there.

**Comment by kevinlondon** [comment]
tempfile.mktemp is [insecure](https://docs.python.org/2/library/tempfile.html#tempfile.mktemp), so it's probably a good idea to swap it out for something else anyway. I'll look into it and may make a pull request.

**Comment by The-Compiler** [comment]
I'm pretty confident it isn't when used with `os.mkfifo` which fails atomically when the file already exists. 

```python
            # tempfile.mktemp is deprecated and discouraged, but we use it here
            # to create a FIFO since the only other alternative would be to
            # create a directory and place the FIFO there, which sucks. Since
            # os.mkfifo will raise an exception anyways when the path doesn't
            # exist, it shouldn't be a big issue.
            self._filepath = tempfile.mktemp(prefix='qutebrowser-userscript-',
                                             dir=standarddir.runtime())
            os.mkfifo(self._filepath)  # pylint: disable=no-member
```

Also see [this SO answer](http://stackoverflow.com/a/1430566/2085149).

**Comment by kevinlondon** [comment]
Ah, okay. Thanks for the link and explanation!
