### ISSUE TITLE
History in Completion When web-history-max-items is 0

### ISSUE THREAD

**Issue by antoyo** [The-Compiler/qutebrowser#934]
Hello.
I set the `web-history-max-items` to 0, but I still have history items in the open completion.
It should not show history items, right?

By the way, by setting `web-history-max-items` to 0, will qutebrowser save the history on the hard drive?
Thanks to fix this.

**Comment by The-Compiler** [comment]
Setting `web-history-max-items` currently requires a restart - see #733.

The setting only affects the completion - for clearing the history on shutdown, #58 would probably be more useful.

**Comment by antoyo** [comment]
I set `web-history-max-items` in the config file, so I restarted qutebrowser a few times, but I still see the history.
Is it normal?

**Comment by The-Compiler** [comment]
Huh, no - when starting qutebrowser with that option, you shouldn't see any history in the completion.

When you do `:set completion web-history-max-items?` do you see `0` in the statusbar? Are you sure you restarted all instances (try `:restart`)? Are you sure qutebrowser didn't overwrite the value in your config?

**Comment by antoyo** [comment]
I tried `:restart`, the value in my config file is still `0` and when I type `:set completion web-history-max-items`, I see that the current value is `0`.

**Comment by The-Compiler** [comment]
Can you show a screenshot of the completion so we can be sure we're talking about the same thing?

Also, could you `:restart`, show the completion, and then `:report`?

**Comment by antoyo** [comment]
Here is the screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/584972/9787767/58d99d7c-5793-11e5-92f7-74874fc9d9cc.png)

**Comment by The-Compiler** [comment]
Ah, I think I see the issue: You're only seeing new entries from the current session, but nothing loaded from the history file, right?

I guess it'd make more sense to limit the completion to that many entries in general, yeah...

**Comment by antoyo** [comment]
Yes, you're right.
Do you want that I work on this issue?
