### ISSUE TITLE
Whitelist for host block lists

### ISSUE THREAD

**Issue by ndalliard** [The-Compiler/qutebrowser#948]
Is it possible to unblock a blocked host?

**Comment by The-Compiler** [comment]
Unfortunately not easily - are you talking about a permanent unblocking or a temporary override?

What host are you having trouble with? If it's something legitimate, it might make sense to get the author of the block list to unblock it as well.

For temporary unblocking, see #273.

But I agree there should be some kind of whitelist as well.

**Comment by ndalliard** [comment]
It is for permanently unblocking of sumome.com

**Comment by The-Compiler** [comment]
That's on multiple blocklists:

```
$  python3 scripts/hostblock_blame.py sumome.com
config path: /home/florian/.config/qutebrowser/qutebrowser.conf
checking http://www.malwaredomainlist.com/hostslist/hosts.txt...
checking http://someonewhocares.org/hosts/hosts...
FOUND sumome.com in http://someonewhocares.org/hosts/hosts:
    127.0.0.1 load.sumome.com
FOUND sumome.com in http://someonewhocares.org/hosts/hosts:
    127.0.0.1 sumome.com
checking http://winhelp2002.mvps.org/hosts.zip...
FOUND sumome.com in http://winhelp2002.mvps.org/hosts.zip:
    0.0.0.0 sumome.com
FOUND sumome.com in http://winhelp2002.mvps.org/hosts.zip:
    0.0.0.0 load.sumome.com
checking http://malwaredomains.lehigh.edu/files/justdomains.zip...
checking http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext...
```

So I think a whitelist would be the right approach here. I'll rename the issue and tag it as "easy", as it should be relatively simple to add that feature - contributions would be very welcome, as I'm drowning in work currently!
