### ISSUE TITLE
Some new feature ideas

### ISSUE THREAD

**Issue by averrin** [The-Compiler/qutebrowser#949]
Hello.
I made some hacky changes in my fork, but imho its too dirty for PR. But maybe my ideas will be usefull:
1. Add list with regex for hosts, which will have auto passthrugh mode
2. Exit from pt mode, when u change tab
3. Add some fuzzy to autocomplete.

My commit with basic implementation:
https://github.com/averrin/qutebrowser/commit/962857b0c328cae72a8f8fc671a147112e5b40cb

**Comment by The-Compiler** [comment]
1: I'd like to handle that with per-domain settings in a more generic way later, see #27 
2: sounds good - would you like to submit a PR for that?
3: I haven't tried yet, but sounds interesting! #133 is the related issue. If you'd like to flesh this out a bit more, I'd love a PR for some further discussion!

For 3:

* Is `fuzzywuzzy` packaged for the distributions important to qutebrowser? (Ubuntu Trusty/Vivid, Debian Jessie, Gentoo, Void Linux, Archlinux, maybe more?)
* How is the performance?

**Comment by averrin** [comment]
2. Yes, its only one list item, but its not very usefull without autorentering in this mode=)
3. U can add it to requitrments.txt. Its just return likeness ration and its fast for our cases.

Ok, ill do PRs =)

**Comment by The-Compiler** [comment]
It's not that easy - for distributions where qutebrowser will be packaged, that'd be an additional dependency which needs packaging.

**Comment by averrin** [comment]
```
./fuzzywuzzy
❯ cat * | wc -l
701
```

**Comment by The-Compiler** [comment]
I'm not sure what you're trying to tell me.

**Comment by averrin** [comment]
I mean, that if you cant install it from pip, this module have only 701 lines and u can bundle it or rewrite.
