### ISSUE TITLE
Some keys work in normal mode on some sites

### ISSUE THREAD

**Issue by Carpetsmoker** [The-Compiler/qutebrowser#955]
Examples:

- [New York times](http://www.nytimes.com/2015/09/18/health/republican-presidential-debate-vaccines.html?hp&action=click&pgtype=Homepage&module=first-column-region&region=top-news&WT.nav=top-news&_r=0) Pressing Left or Right.
- [nrc.nl](http://www.nrc.nl/inbeeld/2015/09/15/het-koffertje-de-hoedjes-en-de-wachtende-oranjefans/) Pressing Space or Page{Down,Up}

@vyp In both pages, pressing the keys trigger some JS actions (go to next/previous page in NYT, some weird scrolling effect on NRC). I would expect that keybinds *don't* do anything on a website in normal mode.

**Comment by vyp** [comment]
Did you mean "don't work"?

**Comment by Carpetsmoker** [comment]
@vyp No, they do something (go to next/previous page in NYT, some weird scrolling effect on NRC). I would expect that keybinds *don't* do anything on a website in normal mode.

**Comment by vyp** [comment]
@Carpetsmoker Ah I see. :+1:

**Comment by The-Compiler** [comment]
By default, all unbound non-alphanumeric keys are passed to the website - you can control that with the `input -> forward-unbound-keys` setting. If I set this to `none`, nothing happens when I press those keys anymore.

So, everything working as expected! :wink:
