### ISSUE TITLE
Possibility To Add My Own Css

### ISSUE THREAD

**Issue by ndalliard** [The-Compiler/qutebrowser#961]
Is there a possibility to add my own css to a defined site?

I use Twitter a lot and think it is a whole mess. I would like to add for example this css ( http://pastebin.com/CQdq0YDc) applied to twitter.com. That is on chrome possible with the stylebot extension.

Maybe its somehow possible with qutebrowser, that would be awesome.

**Comment by The-Compiler** [comment]
In general this is possible with the `ui -> user-stylesheet` setting, but not per page yet. See #27 for that.
