### ISSUE TITLE
Generalize configtypes.List

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/qutebrowser#989]
Currently there;s `List` and subclasses like `RegexList`. Each subclass requires tests for corner cases, and some even handle `none_ok` differently (entire value empty vs. individual item empty).

Instead, `List` should be something like this:

```python
class List(BaseType):

    def __init__(self, inner_type, none_ok=False):
        self.inner_type = inner_type

    def validate(self, value):
        self._basic_validation(value)
        # ...
        for val in self.transform(value):
            self.inner_type.validate(val)

    def transform(self, value):
        # split items
        return [self.inner_type.transform(v) for v in split_values]
```

and then in `configdata.py`:

* `List(String())`
* `List(String(none_ok=True))` - empy item okay, empty list not
* ...

This will also make tests a lot easier as corner-cases don't have to be tested
for every list subtype individually.

**Comment by mlochbaum** [comment]
Working on this now.

**Comment by mlochbaum** [comment]
This can be closed.
