### ISSUE TITLE
History completion broken when using unlimited entries

### ISSUE THREAD

**Issue by arza-zara** [The-Compiler/qutebrowser#991]
After 8a01dc9194a97ab92d510d2d65af6a8ceb759bb0, when completion:web-history-max-items=-1, history doesn't appear in completion.

**Comment by The-Compiler** [comment]
I'll take a look at this somewhen next week probably, unless @antoyo wants to do so in the meantime :wink:

**Comment by antoyo** [comment]
I could fix this in two weeks as I quite busy now.

Perhaps changing the line:

```python
if self._history_cat.rowCount() > self._max_history:
```
by
```python
if self._max_history != -1 and self._history_cat.rowCount() > self._max_history:
```
would fix it.

**Comment by The-Compiler** [comment]
This fixed it indeed - thanks @antoyo and thanks @arza-zara for the report!
