### ISSUE TITLE
Some SVG images in <img> elements are not displayed correctly.

### ISSUE THREAD

**Issue by daniel-lawrence-lu** [The-Compiler/qutebrowser#993]
Example test case: http://lawrence.lu/public/svgtest.html

Expected rendering: http://lawrence.lu/sc/2e1cd18485.png

Appearance in qutebrowser: http://lawrence.lu/sc/03e5481e0f.png

The SVG file itself is at http://lawrence.lu/texcache/1fc0c80802e7fef475c68a195544c2c7c38d5b4c.svg and is rendered correctly in qutebrowser.

Both SVG and HTML file pass the W3C validator.

**Comment by The-Compiler** [comment]
I see the same behaviour with Chromium and Midori (WebKit2GTK) - I can't tell you why this is happening, but it definitely doesn't look like qutebrowser's fault.
